### ISSUE TITLE
Crash when startup causes by null object reference bitmap.getWidth()

### ISSUE THREAD

**Issue by gvlekke** [Deletescape-Media/Lawnchair#1117]
## Description

When I startup the launcher it crashes.

## Expected Behavior

Should start up

## Actual Behavior

It crashes

## Steps to Reproduce

1. install
2. open launcher
3. crash

## Environment

* Device: LG G6
* Android version: 7.0
* Launcher version: 1.1.0.1742
* Rom: Stock rom from LG

## Logcat

```
01-17 22:12:34.714 23739-23739/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: ch.deletescape.lawnchair.plah, PID: 23739
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                       at ch.deletescape.lawnchair.FastBitmapDrawable.<init>(Unknown Source)
                                                       at ch.deletescape.lawnchair.BubbleTextView.applyPromiseState(Unknown Source)
                                                       at ch.deletescape.lawnchair.BubbleTextView.applyFromShortcutInfo(Unknown Source)
                                                       at ch.deletescape.lawnchair.BubbleTextView.applyFromShortcutInfo(Unknown Source)
                                                       at ch.deletescape.lawnchair.Launcher.createShortcut(Unknown Source)
                                                       at ch.deletescape.lawnchair.Launcher.createShortcut(Unknown Source)
                                                       at ch.deletescape.lawnchair.Launcher.bindItems(Unknown Source)
                                                       at ch.deletescape.lawnchair.LauncherModel$LoaderTask$5.run(Unknown Source)
                                                       at ch.deletescape.lawnchair.DeferredHandler$Impl.handleMessage(Unknown Source)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6316)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by gvlekke** [comment]
downloaded version 1.1.0.1828 from the ci channel and I didn't experienced any problems with that build.
