### ISSUE TITLE
Crash when long clicking date.

### ISSUE THREAD

**Issue by randomuser112358** [Deletescape-Media/Lawnchair#1160]
```
java.lang.IllegalArgumentException: Provider must be either PROVIDER_OPENWEATHERMAP or PROVIDER_GOOGLE_AWARENESS
	at ch.deletescape.lawnchair.weather.WeatherAPI$Companion.create(Unknown Source)
	at ch.deletescape.lawnchair.weather.WeatherHelper.<init>(Unknown Source)
	at ch.deletescape.lawnchair.QsbBlockerView.setupView(Unknown Source)
	at ch.deletescape.lawnchair.QsbBlockerView.onLongClick(Unknown Source)
	at android.view.View.performLongClick(View.java:5246)
	at android.widget.TextView.performLongClick(TextView.java:9256)
	at android.view.View$CheckForLongPress.run(View.java:21151)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5437)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

- Device: Redmi 4A / Android 6.0.1
- Lawnchair 1.1.0.1742 from F-Droid.

**Comment by divadsn** [comment]
Unsupported for now, as F-Droid builds contain hackery stuff which have disabled Google Awareness APIs for example.

Just set the weather provider to OpenWeatherMap in the settings.
