### ISSUE TITLE
Lawnfeed crashes when clicking on update notification

### ISSUE THREAD

**Issue by kk6axq** [Deletescape-Media/Lawnchair#1212]
## Description

When I go to the home screen, lawnfeed sends a notification saying a new version of lawnfeed is available for download. When I click on it, I get a message that says lawnfeed has stopped.

## Expected Behavior
Lawnfeed updates.

## Actual Behavior
Lawnfeed stops.

## Steps to Reproduce
1. Go to home screen
2. Open notification tray and click on lawnfeed notification.

## Environment

* Device: Sony Xperia E5 Model F3311
* Android version 6.0
* Lawnchair Version 1.1.0.1872
* Lawnfeed Version 1.1.0.1742
* ROM: Stock ROM

**Comment by kk6axq** [comment]
Same as #1181 and #1000.

**Comment by kk6axq** [comment]
Couldn't find changelog as referenced in #1181. What are the steps to remedy this?

**Comment by kk6axq** [comment]
Will post logcat later today.

**Comment by kk6axq** [comment]
Here is the logcat from the crash: 
```
04-16 10:03:45.714 26578 26578 E AndroidRuntime: FATAL EXCEPTION: main
04-16 10:03:45.714 26578 26578 E AndroidRuntime: Process: ch.deletescape.lawnchair.lawnfeed, PID: 26578
04-16 10:03:45.714 26578 26578 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-16 10:03:45.714 26578 26578 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.PermissionActivity.callAsync(PermissionActivity.java:90)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver.onReceive(UpdateReceiver.java:51)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2903)
04-16 10:03:45.714 26578 26578 E AndroidRuntime:        ... 8 more
[Extraneous entries removed]
04-16 10:23:42.898 27464 27464 E AndroidRuntime: FATAL EXCEPTION: main
04-16 10:23:42.898 27464 27464 E AndroidRuntime: Process: ch.deletescape.lawnchair.lawnfeed, PID: 27464
04-16 10:23:42.898 27464 27464 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-16 10:23:42.898 27464 27464 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.PermissionActivity.callAsync(PermissionActivity.java:90)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver.onReceive(UpdateReceiver.java:51)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2903)
04-16 10:23:42.898 27464 27464 E AndroidRuntime:        ... 8 more
[Extraneous entries removed]
04-16 10:24:28.842 19071 19071 E LawnfeedClient: proxy died
04-16 10:24:28.842 19071 19071 E LawnfeedClient: android.os.DeadObjectException
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.os.BinderProxy.transactNative(Native Method)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.os.BinderProxy.transact(Binder.java:511)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.launcherclient.ILauncherClientProxy$Stub$Proxy.reconnect(Unknown Source)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.overlay.LawnfeedClient.reconnect(Unknown Source)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.overlay.LawnfeedClient.onResume(Unknown Source)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.Launcher.onResume(Unknown Source)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1271)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.Activity.performResume(Activity.java:6355)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.performNewIntents(ActivityThread.java:2730)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2737)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.os.Looper.loop(Looper.java:207)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:24:28.842 19071 19071 E LawnfeedClient:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[Extraneous entries removed]
04-16 10:24:31.557 28808 28808 E AndroidRuntime: FATAL EXCEPTION: main
04-16 10:24:31.557 28808 28808 E AndroidRuntime: Process: ch.deletescape.lawnchair.lawnfeed, PID: 28808
04-16 10:24:31.557 28808 28808 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-16 10:24:31.557 28808 28808 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.PermissionActivity.callAsync(PermissionActivity.java:90)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver.onReceive(UpdateReceiver.java:51)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2903)
04-16 10:24:31.557 28808 28808 E AndroidRuntime:        ... 8 more
[Extraneous entries removed]
04-16 10:24:54.076 19071 19071 E LawnfeedClient: proxy died
04-16 10:24:54.076 19071 19071 E LawnfeedClient: android.os.DeadObjectException
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.os.BinderProxy.transactNative(Native Method)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.os.BinderProxy.transact(Binder.java:511)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.launcherclient.ILauncherClientProxy$Stub$Proxy.reconnect(Unknown Source)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.overlay.LawnfeedClient.reconnect(Unknown Source)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.overlay.LawnfeedClient.onResume(Unknown Source)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at ch.deletescape.lawnchair.Launcher.onResume(Unknown Source)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1271)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.Activity.performResume(Activity.java:6355)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.performNewIntents(ActivityThread.java:2730)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2737)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.os.Looper.loop(Looper.java:207)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:24:54.076 19071 19071 E LawnfeedClient:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[Extraneous entries removed]
04-16 10:26:33.524 29026 29026 E AndroidRuntime: FATAL EXCEPTION: main
04-16 10:26:33.524 29026 29026 E AndroidRuntime: Process: ch.deletescape.lawnchair.lawnfeed, PID: 29026
04-16 10:26:33.524 29026 29026 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-16 10:26:33.524 29026 29026 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.PermissionActivity.callAsync(PermissionActivity.java:90)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver.onReceive(UpdateReceiver.java:51)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2903)
04-16 10:26:33.524 29026 29026 E AndroidRuntime:        ... 8 more
04-16 10:26:34.068 19179 19179 E WorkController: Loading failed for worker [context]
04-16 10:26:34.068 19179 19179 E WorkController: java.lang.IllegalStateException: WorkerManager is disposed
04-16 10:26:34.068 19179 19179 E WorkController:        at com.google.android.apps.gsa.search.core.service.f.b.c.hr(SourceFile:7)
04-16 10:26:34.068 19179 19179 E WorkController:        at com.google.android.apps.gsa.search.core.service.workcontroller.a.d.run(Unknown Source)
04-16 10:26:34.068 19179 19179 E WorkController:        at com.google.android.apps.gsa.shared.util.concurrent.b.br.bes(SourceFile:2)
04-16 10:26:34.068 19179 19179 E WorkController:        at com.google.android.apps.gsa.shared.util.concurrent.b.bp.run(SourceFile:2)
04-16 10:26:34.068 19179 19179 E WorkController:        at android.os.Handler.handleCallback(Handler.java:815)
04-16 10:26:34.068 19179 19179 E WorkController:        at android.os.Handler.dispatchMessage(Handler.java:104)
04-16 10:26:34.068 19179 19179 E WorkController:        at android.os.Looper.loop(Looper.java:207)
04-16 10:26:34.068 19179 19179 E WorkController:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:26:34.068 19179 19179 E WorkController:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:26:34.068 19179 19179 E WorkController:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:26:34.068 19179 19179 E WorkController:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
04-16 10:26:34.069 19179 19179 E WorkController: Loading failed for worker [context]
04-16 10:26:34.069 19179 19179 E WorkController: java.lang.IllegalStateException: WorkerManager is disposed
04-16 10:26:34.069 19179 19179 E WorkController:        at com.google.android.apps.gsa.search.core.service.f.b.c.hr(SourceFile:7)
04-16 10:26:34.069 19179 19179 E WorkController:        at com.google.android.apps.gsa.search.core.service.workcontroller.a.d.run(Unknown Source)
04-16 10:26:34.069 19179 19179 E WorkController:        at com.google.android.apps.gsa.shared.util.concurrent.b.br.bes(SourceFile:2)
04-16 10:26:34.069 19179 19179 E WorkController:        at com.google.android.apps.gsa.shared.util.concurrent.b.bp.run(SourceFile:2)
04-16 10:26:34.069 19179 19179 E WorkController:        at android.os.Handler.handleCallback(Handler.java:815)
04-16 10:26:34.069 19179 19179 E WorkController:        at android.os.Handler.dispatchMessage(Handler.java:104)
04-16 10:26:34.069 19179 19179 E WorkController:        at android.os.Looper.loop(Looper.java:207)
04-16 10:26:34.069 19179 19179 E WorkController:        at android.app.ActivityThread.main(ActivityThread.java:5763)
04-16 10:26:34.069 19179 19179 E WorkController:        at java.lang.reflect.Method.invoke(Native Method)
04-16 10:26:34.069 19179 19179 E WorkController:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
04-16 10:26:34.069 19179 19179 E WorkController:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)```

**Comment by divadsn** [comment]
The changelog was saying you should uninstall Lawnfeed and download the latest from https://lawnchair.info/getlawnfeed.html, then install normally.

**Comment by kk6axq** [comment]
I'm still having this issue when a new update is released for lawnfeed. Is the code, particularly https://github.com/LawnchairLauncher/Lawnchair/blob/8eeb702f48fdee03844d45829d93476f9e6bc9ce/lawnfeed/src/main/java/ch/deletescape/lawnchair/lawnfeed/updater/Updater.java meant to do anything when the notification is clicked or is it crashing because of that?

**Comment by divadsn** [comment]
@kk6axq the code you mentioned contains only the checking process and the notification which is created and shown to you. Could you please get a logcat so we could sort it out, as in theory there shouldn't be a crash unless my server is going crazy and the response is malformed (which was the case now as I forgot to pay the bill)

**Comment by kk6axq** [comment]
The logcat looks similar as before here it is below:
```07-18 16:34:20.101 14260 14260 E AndroidRuntime: FATAL EXCEPTION: main
07-18 16:34:20.101 14260 14260 E AndroidRuntime: Process: ch.deletescape.lawnchair.lawnfeed, PID: 14260
07-18 16:34:20.101 14260 14260 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2910)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:111)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5763)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
07-18 16:34:20.101 14260 14260 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:677)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ContextImpl.startActivity(ContextImpl.java:664)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.PermissionActivity.callAsync(PermissionActivity.java:90)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at ch.deletescape.lawnchair.lawnfeed.receivers.UpdateReceiver.onReceive(UpdateReceiver.java:51)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2903)
07-18 16:34:20.101 14260 14260 E AndroidRuntime:        ... 8 more
```

**Comment by divadsn** [comment]
Hm, kinda funny as on Nougat and Oreo it did not crash, I am gonna reproduce it on 6.0, should in theory work without that flag.
