### ISSUE TITLE
TouchInteractionService has leaked IntentReceiver ...

### ISSUE THREAD

**Issue by enricocid** [Deletescape-Media/Lawnchair#1609]
#Environment
* Device: OnePlus X "onyx"
* Android version: 9.0.0 (POSP ROM)
* Launcher version: it says 9 lol
* Rom: Posp 2.3 (2019.06.10)

```
Service com.android.quickstep.TouchInteractionService has leaked IntentReceiver com.android.internal.util.LatencyTracker$1@884310b that was originally registered here. Are you missing a call to unregisterReceiver()?
android.app.IntentReceiverLeaked: Service com.android.quickstep.TouchInteractionService has leaked IntentReceiver com.android.internal.util.LatencyTracker$1@884310b that was originally registered here. Are you missing a call to unregisterReceiver()?
	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
	at com.android.internal.util.LatencyTracker.<init>(LatencyTracker.java:104)
	at com.android.internal.util.LatencyTracker.getInstance(LatencyTracker.java:98)
	at com.android.internal.util.LatencyTracker.isEnabled(LatencyTracker.java:118)
	at com.android.systemui.shared.system.LatencyTrackerCompat.isEnabled(LatencyTrackerCompat.java:28)
	at com.android.quickstep.OverviewCommandHelper$RecentsActivityCommand.createWindowAnimation(OverviewCommandHelper.java:302)
	at com.android.quickstep.OverviewCommandHelper$RecentsActivityCommand.lambda$58M8Q8bLHkgPPJiaoVVAlKBEVb8(Unknown Source:0)
	at com.android.quickstep.-$$Lambda$OverviewCommandHelper$RecentsActivityCommand$58M8Q8bLHkgPPJiaoVVAlKBEVb8.createWindowAnimation(Unknown Source:2)
	at com.android.quickstep.util.RemoteAnimationProvider$1.onCreateAnimation(RemoteAnimationProvider.java:42)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$0(LauncherAnimationRunner.java:56)
	at com.android.launcher3.-$$Lambda$LauncherAnimationRunner$0IBM3bZEOrCXQUatxthdQPQcNQA.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6719)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by suphon-t** [comment]
This is from the Android framework and is registered only once in a process so that's not a problem.
