### ISSUE TITLE
Lawnchair crashes when a video is playing in Chrome with media event source enabled

### ISSUE THREAD

**Issue by Senexis** [Deletescape-Media/Lawnchair#1621]
## Description
When watching a video within Google Chrome while the media event source is enabled, Lawnchair will crash. When the notification is swiped away, everything will start to work as normal again.

## Expected Behavior
Lawnchair should not crash when a Chrome media notification is active / listed in the notifications list.

## Actual Behavior
Lawnchair crashes untill the notification is swiped away.

## Steps to Reproduce

1. Start a video in Google Chrome (I used the video at https://www.mobvoi.com/us/activity/simplyboosted)
2. Press the home button or open recents.
3. Lawnchair will crash.
4. Swipe away the media notification, and try again.
5. Lawnchair will work as normal.

## Environment

* Device: Xiaomi MI MIX 2
* Android version: 9
* Launcher version: 2.0.2236
* Rom: Lineage OS 16 Official

## Log
```
Lawnchair bug report 3 Jul 2019 7:46:12 PM
Lawnchair version: 2.0-2236-ci-alpha (2236)
build.brand: Xiaomi
build.device: chiron
build.display: lineage_chiron-userdebug 9 PQ3A.190605.003 670d971074
build.fingerprint: Xiaomi/chiron/chiron:8.0.0/OPR1.170623.027/V9.5.4.0.ODEMIFA:user/release-keys
build.hardware: qcom
build.id: PQ3A.190605.003
build.manufacturer: Xiaomi
build.model: Mi MIX 2
build.product: lineage_chiron
build.type: user
version.codename: REL
version.incremental: 670d971074
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.IllegalStateException: sbn.notification.contentIntent must not be null
	at ch.deletescape.lawnchair.smartspace.LawnchairSmartspaceController$NotificationClickListener.<init>(LawnchairSmartspaceController.kt:442)
	at ch.deletescape.lawnchair.smartspace.NotificationUnreadProvider.getEventCard(NotificationUnreadProvider.kt:116)
	at ch.deletescape.lawnchair.smartspace.NotificationUnreadProvider.onNotificationsChanged(NotificationUnreadProvider.kt:67)
	at ch.deletescape.lawnchair.smartspace.NotificationsManager$onChange$1.invoke(NotificationsManager.kt:116)
	at ch.deletescape.lawnchair.smartspace.NotificationsManager$onChange$1.invoke(NotificationsManager.kt:34)
	at ch.deletescape.lawnchair.LawnchairUtilsKt$sam$java_lang_Runnable$0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Senexis** [comment]
Already fixed in 2238.
