### ISSUE TITLE
NullPointerException with configuring Icon Packs

### ISSUE THREAD

**Issue by MrEasy** [Deletescape-Media/Lawnchair#1647]
## Steps to Reproduce

In icon settings, moving a custom Icon Pack down to deactivate it, then continuing configuring produces the NullPointer

## Log and Device Info
```
Lawnchair bug report 12.07.2019 07:38:23
Lawnchair version: 2.0-2312-ci-alpha (2312)
build.brand: OnePlus
build.device: OnePlus
build.display: lineage_onyx-userdebug 9 PQ2A.190205.001 eng.root.20190301.230413 release-keys
build.fingerprint: OnePlus/OnePlus/OnePlus:6.0.1/MMB29M/10281213:user/release-keys
build.hardware: qcom
build.id: PQ2A.190205.001
build.manufacturer: OnePlus
build.model: ONE E1003
build.product: OnePlus
build.type: user
version.codename: REL
version.incremental: eng.root.20190301.230413
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Path.transform(android.graphics.Matrix, android.graphics.Path)' on a null object reference
	at ch.deletescape.lawnchair.iconpack.AdaptiveIconCompat.updateMaskBoundsInternal(AdaptiveIconCompat.java:398)
	at ch.deletescape.lawnchair.iconpack.AdaptiveIconCompat.updateLayerBounds(AdaptiveIconCompat.java:348)
	at ch.deletescape.lawnchair.iconpack.AdaptiveIconCompat.onBoundsChange(AdaptiveIconCompat.java:341)
	at android.graphics.drawable.Drawable.setBounds(Drawable.java:235)
	at com.android.launcher3.graphics.LauncherIcons.createIconBitmap(LauncherIcons.java:334)
	at com.android.launcher3.graphics.LauncherIcons.createBadgedIconBitmap(LauncherIcons.java:197)
	at com.android.launcher3.graphics.LauncherIcons.createBadgedIconBitmap(LauncherIcons.java:178)
	at com.android.launcher3.IconCache.addIconToDBAndMemCache(IconCache.java:399)
	at com.android.launcher3.IconCache$SerializedIconUpdateTask.run(IconCache.java:808)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by deletescape** [comment]
@MrEasy A fix for this will roll out in like 30 minutes
