### ISSUE TITLE
[BUG] Lawnchair V2 crashes with QuickSwitch on Android 10/Q beta5

### ISSUE THREAD

**Issue by moldimolt** [Deletescape-Media/Lawnchair#1664]
## Description

Lawnchair v2.0-2325-ci-alpha (2019-07-20) combined with QuickSwitch v2.0.6 (2019-07-22) is somewhat broken on Android 10, causing both Lawnchair and Pixel Launcher to instantly crash. The QuickSwitch module installation script mentions any issues like this are a bug with the launcher, not QuickSwitch itself, so I'm reporting it here based on that.

## Expected Behavior

The Q recents provider should be changed to Lawnchair after selecting it in QuickSwitch and rebooting and Lawnchair should function normally.

## Actual Behavior

After selecting Lawnchair as the recents provider in QuickSwitch and rebooting, Quick Switch reports "boot script failed" and both Lawnchair and Pixel Launcher crash within seconds. However, QuickSwitch *did* work; despite Lawnchair being the default home app, Q recents features remain intact until you reinstall or update Lawnchair even after disabling Quick Switch in Magisk Manager and rebooting (which fixes the crashes).

## Steps to Reproduce

1. Have an Android 10/Q beta5 device rooted with Magisk Canary.
2. Download Quick Switch and Lawnchair V2, set Lawnchair V2 as your default Home app.
4. Open Quick Switch and select Lawnchair V2 as the Recents Provider.
5. Reboot
6. Unlock your device and press Home, observe Lawnchair V2 and Pixel Launcher both instantly crash. 
7. Use the notification shade to open `Settings>Apps>Magisk Manager` and disable QuickSwitch.
8. Reboot
9. Observe that, even though Lawnchair V2 is the default home app, Q recents features like the dock/app drawer, text OCR, etc. are intact, indicating that QuickSwitch **did** work despite the crashes.
10. Observe that the system sometimes gets confused what the default Home app is; for example, swiping away all apps from recents to go Home will take you to Pixel Launcher, but pressing the home button/gesture will take you to Lawnchair. 

## Environment

* Device: Pixel 3 XL
* Android version: 10 (Q)
* Launcher version: Lawnchair v2.0-2325-ci-alpha (2019-07-20)
* ROM: Android Q beta5 (QPP5.190530.014)

## Logcat

 

```
Lawnchair bug report Jul 22, 2019 14:04:13
Lawnchair version: 2.0-2325-ci-alpha (2325)
build.brand: google
build.device: crosshatch
build.display: QPP5.190530.014
build.fingerprint: google/crosshatch/crosshatch:10/QPP5.190530.014/5691763:user/release-keys
build.hardware: crosshatch
build.id: QPP5.190530.014
build.manufacturer: Google
build.model: Pixel 3 XL
build.product: crosshatch
build.type: user
version.codename: REL
version.incremental: 5691763
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ThreadedRenderer$FrameDrawingCallback;
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:668)
	at ch.deletescape.lawnchair.animations.LawnchairAppTransitionManagerImpl.getOpeningWindowAnimators(LawnchairAppTransitionManagerImpl.kt:298)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:639)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.access$300(LauncherAppTransitionManagerImpl.java:96)
	at com.android.launcher3.LauncherAppTransitionManagerImpl$2.onCreateAnimation(LauncherAppTransitionManagerImpl.java:220)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$0$LauncherAnimationRunner(LauncherAnimationRunner.java:56)
	at com.android.launcher3.-$$Lambda$LauncherAnimationRunner$0IBM3bZEOrCXQUatxthdQPQcNQA.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7343)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ThreadedRenderer$FrameDrawingCallback" on path: DexPathList[[zip file "/data/app/ch.deletescape.lawnchair.ci-dcRL1X7LOnfuzEZKC0HJAg==/base.apk"],nativeLibraryDirectories=[/data/app/ch.deletescape.lawnchair.ci-dcRL1X7LOnfuzEZKC0HJAg==/lib/arm64, /data/app/ch.deletescape.lawnchair.ci-dcRL1X7LOnfuzEZKC0HJAg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more
```

**Comment by nyancrimew** [comment]
Lawnchair currently does not yet support the Android Q Quickstep interface. We cannot support it before Q sources are released.

**Comment by moldimolt** [comment]
@deletescape Ah, okay. I thought functionality might've been attempted already given the partially working behavior. Thank you.

**Comment by kbirger** [comment]
Is this on the roadmap now that Android 10 is released?

**Comment by kbirger** [comment]
Should this be reopened now that the source is released?

https://www.androidpolice.com/2019/09/04/android-10-source-code-aosp/

**Comment by DanGLVK** [comment]
@kbirger Work on Android Q support has already started internally

**Comment by satishp7** [comment]
any updates on this issue. Any short hack suggestion meanwhile it lands to main release ??

**Comment by skittles9823** [comment]
@satishp7 Use the q_pre_alpha builds on apk mirror.
