### ISSUE TITLE
crash in work profile

### ISSUE THREAD

**Issue by xiaoxiong2333** [Deletescape-Media/Lawnchair#1684]
## Description

when use "island" to open a work profile,and tap home button to back  home screen,the app will crash,and give dialog launcher stopped.tap home again ,it like restart.

## Expected Behavior

it should go back home screen.

## Actual Behavior

it crash.

## Steps to Reproduce

1.install island app
2.open work profile
3.try back home .
4.

## Environment

* Device:essenstal phone
* Android version:9.0
* Launcher version:2.0-2035-ci-alpha
* Rom:xtended

## Logcat

 

https://del.dog/eqitimezok.sh

**Comment by xiaoxiong2333** [comment]
the lsat version (2.0-2338-ci) have the same problem.

**Comment by steffenl82** [comment]
Has the issue been solved for you? 

Because I have a similar problem with Shelter (https://f-droid.org/en/packages/net.typeblog.shelter/). When pressing the home button, Lawnchair crashes immediately.

(I'm running Android 9 and Lawnchair 2)

**Comment by Robert3141** [comment]
I'm not sure whether this is related to this issue but I have a Huawei with dual app set up for snapchat. In the app drawer it shows main and work profiles. On flicking the switch at the bottom it crashes with a Java exception
Lawnchair bug report 6 Sep 2019 20:30:47
Lawnchair version: 2.0-2393 (2393)
build.brand: HONOR
build.device: HWSTF
build.display: STF-L09 9.1.0.210(C432E2R1P5)
build.fingerprint: HONOR/STF-L09/HWSTF:9/HUAWEISTF-L09/210C432:user/release-keys
build.hardware: hi3660
build.id: HUAWEISTF-L09
build.manufacturer: HUAWEI
build.model: STF-L09
build.product: STF-L09
build.type: user
version.codename: REL
version.incremental: 210C432
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:355)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.IllegalArgumentException: User 128 is not a profile
	at android.os.Parcel.createException(Parcel.java:1957)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.os.IUserManager$Stub$Proxy.requestQuietModeEnabled(IUserManager.java:1930)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:2448)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:2434)
	at com.android.launcher3.compat.UserManagerCompatVP.requestQuietModeEnabled(UserManagerCompatVP.java:1)
	at com.android.launcher3.allapps.WorkModeSwitch$1.doInBackground(WorkModeSwitch.java:6)
	at com.android.launcher3.allapps.WorkModeSwitch$1.doInBackground(WorkModeSwitch.java:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 5 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.setQuietModeEnabled(UserManagerService.java:971)
	at com.android.server.pm.UserManagerService.requestQuietModeEnabled(UserManagerService.java:903)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:764)
	at com.android.server.pm.HwUserManagerService.onTransact(HwUserManagerService.java:103)
	at android.os.Binder.execTransact(Binder.java:739)

**Comment by Robert3141** [comment]
![Screenshot_20190906_204119_ch deletescape lawnchair plah](https://user-images.githubusercontent.com/30229266/64455888-b3da6280-d0e6-11e9-9729-b1aaa34416a1.jpg)
