### ISSUE TITLE
Lawnchair v2 logcat: ActivityManager: Stopping service due to app idle: u0a129 -1m18s218ms ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.bugreport.BugReportService

### ISSUE THREAD

**Issue by chenzhiwei** [Deletescape-Media/Lawnchair#1699]
## Description

There are many logcat logs, this may drain my battery.

For normal apps, there should be no such logs.

## Expected Behavior

no logs.

## Actual Behavior

too many logs.

## Steps to Reproduce

1. Install Lawnchair
2. Set Lawnchair as default launcher
3. check logcat
4.

## Environment

* Device: OnePlus 3
* Android version: 9
* Launcher version: 2.0-2357-ci-alpha
* Rom: Pixel Experience 07-11-2019

## Logcat

 

```
08-10 09:09:40.322 13462 13481 W .android.chrom: Unsupported class loader
08-10 09:09:50.212  2320  2337 W ActivityManager: Stopping service due to app idle: u0a129 -1m18s218ms ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.bugreport.BugReportService
08-10 09:09:50.222  7627  7627 D         : Service disconnected
08-10 09:09:50.226  2320  8579 W ActivityManager: Background start not allowed: service Intent { cmp=ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.bugreport.BugReportService } to ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.bugreport.BugReportService from pid=7627 uid=10129 pkg=ch.deletescape.lawnchair.ci startFg?=false
08-10 09:09:50.238 31411 31411 E ActivityThread: Service ch.deletescape.lawnchair.bugreport.BugReportService has leaked IntentReceiver ch.deletescape.lawnchair.bugreport.BugReportService$onCreate$receiver$1@a4ccc00 that was originally registered here. Are you missing a call to unregisterReceiver()?
08-10 09:09:50.238 31411 31411 E ActivityThread: android.app.IntentReceiverLeaked: Service ch.deletescape.lawnchair.bugreport.BugReportService has leaked IntentReceiver ch.deletescape.lawnchair.bugreport.BugReportService$onCreate$receiver$1@a4ccc00 that was originally registered here. Are you missing a call to unregisterReceiver()?
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1429)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1210)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:636)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at ch.deletescape.lawnchair.bugreport.BugReportService.onCreate(BugReportService.kt:66)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3570)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.os.Looper.loop(Looper.java:193)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
08-10 09:09:50.238 31411 31411 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-10 09:09:50.241  7627  7627 E BugReportClient: Failed to rebind
08-10 09:09:50.241  7627  7627 E BugReportClient: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.deletescape.lawnchair.ci/ch.deletescape.lawnchair.bugreport.BugReportService }: app is in background uid UidRecord{3884bb4 u0a129 SVC  bg:+1m0s19ms idle change:idle procs:2 seq(473,473,473)}
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.app.ContextImpl.startService(ContextImpl.java:1532)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at ch.deletescape.lawnchair.bugreport.BugReportClient.rebind(BugReportClient.kt:61)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at ch.deletescape.lawnchair.bugreport.BugReportClient.access$rebind(BugReportClient.kt:30)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at ch.deletescape.lawnchair.bugreport.BugReportClient$connection$1.onServiceDisconnected(BugReportClient.kt:45)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1723)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.os.Handler.handleCallback(Handler.java:873)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.os.Looper.loop(Looper.java:193)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
08-10 09:09:50.241  7627  7627 E BugReportClient: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-10 09:09:58.226   525   525 E qti_sensors_hal: sendEnableReq:sensor(android.sensor.significant_motion) Sending enable to svc no:40
```

**Comment by DanGLVK** [comment]
Logcat logs have negligible impact on the battery as your system is already generating massive amounts of logs on a daily basis, also lawnchair is an alpha app so issues are expected

**Comment by chenzhiwei** [comment]
@paphonb Hi, could you comment on this issue? Is this the expect behavior or alpha issue?

**Comment by suphon-t** [comment]
@DanGLES3 already did so no reason to explain it again.

**Comment by chenzhiwei** [comment]
I don't think so, he just said the logs have negligible impact on the battery, but he did not say whether this is a lawnchair bug or not.

**Comment by suphon-t** [comment]
Well then I suggest you go read your issue description again. You created an issue about logs, you get an answer about logs.
