### ISSUE TITLE
java.lang.OutOfMemoryError during icon customization

### ISSUE THREAD

**Issue by hsiktas** [Deletescape-Media/Lawnchair#1707]
## Description

Lawnchair hangs and crashes with an ouf of memory error whenever I try to adjust the icon of a single app.

## Expected Behavior

The list of available icons from various icon packs should appear.

## Actual Behavior

The launcher hangs for a few minutes and then crashes with the following error:
```
Lawnchair bug report 12.08.2019 22:28:21
Lawnchair version: 2.0-2357-ci-alpha (2357)
build.brand: OnePlus
build.device: OnePlus5T
build.display: ONEPLUS A5010_43_190731
build.fingerprint: OnePlus/OnePlus5T/OnePlus5T:9/PKQ1.180716.001/1907311828:user/release-keys
build.hardware: qcom
build.id: PKQ1.180716.001
build.manufacturer: OnePlus
build.model: ONEPLUS A5010
build.product: OnePlus5T
build.type: user
version.codename: REL
version.incremental: 1907311828
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 32 free bytes and 32B until OOM, max allowed footprint 268435456, growth limit 268435456
	at android.service.notification.NotificationRankingUpdate.<init>(NotificationRankingUpdate.java:86)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:138)
	at android.service.notification.NotificationRankingUpdate$1.createFromParcel(NotificationRankingUpdate.java:136)
	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:67)
	at android.os.Binder.execTransact(Binder.java:752)

```

## Steps to Reproduce

1. Click and hold an icon on the home screen
2. Select customize
3. Click on the app icon at the top

## Environment

* Device: OnePlus 5T
* Android version: 9
* Launcher version: 2.0-2357-ci-alpha
* Rom: OxygenOS 9.0.8

It might be of relevance that I have in total 69 icon packs installed. 😬

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
