### ISSUE TITLE
Crash When Editing an Icon With "Google Icons" Icon Pack Installed

### ISSUE THREAD

**Issue by bkazoo** [Deletescape-Media/Lawnchair#1737]
Lawnchair crashes when editing an icon with "Google Icons" icon pack installed.

## Description
On a Xiaomi Redmi Note 5A, while using the "Google Icons" pack, trying to select an icon from the pack makes Lawnchair crash. This works on other launchers (such as Lean Launcher) on the same device, but it also works on another device (Nokia 7 Plus, Android 9.0) using the same version of Lawnchair and Icon Pack.
Icon Pack: [https://play.google.com/store/apps/details?id=amirz.googleicons](https://play.google.com/store/apps/details?id=amirz.googleicons)

## Expected Behavior
Google Icons are displayed

## Actual Behavior
Lawnchair crashes

## Steps to Reproduce
1. Install "Icon Pack: Google Icons"
2. Enable icon pack in settings (set it as top preference)
3. Notice at this point that the icon pack itself does not seem to have an icon (default Android app icon)
4. Try to edit any app

or

1. Edit any icon in the desktop
2. Select "Google Icons"

## Environment
* Device: Xiaomi Redmi Note 5A
* Android version: 7.1.2
* Launcher version: 2.0-2400 (Play Store)
* Rom: MIUI Global 10.3.1 | Stable 10.3.1.0(NDFMIXM)

## Logcat
```
Lawnchair bug report 7 set. 2019 7:01:34 p. m.
Lawnchair version: 2.0-2400 (2400)
build.brand: xiaomi
build.device: ugglite
build.display: N2G47H
build.fingerprint: xiaomi/ugglite/ugglite:7.1.2/N2G47H/V10.3.1.0.NDFMIXM:user/release-keys
build.hardware: qcom
build.id: N2G47H
build.manufacturer: Xiaomi
build.model: Redmi Note 5A
build.product: ugglite
build.type: user
version.codename: REL
version.incremental: V10.3.1.0.NDFMIXM
version.release: 7.1.2
version.sdk_int: 25

error: Uncaught exception

--------- beginning of stacktrace
java.lang.ArithmeticException: divide by zero
	at android.content.res.Resources.getDrawableForDensity(Resources.java:864)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:824)
	at ch.deletescape.lawnchair.iconpack.IconPackImpl$Entry.drawableForDensity(IconPackImpl.kt:4)
	at ch.deletescape.lawnchair.iconpack.IconPack$Entry.getDrawable(IconPack.kt:1)
	at ch.deletescape.lawnchair.iconpack.IconPickerActivity$IconItem$loadIcon$1.invoke(IconPickerActivity.kt:3)
	at ch.deletescape.lawnchair.LawnchairUtilsKt$sam$java_lang_Runnable$0.run(LawnchairUtils.kt)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by marcdw1289** [comment]
I was going to open an issue until I found this one. Identical issue here using Frost icon pack from F-Droid.
Frost (Monotone icon pack) - https://f-droid.org/app/com.dkanada.icecons

When customizing an icon and I choose Frost, Lawnchair crashes.

Environment
    Device: Motorola Moto G5 Plus XT1687
    Android version: 7.1.2
    Launcher version: 2.0-2551 (Play Store)
    Rom: AOSP-CAF

Logcat
https://del.dog/odadoxitas

**Comment by marcdw1289** [comment]
Crash also happens with the following icon pack...
Ameixa (Port of TwelF CMTheme for many launchers) - https://f-droid.org/app/org.xphnx.ameixa

Same stacktrace:

```
Lawnchair bug report Jan 15, 2020 05:15:31
Lawnchair version: 2.0-2589 (2589)
build.brand: motorola
build.device: potter
build.display: cardinal_potter-userdebug 7.1.2 NZH54B 8bb06626f9 test-keys
build.fingerprint: motorola/potter/potter:7.0/NPN25.137-67/75:user/release-keys
build.hardware: qcom
build.id: NZH54B
build.manufacturer: motorola
build.model: XT1687
build.product: Moto G5 Plus
build.type: userdebug
version.codename: NOUGAT
version.incremental: 8bb06626f9
version.release: 7.1.2
version.sdk_int: 25

error: Uncaught exception

--------- beginning of stacktrace
java.lang.ArithmeticException: divide by zero
	at android.content.res.Resources.getDrawableForDensity(Resources.java:846)
	at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:806)
	at android.content.res.XResources.getDrawableForDensity(XResources.java:842)
	at ch.deletescape.lawnchair.iconpack.IconPackImpl$Entry.drawableForDensity(IconPackImpl.kt:4)
	at ch.deletescape.lawnchair.iconpack.IconPack$Entry.getDrawable(IconPack.kt:1)
	at ch.deletescape.lawnchair.iconpack.IconPickerActivity$IconItem$loadIcon$1.invoke(IconPickerActivity.kt:3)
	at ch.deletescape.lawnchair.LawnchairUtilsKt$sam$java_lang_Runnable$0.run(LawnchairUtils.kt)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by nickdvlpr** [comment]
@marcdw1289 I'm having the same problem trying to add support for an icon pack in Lawnchair. I think the issue is with Lawnchair's handling of icon packs. It looks like they are using an integer for the drawable density, but this is causing problems when they are dividing by another number. If I'm right, they should use a **float** instead to stop this "divide by zero" error.

That being said, other icon packs have been able to add support so I'm not sure what they did.

**Comment by marcdw1289** [comment]
@nickdvlpr  I forgot to mention, on my only device running Pie I have Librechair (on last non-Q oriented build) where the issue doesn't exist with Frost and Ameixa. Small consolation given that that launcher doesn't work on the devices with Lawnchair (Nougat and Oreo). I really wish this could get fixed.

To be honest I would probably be back to Nova in some cases. Despite how long it's been around it still doesn't provide a search function in the icon picker like Lawnchair and others. If one needs to search they have to bring up the icon pack's dashboard.
Over the past few years most of my ROMs are Google-free (at least GApps-free). The ones that don't use Play Store means I can't use icon packs I paid for. Or so I thought.

Discovered that all icon packs are usable, just not their dashboards which initiates the license or Play Store checks. So a working and searchable icon picker is a must on Google-free setups. Nova is out.
Years of running ROMs and here it's 2020 and still looking for something that just works. Bah!
