### ISSUE TITLE
Null pointer exception error when hold-pressing over app

### ISSUE THREAD

**Issue by CritLoren** [Deletescape-Media/Lawnchair#1756]
## Description

When I hold-press over a specific app (Vivaldi beta) the launcher crashes.

## Expected Behavior

The context menu should pop up like on every other app

## Actual Behavior

The launcher crashes as soon as the animation pops up

## Steps to Reproduce

1. Have Vivaldi beta installed
2. Hold press the icon
3. Crash
4..... Profit? 

## Environment

* Device: pocophone
* Android version: 9
* Launcher version: 2.0-2399
* Rom: crdroid 5.8

## Logcat

 

```
Lawnchair bug report 24 Sep 2019 1:11:45 am
Lawnchair version: 2.0-2399-ci-alpha (2399)
build.brand: Xiaomi
build.device: beryllium
build.display: PQ3A.190801.002
build.fingerprint: Xiaomi/beryllium/beryllium:9/PKQ1.180729.001/V10.2.3.0.PEJMIXM:user/release-keys
build.hardware: qcom
build.id: PQ3A.190801.002
build.manufacturer: Xiaomi
build.model: POCO F1
build.product: beryllium
build.type: user
version.codename: REL
version.incremental: eng.gwolf2.20190910.215055
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
kotlin.KotlinNullPointerException
	at ch.deletescape.lawnchair.iconpack.IconMask.getIcon(IconMask.kt:60)
	at ch.deletescape.lawnchair.iconpack.IconPackImpl.getIcon(IconPackImpl.kt:297)
	at ch.deletescape.lawnchair.iconpack.IconPackManager.getIcon(IconPackManager.kt:124)
	at ch.deletescape.lawnchair.iconpack.LawnchairIconProvider.getIcon(LawnchairIconProvider.kt:43)
	at com.android.launcher3.graphics.LauncherIcons.createShortcutIcon(LauncherIcons.java:364)
	at com.android.launcher3.graphics.LauncherIcons.createShortcutIcon(LauncherIcons.java:357)
	at com.android.launcher3.popup.PopupPopulator.lambda$createUpdateRunnable$3(PopupPopulator.java:161)
	at com.android.launcher3.popup.-$$Lambda$PopupPopulator$85uRll46cXVBeU850ENBL5FwS4U.run(Unknown Source:20)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
