### ISSUE TITLE
bug: frequent crashes due to NullPointerException

### ISSUE THREAD

**Issue by RonitRay** [Deletescape-Media/Lawnchair#1760]
## Description

Until quite recently, the v2 alphas worked near perfectly for me, but with the latest build(2399) I seem to be running into very frequent crashes. This usually happens when I am going back to my home screen from some other app using the back button or swiping away apps from the Android recents screen. 

## Expected Behavior

Not crashing, I guess?

## Actual Behavior

The screen goes blank for a bit before relaunching Lawnchair, and I receive a notification saying "Lawnchair crashed!".

## Steps to Reproduce

This is not exact, I don't think the same sequence of events leads to this every time.
1. Launch some other app
2. Exit it via back button/swipe away from recents screen
3. Crash.

## Environment

* Device: Xiaomi Redmi Note 4
* Android version: 7.0 NRD90M
* Launcher version: 2.0-2399-ci-alpha (2399)
* Rom: MIUI v10.2.3.0

## Logcat

 

```
Lawnchair bug report 2 Oct 2019 12:08:12 am
Lawnchair version: 2.0-2399-ci-alpha (2399)
build.brand: xiaomi
build.device: mido
build.display: AL1512-mido-build-20190128095656
build.fingerprint: xiaomi/mido/mido:7.0/NRD90M/V10.2.3.0.NCFMIXM:user/release-keys
build.hardware: qcom
build.id: NRD90M
build.manufacturer: Xiaomi
build.model: Redmi Note 4
build.product: mido
build.type: user
version.codename: REL
version.incremental: V10.2.3.0.NCFMIXM
version.release: 7.0
version.sdk_int: 24

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke virtual method 'float com.android.launcher3.anim.AnimatorPlaybackController.getProgressFraction()' on a null object reference
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onDragEnd(AbstractStateChangeTouchController.java:374)
	at com.android.launcher3.touch.SwipeDetector.reportDragEnd(SwipeDetector.java:325)
	at com.android.launcher3.touch.SwipeDetector.setState(SwipeDetector.java:126)
	at com.android.launcher3.touch.SwipeDetector.onTouchEvent(SwipeDetector.java:265)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onControllerTouchEvent(AbstractStateChangeTouchController.java:161)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:162)
	at android.view.View.dispatchTouchEvent(View.java:9958)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:247)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3193)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
	at android.view.View.dispatchPointerEvent(View.java:10180)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4494)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3899)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3952)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3918)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4045)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3926)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4102)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3899)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3952)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3918)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3926)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3899)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6306)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6278)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6239)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6414)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:329)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
