### ISSUE TITLE
Crashing while opening folder

### ISSUE THREAD

**Issue by vrnsoma** [Deletescape-Media/Lawnchair#1780]
## Description

When we make a folder in the "normal" apps tab it also shows up in the work tab, and it appears to have no apps in it...but when you tap on that folder(in work tab) the launcher crashes.

## Expected Behavior

The folder without work apps should not be shown in the work tab...I guess this is an issue with folders.

## Actual Behavior

The folder without work apps appears as empty in the work tab and upon taping it, the launcher crashes. 

## Steps to Reproduce

1.Have an active work profile
2. make a folder and put "non work" apps into it
3.switxh to the work tab
4. The folder shows up as empty an tapping it crashes the launcher. 

## Environment

* Device: LAVENDER (7s)
* Android version: 9
* Launcher version: 2.0-2506
* Rom: MIUI (global)

## Logcat

 

```
Lawnchair bug report Oct 15, 2019 3:23:55 PM
Lawnchair version: 2.0-2506 (2506)
build.brand: xiaomi
build.device: lavender
build.display: PKQ1.180904.001
build.fingerprint: xiaomi/lavender/lavender:9/PKQ1.180904.001/V10.3.7.0.PFGINXM:user/release-keys
build.hardware: qcom
build.id: PKQ1.180904.001
build.manufacturer: Xiaomi
build.model: Redmi Note 7S
build.product: lavender
build.type: user
version.codename: REL
version.incremental: V10.3.7.0.PFGINXM
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:10)
	at com.android.launcher3.folder.Folder.animateOpen(Folder.java:15)
	at com.android.launcher3.touch.ItemClickHandler.onClickFolderIcon(ItemClickHandler.java:3)
	at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:9)
	at com.android.launcher3.touch.-$$Lambda$oPqR0koj5OQZ6VtyqmfcFGp5X0Q.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by vrnsoma** [comment]
I guess there is a similar issue with empty folders, I'm not sure if this is related to that

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.

**Comment by William150722** [comment]
@vrnsoma this issues is still able to reproduce in latest Lawnchair

model:Pixel 6a
osVersion:13
sdkVersion:33
stackTrace:java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:12)
	at com.android.launcher3.folder.Folder.animateClosed(Folder.java:5)
	at com.android.launcher3.folder.Folder.handleClose(Folder.java:8)
	at com.android.launcher3.AbstractFloatingView.close(AbstractFloatingView.java:2)
	at com.android.launcher3.folder.Folder.completeDragExit(Folder.java:2)
	at com.android.launcher3.folder.Folder$8.onAlarm(Unknown Source:2)
	at com.android.launcher3.Alarm.run(Alarm.java:9)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
