### ISSUE TITLE
Issue on 7T Pro Oxygen OS 10.0.3

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1809]
Lawnchair bug report Nov 11, 2019 17:07:13
Lawnchair version: 2.0-2500-ci-alpha (2500)
build.brand: OnePlus
build.device: OnePlus7TPro
build.display: HD1913_14_191012
build.fingerprint: OnePlus/OnePlus7TPro_EEA/OnePlus7TPro:10/QKQ1.190716.003/1910120055:user/release-keys
build.hardware: qcom
build.id: QKQ1.190716.003
build.manufacturer: OnePlus
build.model: HD1913
build.product: OnePlus7TPro_EEA
build.type: user
version.codename: REL
version.incremental: 1910120055
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ThreadedRenderer$FrameDrawingCallback;
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:668)
	at ch.deletescape.lawnchair.animations.LawnchairAppTransitionManagerImpl.getOpeningWindowAnimators(LawnchairAppTransitionManagerImpl.kt:298)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:639)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.access$300(LauncherAppTransitionManagerImpl.java:96)
	at com.android.launcher3.LauncherAppTransitionManagerImpl$2.onCreateAnimation(LauncherAppTransitionManagerImpl.java:220)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$0$LauncherAnimationRunner(LauncherAnimationRunner.java:56)
	at com.android.launcher3.-$$Lambda$LauncherAnimationRunner$0IBM3bZEOrCXQUatxthdQPQcNQA.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.ThreadedRenderer$FrameDrawingCallback" on path: DexPathList[[zip file "/data/app/ch.deletescape.lawnchair.ci-Knq_LSEQe00ZV-UpuRlGlQ==/base.apk"],nativeLibraryDirectories=[/data/app/ch.deletescape.lawnchair.ci-Knq_LSEQe00ZV-UpuRlGlQ==/lib/arm64, /data/app/ch.deletescape.lawnchair.ci-Knq_LSEQe00ZV-UpuRlGlQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
