### ISSUE TITLE
crash when entering desktop line/column adjusting

### ISSUE THREAD

**Issue by JJPandari** [Deletescape-Media/Lawnchair#1818]
## Description

I'm using a localized(Chinese) version so not sure which word to use for every term.

## Expected Behavior

can adjust desktop column/line numbers after clicking `matrix size\n5x5`

## Actual Behavior

crashes when I click `matrix size\n5x5`

## Steps to Reproduce

1.->settings
2.->desktop
3.click `matrix size\n5x5`

## Environment

* Device: oneplus 7 pro (guacamole)
* Android version: 10
* Launcher version: 2.0-2546-ci-q-pre-alpha
* Rom: H2OS `OP7PRO_H2_BETA_4` https://www.h2os.com/download

## Logcat

 

```
Lawnchair bug report 2019年11月17日 12:14:54 Lawnchair version: 2.0-2546-ci-q-pre-alpha (2546) build.brand: OnePlus build.device: OnePlus7Pro build.display: GM1910_21_191030 build.fingerprint: OnePlus/OnePlus7Pro_CH/OnePlus7Pro:10/QKQ1.190716.003/1910280100:user/release-keys build.hardware: qcom build.id: QKQ1.190716.003 build.manufacturer: OnePlus build.model: GM1910 build.product: OnePlus7Pro_CH build.type: user version.codename: REL version.incremental: 1910280100 version.release: 10 version.sdk_int: 29 error: Uncaught exception --------- beginning of stacktrace java.lang.IllegalArgumentException: Cannot find BaseActivity in parent tree  at com.android.launcher3.BaseActivity.fromContext(BaseActivity.java:282)  at com.android.launcher3.BaseActivity.fromContext(BaseActivity.java:280)  at com.android.launcher3.BaseActivity.fromContext(BaseActivity.java:280)  at com.android.launcher3.Launcher.getLauncher(Launcher.java:2649)  at ch.deletescape.lawnchair.allapps.BlurQsbLayout$hotseat$2.invoke(BlurQsbLayout.kt:91)  at ch.deletescape.lawnchair.allapps.BlurQsbLayout$hotseat$2.invoke(BlurQsbLayout.kt:44)  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)  at ch.deletescape.lawnchair.allapps.BlurQsbLayout.getHotseat(Unknown Source:7)  at ch.deletescape.lawnchair.allapps.BlurQsbLayout.getBgColor(BlurQsbLayout.kt:168)  at ch.deletescape.lawnchair.allapps.BlurQsbLayout.drawQsb(BlurQsbLayout.kt:151)  at com.google.android.apps.nexuslauncher.qsb.AbstractQsbLayout.draw(AbstractQsbLayout.java:314)  at android.view.View.draw(View.java:21468)  at android.view.ViewGroup.drawChild(ViewGroup.java:4413)  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)  at android.view.View.draw(View.java:21466)  at android.view.ViewGroup.drawChild(ViewGroup.java:4413)  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)  at android.view.View.draw(View.java:21597)  at com.android.launcher3.graphics.LauncherPreviewRenderer$MainThreadRenderer.renderScreenShot(LauncherPreviewRenderer.java:285)  at com.android.launcher3.graphics.LauncherPreviewRenderer$MainThreadRenderer.access$700(LauncherPreviewRenderer.java:137)  at com.android.launcher3.graphics.LauncherPreviewRenderer.lambda$null$0$LauncherPreviewRenderer(LauncherPreviewRenderer.java:124)  at com.android.launcher3.graphics.-$$Lambda$LauncherPreviewRenderer$lej9cY8b8IG7lvr57mpfGik_hNs.run(Unknown Source:6)  at android.os.Handler.handleCallback(Handler.java:883)  at android.os.Handler.dispatchMessage(Handler.java:100)  at android.os.Looper.loop(Looper.java:214)  at android.app.ActivityThread.main(ActivityThread.java:7682)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by JJPandari** [comment]
No longer happens @ 2.1-2599-ci-q-pre-alpha
