### ISSUE TITLE
NullPointerException on dragging app out of folder

### ISSUE THREAD

**Issue by egvimo** [Deletescape-Media/Lawnchair#1824]
## Description
I wanted to drag an app out of a folder on the home screen. After I touched it and started dragging Lawnchair crashed with the NPE. After the restart of Lawnchair pulling the app out of the folder worked like it should. I couldn't reproduce the error.

## Environment
See log.

## Logcat

 

```
Lawnchair bug report 19.11.2019 20:05:09
Lawnchair version: 2.0-2551 (2551)
build.brand: google
build.device: blueline
build.display: QP1A.191105.003
build.fingerprint: google/blueline/blueline:10/QP1A.191105.003/5899767:user/release-keys
build.hardware: blueline
build.id: QP1A.191105.003
build.manufacturer: Google
build.model: Pixel 3
build.product: blueline
build.type: user
version.codename: REL
version.incremental: 5899767
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference
	at com.android.launcher3.Workspace.onDragStart(Workspace.java:2)
	at com.android.launcher3.dragndrop.DragController.callOnDragStart(DragController.java:5)
	at com.android.launcher3.dragndrop.DragController.handleMoveEvent(DragController.java:12)
	at com.android.launcher3.dragndrop.DragController.onDriverDragMove(DragController.java:2)
	at com.android.launcher3.dragndrop.DragDriver.onTouchEvent(DragDriver.java:3)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(DragController.java:9)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:6)
	at android.view.View.dispatchTouchEvent(View.java:13430)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3993)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:13689)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7581)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7654)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:718)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by bill-mcgonigle** [comment]
Possibly broader on Q?
https://del.dog/ydoppemeca

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
