### ISSUE TITLE
[BUG] Null pointer exception when trying to drag app from drawer to home screen

### ISSUE THREAD

**Issue by thewithz** [Deletescape-Media/Lawnchair#1870]
Lawnchair bug report Dec 9, 2019 11:57:44
Lawnchair version: 2.0-2589 (2589)
build.brand: google
build.device: taimen
build.display: QP1A.191105.004
build.fingerprint: google/taimen/taimen:10/QP1A.191105.004/5908170:user/release-keys
build.hardware: taimen
build.id: QP1A.191105.004
build.manufacturer: Google
build.model: Pixel 2 XL
build.product: taimen
build.type: user
version.codename: REL
version.incremental: 5908170
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference
	at com.android.launcher3.Workspace.onDragStart(Workspace.java:2)
	at com.android.launcher3.dragndrop.DragController.callOnDragStart(DragController.java:5)
	at com.android.launcher3.dragndrop.DragController.startDrag(DragController.java:38)
	at com.android.launcher3.widget.PendingItemDragHelper.startDrag(PendingItemDragHelper.java:40)
	at com.android.launcher3.dragndrop.BaseItemDragListener.onDragStart(BaseItemDragListener.java:7)
	at com.android.launcher3.dragndrop.BaseItemDragListener.onDrag(BaseItemDragListener.java:3)
	at android.view.View.callDragEventHandler(View.java:25642)
	at android.view.View.dispatchDragEvent(View.java:25633)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1700)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1846)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1693)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6724)
	at android.view.ViewRootImpl.access$1200(ViewRootImpl.java:142)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4587)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by thewithz** [comment]
A few things of note:
I have turned *on* the locked desktop setting. 
The desktop I was dragging to was completely full. 

I was under the impression that even if the desktop is locked, I would still be able to add apps to dock folders, but that doesn't seem to be the case.

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
