### ISSUE TITLE
Bing search is broken

### ISSUE THREAD

**Issue by electricduck** [Deletescape-Media/Lawnchair#1896]
## Description
With the search engine set to **Bing** -- I know, deary me -- with the Bing app installed (10.7.27268702), Lawnchair crashes when tapping on the search. Weirdly, the voice search button works fine, and correctly opens Bing's voice search. ~~Lawnchair doesn't seem to be producing any logs of the crash either.~~ [Log provided below](https://github.com/LawnchairLauncher/Lawnchair/issues/1896#issuecomment-570915649).

## Steps to Reproduce
1. Have [Bing](https://play.google.com/store/apps/details?id=com.microsoft.bing) installed
2. Open **Settings > Search > Search Engine**
3. Select **Bing** (not **Bing (In Browser)**)
4. Go back home and tap the search box

## Environment
* Device: Xiaomi Mi A3
* Android version: 9.0 (Android One)
* Launcher version: 2.0-2589

**Comment by bohrabhijeet** [comment]
@electricduck Try using the [Scoop](https://del.dog/scoop) app to record logs of the crash.

**Comment by electricduck** [comment]
```
FATAL EXCEPTION: main
Process: ch.deletescape.lawnchair.plah, PID: 15642
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.microsoft.bing/com.microsoft.clients.bing.widget.WidgetSearchActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
	at android.app.Activity.startActivityForResult(Activity.java:4587)
	at com.android.launcher3.Launcher.startActivityForResult(Launcher.java:1)
	at android.app.Activity.startActivity(Activity.java:4902)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:401)
	at com.google.android.apps.nexuslauncher.qsb.HotseatQsbWidget.lambda$doOnClick$0$HotseatQsbWidget(HotseatQsbWidget.java:2)
	at com.google.android.apps.nexuslauncher.qsb.-$$Lambda$HotseatQsbWidget$zRLsKLeW8JIL8qmzBSLMo_dtA5c.invoke(Unknown Source:4)
	at ch.deletescape.lawnchair.globalsearch.providers.BingSearchProvider.startSearch(BingSearchProvider.kt:1)
	at com.google.android.apps.nexuslauncher.qsb.HotseatQsbWidget.startSearch(HotseatQsbWidget.java:15)
	at com.google.android.apps.nexuslauncher.qsb.AbstractQsbLayout.onClick(AbstractQsbLayout.java:14)
	at com.google.android.apps.nexuslauncher.qsb.HotseatQsbWidget.onClick(HotseatQsbWidget.java:1)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25889)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by electricduck** [comment]
Out of absolutely nowhere, without an update to the Bing app or Lawnchair, it suddenly began working again. Gonna keep an eye on it though!

**Comment by electricduck** [comment]
Closing this. The issue has vanished all by itself somehow.
