### ISSUE TITLE
Search hidden shortcut icon issue

### ISSUE THREAD

**Issue by JeelsBoobz** [Deletescape-Media/Lawnchair#1897]
## Description

I have hidden shortcut icon and after search hidden apps i have problem
Lawnchair force close

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Redmi Note 4 Snapdragon (mido)
* Android version: 10
* Launcher version: 2.1-2599-ci-q-pre-alpha
* Rom: Havoc 3.0

## Logcat

 

```
Lawnchair bug report Jan 6, 2020 13:55:42
Lawnchair version: 2.1-2599-ci-q-pre-alpha (212599)
build.brand: Xiaomi
build.device: mido
build.display: QQ1B.191205.011
build.fingerprint: xiaomi/mido/mido:7.0/NRD90M/V9.6.1.0.NCFMIFD:user/release-keys
build.hardware: qcom
build.id: QQ1B.191205.011
build.manufacturer: Xiaomi
build.model: Redmi Note 4
build.product: havoc_mido
build.type: user
version.codename: REL
version.incremental: eng.SagarR.20191223.092413
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.IllegalStateException: Cache accessed on wrong thread Looper (main, tid 2) {a5a669c}
	at com.android.launcher3.icons.cache.BaseIconCache.assertWorkerThread(BaseIconCache.java:560)
	at com.android.launcher3.icons.cache.BaseIconCache.cacheLocked(BaseIconCache.java:316)
	at com.android.launcher3.icons.cache.BaseIconCache.cacheLocked(BaseIconCache.java:308)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:210)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:191)
	at com.android.launcher3.allapps.AlphabeticalAppsList.getFiltersAppInfos(AlphabeticalAppsList.java:555)
	at com.android.launcher3.allapps.AlphabeticalAppsList.refillAdapterItems(AlphabeticalAppsList.java:433)
	at com.android.launcher3.allapps.AlphabeticalAppsList.updateAdapterItems(AlphabeticalAppsList.java:376)
	at com.android.launcher3.allapps.AlphabeticalAppsList.onAppsUpdated(AlphabeticalAppsList.java:368)
	at com.android.launcher3.allapps.AlphabeticalAppsList.setOrderedFilter(AlphabeticalAppsList.java:295)
	at com.google.android.apps.nexuslauncher.qsb.FallbackAppsSearchView.onSearchResult(FallbackAppsSearchView.java:54)
	at com.google.android.apps.nexuslauncher.search.SearchThread.handleMessage(SearchThread.java:97)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by RikKoedoot** [comment]
closing the issue as we are focusing efforts on lawnchair 12
