### ISSUE TITLE
[BUG] Launcher cannot start and constantly crashes

### ISSUE THREAD

**Issue by romaroman** [Deletescape-Media/Lawnchair#1921]
## Descipriton
After switching provider to Lawnchair in QuickSwitch and rebooting both Pixel Launcher and Lawnchair constantly crashing

## Environment

* Device: Xiaomi Mi 9T (davinci)
* Android version:
* Launcher version: 2.1-2599-ci-q-pre-alpha
* Rom: Pixel Experience 20200124
* QuickSwitch 3.0+ (tested on almost every version)

## Logcat
Lawnchair bug report Jan 27, 2020 19:26:43
Lawnchair version:  (212599)
build.brand: Xiaomi
build.device: davinci
build.display: QQ1B.200105.004
build.fingerprint: google/coral/coral:10/QQ1B.200105.004/6031802:user/release-keys
build.hardware: qcom
build.id: QQ1B.200105.004
build.manufacturer: Xiaomi
build.model: Mi 9T
build.product: aosp_davinci
build.type: user
version.codename: REL
version.incremental: 45e29025c3
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Trying to create invalid component key: notion_id
	at com.android.launcher3.Utilities.makeComponentKey(Utilities.java:1163)
	at ch.deletescape.lawnchair.iconpack.DefaultPack.newIcon(DefaultPack.kt:160)
	at ch.deletescape.lawnchair.iconpack.IconPackManager.newIcon(IconPackManager.kt:138)
	at ch.deletescape.lawnchair.iconpack.LawnchairDrawableFactory.newIcon(LawnchairDrawableFactory.kt:36)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:379)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:342)
	at com.android.launcher3.BubbleTextView.applyFromWorkspaceItem(BubbleTextView.java:326)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1184)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1170)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:2093)
	at com.android.launcher3.model.BaseLoaderResults.lambda$bindWorkspaceItems$6(BaseLoaderResults.java:263)
	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$k7Ikxsm2upd4TEbQqLlOrd7Q5Oc.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLoaderResults.lambda$executeCallbacksTask$9$BaseLoaderResults(BaseLoaderResults.java:297)
	at com.android.launcher3.model.-$$Lambda$BaseLoaderResults$2nIUDOkJsQI01fjwU7tbsouXsVI.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by DanGLVK** [comment]
@romaroman it's a known icon pack related crash on the prealphas, try accessing lawnchair settings by going into
Settings > Apps & Notifications > All apps > Lawnchair > Additional settings in app and resetting custom icons, if that doesn't work then clear Lanwchair's data

and for the moment i would highly discourage making/restoring backups that have icons packs

**Comment by romaroman** [comment]
> @romaroman it's a known icon pack related crash on the prealphas, try accessing lawnchair settings by going into
> Settings > Apps & Notifications > All apps > Lawnchair > Additional settings in app and resetting custom icons, if that doesn't work then clear Lanwchair's data
> 
> and for the moment i would highly discourage making/restoring backups that have icons packs

Thank you, worked out!

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
