### ISSUE TITLE
Lawnchair loads for a few seconds and then crashes upon startup

### ISSUE THREAD

**Issue by azucchann** [Deletescape-Media/Lawnchair#1925]
## Description

It was working fine until I had to restart my phone. From there, it would load for a few seconds and then crash on startup, citing a NullPointerException. No updates, no new installs, just my phone dying and then when turned on, it crashes every time.

## Expected Behavior

It should ideally just launch and show the homescreen.

## Actual Behavior

Crashes citing nullpointerexception, and creating an invalid component key.

## Steps to Reproduce

1. Launch

## Environment

* Device: Samsung Galaxy A7 (2018)
* Android version: Android 9.0.0
* Launcher version: Lawnchair 2 2.1
* Rom:

## Logcat

 

```
Lawnchair bug report Jan 31, 2020 12:47:44 PM
Lawnchair version: 2.1-2599-ci-q-pre-alpha (212599)
build.brand: samsung
build.device: a7y18lte
build.display: PPR1.180610.011.A750GNDXS5BTA1
build.fingerprint: samsung/a7y18ltedx/a7y18lte:9/PPR1.180610.011/A750GNDXS5BTA1:user/release-keys
build.hardware: samsungexynos7885
build.id: PPR1.180610.011
build.manufacturer: samsung
build.model: SM-A750GN
build.product: a7y18ltedx
build.type: user
version.codename: REL
version.incremental: A750GNDXS5BTA1
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Trying to create invalid component key: samsung_rewards
	at com.android.launcher3.Utilities.makeComponentKey(Utilities.java:1163)
	at ch.deletescape.lawnchair.iconpack.DefaultPack.newIcon(DefaultPack.kt:160)
	at ch.deletescape.lawnchair.iconpack.IconPackManager.newIcon(IconPackManager.kt:138)
	at ch.deletescape.lawnchair.iconpack.LawnchairDrawableFactory.newIcon(LawnchairDrawableFactory.kt:36)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:379)
	at com.android.launcher3.BubbleTextView.applyFromApplicationInfo(BubbleTextView.java:353)
	at com.android.launcher3.BubbleTextView.reapplyItemInfo(BubbleTextView.java:800)
	at com.android.launcher3.icons.IconCache$1.lambda$run$0$IconCache$1(IconCache.java:141)
	at com.android.launcher3.icons.-$$Lambda$IconCache$1$uzM_TiIBOiYHLEDTHkJULvj6i9c.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
