### ISSUE TITLE
Crash on returning home

### ISSUE THREAD

**Issue by mh0pe** [Deletescape-Media/Lawnchair#1943]
It's just a null check missing.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```
Lawnchair bug report Feb 16, 2020 7:43:56 AM
Lawnchair version: 2.1-2599-ci-q-pre-alpha (212599)
build.brand: OnePlus
build.device: OnePlus7TProNR
build.display: HD1925_46_200110
build.fingerprint: OnePlus/OnePlus7TProNR/OnePlus7TProNR:10/QKQ1.190716.003/2001101147:user/release-keys
build.hardware: qcom
build.id: QKQ1.190716.003
build.manufacturer: OnePlus
build.model: HD1925
build.product: OnePlus7TProNR
build.type: user
version.codename: REL
version.incremental: 2001101147
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
kotlin.TypeCastException: null cannot be cast to non-null type com.android.launcher3.CellLayout
	at ch.deletescape.lawnchair.ClockVisibilityManager.onWorkspacePageChanged(ClockVisibilityManager.kt:72)
	at com.android.launcher3.Workspace.setCurrentPage(Workspace.java:3422)
	at com.android.launcher3.PagedView.snapToPage(PagedView.java:1480)
	at com.android.launcher3.PagedView.snapToPage(PagedView.java:1470)
	at com.android.launcher3.PagedView.snapToPage(PagedView.java:1457)
	at com.android.launcher3.PagedView.snapToPage(PagedView.java:1449)
	at com.android.launcher3.uioverrides.touchcontrollers.FlingAndHoldTouchController.onDragEnd(FlingAndHoldTouchController.java:209)
	at com.android.launcher3.touch.SwipeDetector.reportDragEnd(SwipeDetector.java:394)
	at com.android.launcher3.touch.SwipeDetector.setState(SwipeDetector.java:174)
	at com.android.launcher3.touch.SwipeDetector.onTouchEvent(SwipeDetector.java:330)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onControllerTouchEvent(AbstractStateChangeTouchController.java:164)
	at com.android.launcher3.views.BaseDragLayer.proxyTouchEvent(BaseDragLayer.java:301)
	at com.android.quickstep.inputconsumers.OverviewInputConsumer.lambda$v3Xpt2f2_jzgJA9LPEZXy3ub-ng(Unknown Source:0)
	at com.android.quickstep.inputconsumers.-$$Lambda$OverviewInputConsumer$v3Xpt2f2_jzgJA9LPEZXy3ub-ng.test(Unknown Source:4)
	at com.android.quickstep.inputconsumers.OverviewInputConsumer.onMotionEvent(OverviewInputConsumer.java:94)
	at com.android.quickstep.TouchInteractionService.onInputEvent(TouchInteractionService.java:651)
	at com.android.quickstep.TouchInteractionService.lambda$5N8OpQhfWV7_tkhenf8Ys3ECXWs(Unknown Source:0)
	at com.android.quickstep.-$$Lambda$TouchInteractionService$5N8OpQhfWV7_tkhenf8Ys3ECXWs.onInputEvent(Unknown Source:2)
	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:85)
	at xyz.paphonb.quickstep.compat.ten.InputCompatVQ$1.onInputEvent(InputCompatVQ.java:28)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
