### ISSUE TITLE
[Bug] Crash on launch

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1955]
## Description

[Bug] Crash on launch 

## Steps to Reproduce

1.launch it

## Environment

* Device: Nexus 7 flo
* Android version: 7.1.2
* Launcher version: 2.1-2616-ci-q-pre-alpha
* Rom: aokp_flo_nightly_2019-11-12_1232

## Logcat

 

```

Lawnchair bug report 9 march 2020 8:51:18
Lawnchair version: 2.1-2616-ci-q-pre-alpha (212616)
build.brand: google
build.device: flo
build.display: aokp_flo-userdebug 7.1.2 NJH47F d219eb530b test-keys
build.fingerprint: google/razor/flo:6.0.1/MOB30X/3036618:user/release-keys
build.hardware: flo
build.id: NJH47F
build.manufacturer: asus
build.model: Nexus 7
build.product: razor
build.type: user
version.codename: REL
version.incremental: d219eb530b
version.release: 7.1.2
version.sdk_int: 25
display.density_dpi: 320

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
	at com.android.systemui.shared.plugins.PluginManagerImpl.invoke(PluginManagerImpl.java:468)
	at com.android.systemui.shared.plugins.PluginManagerImpl.<init>(PluginManagerImpl.java:90)
	at com.android.launcher3.uioverrides.plugins.PluginManagerWrapper.<init>(PluginManagerWrapper.java:43)
	at com.android.launcher3.uioverrides.plugins.PluginManagerWrapper.lambda$BPQstKVZHu0UxNfm4Ke1dhRqRVc(PluginManagerWrapper.java)
	at com.android.launcher3.uioverrides.plugins.-$$Lambda$PluginManagerWrapper$BPQstKVZHu0UxNfm4Ke1dhRqRVc.get(lambda)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:42)
	at com.android.launcher3.allapps.FloatingHeaderView.onAttachedToWindow(FloatingHeaderView.java:136)
	at android.view.View.dispatchAttachedToWindow(View.java:15513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)```

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
