### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by fomalsd** [Deletescape-Media/Lawnchair#2015]
Not sure what I did to cause this, but:
```
Lawnchair version: 2.1-2627-ci-q-merge (212627)
build.manufacturer: Google
build.model: Pixel 4
build.product: flame
version.release: 10
version.sdk_int: 29

error: Uncaught exception

--------- beginning of stacktrace
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.android.launcher3.allapps.AlphabeticalAppsList.refillAdapterItems(AlphabeticalAppsList.java:436)
	at com.android.launcher3.allapps.AlphabeticalAppsList.lambda$updateAdapterItems$0$AlphabeticalAppsList(AlphabeticalAppsList.java:378)
	at com.android.launcher3.allapps.-$$Lambda$AlphabeticalAppsList$0oW039EACEyqwnxmY69EZ44W6Kc.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
