### ISSUE TITLE
[BUG]Shortcuts instantly disappear after placing on home screen

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2020]
Whenever I put a web page or other shortcut on home screen, it disappears.

## Description
It is obvious that this should not happen.

## Expected Behavior

It should stay there.

## Actual Behavior

It disappears.

## Steps to Reproduce

1.Open Chrome
2.Open a web page(any)
3.Click on three dots on top
4.Click on "Add to home screen" 

## Environment

* Device:Xiaomi Redmi Note 5 Pro
* Android version:9.0
* Launcher version:Lawnchair 2.1-2627-ci-q-merge
* Rom:MIUI 11

## Logcat

 

```
your log here
```

**Comment by ziddey** [comment]
https://github.com/LawnchairLauncher/Lawnchair/issues/111

**Comment by MarcoDjallo** [comment]
Can confirm this, every shortcut disappears after a second. The only shortcut that seems to survive a little longer is the one pointing to Lawnchair settings.

**Comment by rodrigost23** [comment]
I have the same issue. The error below appears in logcat, and it seems related to it:
<big><pre>
**Activity com.android.launcher3.dragndrop.AddItemActivity has leaked IntentReceiver com.google.android.apps.nexuslauncher.DynamicIconProvider$1@a1a7135 that was originally registered here. Are you missing a call to unregisterReceiver()?**
android.app.IntentReceiverLeaked: Activity com.android.launcher3.dragndrop.AddItemActivity has leaked IntentReceiver com.google.android.apps.nexuslauncher.DynamicIconProvider$1@a1a7135 that was originally registered here. Are you missing a call to unregisterReceiver()?
 at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1593)
 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1373)
 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:640)
 at com.google.android.apps.nexuslauncher.DynamicIconProvider.<init>(DynamicIconProvider.java:57)
 at ch.deletescape.lawnchair.iconpack.LawnchairIconProvider.<init>([LawnchairIconProvider.kt:30](https://github.com/LawnchairLauncher/Lawnchair/blob/87c0ab17050bca7fe354bf99d41a461b04aa9958/lawnchair/src/ch/deletescape/lawnchair/iconpack/LawnchairIconProvider.kt#L30))
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at com.android.launcher3.util.ResourceBasedOverride$Overrides.getObject(ResourceBasedOverride.java:40)
 at com.android.launcher3.IconProvider.newInstance(IconProvider.java:13)
 at com.android.launcher3.dragndrop.PinShortcutRequestActivityInfo.<init>(PinShortcutRequestActivityInfo.java:65)
 at com.android.launcher3.dragndrop.AddItemActivity.setupShortcut(AddItemActivity.java:204)
 at com.android.launcher3.dragndrop.AddItemActivity.onCreate(AddItemActivity.java:121)
 at android.app.Activity.performCreate(Activity.java:7825)
 at android.app.Activity.performCreate(Activity.java:7814)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7397)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
</pre></big>

**Comment by katspanos** [comment]
Still happens to me. After several updates this bug is not fixed.

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
