### ISSUE TITLE
Long pressing Bromite crashes app

### ISSUE THREAD

**Issue by ssakuh** [Deletescape-Media/Lawnchair#2026]
## Description

When long pressing the app icon for Bromite, the app crashes with this log:

https://del.dog/cahetingon

## Expected Behavior

Should be able to move app icon.

## Actual Behavior

App crashes with error pasted below.

## Steps to Reproduce

1. Install Bromite from F-Droid
2. Long press its shortcut from within app drawer or homescreen
3. Crash

## Environment

* Device: Huawei P20 Pro
* Android version: 10
* Launcher version: 2.1-2616-ci-q-pre-alpha (212616)
* Rom: OpenKirin GSI AOSPExtended

## Logcat

 

```
Lawnchair bug report Jul 28, 2020 11:48:55
Lawnchair version: 2.1-2616-ci-q-pre-alpha (212616)
build.brand: HUAWEI
build.device: HWCLT
build.display: OpenKirin-AntiEng 10 FGApps b1 patch1 release-keys
build.fingerprint: HUAWEI/BLA-L29/HWBLA:8.0.0/HUAWEIBLA-L29S/137(C432):user/release-keys
build.hardware: kirin970
build.id: AntiEng.FGApps.b1
build.manufacturer: HUAWEI
build.model: CLT-L09
build.product: CLT-L09
build.type: user
version.codename: REL
version.incremental: 264b7a9ad2
version.release: 10
version.sdk_int: 29
display.density_dpi: 329

error: Uncaught exception

--------- beginning of stacktrace
java.lang.IllegalStateException: super.getShortcutIconDraâ¦le(shortcutInfo, density) must not be null
	at ch.deletescape.lawnchair.shortcuts.LawnchairShortcutManager.getShortcutIconDrawable(LawnchairShortcutManager.kt:86)
	at com.android.launcher3.icons.LauncherIcons.createShortcutIcon(LauncherIcons.java:130)
	at com.android.launcher3.icons.LauncherIcons.createShortcutIcon(LauncherIcons.java:124)
	at com.android.launcher3.popup.PopupPopulator.lambda$createUpdateRunnable$3(PopupPopulator.java:153)
	at com.android.launcher3.popup.-$$Lambda$PopupPopulator$6Pl_Lwy4YCKq_NKKw2xaJhCokkU.run(Unknown Source:16)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by quamok** [comment]
For me bromite is fine, but I'm having the exact same issue with an app named Joplin.

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
