### ISSUE TITLE
[crash] when opening any app

### ISSUE THREAD

**Issue by mirsella** [Deletescape-Media/Lawnchair#2046]
## Description
when launching a any application from lawnchair, the launcher crash. the default launcher goes back to pixel launcher.
I can't use lawnchair since it I can't open any app with it.

## Expected Behavior
don't crash when opening a app so i can go back to the laucher when pressing home

## Actual Behavior
it open the app but crash too

## Steps to Reproduce
install lawnchair
set it to default or not, it crash for both
launch any app (even long click -> launcher settings)

## Environment
Device: Xiaomi MI9T pro
Android version : 10
ROM : EvolutionX 27/08 (it was working before, but i clean flashed because hotpost wasn't working properly and now it crash)
Launcher version : 2.0-2589 from playstore

## Logcat
https://del.dog/ducexanodo
```
time: 1599409685060
msg: java.lang.ClassNotFoundException: android.view.ThreadedRenderer$FrameDrawingCallback
stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/ThreadedRenderer$FrameDrawingCallback;
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:23)
	at ch.deletescape.lawnchair.animations.LawnchairAppTransitionManagerImpl.getOpeningWindowAnimators(LawnchairAppTransitionManagerImpl.kt:2)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.getOpeningWindowAnimators(LauncherAppTransitionManagerImpl.java:1)
	at com.android.launcher3.LauncherAppTransitionManagerImpl.access$300(LauncherAppTransitionManagerImpl.java:1)
	at com.android.launcher3.LauncherAppTransitionManagerImpl$2.onCreateAnimation(LauncherAppTransitionManagerImpl.java:12)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$0$LauncherAnimationRunner(LauncherAnimationRunner.java:3)
	at com.android.launcher3.-$$Lambda$LauncherAnimationRunner$0IBM3bZEOrCXQUatxthdQPQcNQA.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
Caused by: java.lang.ClassNotFoundException: android.view.ThreadedRenderer$FrameDrawingCallback
	... 14 more
```

i got this log with logcat Extreme : https://drive.google.com/file/d/1-0TqyphOJcHbeb06g3Mb8vuHOOnytjBw/view?usp=sharing

thanks. I hope you have the time to look into it

**Comment by mirsella** [comment]
I tried to download the latest version from apkmirror which is 212627 from june 2, first launch it crash with an out of bound on smartspace something, but after it work, i'm closing since it fixed for later version. thanks
