### ISSUE TITLE
Andriod 11 crash

### ISSUE THREAD

**Issue by Thomvr** [Deletescape-Media/Lawnchair#2068]
I use a oneplus 8 pro. Just updated to Oxygen os 11. After updating if i want to use lawnchair all apps crash the launcher as soon as you open an app.

Lawnchair bug report 23 Oct 2020 12:44:45
Lawnchair version: 2.1-2627-ci-q-merge (212627)
build.brand: OnePlus
build.device: OnePlus8Pro
build.display: IN2023_15_200930
build.fingerprint: OnePlus/OnePlus8Pro_EEA/OnePlus8Pro:11/RP1A.201005.001/2009301800:user/release-keys
build.hardware: qcom
build.id: RP1A.201005.001
build.manufacturer: OnePlus
build.model: IN2023
build.product: OnePlus8Pro_EEA
build.type: user
version.codename: REL
version.incremental: 2009301800
version.release: 11
version.sdk_int: 30
display.density_dpi: 560

error: Uncaught exception

--------- beginning of stacktrace
java.lang.NoSuchMethodError: No static method write(IIII[BZ)I in class Landroid/util/StatsLog; or its super classes (declaration of 'android.util.StatsLog' appears in /apex/com.android.os.statsd/javalib/framework-statsd.jar)
	at com.android.systemui.shared.system.StatsLogCompat.write(StatsLogCompat.java:34)
	at com.android.quickstep.logging.StatsLogCompatManager.logAppLaunch(StatsLogCompatManager.java:63)
	at com.android.launcher3.BaseDraggingActivity.startActivitySafely(BaseDraggingActivity.java:181)
	at com.android.launcher3.Launcher.startActivitySafely(Launcher.java:1883)
	at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(ItemClickHandler.java:294)
	at com.android.launcher3.touch.ItemClickHandler.onClickAppShortcut(ItemClickHandler.java:263)
	at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:93)
	at com.android.launcher3.touch.ItemClickHandler.lambda$getInstance$0(ItemClickHandler.java:78)
	at com.android.launcher3.touch.-$$Lambda$ItemClickHandler$_rHy-J5yxnvGlFKWSh6CdrSf-lA.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7493)
	at android.view.View.performClickInternal(View.java:7462)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28475)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:7945)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by ibnu-ja** [comment]
I can confirm this
https://del.dog/styloregit

**Comment by RikoDEV** [comment]
Same: https://del.dog/icryruniwo

**Comment by artizirk** [comment]
so, i found the offending code and deleted it here, seems to work on my samsung s10e 
* https://github.com/artizirk/Lawnchair/tree/android11-fix

Attatched is a q-merge branch based apk that sorta works

[Lawnchair-aosp-withQuickstep-lawnchair-dev-optimized.zip](https://github.com/LawnchairLauncher/Lawnchair/files/5937026/Lawnchair-aosp-withQuickstep-lawnchair-dev-optimized.zip)

i still have no clue on how to get google news feed working with this apk and backup restore crashed

**Comment by JediRhymeTrix** [comment]
+1 Samsung Galaxy Z Fold2 running Android 11 (OneUI 3.0)

Same stacktrace

**Comment by BenDevelopment** [comment]
Same with OnePlus 8T running OxygenOS 11.

**Comment by artizirk** [comment]
@JediRhymeTrix @BenDevelopment does using the apk in the attached zip fix this issue?

**Comment by Ikkyul** [comment]
I cannot add widget to the dock like before. Any work around?

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
