### ISSUE TITLE
[bug] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by fm-sys** [Deletescape-Media/Lawnchair#2076]
## Description

I did nearly nothing, but for some reason Lawnchair crashed right after granting widget permission...

## Logcat

 

```
Lawnchair bug report 04.02.2021 18:28:30
Lawnchair version: 2.0-dev (1)
build.brand: HUAWEI
build.device: HWSNE
build.display: SNE-LX1 10.0.0.245(C432E10R1P1)
build.fingerprint: HUAWEI/SNE-LX1/HWSNE:10/HUAWEISNE-L21/10.0.0.245C432:user/release-keys
build.hardware: kirin710
build.id: HUAWEISNE-L21
build.manufacturer: HUAWEI
build.model: SNE-LX1
build.product: SNE-LX1
build.type: user
version.codename: REL
version.incremental: 10.0.0.245C432
version.release: 10
version.sdk_int: 29


error: Uncaught exception


--------- beginning of stacktrace
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
 at java.util.ArrayList.get(ArrayList.java:437)
 at ch.deletescape.lawnchair.smartspace.SmartspaceDataWidget$SmartspaceWidgetHostView.updateAppWidget(SmartspaceDataWidget.kt:176)
 at android.appwidget.AppWidgetHost.updateAppWidgetView(AppWidgetHost.java:453)
 at android.appwidget.AppWidgetHost$UpdateHandler.handleMessage(AppWidgetHost.java:143)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:213)
 at android.app.ActivityThread.main(ActivityThread.java:8178)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by charlesmema** [comment]
Same, literally did nothing. Did you fixed it?

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
