### ISSUE TITLE
[BUG]Uncaught exception, IndexOutOfBound

### ISSUE THREAD

**Issue by charlesmema** [Deletescape-Media/Lawnchair#2090]
Also my realme 6 pro doesn't detect newly installed launchers, making the default launcher unchangeable.

Lawnchair bug report 13 Mar 2021 11:00:52 pm
Lawnchair version: 10.0 Alpha 8 (10002926)
build.brand: realme
build.device: RMX2061L1
build.display: RMX2061_11_A.41
build.fingerprint: realme/RMX2061/RMX2061L1:10/QKQ1.191222.002/1605989499:user/release-keys
build.hardware: qcom
build.id: QKQ1.191222.002
build.manufacturer: realme
build.model: RMX2061
build.product: RMX2061
build.type: user
version.codename: REL
version.incremental: 1605989499
version.release: 10
version.sdk_int: 29
display.density_dpi: 408

error: Uncaught exception

--------- beginning of stacktrace
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at ch.deletescape.lawnchair.smartspace.SmartspaceDataWidget$SmartspaceWidgetHostView.updateAppWidget(SmartspaceDataWidget.kt:174)
	at android.appwidget.AppWidgetHost.updateAppWidgetView(AppWidgetHost.java:443)
	at android.appwidget.AppWidgetHost$UpdateHandler.handleMessage(AppWidgetHost.java:137)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by ghost** [comment]
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.
