### ISSUE TITLE
MainProcessInitializer: Unseal fail!

### ISSUE THREAD

**Issue by qian-jiahong** [Deletescape-Media/Lawnchair#2190]
Project build.gradle

    defaultConfig {
        minSdkVersion 25
        targetSdkVersion 30
    }

---

2021-07-27 01:41:03.018 8630-8630/app.lawnchair E/MainProcessInitializer: **Unseal fail!**
2021-07-27 01:41:03.018 8630-8630/app.lawnchair W/System.err: java.lang.reflect.InvocationTargetException
2021-07-27 01:41:03.019 8630-8630/app.lawnchair W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-07-27 01:41:03.019 8630-8630/app.lawnchair W/System.err:     at org.chickenhook.restrictionbypass.RestrictionBypass.getDeclaredMethod(RestrictionBypass.java:18)
2021-07-27 01:41:03.020 8630-8630/app.lawnchair W/System.err:     at org.chickenhook.restrictionbypass.Unseal.unseal(Unseal.java:15)
2021-07-27 01:41:03.020 8630-8630/app.lawnchair W/System.err:     at com.android.launcher3.MainProcessInitializer.initialize(**MainProcessInitializer.java:41**)
2021-07-27 01:41:03.021 8630-8630/app.lawnchair W/System.err:     at com.android.launcher3.LauncherProvider.onCreate(**LauncherProvider.java:132**)
2021-07-27 01:41:03.021 8630-8630/app.lawnchair W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
2021-07-27 01:41:03.022 8630-8630/app.lawnchair W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
2021-07-27 01:41:03.022 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
2021-07-27 01:41:03.022 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
2021-07-27 01:41:03.023 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
2021-07-27 01:41:03.023 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2021-07-27 01:41:03.024 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
2021-07-27 01:41:03.024 8630-8630/app.lawnchair W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-07-27 01:41:03.025 8630-8630/app.lawnchair W/System.err:     at android.os.Looper.loop(Looper.java:164)
2021-07-27 01:41:03.025 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6518)
2021-07-27 01:41:03.025 8630-8630/app.lawnchair W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-07-27 01:41:03.026 8630-8630/app.lawnchair W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2021-07-27 01:41:03.026 8630-8630/app.lawnchair W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2021-07-27 01:41:03.027 8630-8630/app.lawnchair W/System.err: **Caused by**: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
2021-07-27 01:41:03.028 8630-8630/app.lawnchair W/System.err:     at java.lang.Class.getMethod(Class.java:2068)
2021-07-27 01:41:03.028 8630-8630/app.lawnchair W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:2047)
2021-07-27 01:41:03.028 8630-8630/app.lawnchair W/System.err: 	... 18 more
2021-07-27 01:41:03.120 8630-8630/app.lawnchair W/System.err: java.lang.NoSuchMethodException: setContextPriority [int]
2021-07-27 01:41:03.120 8630-8630/app.lawnchair W/System.err:     at java.lang.Class.getMethod(Class.java:2068)
2021-07-27 01:41:03.121 8630-8630/app.lawnchair W/System.err:     at java.lang.Class.getMethod(Class.java:1690)
2021-07-27 01:41:03.121 8630-8630/app.lawnchair W/System.err:     at com.android.systemui.shared.system.ThreadedRendererCompat.setContextPriority(**ThreadedRendererCompat.java:38**)
2021-07-27 01:41:03.122 8630-8630/app.lawnchair W/System.err:     at com.android.quickstep.QuickstepProcessInitializer.init(**QuickstepProcessInitializer.java:52**)
2021-07-27 01:41:03.122 8630-8630/app.lawnchair W/System.err:     at com.android.launcher3.MainProcessInitializer.initialize(**MainProcessInitializer.java:49**)
2021-07-27 01:41:03.123 8630-8630/app.lawnchair W/System.err:     at com.android.launcher3.LauncherProvider.onCreate(**LauncherProvider.java:132**)
2021-07-27 01:41:03.123 8630-8630/app.lawnchair W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
2021-07-27 01:41:03.123 8630-8630/app.lawnchair W/System.err:     at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
2021-07-27 01:41:03.124 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
2021-07-27 01:41:03.124 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
2021-07-27 01:41:03.125 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
2021-07-27 01:41:03.125 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2021-07-27 01:41:03.125 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
2021-07-27 01:41:03.126 8630-8630/app.lawnchair W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-07-27 01:41:03.126 8630-8630/app.lawnchair W/System.err:     at android.os.Looper.loop(Looper.java:164)
2021-07-27 01:41:03.126 8630-8630/app.lawnchair W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6518)
2021-07-27 01:41:03.127 8630-8630/app.lawnchair W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-07-27 01:41:03.127 8630-8630/app.lawnchair W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2021-07-27 01:41:03.127 8630-8630/app.lawnchair W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2021-07-27 01:41:03.161 8630-8630/app.lawnchair E/BypassProvider: Unable to unseal hidden api access
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.chickenhook.restrictionbypass.RestrictionBypass.getDeclaredMethod(RestrictionBypass.java:18)
        at org.chickenhook.restrictionbypass.Unseal.unseal(Unseal.java:15)
        at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(BypassProvider.java:51)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     **Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions** [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.chickenhook.restrictionbypass.RestrictionBypass.getDeclaredMethod(RestrictionBypass.java:18) 
        at org.chickenhook.restrictionbypass.Unseal.unseal(Unseal.java:15) 
        at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(BypassProvider.java:51) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6263) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5829) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5737) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6518) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by RikKoedoot** [comment]
Close because of lack of information
