### ISSUE TITLE
lawnchair 11 crash

### ISSUE THREAD

**Issue by pbanj** [Deletescape-Media/Lawnchair#2192]
Here's the log for a crash that seems to pop up every now and then. I have a pixel 3a on the July update.

`FATAL EXCEPTION: main
Process: app.lawnchair, PID: 9557
java.lang.AbstractMethodError: abstract method "void android.provider.DeviceConfig$OnPropertiesChangedListener.onPropertiesChanged(android.provider.DeviceConfig$Properties)"
	at android.provider.DeviceConfig.lambda$handleChange$0(DeviceConfig.java:807)
	at android.provider.-$$Lambda$DeviceConfig$6U9gBH6h5Oab2DB_e83az4n_WEo.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by RikKoedoot** [comment]
Does this still occur on alpha 6?

**Comment by pbanj** [comment]
> 
> 
> Does this still occur on alpha 6?

i stopped using it, but ill reinstall to see if it still happens. sorry for taking so long to respond.

**Comment by pbanj** [comment]
Ya it's still happening. But I will say it seems far less than before. Oh I also meant to say it's a pixel 3a running the stock rom rooted with Magisk and using the quick switch mod. I'm also now running the September update.

`FATAL EXCEPTION: main
Process: app.lawnchair, PID: 11758
java.lang.AbstractMethodError: abstract method "void android.provider.DeviceConfig$OnPropertiesChangedListener.onPropertiesChanged(android.provider.DeviceConfig$Properties)"
	at android.provider.DeviceConfig.lambda$handleChange$0(DeviceConfig.java:807)
	at android.provider.-$$Lambda$DeviceConfig$6U9gBH6h5Oab2DB_e83az4n_WEo.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by SuperDragonXD** [comment]
Late reply, but this crash from V11 may have been fixed in the later versions (Lawnchair 12.1). Also closing since this is relevant to the older versions only (we no longer support older versions).
