### ISSUE TITLE
Crash on Lawnchair 9.1 Alpha 3

### ISSUE THREAD

**Issue by ale5000-git** [Deletescape-Media/Lawnchair#2224]
Lawnchair bug report 24 ago 2021 21:07:23
Lawnchair version: 9.1 Alpha 3 (9012942)
build.brand: HOMTOM
build.device: HT50
build.display: HOMTOM-HT50-Android_7.0-R19-20171227
build.fingerprint: HOMTOM/full_aeon6737m_65_d_n/aeon6737m_65_d_n:7.0/NRD90M/20171227.164716:user/release-keys
build.hardware: mt6735
build.id: NRD90M
build.manufacturer: HOMTOM
build.model: HT50
build.product: HT50
build.type: user
version.codename: REL
version.incremental: 1514364403
version.release: 7.0
version.sdk_int: 24

error: Uncaught exception

```
--------- beginning of stacktrace
java.lang.NullPointerException: Attempt to invoke virtual method 'float com.android.launcher3.anim.AnimatorPlaybackController.getProgressFraction()' on a null object reference
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onDragEnd(AbstractStateChangeTouchController.java:374)
	at com.android.launcher3.touch.SwipeDetector.reportDragEnd(SwipeDetector.java:325)
	at com.android.launcher3.touch.SwipeDetector.setState(SwipeDetector.java:126)
	at com.android.launcher3.touch.SwipeDetector.onTouchEvent(SwipeDetector.java:265)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onControllerTouchEvent(AbstractStateChangeTouchController.java:161)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:162)
	at android.view.View.dispatchTouchEvent(View.java:10065)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:247)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3063)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
	at android.view.View.dispatchPointerEvent(View.java:10296)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by RikKoedoot** [comment]
closing due to development focusing on lawnchair 12
