### ISSUE TITLE
[Bug] Crash when opening Firefox search widget

### ISSUE THREAD

**Issue by SerjSX** [Deletescape-Media/Lawnchair#2238]
When I opened Firefox's search widget from homescreen Lawnchair crashed and the system changed the default launcher to the stock one. The crash log is attached here:
[FATAL.txt](https://github.com/LawnchairLauncher/lawnchair/files/7234741/FATAL.txt)

I use the latest version of Lawnchair 11 (Alpha 6.1)

**Comment by JoaquinDecima** [comment]
Add Log data

```log
FATAL EXCEPTION: main
Process: app.lawnchair, PID: 18278
java.lang.NoSuchFieldError: No static field ACTION_PAGE_RIGHT of type Landroid/view/accessibility/AccessibilityNodeInfo$AccessibilityAction; in class Landroid/view/accessibility/AccessibilityNodeInfo$AccessibilityAction; or its superclasses (declaration of 'android.view.accessibility.AccessibilityNodeInfo$AccessibilityAction' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.launcher3.PagedView.onInitializeAccessibilityNodeInfo(Unknown Source:51)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7730)
	at android.view.View.createAccessibilityNodeInfo(View.java:7715)
	at com.android.launcher3.Workspace.createAccessibilityNodeInfo(Unknown Source:9)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchPredecessorsOfRealNode(AccessibilityInteractionController.java:1082)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:966)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
	at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:67)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by RikKoedoot** [comment]
does this issue still occur?

**Comment by SerjSX** [comment]
Unsure, I'm using the latest 9.1 Alpha 3 from APK Mirror. Lawnchair needs to find another source for providing beta APKs, couldn't find latest from APKMirror. I don't have Telegram (deleted) as I don't want to use it, hence can't get the beta ones. I am going to close this issue.
