### ISSUE TITLE
Lawnchair immediately crashes on Windows Subsystem for Android

### ISSUE THREAD

**Issue by PeterNjeim** [Deletescape-Media/Lawnchair#2272]
```
[10-26 14:05:14.943 663:2475 V/IntentRedirectionHandler] Receive IntentMessage LaunchPackage
[10-26 14:05:14.945 214:5618 I/ActivityTaskManager] START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10010000 pkg=app.lawnchair cmp=app.lawnchair/.LawnchairLauncher} from uid 10081
[10-26 14:05:14.982 214:5618 I/DisplayManagerService] Display device added: DisplayDeviceInfo{"app.lawnchair:10": uniqueId="virtual:com.microsoft.windows.systemapp:app.lawnchair:10", 772 x 432, modeId 15, defaultModeId 15, supportedModes [{id=15, width=772, height=432, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 160, 160.0 x 160.0 dpi, appVsyncOff 0, presDeadline 16666666, touch VIRTUAL, rotation 0, type VIRTUAL, deviceProductInfo null, state OFF, owner com.microsoft.windows.systemapp (uid 1000), FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_OWN_CONTENT_ONLY}
[10-26 14:05:14.990 214:5618 I/WindowManager] Override config changes=20005df8 {0.0 ?mcc?mnc ?localeList ?layoutDir sw432dp w772dp h432dp 160dpi nrml long land ?uimode ?night finger qwerty/v/v -nav/h winConfig={ mBounds=Rect(0, 0 - 772, 432) mAppBounds=Rect(0, 0 - 772, 432) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0}} for displayId=10
[10-26 14:05:14.991 352:352 W/DisplayController] Skipping Display Configuration change on non-added display.
[10-26 14:05:14.999 214:5618 I/ActivityTaskManager] START u0 {flg=0x18000000 cmp=com.microsoft.windows.userapp/.PlaceholderActivity} from uid 1000
[10-26 14:05:15.002 214:5618 W/ActivityTaskManager] Tried to set launchTime (0) < mLastActivityLaunchTime (395769)
[10-26 14:05:15.002 214:5618 W/InputDispatcher] Focused display #10 does not have a focused window.
[10-26 14:05:15.002 214:5618 E/InputDispatcher] But another display has a focused window:
[10-26 14:05:15.002 214:5618 E/InputDispatcher] Display #0 has focused window: 'Window{dc9cf45 u0 com.microsoft.windows.userapp/com.microsoft.windows.home.Home}'
[10-26 14:05:15.023 214:234 I/DisplayManagerService] Display device changed state: "app.lawnchair:10", ON
[10-26 14:05:15.028 214:505 I/ActivityTaskManager] moveTaskToBack: Task{309253 #80 visible=false type=standard mode=fullscreen translucent=true I=com.microsoft.windows.userapp/.PlaceholderActivity U=0 StackId=80 sz=1}
[10-26 14:05:15.039 214:234 D/CompatibilityChangeReporter] Compat change id reported: 135634846; UID 10087; state: DISABLED
[10-26 14:05:15.039 214:241 D/CompatibilityChangeReporter] Compat change id reported: 143937733; UID 10087; state: ENABLED
[10-26 14:05:15.039 214:234 I/InputManager-JNI] Viewport [0] to add: local:0, isActive: true
[10-26 14:05:15.039 214:234 I/InputManager-JNI] Viewport [1] to add: virtual:com.microsoft.windows.systemapp:com.dp.logcatapp:3, isActive: true
[10-26 14:05:15.039 214:234 I/InputManager-JNI] Viewport [2] to add: virtual:com.microsoft.windows.systemapp:app.lawnchair:10, isActive: true
[10-26 14:05:15.040 214:283 I/InputReader] Reconfiguring input devices, changes=DISPLAY_INFO | 
[10-26 14:05:15.045 66:66 D/Zygote] Forked child process 8703
[10-26 14:05:15.047 214:241 I/ActivityManager] Start proc 8703:app.lawnchair/u0a87 for top-activity {app.lawnchair/app.lawnchair.LawnchairLauncher}
[10-26 14:05:15.052 8703:8703 W/app.lawnchair] Unexpected CPU variant for X86 using defaults: x86_64
[10-26 14:05:15.054 8703:8703 E/app.lawnchair] Not starting debugger since process cannot load the jdwp agent.
[10-26 14:05:15.078 8703:8703 D/NetworkSecurityConfig] No Network Security Config specified, using platform default
[10-26 14:05:15.079 8703:8703 D/NetworkSecurityConfig] No Network Security Config specified, using platform default
[10-26 14:05:15.087 8703:8724 D/native] Found attached 0
[10-26 14:05:15.087 8703:8724 D/native] Calling class is: java.lang.Class
[10-26 14:05:15.087 8703:8725 D/native] Found attached 0
[10-26 14:05:15.088 8703:8725 D/native] Calling class is: java.lang.Class
[10-26 14:05:15.093 214:225 W/System] A resource failed to call release. 
[10-26 14:05:15.094 8703:8726 D/native] Found attached 0
[10-26 14:05:15.095 8703:8726 D/native] Calling class is: java.lang.Class
[10-26 14:05:15.095 214:225 W/System] A resource failed to call release. 
[10-26 14:05:15.095 8703:8727 D/native] Found attached 0
[10-26 14:05:15.095 8703:8727 D/native] Calling class is: java.lang.Class
[10-26 14:05:15.095 8703:8703 I/MainProcessInitializer] Unseal success!
[10-26 14:05:15.096 214:225 W/System] A resource failed to call release. 
[10-26 14:05:15.098 214:225 I/chatty] uid=1000(system) FinalizerDaemon identical 5 lines
[10-26 14:05:15.098 214:225 W/System] A resource failed to call release. 
[10-26 14:05:15.123 8703:8703 D/LawnchairApp] config_recentsComponentName (ComponentInfo{com.google.android.apps.nexuslauncher/com.android.quickstep.RecentsActivity}) is not Lawnchair, disabling recents
[10-26 14:05:15.174 7123:7144 D/EGL_emulation] app_time_stats: avg=1129.19ms min=8.69ms max=4255.09ms count=4
[10-26 14:05:15.193 8703:8734 D/libEGL] loaded /vendor/lib64/egl/libEGL_emulation.so
[10-26 14:05:15.193 8703:8734 D/libEGL] loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
[10-26 14:05:15.195 8703:8734 D/libEGL] loaded /vendor/lib64/egl/libGLESv2_emulation.so
[10-26 14:05:15.208 8703:8732 D/HostConnection] createUnique: call
[10-26 14:05:15.211 8703:8732 D/librcm] SocketClient connected to host port 22469
[10-26 14:05:15.211 8703:8732 D/HostConnection] HostConnection::get() New Host Connection established 0x7e4649608250, tid 8732
[10-26 14:05:15.212 8703:8732 D/HostConnection] HostComposition ext ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_virtio_gpu_next ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr GL_EXT_texture_compression_bptc GL_EXT_texture_compression_s3tc ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[10-26 14:05:15.213 28:28 I/hwservicemanager] getTransport: Cannot find entry android.hardware.configstore@1.0::ISurfaceFlingerConfigs/default in either framework or device manifest.
[10-26 14:05:15.214 8703:8732 D/EGL_emulation] eglCreateContext: 0x7e46496083d0: maj 3 min 0 rcv 3
[10-26 14:05:15.216 8703:8732 D/EGL_emulation] eglMakeCurrent: 0x7e46496083d0: ver 3 0 (tinfo 0x7e484ec2c100) (first time)
[10-26 14:05:15.222 28:28 I/hwservicemanager] getTransport: Cannot find entry android.hardware.graphics.mapper@4.0::IMapper/default in either framework or device manifest.
[10-26 14:05:15.222 8703:8732 I/Gralloc4] mapper 4.x is not supported
[10-26 14:05:15.222 28:28 I/hwservicemanager] getTransport: Cannot find entry android.hardware.graphics.mapper@3.0::IMapper/default in either framework or device manifest.
[10-26 14:05:15.222 8703:8732 W/Gralloc3] mapper 3.x is not supported
[10-26 14:05:15.224 28:28 I/hwservicemanager] getTransport: Cannot find entry android.hardware.graphics.allocator@4.0::IAllocator/default in either framework or device manifest.
[10-26 14:05:15.224 8703:8732 W/Gralloc4] allocator 3.x is not supported
[10-26 14:05:15.224 28:28 I/hwservicemanager] getTransport: Cannot find entry android.hardware.graphics.allocator@3.0::IAllocator/default in either framework or device manifest.
[10-26 14:05:15.224 8703:8732 W/Gralloc3] allocator 3.x is not supported
[10-26 14:05:15.227 8703:8732 D/HostConnection] createUnique: call
[10-26 14:05:15.228 8703:8732 D/librcm] SocketClient connected to host port 22469
[10-26 14:05:15.228 8703:8732 D/HostConnection] HostConnection::get() New Host Connection established 0x7e4649608190, tid 8732
[10-26 14:05:15.229 8703:8732 D/HostConnection] HostComposition ext ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_virtio_gpu_next ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr GL_EXT_texture_compression_bptc GL_EXT_texture_compression_s3tc ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[10-26 14:05:15.254 8703:8732 E/FrameEvents] updateAcquireFence: Did not find frame.
[10-26 14:05:15.263 8703:8732 I/chatty] uid=10087(app.lawnchair) RenderThread identical 1 line
[10-26 14:05:15.271 8703:8732 E/FrameEvents] updateAcquireFence: Did not find frame.
[10-26 14:05:15.289 8703:8703 V/Launcher] LauncherAppState initiated
[10-26 14:05:15.307 8703:8742 E/AndroidRuntime] FATAL EXCEPTION: pool-2-thread-1
Process: app.lawnchair, PID: 8703
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.app.DisabledWallpaperManager.getDesiredMinimumWidth(DisabledWallpaperManager.java:262)
	at com.android.launcher3.Workspace$3.run(Unknown Source:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
[10-26 14:05:15.309 214:8744 I/DropBoxManagerService] add tag=data_app_crash isTagEnabled=true flags=0x2
[10-26 14:05:15.309 214:5618 W/ActivityTaskManager]   Force finishing activity app.lawnchair/.LawnchairLauncher
[10-26 14:05:15.311 8703:8742 I/Process] Sending signal. PID: 8703 SIG: 9
[10-26 14:05:15.313 214:240 W/BroadcastQueue] Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
[10-26 14:05:15.313 214:240 W/BroadcastQueue] Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
[10-26 14:05:15.319 214:4325 I/ActivityManager] Process app.lawnchair (pid 8703) has died: prcp TOP 
[10-26 14:05:15.320 66:66 I/Zygote] Process 8703 exited due to signal 9 (Killed)
[10-26 14:05:15.322 214:4325 W/InputDispatcher] Focused display #0 does not have a focused window.
[10-26 14:05:15.329 214:4325 I/DisplayManagerService] Display device removed: DisplayDeviceInfo{"app.lawnchair:10": uniqueId="virtual:com.microsoft.windows.systemapp:app.lawnchair:10", 772 x 432, modeId 15, defaultModeId 15, supportedModes [{id=15, width=772, height=432, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 160, 160.0 x 160.0 dpi, appVsyncOff 0, presDeadline 16666666, touch VIRTUAL, rotation 0, type VIRTUAL, deviceProductInfo null, state OFF, owner com.microsoft.windows.systemapp (uid 1000), FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_OWN_CONTENT_ONLY}
[10-26 14:05:15.331 646:2323 V/SettingsRedirectionHandler] Receive SettingsMessage ClosedCaptions
[10-26 14:05:15.334 214:234 W/DisplayManagerService] Attempted to change non-existent display device: DisplayDeviceInfo{"app.lawnchair:10": uniqueId="virtual:com.microsoft.windows.systemapp:app.lawnchair:10", 772 x 432, modeId 15, defaultModeId 15, supportedModes [{id=15, width=772, height=432, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 160, 160.0 x 160.0 dpi, appVsyncOff 0, presDeadline 16666666, touch VIRTUAL, rotation 0, type VIRTUAL, deviceProductInfo null, state OFF, owner com.microsoft.windows.systemapp (uid 1000), FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_OWN_CONTENT_ONLY}
[10-26 14:05:15.334 646:2323 V/SettingsRedirectionHandler] Receive SettingsMessage ClosedCaptions
[10-26 14:05:15.334 214:234 W/DisplayManagerService] Attempted to change non-existent display device: DisplayDeviceInfo{"app.lawnchair:10": uniqueId="virtual:com.microsoft.windows.systemapp:app.lawnchair:10", 772 x 432, modeId 15, defaultModeId 15, supportedModes [{id=15, width=772, height=432, fps=60.0}], colorMode 0, supportedColorModes [0], HdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 160, 160.0 x 160.0 dpi, appVsyncOff 0, presDeadline 16666666, touch VIRTUAL, rotation 0, type VIRTUAL, deviceProductInfo null, state OFF, owner com.microsoft.windows.systemapp (uid 1000), FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_OWN_CONTENT_ONLY}
[10-26 14:05:15.336 214:234 I/InputManager-JNI] Viewport [0] to add: local:0, isActive: true
[10-26 14:05:15.336 214:214 W/WindowManager] removeWindowToken: Attempted to remove token: android.os.Binder@2e92366 for non-exiting displayId=1
```

This is on Windows Subsystem for Android (WSA), which is Andriod 11. Lawnchair version is 12 Alpha 2. I believe it's due to how WSA opens new apps in separate windows, and default window size may be too small (and it's landscape as well) (it is 774x464)

**Comment by arthur-star** [comment]
I found a relevant issue for this problem, https://github.com/inaturalist/iNaturalistAndroid/issues/1121. The exception may be caused by the object `mWallpaperManager` is null. A null pointer checking is needed here.

https://github.com/LawnchairLauncher/lawnchair/blob/f0688335a9419947a3d2f9ca08ba781346447ee9/src/com/android/launcher3/Workspace.java#L1173

**Comment by PeterNjeim** [comment]
I think you're right. I'm currently using Microsoft Launcher in WSA, as it's the only launcher that I got working so far, but whenever I try to set my wallpaper, it crashes, so it just has a black background.

Every single "pixel" launcher has crashed immediately so far, including CPL, Lawnchair, and Rootless Launcher. I haven't checked the logs for those ones but I suspect it's the same.

**Comment by PeterNjeim** [comment]
Fixed it by adding a check of `mWallpaperManager.isWallpaperSupported()` to the if statement. However Lawnchair still forces the aspect ratio to be the same as the `mWallpaperManager.suggestDesiredDimensions(minimumWidth, minimumHeight)`, so I added another if statement to check if the wallpaper was supported, and if it wasn't, I set the minimum width and height to 0.

```java
if (!mWallpaperManager.isWallpaperSupported()) {
    mWallpaperManager.suggestDesiredDimensions(0, 0);
} else if (size.x != mWallpaperManager.getDesiredMinimumWidth() || size.y != mWallpaperManager.getDesiredMinimumHeight()) {
    mWallpaperManager.suggestDesiredDimensions(size.x, size.y);
}
```

Pull: #2373

**Comment by PeterNjeim** [comment]
I guess it's common practice to leave the issue open until the PR is merged, so I'll leave it open for now
