### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2316]
Lawnchair bug report Nov 6, 2021 22:23:11
version: 12.0 Alpha 3 (120003)
commit: 7e4d7bb
build.brand: samsung
build.device: a20s
build.display: RP1A.200720.012.A207MUBU2CUFA
build.fingerprint: samsung/a20sub/a20s:11/RP1A.200720.012/A207MUBU2CUFA:user/release-keys
build.hardware: qcom
build.id: RP1A.200720.012
build.manufacturer: samsung
build.model: SM-A207M
build.product: a20sub
build.type: user
version.codename: REL
version.incremental: A207MUBU2CUFA
version.release: 11
version.sdk_int: 30
display.density_dpi: 232

error: Uncaught exception

java.lang.IllegalArgumentException: Can't represent a size of 2147483520 in Constraints
	at h2.b$a.a(Unknown Source:54)
	at h2.b$a.b(Unknown Source:8)
	at h2.c.a(Unknown Source:28)
	at x.q0.b(Unknown Source:151)
	at x.q0.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at z.k.a(Unknown Source:50)
	at y.d0.a(Unknown Source:12)
	at y.s.b(Unknown Source:274)
	at y.q$c.a(Unknown Source:282)
	at z.g$a.a(Unknown Source:31)
	at z.g$a.invoke(Unknown Source:8)
	at n1.t0$d.c(Unknown Source:67)
	at p1.e.o(Unknown Source:27)
	at x.i0.J(Unknown Source:143)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at b1.e1.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.j0$a.c(Unknown Source:175)
	at p1.e.o(Unknown Source:27)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.g$c.c(Unknown Source:84)
	at p1.e.o(Unknown Source:27)
	at x.f0.J(Unknown Source:50)
	at p1.t.o(Unknown Source:17)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.j0$a.c(Unknown Source:175)
	at p1.e.o(Unknown Source:27)
	at x.r.J(Unknown Source:108)
	at p1.t.o(Unknown Source:17)
	at x.i0.J(Unknown Source:143)
	at p1.t.o(Unknown Source:17)
	at u.z.J(Unknown Source:47)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at b1.e1.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.g$c.c(Unknown Source:84)
	at p1.e.o(Unknown Source:27)
	at h5.c$c.a(Unknown Source:33)
	at h5.c$c.I(Unknown Source:10)
	at n1.w.J(Unknown Source:16)
	at p1.t.o(Unknown Source:17)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.j0$a.c(Unknown Source:175)
	at p1.e.o(Unknown Source:27)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.g$c.c(Unknown Source:84)
	at p1.e.o(Unknown Source:27)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at b1.e1.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at b1.r.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at x.c0.J(Unknown Source:10)
	at p1.t.o(Unknown Source:17)
	at p1.b.o(Unknown Source:7)
	at x.r.J(Unknown Source:108)
	at p1.t.o(Unknown Source:17)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.g$c.c(Unknown Source:221)
	at x.j$a.a(Unknown Source:36)
	at x.j$a.invoke(Unknown Source:8)
	at n1.t0$d.c(Unknown Source:67)
	at p1.e.o(Unknown Source:27)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at n1.p0.c(Unknown Source:50)
	at p1.e.o(Unknown Source:27)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.h$a.c(Unknown Source:62)
	at u0.v.j(Unknown Source:264)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.g.I0(Unknown Source:8)
	at p1.m.j(Unknown Source:9)
	at p1.m.a(Unknown Source:0)
	at p1.m.m(Unknown Source:89)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(Unknown Source:107)
	at android.view.View.measure(View.java:27131)
	at androidx.compose.ui.platform.a.i(Unknown Source:63)
	at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27131)
	at j2.a.onMeasure(Unknown Source:5)
	at android.view.View.measure(View.java:27131)
	at j2.a$e.c(Unknown Source:99)
	at p1.e.o(Unknown Source:27)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.b.o(Unknown Source:7)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.v.j(Unknown Source:276)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.z.o(Unknown Source:54)
	at p1.g.o(Unknown Source:2)
	at x.g$c.c(Unknown Source:221)
	at p1.e.o(Unknown Source:27)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:2)
	at p1.z$c.invoke(OuterMeasurablePlaceable.kt:1)
	at u0.h$a.c(Unknown Source:62)
	at u0.v.j(Unknown Source:264)
	at p1.d0.e(Unknown Source:17)
	at p1.d0.d(Unknown Source:12)
	at p1.z.M0(Unknown Source:158)
	at p1.g.I0(Unknown Source:8)
	at p1.g.J0(Unknown Source:10)
	at p1.m.j(Unknown Source:15)
	at p1.m.a(Unknown Source:0)
	at p1.m.m(Unknown Source:89)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(Unknown Source:107)
	at android.view.View.measure(View.java:27131)
	at androidx.compose.ui.platform.a.i(Unknown Source:63)
	at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1173)
	at android.view.View.measure(View.java:27131)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4187)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2936)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:744)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by suphon-t** [comment]
This is already fixed. The fix will be released in the next alpha.
