### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aacai** [Deletescape-Media/Lawnchair#2355]
crash Lawnchair bug report 2 Dec 2021 6:44:03 pm
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: lge
build.device: flashlmdd
build.display: QKQ1.191021.002
build.fingerprint: lge/flashlmdd_lao_com/flashlmdd:10/QKQ1.191021.002/2106117005411.OPEN_KR:user/release-keys
build.hardware: flashlmdd
build.id: QKQ1.191021.002
build.manufacturer: LGE
build.model: LM-V500N
build.product: flashlmdd_lao_com
build.type: user
version.codename: REL
version.incremental: 2106117005411.OPEN_KR
version.release: 10
version.sdk_int: 29
display.density_dpi: 280

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(Unknown Source:8)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(Unknown Source:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(Unknown Source:0)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(Unknown Source:104)
	at com.android.quickstep.views.RecentsView.getTaskSize(Unknown Source:10)
	at com.android.quickstep.views.RecentsView.updateSizeAndPadding(Unknown Source:8)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:17)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.setInsets(Unknown Source:43)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setInsets(Unknown Source:13)
	at com.android.launcher3.LauncherRootView.dispatchInsets(Unknown Source:13)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:1)
	at com.android.launcher3.Launcher.onIdpChanged(Unknown Source:6)
	at com.android.launcher3.Launcher.onConfigurationChanged(Unknown Source:14)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(Unknown Source:0)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5643)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5510)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5478)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5966)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:48)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7573)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)

**Comment by aacai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
