### ISSUE TITLE
Sony Xz3 not responding issue

### ISSUE THREAD

**Issue by Vdogar56** [Deletescape-Media/Lawnchair#2362]
Lawnchair bug report Dec 4, 2021 4:28:50 PM
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: KDDI
build.device: SOV39
build.display: 52.1.C.0.360
build.fingerprint: KDDI/SOV39_jp_kdi/SOV39:10/52.1.C.0.360/052001C000036000726438165:user/release-keys
build.hardware: qcom
build.id: 52.1.C.0.360
build.manufacturer: Sony
build.model: SOV39
build.product: SOV39_jp_kdi
build.type: user
version.codename: REL
version.incremental: 052001C000036000726438165
version.release: 10
version.sdk_int: 29
display.density_dpi: 476

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(Unknown Source:8)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(Unknown Source:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(Unknown Source:0)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(Unknown Source:104)
	at com.android.quickstep.views.RecentsView.getTaskSize(Unknown Source:10)
	at com.android.quickstep.views.RecentsView.updateSizeAndPadding(Unknown Source:8)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:17)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.setInsets(Unknown Source:43)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(Unknown Source:13)
	at com.android.launcher3.InsettableFrameLayout.setInsets(Unknown Source:13)
	at com.android.launcher3.LauncherRootView.dispatchInsets(Unknown Source:13)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:1)
	at com.android.launcher3.Launcher.onIdpChanged(Unknown Source:6)
	at com.android.launcher3.Launcher.onConfigurationChanged(Unknown Source:14)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(Unknown Source:0)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5547)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5414)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5392)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5812)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:48)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:7418)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by Vdogar56** [comment]
Not responding
