### ISSUE TITLE
HDMI output; Forced dekstop mode;

### ISSUE THREAD

**Issue by Gouster4** [Deletescape-Media/Lawnchair#2365]
Lawnchair as default launcher is constantly crashing when HDMI plugged into TV while force desktop mode dev setting is enabled. Seems like lawnchair doesnt like to be on multiple screens at same time.
```
Lawnchair bug report 7. 12. 2021 22:28:15
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: Sony
build.device: XQ-BC52
build.display: 61.0.A.23.20 release-keys
build.fingerprint: Sony/XQ-BC52_EEA/XQ-BC52:11/61.0.A.23.20/061000A023002002691347586:user/release-keys
build.hardware: qcom
build.id: 61.0.A.23.20
build.manufacturer: Sony
build.model: XQ-BC52
build.product: XQ-BC52_EEA
build.type: user
version.codename: REL
version.incremental: 061000A023002002691347586
version.release: 11
version.sdk_int: 30
display.density_dpi: 420

error: Uncaught exception

android.view.InflateException: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: android.view.InflateException: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:461)
	at android.app.Activity.setContentView(Activity.java:3468)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.initUi(Unknown Source:52)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.onAttachedToWindow(Unknown Source:3)
	at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:1728)
	at android.view.View.dispatchAttachedToWindow(View.java:20498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2424)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1959)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8187)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7730)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassCastException: com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher cannot be cast to app.lawnchair.LawnchairLauncher
	at k4.o.a(Unknown Source:14)
	at l4.d.<init>(Unknown Source:33)
	at com.android.launcher3.allapps.AllAppsContainerView$AdapterHolder.<init>(Unknown Source:30)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:24)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:2)
	... 31 more
```

**Comment by hmtheboy154** [comment]
Bump this issue, since Lawnchair is lacking of Desktop Mode so everytime I wanna use the secondary screen (HDMI or scrcpy) it will crash

**Comment by Gouster4** [comment]
Would be cool if lawnchair will get desktop mode support in future.

**Comment by Gouster4** [comment]
I guess its related to this issue;
https://github.com/LawnchairLauncher/lawnchair/issues/2574

**Comment by hmtheboy154** [comment]
it seems like this time they disable the Desktop Mode launcher, can you check to see if it's true ?

**Comment by suphon-t** [comment]
Should be fixed, as the desktop mode launcher has been disabled.
