### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Deletescape-Media/Lawnchair#2370]
Latest version multiple crashes with:
`Lawnchair version: 9.1 Alpha 3 (9012942)

error: Uncaught exception

--------- beginning of stacktrace
java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@7930136 class android.service.notification.INotificationListener$Stub$Proxy
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:4806)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:937)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:914)
	at com.android.launcher3.notification.NotificationListener.onNotificationRankingUpdate(NotificationListener.java:298)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2150)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:904)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4240)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2182)
	at android.os.Binder.execTransactInternal(Binder.java:1157)
	at android.os.Binder.execTransact(Binder.java:1126)

`

Dodgebin Uploads failed

**Comment by suphon-t** [comment]
V9 is discontinued. Development is now focused on V12.
