### ISSUE TITLE
[Bug Report] ClassCastException Crash on Launch

### ISSUE THREAD

**Issue by fallsimply** [Deletescape-Media/Lawnchair#2380]
Lawnchair bug report Dec 17, 2021 21:09:16
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: google
build.device: coral
build.display: SQ1A.211205.008
build.fingerprint: google/coral/coral:12/SQ1A.211205.008/7888514:user/release-keys
build.hardware: coral
build.id: SQ1A.211205.008
build.manufacturer: Google
build.model: Pixel 4 XL
build.product: coral
build.type: user
version.codename: REL
version.incremental: 7888514
version.release: 12
version.sdk_int: 31
display.density_dpi: 560

error: Uncaught exception

java.lang.ClassCastException: com.android.launcher3.model.data.WorkspaceItemInfo cannot be cast to com.android.launcher3.model.data.FolderInfo
	at com.android.launcher3.model.QuickstepModelDelegate.modelLoadComplete(Unknown Source:80)
	at com.android.launcher3.model.LoaderTask.run(Unknown Source:374)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by gitch22** [comment]
I got the exact same error message the day before this was posted. Not sure what the long term solution is, but as a short term fix I removed web apps or shortcuts from folders on homescreen and in dock. 

No crashes since. I'd like to have web app shortcuts in folders, however, so hopefully this can be looked at. Thank you!
