### ISSUE TITLE
Bug About Add Widgets

### ISSUE THREAD

**Issue by Maazellat** [Deletescape-Media/Lawnchair#2414]
Lawnchair bug report 12 Oca 2022 16:44:28
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: Sony
build.device: XQ-BC72
build.display: 61.1.A.1.149 release-keys
build.fingerprint: Sony/XQ-BC72_RU/XQ-BC72:12/61.1.A.1.149/061001A001014902690495935:user/release-keys
build.hardware: qcom
build.id: 61.1.A.1.149
build.manufacturer: Sony
build.model: XQ-BC72
build.product: XQ-BC72_RU
build.type: user
version.codename: REL
version.incremental: 061001A001014902690495935
version.release: 12
version.sdk_int: 31
display.density_dpi: 420

error: Uncaught exception

java.lang.RuntimeException: Unable to stop activity {app.lawnchair/app.lawnchair.LawnchairLauncher}: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5166)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5138)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5203)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2476)
	at android.os.Parcel.createException(Parcel.java:2448)
	at android.os.Parcel.readException(Parcel.java:2431)
	at android.os.Parcel.readException(Parcel.java:2373)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:792)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:258)
	at com.android.launcher3.widget.LauncherAppWidgetHost.stopListening(Unknown Source:6)
	at com.android.launcher3.widget.LauncherAppWidgetHost.setShouldListenFlag(Unknown Source:39)
	at com.android.launcher3.widget.LauncherAppWidgetHost.setActivityStarted(Unknown Source:1)
	at com.android.launcher3.Launcher.onStop(Unknown Source:25)
	at app.lawnchair.LawnchairLauncher.onStop(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1497)
	at android.app.Activity.performStop(Activity.java:8281)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5158)
	... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids(AppWidgetServiceImpl.java:4170)
	at com.android.server.appwidget.AppWidgetServiceImpl.stopListening(AppWidgetServiceImpl.java:794)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:311)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)

**Comment by emillime** [comment]
Any updates about how to solve this? It is still happening on some devices.

**Comment by SuperDragonXD** [comment]
See https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#adding-widgets-crashes-lawnchair

**Comment by William150722** [comment]
@SuperDragonXD hi, may i know what is this FAQ for? the issues above is expected behaviour? Thanks.

**Comment by SuperDragonXD** [comment]
Not really expected behavior, but - since it's a very common issue, it has been added to the FAQ alongside a workaround.

**Comment by William150722** [comment]
@SuperDragonXD thanks for the reply, but I don't see any workaround inside the FAQ, or am I missed the document? Can provide the guidelines?

**Comment by SuperDragonXD** [comment]
The link that I added 3 months ago is outdated now. See this: https://lawnchair.app/faq/#adding-widgets-makes-lawnchair-crash

**Comment by William150722** [comment]
Hi @SuperDragonXD 

 Adding widgets makes Lawnchair crash
This is a common issue (especially when the widget has a settings screen), and here's a temporary solution:

Change the default launcher to your system launcher.
Open Lawnchair.
Add the widget.
Re-set Lawnchair as the default launcher.
Unfortunately, there isn't a fix for this yet.

This above statement is temporary solution?

**Comment by SuperDragonXD** [comment]
Yes. There are many types of widget crashes and we still haven't fixed all of them.

**Comment by William150722** [comment]
@SuperDragonXD noted with thanks.

**Comment by Goooler** [comment]
Related to #2820?


```
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId'
on a null object reference in method 'android.util.SparseArray com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids()'
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
    at android.os.Parcel.createException(Parcel.java:2995)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.os.Parcel.readException(Parcel.java:2920)
    at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:677)
    at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:267)
    at com.android.launcher3.widget.LauncherAppWidgetHost.stopListening(Unknown Source:6)
    at com.android.launcher3.widget.LauncherAppWidgetHost.setShouldListenFlag(Unknown Source:39)
    at com.android.launcher3.widget.LauncherAppWidgetHost.setActivityStarted(Unknown Source:1)
    at com.android.launcher3.Launcher.onStop(Unknown Source:25)
    at app.lawnchair.LawnchairLauncher.onStop(Unknown Source:0)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1584)
    at android.app.Activity.performStop(Activity.java:8527)
    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5170)
    ... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids(AppWidgetServiceImpl.java:4275)
    at com.android.server.appwidget.AppWidgetServiceImpl.stopListening(AppWidgetServiceImpl.java:814)
    at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:308)
    at android.os.Binder.execTransactInternal(Binder.java:1280)
    at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by William150722** [comment]
> Related to #2820?

yea. @Goooler similar issues.

**Comment by William150722** [comment]
@SuperDragonXD @Goooler notice that issues will occur quite frequently, any alternative solution i can fix it?

**Comment by Goooler** [comment]
> any alternative solution i can fix it?

https://lawnchair.app/faq/#adding-widgets-makes-lawnchair-crash

**Comment by tungstengmd** [comment]
Bruh wha

**Comment by William150722** [comment]
what?

**Comment by non-bin** [comment]
Still happening 😭

**Comment by NIGHTZ-hangout** [comment]
What the hell is going on with your device?

**Comment by MrSluffy** [comment]
> Still happening 😭

this fixed in latest nightly
