### ISSUE TITLE
Dragging one of two icons out of a folder in the Dock has resulted in a crash. 

### ISSUE THREAD

**Issue by martijnw1986** [Deletescape-Media/Lawnchair#2415]
I expected to be able to drag one icon to a different folder and see the previous folder return back to the single app that was left. Instead, a crash occurred.

**Comment by martijnw1986** [comment]
Bugreport:

`Lawnchair bug report 12 jan. 2022 18:59:33
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: google
build.device: bramble
build.display: SQ1A.211205.008
build.fingerprint: google/bramble/bramble:12/SQ1A.211205.008/7888514:user/release-keys
build.hardware: bramble
build.id: SQ1A.211205.008
build.manufacturer: Google
build.model: Pixel 4a (5G)
build.product: bramble
build.type: user
version.codename: REL
version.incremental: 7888514
version.release: 12
version.sdk_int: 31
display.density_dpi: 420

error: Uncaught exception

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:12)
	at com.android.launcher3.folder.Folder.animateClosed(Unknown Source:28)
	at com.android.launcher3.folder.Folder.handleClose(Unknown Source:40)
	at com.android.launcher3.AbstractFloatingView.close(Unknown Source:5)
	at com.android.launcher3.folder.Folder.completeDragExit(Unknown Source:5)
	at com.android.launcher3.folder.Folder$8.onAlarm(Unknown Source:2)
	at com.android.launcher3.Alarm.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by RikKoedoot** [comment]
could you screen record the issue? As i am not able to reproduce the crash.

**Comment by martijnw1986** [comment]
Sorry Rik,

I tried to replicate it in rapid succession but the crash does not occur as it did before.


Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
