### ISSUE TITLE
Lawnchair crash

### ISSUE THREAD

**Issue by Ashutosh1n1** [Deletescape-Media/Lawnchair#2422]
https://katb.in/ruzowagequr

**Comment by Ashutosh1n1** [comment]
Lawnchair bug report Jan 16, 2022 9:40:53 AM
version: 12.0 Alpha 4 (120004)
commit: 2cce1b0
build.brand: realme
build.device: RMX2001L1
build.display: RMX2001_11_C.16
build.fingerprint: realme/RMX2001/RMX2001L1:11/RP1A.200720.011/1639110559567:user/release-keys
build.hardware: mt6785
build.id: RP1A.200720.011
build.manufacturer: realme
build.model: RMX2001
build.product: RMX2001
build.type: user
version.codename: REL
version.incremental: 1639110559567
version.release: 11
version.sdk_int: 30
display.density_dpi: 408

error: Uncaught exception

android.view.InflateException: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
Caused by: java.lang.IllegalArgumentException: Binary XML file line #25: Duplicate id 0xffffffff, tag smart_space_view, or parent id 0x7f0a0180 with another fragment for app.lawnchair.nexuslauncher.SmartspaceQsb$SmartSpaceFragment
	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3568)
	at android.app.FragmentController.onCreateView(FragmentController.java:104)
	at android.app.Activity.onCreateView(Activity.java:7245)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1082)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at com.android.launcher3.Workspace.bindAndInitFirstWorkspaceScreen(Unknown Source:29)
	at com.android.launcher3.Workspace.removeAllWorkspaceScreens(Unknown Source:46)
	at com.android.launcher3.Launcher.startBinding(Unknown Source:29)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$bind$0(Unknown Source:3)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.f(Unknown Source:0)
	at com.android.launcher3.model.o.execute(Unknown Source:0)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$executeCallbacksTask$9(Unknown Source:18)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.c(Unknown Source:0)
	at com.android.launcher3.model.p.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by Ashutosh1n1** [comment]
https://katb.in/kiworoqivuw


Another crash

**Comment by RikKoedoot** [comment]
Please provide explanations of what happened with each crash

**Comment by Ashutosh1n1** [comment]
When i add widgets from( https://play.google.com/store/apps/details?id=com.tommasoberlose.anotherwidget )from this app suddenly luncher crashes and i tried so many times with changing home screen grid but crash occurred everytime.

Crash also happens with 
https://play.google.com/store/apps/details?id=twelve.clock.mibrahim
This application also but here problem is different if i try to add a widget from home screen by long press and then touch and hold to drag the widget and when i try to add that on home screen then crash occoured but if i add widget from the application because this app support that then no crash happened.

If u could not understand then plz reply again i will try to explain that again

**Comment by RikKoedoot** [comment]
Are you on android 12?

**Comment by Ashutosh1n1** [comment]
No realme ui 2.0 based on Android 11

**Comment by tiagogaspar8** [comment]
Hi all!

@RikKoedoot I must also report this also happens in android 12, in my case it's a OnePlus 8.
