### ISSUE TITLE
Lawnchair 12 Crashes while trying to open apps in Split Screen

### ISSUE THREAD

**Issue by MuhammadAyan** [Deletescape-Media/Lawnchair#2453]
Please fix it in next update
[Lawnchair bug report Feb 5, 2022 91000 AM.txt](https://github.com/LawnchairLauncher/lawnchair/files/8007575/Lawnchair.bug.report.Feb.5.2022.91000.AM.txt)

**Comment by Donkey-Doug** [comment]
I have the same issue:

Lawnchair bug report Mar 5, 2022 22:35:26
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: Xiaomi
build.device: raphael
build.display: lineage_raphael-userdebug 10 QQ3A.200705.002 eng.abhish.20200710.065119 test-keys
build.fingerprint: google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys
build.hardware: qcom
build.id: QQ3A.200705.002
build.manufacturer: Xiaomi
build.model: Mi 9T Pro
build.product: raphael_eea
build.type: userdebug
version.codename: REL
version.incremental: eng.abhish.20200710.065119
version.release: 10
version.sdk_int: 29
display.density_dpi: 396

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:1)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:2)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:1)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:17)
	at com.android.quickstep.util.LayoutUtils.getShelfTrackingDistance(LayoutUtils.java:2)
	at com.android.launcher3.uioverrides.touchcontrollers.NoButtonQuickSwitchTouchController.<init>(NoButtonQuickSwitchTouchController.java:10)
	at com.android.launcher3.uioverrides.QuickstepLauncher.createTouchControllers(QuickstepLauncher.java:12)
	at com.android.launcher3.dragndrop.DragLayer.recreateControllers(Unknown Source:4)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:10)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:9)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:1)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:3)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:2)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(QuickstepLauncher.java:1)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5525)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5392)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:5370)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5790)
	at android.app.ActivityThread$ActivityClientRecord.lambda$init$0$ActivityThread$ActivityClientRecord(ActivityThread.java:573)
	at android.app.-$$Lambda$ActivityThread$ActivityClientRecord$HOrG1qglSjSUHSjKBn2rXtX0gGg.onConfigurationChanged(Unknown Source:2)
	at android.view.ViewRootImpl.performConfigurationChange(ViewRootImpl.java:4399)
	at android.view.ViewRootImpl.access$400(ViewRootImpl.java:146)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4634)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by SuperDragonXD** [comment]
Late reply, but it may have been fixed in the later versions (Lawnchair 12.1). Also closing since this is relevant to the older versions only (we no longer support older versions).
