### ISSUE TITLE
ClassCastExeption on Start

### ISSUE THREAD

**Issue by BlazeCodeDev** [Deletescape-Media/Lawnchair#2454]
As soon as I open the app it stays open for roughly a second and then crashes with the following error.

```
FATAL EXCEPTION: launcher-loader
Process: app.lawnchair, PID: 7760
java.lang.ClassCastException: com.android.launcher3.model.data.WorkspaceItemInfo cannot be cast to com.android.launcher3.model.data.FolderInfo
	at com.android.launcher3.model.QuickstepModelDelegate.modelLoadComplete(QuickstepModelDelegate.java:11)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:75)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
```

I'm using Lawnchair 12 Alpha 5 on Android 12 (SQ1D.220105.007) Magisk rooted, not using QuickSwitch

**Comment by derwerbebriefkasten** [comment]
Same here on my Pixel4a, SQ1A.220105.002.
Not rooted, alpha5 updated on running alpha4. 
Now back on alpha4 everything works fine.

**Comment by BlazeCodeDev** [comment]
Issue persists with February Patch Android 12 (SQ1D.220205.003)
