### ISSUE TITLE
Launchair 12 Alpha 5 crashing on startup

### ISSUE THREAD

**Issue by kartikj07** [Deletescape-Media/Lawnchair#2460]
```
Lawnchair bug report 06-Feb-2022 22:02:50
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: OnePlus
build.device: Nord
build.display: AC2001_14_220117
build.fingerprint: OnePlus/Nord_IND/Nord:11/RP1A.201005.001/2201171930:user/release-keys
build.hardware: qcom
build.id: RP1A.201005.001
build.manufacturer: OnePlus
build.model: AC2001
build.product: Nord_IND
build.type: user
version.codename: REL
version.incremental: 2201171930
version.release: 11
version.sdk_int: 30
display.density_dpi: 399

error: Uncaught exception

java.lang.ClassCastException: com.android.launcher3.model.data.WorkspaceItemInfo cannot be cast to com.android.launcher3.model.data.FolderInfo
	at com.android.launcher3.model.QuickstepModelDelegate.modelLoadComplete(QuickstepModelDelegate.java:11)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:75)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:245)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```
This is the error log associated with the crash. Please help.

**Comment by SuperDragonXD** [comment]
Late reply, but try updating to the later versions (Lawnchair 12.1) and see if it fixes the issue. Also closing since this is relevant to the older versions only (we no longer support older versions).
