### ISSUE TITLE
Lawnchair Home Settings crashes when clicking on Notification Dots settings

### ISSUE THREAD

**Issue by SunilSunil** [Deletescape-Media/Lawnchair#2462]
Open Home Settings
General
Notification Dots and observe home settings crashed with below error

Observed on Redmi Note 5 Pro running Lawnchair 12 Alpha 5

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings$ConfigureNotificationSettingsActivity}: java.lang.IllegalArgumentException: Key cannot be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalArgumentException: Key cannot be null
	at androidx.preference.PreferenceGroup.t(PreferenceGroup.java:368)
	at com.android.settingslib.core.a.setVisible(AbstractPreferenceController.java:87)
	at com.android.settingslib.core.a.displayPreference(AbstractPreferenceController.java:36)
	at com.android.settings.notification.LockScreenNotificationPreferenceController.displayPreference(LockScreenNotificationPreferenceController.java:96)
	at com.android.settings.dashboard.DashboardFragment.a(DashboardFragment.java:295)
	at com.android.settings.dashboard.DashboardFragment.lambda$v89ChbJfRguyCnXbbFTl6PFZb6I(Unknown Source:0)
	at com.android.settings.dashboard.-$$Lambda$DashboardFragment$v89ChbJfRguyCnXbbFTl6PFZb6I.accept(Unknown Source:4)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:133)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:235)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:419)
	at com.android.settings.dashboard.DashboardFragment.Kh(DashboardFragment.java:294)
	at com.android.settings.dashboard.DashboardFragment.cE(DashboardFragment.java:339)
	at com.android.settings.dashboard.DashboardFragment.onBindPreferences(DashboardFragment.java:424)
	at androidx.preference.g.jS(PreferenceFragment.java:505)
	at androidx.preference.g.onViewCreated(PreferenceFragment.java:285)
	at com.android.settings.SettingsPreferenceFragment.onViewCreated(SettingsPreferenceFragment.java:301)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3003)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
	at android.app.Activity.performCreate(Activity.java:7236)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	... 11 more

**Comment by SuperDragonXD** [comment]
Late reply, but try updating to the later versions (Lawnchair 12.1) and see if it fixes the issue. Also closing since this is relevant to the older versions only (we no longer support older versions).
