### ISSUE TITLE
Cannot open any app on Android Tiramisu (13)

### ISSUE THREAD

**Issue by renattele** [Deletescape-Media/Lawnchair#2476]
When I`m trying to open any app on Android 13(Tiramisu) Lawnchair crashes with error:

> java.lang.NoSuchMethodError: No virtual method setSplashscreenStyle(I)V in class Landroid/app/ActivityOptions; or its super classes (declaration of 'android.app.ActivityOptions' appears in /system/framework/framework.jar) at com.android.launcher3.BaseQuickstepLauncher.getActivityLaunchOptions(Unknown Source:39)	at com.android.launcher3.BaseDraggingActivity.startActivitySafely(Unknown Source:25)
at com.android.launcher3.Launcher.startActivitySafely(Unknown Source:26)
	at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(Unknown Source:14)
	at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(Unknown Source:93)
	at com.android.launcher3.touch.ItemClickHandler.onClick(Unknown Source:58)
	at com.android.launcher3.touch.ItemClickHandler.b(Unknown Source:0)
	at com.android.launcher3.touch.f.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7456)
	at android.view.View.performClickInternal(View.java:7433)
	at android.view.View.access$3700(View.java:836)
	at android.view.View$PerformClick.run(View.java:28832)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7902)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)```

Tested on version 12.0 Alpha 4.
Android Developers site says that this method was added in Android Tiramisu

**Comment by SuperDragonXD** [comment]
Try updating to Lawnchair 12.1, it may have fixed the issue. Also closing since this is relevant to the older versions only.
