### ISSUE TITLE
Exception when adding certain widgets

### ISSUE THREAD

**Issue by Danmyrer** [Deletescape-Media/Lawnchair#2483]
### Describe the bug

Whenever I try to add a Widget from one of the following apps, I get an exception and the Widget doesn't get added:
- WarnWetter
- Untis Mobile
- Clock (Samsung)
- Glasswire

Lawnchair bug report 18.02.2022 15:21:31
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: samsung
build.device: d1
build.display: SP1A.210812.016.N970FXXU7GVA5
build.fingerprint: samsung/d1eea/d1:12/SP1A.210812.016/N970FXXU7GVA5:user/release-keys
build.hardware: exynos9825
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-N970F
build.product: d1eea
build.type: user
version.codename: REL
version.incremental: N970FXXU7GVA5
version.release: 12
version.sdk_int: 31
display.density_dpi: 420

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.dragndrop.DragLayer$2.onAnimationEnd(DragLayer.java:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1061)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

### Steps to reproduce

1. Download any of the mentioned Apps (i.e GlassWire)
2. Go to Lawnchair
3. Go to Widgets
4. Try to add any Widget from said app

### Expected behavior

The Widget gets added.

### Device information

- Device: Samsung Galaxy Note 10
- OS: Samsung One UI 4 (Android 12)
- App version: 12.0.0 Alpha 5

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with this  specific error) are now being tracked on #2820. Closing this issue.
