### ISSUE TITLE
[BUG] lc12 crashes as i install latest debug version

### ISSUE THREAD

**Issue by ljgp6** [Deletescape-Media/Lawnchair#2488]
### Describe the bug

Lc crashes as i install latest debug version on huawei nova 7se.

### Steps to reproduce

1. Install latest debug
2. Click open 
3. See error

### Expected behavior

Lc should not crash

### Device information

- Device: Huawei Nova 7se CDY-NX9B
- OS: Android 10, Emui 10.1.1
- App version 12 Dev (663)

**Comment by suphon-t** [comment]
Please be reminded that debug builds are unsupported, and always provide a crash log when reporting a crash.

**Comment by ljgp6** [comment]
Lawnchair bug report 25 Feb 2022 6:39:09 pm
version: 12.0.0 Dev (#663) (120005)
commit: e6c3c36
build.brand: HUAWEI
build.device: HWCDY
build.display: CDY-N29B 10.1.1.295(C636E2R1P1)
build.fingerprint: HUAWEI/CDY-NX9B/HWCDY:10/HUAWEICDY-N29B/10.1.1.295C636:user/release-keys
build.hardware: kirin820
build.id: HUAWEICDY-N29B
build.manufacturer: HUAWEI
build.model: CDY-NX9B
build.product: CDY-NX9B
build.type: user
version.codename: REL
version.incremental: 10.1.1.295C636
version.release: 10
version.sdk_int: 29
display.density_dpi: 480

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'int android.view.WindowManager$LayoutParams.flags' on a null object reference
	at androidx.core.view.WindowInsetsControllerCompat$Impl20.unsetWindowFlag(WindowInsetsControllerCompat.java:511)
	at androidx.core.view.WindowInsetsControllerCompat$Impl20.showForType(WindowInsetsControllerCompat.java:428)
	at androidx.core.view.WindowInsetsControllerCompat$Impl20.show(WindowInsetsControllerCompat.java:420)
	at androidx.core.view.WindowInsetsControllerCompat.show(WindowInsetsControllerCompat.java:163)
	at app.lawnchair.LawnchairLauncher$onCreate$4.invokeSuspend(LawnchairLauncher.kt:204)
	at app.lawnchair.LawnchairLauncher$onCreate$4.invoke(Unknown Source:12)
	at app.lawnchair.LawnchairLauncher$onCreate$4.invoke(Unknown Source:10)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:81)
	at com.patrykmichalik.preferencemanager.PreferenceImpl$get$$inlined$map$1$2.emit(Emitters.kt:224)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$1$1.emit(Limit.kt:40)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
	at kotlinx.coroutines.flow.FlowKt__LimitKt$dropWhile$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at androidx.datastore.core.SingleProcessDataStore$data$1$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invokeSuspend(SingleProcessDataStore.kt:117)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:8)
	at androidx.datastore.core.SingleProcessDataStore$data$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:227)
	at com.patrykmichalik.preferencemanager.PreferenceImpl$get$$inlined$map$1.collect(SafeCollector.common.kt:113)
	at kotlinx.coroutines.flow.DistinctFlowImpl.collect(Distinct.kt:76)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect(SafeCollector.common.kt:113)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.collect(Collect.kt:30)
	at kotlinx.coroutines.flow.FlowKt.collect(Unknown Source:1)
	at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend(Collect.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.launchIn(Collect.kt:49)
	at kotlinx.coroutines.flow.FlowKt.launchIn(Unknown Source:1)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:211)
	at android.app.Activity.performCreate(Activity.java:8085)
	at android.app.Activity.performCreate(Activity.java:8073)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by ljgp6** [comment]
Its fine i just want to report it maybe for reference whenever it will be carried to alpha build. Thank  you

**Comment by ljgp6** [comment]
Now fixed in lc 12 debug # 666. Thank you
