### ISSUE TITLE
[BUG] latest lawnchair outputs random string and crashes

### ISSUE THREAD

**Issue by julianh0486** [Deletescape-Media/Lawnchair#2511]
### Describe the bug

While using lawnchair on my device the lawnchair app crashes randomly and dumps a lot of strange text

### Steps to reproduce

1. Use lawnchair on OnePlus 9 pro with 5g and click on the date widget
2. See error

### Expected behavior

Open the calander app

### Screenshots

No screenshot only debug log

### Device information

- Device: [OnePlus 9 Pro]
- OS: [stock ROM Android version 12.0]
- App version [12.0.0 Alpha 5]

### Additional context

Debug log.

Lawnchair bug report Mar 13, 2022 20:46:15
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: OnePlus
build.device: OnePlus9Pro
build.display: LE2123_11_C.44
build.fingerprint: OnePlus/OnePlus9Pro_EEA/OnePlus9Pro:12/SKQ1.210216.001/R.202201181959:user/release-keys
build.hardware: qcom
build.id: SKQ1.210216.001
build.manufacturer: OnePlus
build.model: LE2123
build.product: OnePlus9Pro_EEA
build.type: user
version.codename: REL
version.incremental: R.202201181959
version.release: 12
version.sdk_int: 31
display.density_dpi: 480

error: Uncaught exception

android.view.InflateException: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #25 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
Caused by: java.lang.IllegalArgumentException: Binary XML file line #25: Duplicate id 0xffffffff, tag smart_space_view, or parent id 0x7f0a0186 with another fragment for app.lawnchair.nexuslauncher.SmartspaceQsb$SmartSpaceFragment
	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3568)
	at android.app.FragmentController.onCreateView(FragmentController.java:105)
	at android.app.Activity.onCreateView(Activity.java:7250)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.launcher3.Workspace.bindAndInitFirstWorkspaceScreen(Workspace.java:4)
	at com.android.launcher3.Workspace.removeAllWorkspaceScreens(Workspace.java:9)
	at com.android.launcher3.Launcher.startBinding(Launcher.java:6)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$bind$0(BaseLoaderResults.java:2)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.f(Unknown Source:0)
	at com.android.launcher3.model.o.execute(Unknown Source:0)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$executeCallbacksTask$9(BaseLoaderResults.java:3)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.c(Unknown Source:0)
	at com.android.launcher3.model.p.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8184)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by SuperDragonXD** [comment]
Should be fixed in the latest version of Lawnchair (Lawnchair 12.1 Alpha 4). Closing this issue
