### ISSUE TITLE
[BUG] Lawnchair keeps crashing

### ISSUE THREAD

**Issue by Sidd-Neog** [Deletescape-Media/Lawnchair#2527]
### Describe the bug

Lawnchair crashes randomly and generates a log

### Steps to reproduce

1. Go to Homescreen from any app

### Expected behavior

Shouldn't crash

### Screenshots

![Screenshot_20220401-202109_Chrome](https://user-images.githubusercontent.com/102815216/161288207-55933036-0151-40d3-a8c2-9adc6b3c4e07.png)

### Device information

- Device: Redmi k20
- OS: [SparkOS ROM Android version 12.0]
- App version [e.g. 12.0.0 Alpha 5]

### Additional context

Lawnchair bug report 01-Apr-2022 8:11:23 pm
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: Xiaomi
build.device: davinciin
build.display: spark_davinci-userdebug 12 SQ1D.220205.003 13 release-keys
build.fingerprint: Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/release-keys
build.hardware: qcom
build.id: SQ1D.220205.003
build.manufacturer: Xiaomi
build.model: Redmi K20
build.product: spark_davinci
build.type: userdebug
version.codename: REL
version.incremental: 13
version.release: 12
version.sdk_int: 31
display.density_dpi: 440

error: Uncaught exception

android.view.InflateException: Binary XML file line #17 in app.lawnchair:layout/digital_wellbeing_toast: Binary XML file line #17 in app.lawnchair:layout/digital_wellbeing_toast: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #17 in app.lawnchair:layout/digital_wellbeing_toast: Error inflating class <unknown>
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0402a6 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
	at android.widget.TextView.readTextAppearance(TextView.java:4058)
	at android.widget.TextView.<init>(TextView.java:1127)
	at android.widget.TextView.<init>(TextView.java:1028)
	at android.widget.TextView.<init>(TextView.java:1024)
	at android.view.LayoutInflater.tryCreateViewDirect(LayoutInflater.java:1398)
	at android.view.LayoutInflater.createView(LayoutInflater.java:814)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:942)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:962)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.launcher3.util.ViewCache.getView(ViewCache.java:8)
	at com.android.quickstep.views.DigitalWellBeingToast.setLimit(DigitalWellBeingToast.java:3)
	at com.android.quickstep.views.DigitalWellBeingToast.lambda$initialize$0(DigitalWellBeingToast.java:1)
	at com.android.quickstep.views.DigitalWellBeingToast.b(Unknown Source:0)
	at com.android.quickstep.views.c.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7837)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by SuperDragonXD** [comment]
Try force stopping, clearing cache, clear data, reinstall.

**Comment by Sidd-Neog** [comment]
Already tried it. It starts crashing after a while.

**Comment by SuperDragonXD** [comment]
When you mean "randomly", are you doing some action, eg opening apps, adding widgets, opening app drawer, and such before it crashes, or are you just doing nothing?

Also, do you have the "Per-App Icon Customization" on?

**Comment by Sidd-Neog** [comment]
Everytime I return to Homescreen from any app it crashes

**Comment by SuperDragonXD** [comment]
Screen recording on when it happens?

Also, looking at the debug log, it seems to be related to a widget.

**Comment by Sidd-Neog** [comment]
Does it says which widget? I have the default google at glance widget.

**Comment by scoobydooo86** [comment]
content://app.lawnchair.bugreport.provider/log_files/a50a4694/Lawnchair%20bug%20report%20Apr%203%2C%202022%206%3A17%3A23%20PM.txt

**Comment by RikKoedoot** [comment]
You know we cannot open that @scoobydooo86, that's not a link.

**Comment by PetbkA** [comment]
**12.1.0 Alpha 3** - same here bit in my case the Recent Apps have stopped working.

Today I've updated Lawnchair to the latest 12.1.0 Alpha 3 (IzzyOnDroid repo).

Updated app has started to crash frequently, but, what's the most annoying, Recent Apps functionality has gone, whether I use "square button" on classic three-buttons-navbar or gesture in the new types of navbar.

When I've changed default home app back to Lawnchair from the Nova Launcher 7.0.57, I've got the following message:
> Incompatible System Configuration
> Your device is configured to have system gestures (known as Quickstep) provided by Lawnchair, but this version of Lawnchair is not compatible with your Android version

Although I'm not using Quickstep - I use classic navbar type, so I don't understand why this error is being raised.

I also can't downgrade - attempts with Alpha 1 and 12.0.0 Alpha 5 are failing with
> Failed to install due to unknown error

error. May be it's because Lawn chair is system app. This is another reason I don't want to reinstall it - I'm afraid that the whole OS will crash, and I can't recover it 'cause there's now ways to decrypt and backup data partition for Android 12 AFAIK.

Crashes contain the following dump:
<details>
  <summary>Dump</summary>

> Lawnchair bug report Jun 14, 2022 06:57:53
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: Redmi
build.device: joyeuse
build.display: lineage_miatoll-userdebug 12 SQ1D.220205.003 116 release-keys
build.fingerprint: google/raven/raven:12/SQ1D.220205.003/8069835:user/release-keys
build.hardware: qcom
build.id: SQ1D.220205.003
build.manufacturer: Xiaomi
build.model: Redmi Note 9 Pro
build.product: lineage_miatoll
build.type: user
version.codename: REL
version.incremental: 116
version.release: 12
version.sdk_int: 31
display.density_dpi: 440
isRecentsEnabled: false

> error: Uncaught exception

>java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.quickstep.RecentsAnimationDeviceState.isUserUnlocked()' on a null object reference
	at com.android.quickstep.TouchInteractionService.onConfigurationChanged(TouchInteractionService.java:1)
	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:275)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:242)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:139)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5947)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
</details>

**Comment by SuperDragonXD** [comment]
> Although I'm not using Quickstep - I use classic navbar type, so I don't understand why this error is being raised.

Do you have QuickSwitch installed tho?

Also, Lawnchair 12.1 is NOT compatible with Android 12, so that error

**Comment by PetbkA** [comment]
> Do you have QuickSwitch installed tho?

No.

> Lawnchair 12.1 is NOT compatible with Android 12, so that error

1. I've upgraded from 1.2.0 Alpha 3 if I'm not mistaken. Everything was OK there in Android 12 too;
2. There were no warnings on the F-Droid so I couldn't be aware of it before the update. I don't even see such on the [Releases](https://github.com/LawnchairLauncher/lawnchair/releases) page

**Comment by SuperDragonXD** [comment]
I meant the bottom part of my message above is when you use Quickswitch.

(Do you see this menu:

![Screenshot_2022-06-15-10-56-57-15_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/70206496/173727119-3ed56c46-854d-4f59-9fa2-9fec5271448f.jpg)
)

> May be it's because Lawn chair is system app.
How did you do that? Did you root or something?

**Comment by PetbkA** [comment]
> Do you see this menu

No, even if I install QuickSwitch and restart Lawnchair.

> May be it's because Lawn chair is system app

It was in the ROM from the beginning (I guess I used the March build of [this one](https://www.pling.com/p/1734495/))
