### ISSUE TITLE
[BUG] App crashes after manually adding "At A Glance"

### ISSUE THREAD

**Issue by pgrynfelder** [Deletescape-Media/Lawnchair#2531]
### Describe the bug

App crashes after manually adding the "At A Glance" Google widget.

### Steps to reproduce

1. Go to Widgets.
2. Go to "Google"
3. Add "At A Glance" to home screen.
4. App crashes.

### Expected behavior

The widget should get added to the home screen.

### Device information

```
Lawnchair bug report 9 Apr 2022 00:20:18
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: OnePlus
build.device: OnePlus8T
build.display: KB2005_11_C.11
build.fingerprint: OnePlus/OnePlus8T/OnePlus8T:12/SKQ1.210216.001/R.202203142337:user/release-keys
build.hardware: qcom
build.id: SKQ1.210216.001
build.manufacturer: OnePlus
build.model: KB2005
build.product: OnePlus8T
build.type: user
version.codename: REL
version.incremental: R.202203142337
version.release: 12
version.sdk_int: 31
display.density_dpi: 480

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.dragndrop.DragLayer$2.onAnimationEnd(DragLayer.java:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:563)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1505)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1221)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1020)
	at android.view.Choreographer.doFrame(Choreographer.java:921)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1208)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with this  specific error) are now being tracked on #2820. Closing this issue.
