### ISSUE TITLE
[BUG] App crashes when opened in the Secondary Splitscreen side

### ISSUE THREAD

**Issue by ComValer** [Deletescape-Media/Lawnchair#2532]
### Describe the bug

For some reason, when you put some app into splitscreen mode, and trying to find some second one in the Lawnchair (in Home screen or App Drawer, whatever) - it just dies.

### Steps to reproduce

1. Set any app to Splitscreen mode
2. Instead of instantly choosing the Second app between the Recent ones, try to get to Lawnchair and find some app there
3. See error

### Expected behavior

As it was in the Lawnchair 1, it should just get wide, and allow you to launch some app to be in the second Splitscreen side. But the app crashes instead.

### Screenshots

![Screenshot_20220410-230348](https://user-images.githubusercontent.com/72487083/162637639-4ed253e6-9575-499d-879c-723d7f3b169f.jpg)

Here's
Lawnchair bug report Apr 10, 2022 10:00:00 PM
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: Lenovo
build.device: 15IWL
build.display: android_x86_64-userdebug 9 PQ2A.190405.003 eng.jenkin.20220309.060428 test-keys
build.fingerprint: Android-x86/android_x86_64/x86_64:9/PSV1.210329.015/jenkins11071714:userdebug/test-keys
build.hardware: android_x86_64
build.id: PQ2A.190405.003
build.manufacturer: LENOVO
build.model: 81MV
build.product: IdeaPad S145
build.type: userdebug
version.codename: REL
version.incremental: eng.jenkin.20220309.060428
version.release: 9
version.sdk_int: 28
display.density_dpi: 192

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:1)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:2)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:1)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:17)
	at com.android.quickstep.views.RecentsView.getTaskSize(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.updateSizeAndPadding(RecentsView.java:2)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:17)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:9)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:2)
	at com.android.launcher3.statemanager.StatefulActivity.reapplyUi(StatefulActivity.java:1)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:3)
	at com.android.launcher3.Launcher.onConfigurationChanged(Launcher.java:2)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onConfigurationChanged(QuickstepLauncher.java:1)
	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:5071)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4938)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4916)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5293)
	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:43)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

### Device information

- Device: Lenovo IdeaPad S145 81MV
- OS: stock Android Pie
- App version 12.0.0 Alpha 5
- System Info: x86-64 ABI, 1920x1080 192 Y/XDPI

### Additional context

This problem didn't appeared in Android 11 device

**Comment by dhirenvasnani** [comment]
I also faced the same bug!
Device: Poco C3(angelicain)
OS: MIUI 12.0.17.0, Based on Android

Here's the bug report:-

Lawnchair bug report 11-Apr-2022 3:48:09 am
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: POCO
build.device: angelicain
build.display: QP1A.190711.020
build.fingerprint: POCO/angelicain/angelicain:10/QP1A.190711.020/V12.0.17.0.QCRINXM:user/release-keys
build.hardware: mt6765
build.id: QP1A.190711.020
build.manufacturer: Xiaomi
build.model: M2006C3MI
build.product: angelicain
build.type: user
version.codename: REL
version.incremental: V12.0.17.0.QCRINXM
version.release: 10
version.sdk_int: 29
display.density_dpi: 320

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:1)
	at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:2)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4)
	at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:1)
	at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:17)
	at com.android.quickstep.views.RecentsView.getTaskSize(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.updateSizeAndPadding(RecentsView.java:2)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:17)
	at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1)
	at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:9)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3)
	at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:2)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:39)
	at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:1)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:3)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by ComValer** [comment]
> I also faced the same bug! Device: Poco C3(angelicain) OS: MIUI 12.0.17.0, Based on Android
> 
> Here's the bug report:-
> 
> Lawnchair bug report 11-Apr-2022 3:48:09 am version: 12.0.0 Alpha 5 (120005) commit: [56a18d7](https://github.com/LawnchairLauncher/lawnchair/commit/56a18d71a3f4409d2ab6054814fa15cf9e8b3d17) build.brand: POCO build.device: angelicain build.display: QP1A.190711.020 build.fingerprint: POCO/angelicain/angelicain:10/QP1A.190711.020/V12.0.17.0.QCRINXM:user/release-keys build.hardware: mt6765 build.id: QP1A.190711.020 build.manufacturer: Xiaomi build.model: M2006C3MI build.product: angelicain build.type: user version.codename: REL version.incremental: V12.0.17.0.QCRINXM version.release: 10 version.sdk_int: 29 display.density_dpi: 320
> 
> error: Uncaught exception
> 
> java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex) at com.android.quickstep.util.SplitScreenBounds.createDefaultWindowBounds(SplitScreenBounds.java:1) at com.android.quickstep.util.SplitScreenBounds.getSecondaryWindowBounds(SplitScreenBounds.java:2) at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:4) at com.android.quickstep.BaseActivityInterface.getTaskDimension(BaseActivityInterface.java:2) at com.android.quickstep.BaseActivityInterface.calculateTaskSizeInternal(BaseActivityInterface.java:1) at com.android.quickstep.BaseActivityInterface.calculateTaskSize(BaseActivityInterface.java:17) at com.android.quickstep.views.RecentsView.getTaskSize(RecentsView.java:1) at com.android.quickstep.views.RecentsView.updateSizeAndPadding(RecentsView.java:2) at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:17) at com.android.quickstep.views.RecentsView.updateOrientationHandler(RecentsView.java:1) at com.android.quickstep.views.RecentsView.setInsets(RecentsView.java:9) at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3) at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3) at com.android.launcher3.InsettableFrameLayout.setFrameLayoutChildInsets(InsettableFrameLayout.java:3) at com.android.launcher3.InsettableFrameLayout.setInsets(InsettableFrameLayout.java:3) at com.android.launcher3.LauncherRootView.dispatchInsets(LauncherRootView.java:2) at com.android.launcher3.Launcher.onCreate(Launcher.java:39) at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:1) at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:3) at android.app.Activity.performCreate(Activity.java:7893) at android.app.Activity.performCreate(Activity.java:7880) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3489) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:225) at android.app.ActivityThread.main(ActivityThread.java:7563) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

Yeah, nice to see another one)
I didn't got the bug on Android 11 Realme UI 2.0 based Realme 8i smartphone - everything worked just nice. It's supposed to be something with the Android 10 and older APIs and their methods)( At least there the cases of this, just waiting for devs to solve it finally! 😃😃
