### ISSUE TITLE
[BUG] Lawnchair crashes when opening apps on Android 13 Beta 1

### ISSUE THREAD

**Issue by james-amend** [Deletescape-Media/Lawnchair#2553]
### Describe the bug

Lawnchair crashes when opening any app

### Steps to reproduce

Launch any app from the homescreen or app drawer

### Expected behavior

Selected app opens

### Device information

- Device: Google Pixel 6
- OS: Android 13 Beta 1
- App version: 12.0.0 Alpha 5

### Additional context

Lawnchair bug report Apr 26, 2022 15:39:11
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: google
build.device: oriole
build.display: TPB1.220310.029
build.fingerprint: google/oriole/oriole:Tiramisu/TPB1.220310.029/8473704:user/release-keys
build.hardware: oriole
build.id: TPB1.220310.029
build.manufacturer: Google
build.model: Pixel 6
build.product: oriole
build.type: user
version.codename: Tiramisu
version.incremental: 8473704
version.release: 12
version.sdk_int: 32
display.density_dpi: 420

error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method setSplashscreenStyle(I)V in class Landroid/app/ActivityOptions; or its super classes (declaration of 'android.app.ActivityOptions' appears in /system/framework/framework.jar)
	at com.android.launcher3.BaseQuickstepLauncher.getActivityLaunchOptions(BaseQuickstepLauncher.java:7)
	at com.android.launcher3.BaseDraggingActivity.startActivitySafely(BaseDraggingActivity.java:3)
	at com.android.launcher3.Launcher.startActivitySafely(Launcher.java:6)
	at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(QuickstepLauncher.java:2)
	at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(ItemClickHandler.java:14)
	at com.android.launcher3.touch.ItemClickHandler.onClickAppShortcut(ItemClickHandler.java:8)
	at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:6)
	at com.android.launcher3.touch.ItemClickHandler.b(Unknown Source:0)
	at com.android.launcher3.touch.f.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7497)
	at android.view.View.performClickInternal(View.java:7474)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29180)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7844)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Darkham42** [comment]
Same on my Pixel 5.

**Comment by N0spark** [comment]
Same exact problem. Pixel 4. Splash screen error of some sort?

**Comment by SuperDragonXD** [comment]
It's likely because Lawnchair 12 hasn't been ported to Launcher3 13, let alone Launcher3 12.1. Or maybe because there isn't support for higher android versions yet (manual porting, not change base).

Looking at the logs, it seems like the splash screen code has been removed (since error `java.lang.NoSuchMethodError: No virtual method setSplashscreenStyle(I)V in class Landroid/app/ActivityOptions;`); I'm not sure though.

**Comment by N0spark** [comment]
I figured. They are both in beta. Awaiting updates!

**Comment by Darkham42** [comment]
Exact problem on Beta 2, seems Google doesn't want us to use LawnchairLauncher.

**Comment by RikKoedoot** [comment]
Does the crash also occur in this apk? https://github.com/LawnchairLauncher/lawnchair/suites/6463958538/artifacts/238415984

**Comment by Darkham42** [comment]
> Does the crash also occur in this apk? https://github.com/LawnchairLauncher/lawnchair/suites/6463958538/artifacts/238415984

Seems ok for me !

**Comment by RikKoedoot** [comment]
Closing as it's fixed in next release
