### ISSUE TITLE
[BUG] Desktop mode making Lawnchair crush when it's the default launcher 

### ISSUE THREAD

**Issue by thoweeth** [Deletescape-Media/Lawnchair#2574]
### Describe the bug

Lately, I've started using the desktop mode on my LG G8S, Android 11, and the device normally works great with the Alpha 5, but when I plug my phone to the screen, Lawnchair crushes, and even though I can change the launcher to the stock one, I have to restart my device to be able to run Lawnchair again 😕 I've tried changing the default launcher to the stock one before plugging it in, and that lets me change it back after I'm done using the desktop mode, but when I start running apps, Lawnchair crushes again 🤔 I can still run it when I launch it from the stock launcher, but not as the default one, and whenever I try to change it, it crushes

### Steps to reproduce

Plug the phone in to a screen, using an HDMI cable, with Lawnchair set as default, and the app crushes. The same happening when Lawnchair is set as default afterwards, not having been default before plugging the phone in, and the solution at the moment is to restart the phone every time, which is problematic

### Expected behavior

I expect Lawnchair to keep on working without any crushes, with the desktop mode working normally on the external screen, and Lawnchair normally on the phone

### Device information

- Device: LG G8S
- OS: LG's stock ROM, Android version 11
- App version: 12.0.0 Alpha 5

### Additional context

Lawnchair bug report 12 mai 2022 00:38:14
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: lge
build.device: betalm
build.display: RKQ1.210420.001
build.fingerprint: lge/betalm_e/betalm:11/RKQ1.210420.001/220141702a5f6.OPEN_EU_DS:user/release-keys
build.hardware: betalm
build.id: RKQ1.210420.001
build.manufacturer: LGE
build.model: LM-G810
build.product: betalm_e
build.type: user
version.codename: REL
version.incremental: 220141702a5f6.OPEN_EU_DS
version.release: 11
version.sdk_int: 30
display.density_dpi: 420

error: Uncaught exception

android.view.InflateException: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: android.view.InflateException: Binary XML file line #44 in app.lawnchair:layout/secondary_launcher: Error inflating class com.android.launcher3.allapps.AllAppsContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:463)
	at android.app.Activity.setContentView(Activity.java:3487)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.initUi(SecondaryDisplayLauncher.java:10)
	at com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher.onAttachedToWindow(SecondaryDisplayLauncher.java:2)
	at com.android.internal.policy.DecorView.onAttachedToWindow(DecorView.java:1867)
	at android.view.View.dispatchAttachedToWindow(View.java:20526)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3576)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2562)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2035)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8585)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
	at android.view.Choreographer.doFrame(Choreographer.java:811)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7888)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: java.lang.ClassCastException: com.android.launcher3.secondarydisplay.SecondaryDisplayLauncher cannot be cast to app.lawnchair.LawnchairLauncher
	at s4.r.a(Unknown Source:14)
	at t4.d.<init>(LawnchairAlphabeticalAppsList.kt:4)
	at com.android.launcher3.allapps.AllAppsContainerView$AdapterHolder.<init>(AllAppsContainerView.java:5)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:24)
	at com.android.launcher3.allapps.AllAppsContainerView.<init>(AllAppsContainerView.java:2)
	... 31 more

**Comment by suphon-t** [comment]
Fixed by 515efb6 (disabling the broken secondary launcher)
