### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by divyanshkatiyar** [Deletescape-Media/Lawnchair#2581]
### Describe the bug

Lawnchair bug report May 15, 2022 7:47:15 PM
version: 12.0.0 Alpha 5 (120005)
commit: 56a18d7
build.brand: samsung
build.device: m21
build.display: SP1A.210812.016.M215FXXU2CVCC
build.fingerprint: samsung/m21nnxx/m21:12/SP1A.210812.016/M215FXXU2CVCC:user/release-keys
build.hardware: exynos9611
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-M215F
build.product: m21nnxx
build.type: user
version.codename: REL
version.incremental: M215FXXU2CVCC
version.release: 12
version.sdk_int: 31
display.density_dpi: 420

error: Uncaught exception

java.lang.RuntimeException: Unable to destroy activity {app.lawnchair/app.lawnchair.LawnchairLauncher}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler android.app.FragmentHostCallback.getHandler()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler android.app.FragmentHostCallback.getHandler()' on a null object reference
	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2008)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2061)
	at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2709)
	at android.app.FragmentController.saveAllState(FragmentController.java:119)
	at android.app.Activity.onSaveInstanceState(Activity.java:2321)
	at com.android.launcher3.Launcher.onSaveInstanceState(Launcher.java:16)
	at app.lawnchair.LawnchairLauncher.onSaveInstanceState(LawnchairLauncher.kt:1)
	at com.android.launcher3.Launcher.onIdpChanged(Launcher.java:5)
	at f5.b$a$a.a(Effects.kt:11)
	at m0.x.f(Effects.kt:1)
	at m0.o$a.e(Composition.kt:5)
	at m0.o.a(Composition.kt:15)
	at androidx.compose.ui.platform.WrappedComposition.a(Wrapper.android.kt:5)
	at androidx.compose.ui.platform.WrappedComposition.n(Wrapper.android.kt:2)
	at androidx.lifecycle.s$a.a(LifecycleRegistry.java:3)
	at androidx.lifecycle.s.d(LifecycleRegistry.java:10)
	at androidx.lifecycle.s.p(LifecycleRegistry.java:5)
	at androidx.lifecycle.s.l(LifecycleRegistry.java:5)
	at androidx.lifecycle.s.h(LifecycleRegistry.java:2)
	at app.lawnchair.LawnchairLauncher.onDestroy(LawnchairLauncher.kt:2)
	at android.app.Activity.performDestroy(Activity.java:8571)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
	... 13 more

### Expected behavior

Lawnchair crashed 

### Device information

Device: Samsung Galaxy m21 
OS: android 12

**Comment by RikKoedoot** [comment]
Closing due to lack of Information
