### ISSUE TITLE
Lawnchair's search bar google lens crashed, cant be use

### ISSUE THREAD

**Issue by zicodm** [Deletescape-Media/Lawnchair#2619]
### Describe the bug

Can not use google lens on lawnchair google search bar dock

### Steps to reproduce

1. Go to Home Screen
2. Click on 'Lens logo on the right side.'
3. See error 'Notification of Lawnchair crashed

### Expected behavior

Launcher crashed

### Device information

- Device: [Samsung Galaxy S8+]
- OS: [Android 9 Pie (One UI 1.0)]
- App version [12.1 Alpha 3]

### Additional context

Lawnchair bug report May 20, 2022 12:13:16
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: dream2lte
build.hardware: samsungexynos8895
build.manufacturer: samsung
build.model: SM-G955F
build.product: dream2ltexx
build.type: user
version.codename: REL
version.incremental: G955FXXUCDUD1
version.release: 9
version.sdk_int: 28
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.ar.lens/com.google.vr.apps.ornament.app.lens.LensLauncherActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2016)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
	at android.app.Activity.startActivityForResult(Activity.java:4689)
	at com.android.launcher3.Launcher.startActivityForResult(Launcher.java:2)
	at com.android.launcher3.BaseQuickstepLauncher.startActivityForResult(BaseQuickstepLauncher.java:6)
	at android.app.Activity.startActivityForResult(Activity.java:4647)
	at android.app.Activity.startActivity(Activity.java:5008)
	at android.app.Activity.startActivity(Activity.java:4976)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
	at app.lawnchair.qsb.QsbLayout.o(Unknown Source:14)
	at app.lawnchair.qsb.QsbLayout.c(Unknown Source:0)
	at b6.c.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7352)
	at android.view.View.performClickInternal(View.java:7318)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27800)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by SuperDragonXD** [comment]
Sorry for the late reply, but installing the Lens app from the play store will fix this issue. Therefore closing this issue.

**Comment by Goooler** [comment]
I can repro this issue, if we are removing Google Lens and go back to the home screen to tap the Lens icon will trigger the crash.
