### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Jen88uk** [Deletescape-Media/Lawnchair#2620]
### Describe the bug

Just crashed while moving an icon around on the home screen

### Steps to reproduce

Doesn't always happen but happened while moving an icon

### Expected behavior

Not crash

### Screenshots

Lawnchair bug report 20 May 2022 10:12:36 am
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: y2s
build.display: SP1A.210812.016.G986BXXUEFVDB
build.fingerprint: samsung/y2sxeea/y2s:12/SP1A.210812.016/G986BXXUEFVDB:user/release-keys
build.hardware: exynos990
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-G986B
build.product: y2sxeea
build.type: user
version.codename: REL
version.incremental: G986BXXUEFVDB
version.release: 12
version.sdk_int: 31
display.density_dpi: 448
isRecentsEnabled: false

error: Uncaught exception

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:12)
	at com.android.launcher3.folder.Folder.animateClosed(Folder.java:5)
	at com.android.launcher3.folder.Folder.handleClose(Folder.java:8)
	at com.android.launcher3.AbstractFloatingView.close(AbstractFloatingView.java:2)
	at com.android.launcher3.folder.Folder.completeDragExit(Folder.java:2)
	at com.android.launcher3.folder.Folder$8.onAlarm(Unknown Source:2)
	at com.android.launcher3.Alarm.run(Alarm.java:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Device information

- Device: Samsung Galaxy S20+ 5G SM-G986B/DS
- OS: Android 12 One UI 4.1
- App version 12.1.0 alpha 3

### Additional context

Lawnchair bug report 20 May 2022 10:12:36 am
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: y2s
build.display: SP1A.210812.016.G986BXXUEFVDB
build.fingerprint: samsung/y2sxeea/y2s:12/SP1A.210812.016/G986BXXUEFVDB:user/release-keys
build.hardware: exynos990
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-G986B
build.product: y2sxeea
build.type: user
version.codename: REL
version.incremental: G986BXXUEFVDB
version.release: 12
version.sdk_int: 31
display.density_dpi: 448
isRecentsEnabled: false

error: Uncaught exception

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:12)
	at com.android.launcher3.folder.Folder.animateClosed(Folder.java:5)
	at com.android.launcher3.folder.Folder.handleClose(Folder.java:8)
	at com.android.launcher3.AbstractFloatingView.close(AbstractFloatingView.java:2)
	at com.android.launcher3.folder.Folder.completeDragExit(Folder.java:2)
	at com.android.launcher3.folder.Folder$8.onAlarm(Unknown Source:2)
	at com.android.launcher3.Alarm.run(Alarm.java:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by William150722** [comment]
Hi any find out on this?
