### ISSUE TITLE
[BUG] Lawnchair has crashed, NullPointerException - crash on changing work profile app icons

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2624]
### Describe the bug

lawnchair crash when trying to change work profile apps icons

### Steps to reproduce

1. Go to Edit user app icon (eg whatapps, systemapps seems to work fine)
2. Click on Icon

### Expected behavior

be able to change the icon

### Device information

- Device: Google Pixel 5A
- OS: ANDROID 12.1
- App version 12.1.0 Alpha 3

### Additional context

```
Uncaught exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.pm.LauncherActivityInfo.getLabel()' on a null object reference
	at n6.h0.a(SelectIconPreference.kt:13)
	at n6.j$a.a(SelectIconPreference.kt:5)
	at n6.j$a.M(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.M(Unknown Source:8)
	at u8.b$i$a.a(AnimatedNavHost.kt:4)
	at u8.b$i$a.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at n0.r.a(CompositionLocal.kt:3)
	at w0.d.b(SaveableStateHolder.kt:16)
	at o4.h.b(NavBackStackEntryProvider.kt:10)
	at o4.h.c(Unknown Source:0)
	at o4.h$a.a(Unknown Source:28)
	at o4.h$a.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at n0.r.a(CompositionLocal.kt:3)
	at o4.h.a(NavBackStackEntryProvider.kt:6)
	at u8.b$i.a(AnimatedNavHost.kt:7)
	at u8.b$i.M(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.M(Unknown Source:8)
	at t.b$c$c.a(AnimatedContent.kt:6)
	at t.b$c$c.C(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b.C(Unknown Source:8)
	at t.f.a(AnimatedVisibility.kt:78)
	at t.f.b(AnimatedVisibility.kt:5)
	at t.b$c.a(AnimatedContent.kt:30)
	at t.b$c.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at t.b.a(AnimatedContent.kt:98)
	at u8.b.b(AnimatedNavHost.kt:60)
	at u8.b$a.a(Unknown Source:23)
	at u8.b$a.i0(Unknown Source:8)
	at n0.f1.g(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.C(Composer.kt:5)
	at u6.i$c.a(ProvideBottomSheetHandler.kt:2)
	at u6.i$c.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at h0.d1$a.a(ModalBottomSheet.kt:42)
	at h0.d1$a.C(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b$a.a(Unknown Source:13)
	at u0.b$a.i0(Unknown Source:8)
	at n0.f1.g(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.x1(Composer.kt:9)
	at n0.j$i.a(Composer.kt:11)
	at n0.j$i.q(Unknown Source:0)
	at n0.v1.d(DerivedState.kt:6)
	at n0.u1.j(Unknown Source:0)
	at n0.j.s0(Composer.kt:18)
	at n0.j.X0(Composer.kt:5)
	at n0.o.y(Composition.kt:4)
	at n0.g1.f0(Recomposer.kt:8)
	at n0.g1.K(Unknown Source:0)
	at n0.g1$j$a.a(Recomposer.kt:50)
	at n0.g1$j$a.invoke(Unknown Source:6)
	at androidx.compose.ui.platform.e0$c.doFrame(Unknown Source:10)
	at androidx.compose.ui.platform.c0.b1(AndroidUiDispatcher.android.kt:10)
	at androidx.compose.ui.platform.c0.V0(Unknown Source:0)
	at androidx.compose.ui.platform.c0$d.doFrame(AndroidUiDispatcher.android.kt:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: wb.y0: [n0.x0@dd8d970, androidx.compose.ui.platform.e1@434e4e9, v2{Cancelling}@d7aa56e, c0@cb4240f] 
```

**Comment by miacate** [comment]
Can confirm this bug; also experiencing it. Although it only happens with apps that are only present in the work profile. 

Also on 12.1.0 Alpha 3; Android 11; Google Pixel 3A xl

**Comment by miacate** [comment]
I hate stale bot.

**Comment by PalmDevs** [comment]
Still happening on latest builds (1387).

Editing the apps that is installed on both the work profile and the normal profile (Profile 0) makes it not crash. However, if that app does not exist on the normal profile, it's a hard crash.

Edits to the app also get reset on reboot.

**Comment by icarusinthewings** [comment]
Still happening, and I'm encountering this error as well while isolating my big brother apps with Insular.

**Comment by miacate** [comment]
useless stale bot

**Comment by PalmDevs** [comment]
hey, this isn't fixed!?
