### ISSUE TITLE
Uncaught Exception 

### ISSUE THREAD

**Issue by vicl89** [Deletescape-Media/Lawnchair#2636]
### Describe the bug

Everytime I want to add a Google app widget, it crashes. Doesn't matter what widget I choose, every Google widget fails.

Well, only Calendar seems to work properly.

### Steps to reproduce

1. just try to add a widget from any Google app like clock, GDrive, etc.

### Expected behavior

The widget must appear on screen

### Device information

- Device: POCO X3 PRO
- OS: Android 12 MIUI V13.0.3.0.SJUMIXM
- App version 12.1.0 Alpha 3 (12010003)

### Additional context

Lawnchair bug report 22 may. 2022 21:56:01
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: POCO
build.device: vayu
build.display: SKQ1.211006.001 release-keys
build.fingerprint: POCO/vayu_global/vayu:12/SKQ1.211006.001/V13.0.3.0.SJUMIXM:user/release-keys
build.hardware: qcom
build.id: SKQ1.211006.001
build.manufacturer: Xiaomi
build.model: M2102J20SG
build.product: vayu_global
build.type: user
version.codename: REL
version.incremental: V13.0.3.0.SJUMIXM
version.release: 12
version.sdk_int: 31
display.density_dpi: 440
isRecentsEnabled: false

error: Uncaught Exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Unknown Source:0)
	at android.animation.AnimatorSet.endAnimation(Unknown Source:56)
	at android.animation.AnimatorSet.doAnimationFrame(Unknown Source:269)
	at android.animation.AnimationHandler.doAnimationFrame(Unknown Source:30)
	at android.animation.AnimationHandler.access$100(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(Unknown Source:10)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:12)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:307)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

**Comment by gotenksIN** [comment]
@vicl89 miui moment
