### ISSUE TITLE
[BUG] Crash when creating backup

### ISSUE THREAD

**Issue by pokemaster974** [Deletescape-Media/Lawnchair#2639]
### Describe the bug

Everytime I try to create backup, it crashes

### Steps to reproduce

1. Go to settings
2. Click on Create backup
3. Wait

### Expected behavior

Create backup

### Device information

- Device: Xiaomi Mi 9
- OS: crDroid 8.2 (Android 12)
- App version : 12.1.0 Alpha 3 (12010003)

### Additional context

time: 1653232614487
msg: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
stacktrace: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:699)
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1605)
	at com.android.launcher3.icons.FastBitmapDrawable.drawInternal(Unknown Source:5)
	at com.android.launcher3.icons.FastBitmapDrawable.draw(FastBitmapDrawable.java:7)
	at com.android.launcher3.folder.PreviewItemManager.drawPreviewItem(PreviewItemManager.java:10)
	at com.android.launcher3.folder.PreviewItemManager.drawParams(PreviewItemManager.java:5)
	at com.android.launcher3.folder.PreviewItemManager.draw(PreviewItemManager.java:11)
	at com.android.launcher3.folder.FolderIcon.dispatchDraw(FolderIcon.java:7)
	at android.view.View.draw(View.java:22516)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22516)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at com.android.launcher3.CellLayout.dispatchDraw(CellLayout.java:1)
	at android.view.View.draw(View.java:22648)
	at android.view.View.draw(View.java:22518)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22516)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22648)
	at l5.d$c.run(CreateBackupViewModel.kt:11)
	at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:4)
	at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:2)
	at x6.h.m(LauncherPreviewView.kt:13)
	at x6.h.l(Unknown Source:16)
	at x6.h.c(Unknown Source:0)
	at x6.d.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by suphon-t** [comment]
Already fixed for next release

**Comment by William150722** [comment]
> Already fixed for next release

@paphonb can I know which commit history?
