### ISSUE TITLE
[BUG] Crash when creating backup

### ISSUE THREAD

**Issue by Doomsdayrs** [Deletescape-Media/Lawnchair#2677]
### Describe the bug

I try to create backup, crash occurs

### Steps to reproduce

1. Go to lawn chair settings
2. Click on more actions on top right
3. Click create backup
4. See crash

### Expected behavior

Does not crash

### Device information

- Device: OP8T
- OS: Havoc OS 11
- App version 12.1.0 Alpha 3

### Additional context

https://bin.kv2.dev/~62979a3f410e7c32e669de82

**Comment by inglar** [comment]
I have the same issue with error "Software rendering doesn't support hardware bitmaps"

**Device information**
Device: Redmi Note 10 Pro
OS: Arrow OS 12.1
App version 12.1.0 Alpha 3

**Comment by nosedive** [comment]
Same Issue here too..

Device information
Device: Xiaomi Mi 11 Lite 5G
OS: Corvus OS 12.1
App version 12.1.0 Alpha 3

`Lawnchair` bug report 26 Jun 2022 14:49:26
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: Xiaomi
build.device: renoir
build.display: SP2A.220505.002
build.fingerprint: Xiaomi/renoir_eea/renoir:11/RKQ1.201112.002/V12.5.6.0.RKIEUXM:user/release-keys
build.hardware: qcom
build.id: SP2A.220505.002
build.manufacturer: Xiaomi
build.model: M2101K9G
build.product: corvus_renoir
build.type: user
version.codename: REL
version.incremental: 1655102274
version.release: 12
version.sdk_int: 32
display.density_dpi: 352
isRecentsEnabled: false

error: Uncaught exception

java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:699)
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1605)
	at com.android.launcher3.icons.FastBitmapDrawable.drawInternal(Unknown Source:5)
	at com.android.launcher3.icons.FastBitmapDrawable.draw(FastBitmapDrawable.java:7)
	at android.widget.TextView.onDraw(TextView.java:8032)
	at com.android.launcher3.BubbleTextView.drawWithoutDot(Unknown Source:0)
	at com.android.launcher3.views.DoubleShadowBubbleTextView.onDraw(DoubleShadowBubbleTextView.java:7)
	at android.view.View.draw(View.java:22704)
	at android.view.View.draw(View.java:22577)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22575)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at com.android.launcher3.CellLayout.dispatchDraw(CellLayout.java:1)
	at android.view.View.draw(View.java:22707)
	at android.view.View.draw(View.java:22577)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22575)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
	at android.view.View.draw(View.java:22707)
	at l5.d$c.run(CreateBackupViewModel.kt:11)
	at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:4)
	at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:2)
	at x6.h.m(LauncherPreviewView.kt:13)
	at x6.h.l(Unknown Source:16)
	at x6.h.c(Unknown Source:0)
	at x6.d.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
`

**Comment by William150722** [comment]
Hi any comment on this? I encounter this issues as well.

**Comment by SuperDragonXD** [comment]
Does it still persist in the latest versions?

**Comment by William150722** [comment]
Yea. Any idea how you try to fixes it?
