### ISSUE TITLE
Lawnchair crashes when placing the Notes List Google Keep widgets on the homescreen on OneUI 4.1 

### ISSUE THREAD

**Issue by lunandd** [Deletescape-Media/Lawnchair#2685]
### Describe the bug

When placing the "Note List" Google Keep widget on the homescreen, Lawnchair crashes. Logs have been attached below!

### Steps to reproduce

1. Hold on an empty place on your homescreen until the Desktop Bubble is shown
2. Click on Widgets
3. Scroll down to Google Keep
4. Click the "Note List" widget
5. Press and hold to place it on your homescreen

### Expected behavior

What should happen is that the widget is placed on the homescreen without Lawnchair crashing.

### Device information

- Device: Samsung Galaxy A32 5G
- OS: OneUI 4.1, Android 12
- App version: 12.1.0 Alpha 3

### Additional context

Logs:
```
Lawnchair bug report Jun 5, 2022 5:07:40 PM
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: a32x
build.display: SP1A.210812.016.A326BXXU4BVE8
build.fingerprint: samsung/a32xeea/a32x:12/SP1A.210812.016/A326BXXU4BVE8:user/release-keys
build.hardware: mt6853
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-A326B
build.product: a32xeea
build.type: user
version.codename: REL
version.incremental: A326BXXU4BVE8
version.release: 12
version.sdk_int: 31
display.density_dpi: 300
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

**Comment by SuperDragonXD** [comment]
See https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#adding-widgets-crashes-lawnchair

**Comment by lunandd** [comment]
> See https://github.com/LawnchairLauncher/lawnchair/wiki/FAQ#adding-widgets-crashes-lawnchair

Oh, thank you!
