### ISSUE TITLE
Serializer for class 'a' is not found. Mark the class as @Serializable or provide the serializer explicitly.

### ISSUE THREAD

**Issue by tushar09** [Deletescape-Media/Lawnchair#2686]
I am getting and error like below:
`Fatal Exception: fk.j: Serializer for class 'a' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
       at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
       at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:29)
       at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:60)
       at kotlinx.serialization.SerializersKt.serializer(SerializersKt.java:1)
       at app.lawnchair.preferences2.PreferenceManager2$special$$inlined$serializablePreference$2.invoke(PreferenceManager2.kt:388)
       at app.lawnchair.preferences2.PreferenceManager2$special$$inlined$serializablePreference$2.invoke(PreferenceManager2.kt:345)
       at com.patrykmichalik.preferencemanager.PreferenceImpl$set$2.invokeSuspend(PreferenceImpl.kt:25)
       at com.patrykmichalik.preferencemanager.PreferenceImpl$set$2.invoke(PreferenceImpl.kt:8)
       at com.patrykmichalik.preferencemanager.PreferenceImpl$set$2.invoke(PreferenceImpl.kt:4)
       at androidx.datastore.preferences.core.PreferencesKt$edit$2.invokeSuspend(Preferences.kt:329)
       at androidx.datastore.preferences.core.PreferencesKt$edit$2.invoke(Preferences.kt:8)
       at androidx.datastore.preferences.core.PreferencesKt$edit$2.invoke(Preferences.kt:4)
       at androidx.datastore.preferences.core.PreferenceDataStore$updateData$2.invokeSuspend(PreferenceDataStoreFactory.kt:84)
       at androidx.datastore.preferences.core.PreferenceDataStore$updateData$2.invoke(PreferenceDataStoreFactory.kt:8)
       at androidx.datastore.preferences.core.PreferenceDataStore$updateData$2.invoke(PreferenceDataStoreFactory.kt:4)
       at androidx.datastore.core.SingleProcessDataStore$transformAndWrite$newData$1.invokeSuspend(SingleProcessDataStore.kt:402)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$setScheduledFrameDispatch$p(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7436)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)`

**Comment by yasanglass** [comment]
It looks like an error from Google/Android's libraries and they probably have to just update those libraries when a fix is available.

**Comment by tushar09** [comment]
How can we let Google know about this error? Or they already know it?

**Comment by msfjarvis** [comment]
It's more likely to be an implementation error in Lawnchair than a bug in DataStore, please don't jump to conclusions without investigating the issue.

**Comment by suphon-t** [comment]
Please create a new issue using the issue template.
