### ISSUE TITLE
[BUG] Work profile applications' icon isn't customizable

### ISSUE THREAD

**Issue by flame-0** [Deletescape-Media/Lawnchair#2712]
### Description
Work profile icons cannot be changed.

### Reproduce
1. Select and hold any app's icon
2. Click 'Customize' from bubble option
3. Click the logo of the app
4. Select any icon on System Icons or in your installed Icon Pack

### Expected Behavior
Work profile applications' icon should be customizable.

### Video Demonstration
https://user-images.githubusercontent.com/40175769/174283647-1ac97a7d-face-4452-bbe2-ef0ac2686fc8.mp4

### Device information
- Device: POCO F3 Global
- Operating System: LineageOS 19.1 (Android 12)
- Application Version: 12.1.0 Alpha 4

**Comment by ghost** [comment]
For me it also isn't customizable. When I tap on the icon to change it, Lawnchair crashes giving an error notification.

https://user-images.githubusercontent.com/107772832/174456449-0dc2d16d-5e01-4003-b344-af227a715cfc.mp4

Lawnchair bug report 18.06.2022 22:39:52

version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: google
build.device: sargo
build.display: SQ3A.220605.009.A1.22306002
build.fingerprint: google/sargo/sargo:12/SP2A.220505.006/8561491:user/release-keys
build.hardware: sargo
build.id: SQ3A.220605.009.A1
build.manufacturer: Google
build.model: Pixel 3a
build.product: sargo
build.type: user
version.codename: REL
version.incremental: 22306002
version.release: 12
version.sdk_int: 32
display.density_dpi: 396
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.pm.LauncherActivityInfo.getLabel()' on a null object reference
	at n6.h0.a(SelectIconPreference.kt:13)
	at n6.j$a.a(SelectIconPreference.kt:5)
	at n6.j$a.M(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.M(Unknown Source:8)
	at u8.b$i$a.a(AnimatedNavHost.kt:4)
	at u8.b$i$a.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at n0.r.a(CompositionLocal.kt:3)
	at w0.d.b(SaveableStateHolder.kt:16)
	at o4.h.b(NavBackStackEntryProvider.kt:10)
	at o4.h.c(Unknown Source:0)
	at o4.h$a.a(Unknown Source:28)
	at o4.h$a.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at n0.r.a(CompositionLocal.kt:3)
	at o4.h.a(NavBackStackEntryProvider.kt:6)
	at u8.b$i.a(AnimatedNavHost.kt:7)
	at u8.b$i.M(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.M(Unknown Source:8)
	at t.b$c$c.a(AnimatedContent.kt:6)
	at t.b$c$c.C(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b.C(Unknown Source:8)
	at t.f.a(AnimatedVisibility.kt:78)
	at t.f.b(AnimatedVisibility.kt:5)
	at t.b$c.a(AnimatedContent.kt:30)
	at t.b$c.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at t.b.a(AnimatedContent.kt:98)
	at u8.b.b(AnimatedNavHost.kt:60)
	at u8.b$a.a(Unknown Source:23)
	at u8.b$a.i0(Unknown Source:8)
	at n0.f1.g(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.C(Composer.kt:5)
	at u6.i$c.a(ProvideBottomSheetHandler.kt:2)
	at u6.i$c.i0(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.i0(Unknown Source:8)
	at h0.d1$a.a(ModalBottomSheet.kt:42)
	at h0.d1$a.C(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b$a.a(Unknown Source:13)
	at u0.b$a.i0(Unknown Source:8)
	at n0.f1.g(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.x1(Composer.kt:9)
	at n0.j$i.a(Composer.kt:11)
	at n0.j$i.q(Unknown Source:0)
	at n0.v1.d(DerivedState.kt:6)
	at n0.u1.j(Unknown Source:0)
	at n0.j.s0(Composer.kt:18)
	at n0.j.X0(Composer.kt:5)
	at n0.o.y(Composition.kt:4)
	at n0.g1.f0(Recomposer.kt:8)
	at n0.g1.K(Unknown Source:0)
	at n0.g1$j$a.a(Recomposer.kt:50)
	at n0.g1$j$a.invoke(Unknown Source:6)
	at androidx.compose.ui.platform.e0$c.doFrame(Unknown Source:10)
	at androidx.compose.ui.platform.c0.b1(AndroidUiDispatcher.android.kt:10)
	at androidx.compose.ui.platform.c0.V0(Unknown Source:0)
	at androidx.compose.ui.platform.c0$d.doFrame(AndroidUiDispatcher.android.kt:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: wb.y0: [n0.x0@81651e1, androidx.compose.ui.platform.e1@3799b06, v2{Cancelling}@4a705c7, c0@dca47f4]

**Comment by cebtenzzre** [comment]
I am also running into this crash on Lawnchair 12.1.0 Alpha 4 (12010005).

**Comment by RWCoding58** [comment]
Hi, we're centralising discussion of this issue at #4988
