### ISSUE TITLE
[BUG] App crash on customize icon on home screen after restart

### ISSUE THREAD

**Issue by rahul-gill** [Deletescape-Media/Lawnchair#2728]
### Describe the bug

Afer restarting the launcher, pressing customize icon on home screen causes app crash.

### Steps to reproduce

1. Restart the launcher from Home settings overflow menu
2. Long press on any app icon on home screen and click on customize

### Expected behavior

Crash shouldn't be happening

### Device information

Lawnchair bug report 22 Jun 2022 4:33:26 pm
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: xiaomi
build.device: vince
build.display: ZQL1711-vince-build-20191108142512
build.fingerprint: xiaomi/vince/vince:8.1.0/OPM1.171019.019/V11.0.2.0.OEGMIXM:user/release-keys
build.hardware: qcom
build.id: OPM1.171019.019
build.manufacturer: Xiaomi
build.model: Redmi Note 5
build.product: vince
build.type: user
version.codename: REL
version.incremental: V11.0.2.0.OEGMIXM
version.release: 8.1.0
version.sdk_int: 27
display.density_dpi: 480
isRecentsEnabled: false

### Additional context
error: Uncaught exception

java.lang.NullPointerException
	at m6.b$b.onClick(LawnchairShortcut.kt:3)
	at android.view.View.performClick(View.java:6312)
	at android.view.View$PerformClick.run(View.java:24811)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by suphon-t** [comment]
Please attach the full log.

**Comment by rahul-gill** [comment]
@paphonb. Sorry, I forgot to add the stacktrace.
