### ISSUE TITLE
[BUG] widget gesture

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2770]
### Describe the bug

lawnchair crashes when I run an application using widget gesture. Widget application - [Another Widget](https://play.google.com/store/apps/details?id=com.tommasoberlose.anotherwidget&hl=en&gl=US)

### Steps to reproduce

1. Click on widget
2. See error

### Expected behavior

1. Click on widget
2. See expected application

### Device information

- Device: [Google Pixel 4a 5G]
- OS: [stock ROM Android version 12.1]
- App version [12.1.0 Alpha 3]

### Additional context

Lawnchair bug report Jul 16, 2022 3:13:31 PM
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: google
build.device: bramble
build.display: SQ3A.220705.003.A1
build.fingerprint: google/bramble/bramble:12/SQ3A.220705.003.A1/8672226:user/release-keys
build.hardware: bramble
build.id: SQ3A.220705.003.A1
build.manufacturer: Google
build.model: Pixel 4a (5G)
build.product: bramble
build.type: user
version.codename: REL
version.incremental: 8672226
version.release: 12
version.sdk_int: 32
display.density_dpi: 356
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method registerRemoteAnimationForNextActivityStart(Ljava/lang/String;Landroid/view/RemoteAnimationAdapter;)V in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
	at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(QuickstepInteractionHandler.java:12)
	at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:882)
	at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
	at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6555)
	at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6403)
	at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1199)
	at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by martindmtrv** [comment]
Having the same error popup when using [Month calendar](http://www.candlapps.com/)

**Comment by ghost** [comment]
can't reproduce with 12.1.0 Alpha 4
