### ISSUE TITLE
[BUG] Lawnchair crashes on adding widgets in Samsung A52

### ISSUE THREAD

**Issue by UKMIITB** [Deletescape-Media/Lawnchair#2788]
### Describe the bug

In my Samsung A52, Android 12, whenever I try adding any widgets on homescreen Lawnchair crashes

I am using the latest lawnchair app

### Steps to reproduce

1. Long press on home scree & select widgets
2. Long press on any widgets & place it to home screen
3. Lawnchair app crashes

### Expected behavior

The app should not crash & the widgets should be added to home screen successfully

### Device information

- Device: Samsung A52
- OS: Android 12
- App version: 12.1.0 Alpha 3

### Additional context

Crash Log:
Lawnchair bug report 23-Jul-2022 11:24:19
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: a52q
build.display: SP1A.210812.016.A525FXXU4BVG1
build.fingerprint: samsung/a52qnsxx/a52q:12/SP1A.210812.016/A525FXXU4BVG1:user/release-keys
build.hardware: qcom
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-A525F
build.product: a52qnsxx
build.type: user
version.codename: REL
version.incremental: A525FXXU4BVG1
version.release: 12
version.sdk_int: 31
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by kahanzammi** [comment]
I had this issue in Galaxy S22 - clearing both cache and app data from Samsung app settings resolved the issue.
You may need to star over with the Lawnchair settings - do not try to restore the settings.

**Comment by SuperDragonXD** [comment]
Widget crashing issues (with this  specific error) are being tracked on #2820. Closing this issue.
