### ISSUE TITLE
Lawnchair crashes with certain widgets

### ISSUE THREAD

**Issue by howmanysmall** [Deletescape-Media/Lawnchair#2792]
I've only noticed this happens with mostly my Samsung related widgets, but it was also happening with a few others.

Here's a crash log from them I tried to add the device care widget from Samsung. 

```
Lawnchair bug report Jul 23, 2022 3:31:19 PM
version: 12.1.0 Alpha 3 (12010003)
commit: e7f0269
build.brand: samsung
build.device: b0q
build.display: SP1A.210812.016.S908USQU2AVF7
build.fingerprint: samsung/b0qsqw/b0q:12/SP1A.210812.016/S908USQU2AVF7:user/release-keys
build.hardware: qcom
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-S908U
build.product: b0qsqw
build.type: user
version.codename: REL
version.incremental: S908USQU2AVF7
version.release: 12
version.sdk_int: 31
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

**Comment by howmanysmall** [comment]
Just saw there was another issue (#2788).
