### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FlyGuy240** [Deletescape-Media/Lawnchair#2802]
### Describe the bug

YouTube/YouTube Vanced (Tried both) are exiting full screen whenever it can while using this launcher. 

I have to fight with it and full screen it about 5 times before it works but Netflix didn't give me this issue. I tried two different launchers with no problems. (Google Home & Nova)  once it finally settles in full screen it's only a matter of time before it cancels again and goes back to the home screen with the video playing in picture. 

### Steps to reproduce

1. Go to 'Youtube or YouTube Vanced'
2. Click on 'Any Video
3. Full screen the video 
4. The video should exist Fullscreen after a second or two and you should be back on the home screen with the video playing in the corner. 

### Expected behavior

Full screen should stay and not exit without my input. 

### Device information

- Device: Google Pixel 6 Pro
- OS: Android 12
- App version Most Recent

**Comment by TristanK27** [comment]
Same bug here. It happens with any video that plays fullscreen(firefox, stremio, yt, yt vanced).

Android 12 (syberia) oneplus 6

**Comment by TristanK27** [comment]
Stacktrace of the moment that fullscreen is exited and the small video box is created: 
```
2022-08-11 11:35:26.565 1297-1313/? D/NotificationListeners: Removing active service ComponentInfo{ch.deletescape.lawnchair.plah/com.android.launcher3.notification.NotificationListener}
2022-08-11 11:35:26.566 1297-1297/? V/NotificationListeners: 0 notification listener connection lost: ComponentInfo{ch.deletescape.lawnchair.plah/com.android.launcher3.notification.NotificationListener}
2022-08-11 11:35:26.566 1297-1314/? I/ActivityManager: Process ch.deletescape.lawnchair.plah (pid 30343) has died: prcl BFGS
2022-08-11 11:35:26.569 1297-2660/? I/WindowManager: WIN DEATH: Window{13805ee u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher}
2022-08-11 11:35:26.569 1297-2660/? W/InputManager-JNI: Input channel object '13805ee ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher (client)' was disposed without first being removed with the input manager!
2022-08-11 11:35:26.571 1297-1314/? W/ActivityManager: Scheduling restart of crashed service ch.deletescape.lawnchair.plah/com.android.launcher3.notification.NotificationListener in 1000ms for connection
2022-08-11 11:35:26.576 1297-1390/? W/UsageStatsService: Unexpected activity event reported! (ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.LawnchairLauncher event : 23 instanceId : 221792387)
2022-08-11 11:35:27.595 1297-1392/? I/ActivityManager: Start proc 9288:ch.deletescape.lawnchair.plah/u0a401 for service {ch.deletescape.lawnchair.plah/com.android.launcher3.notification.NotificationListener}
2022-08-11 11:35:27.603 9288-9288/? E/.lawnchair.pla: Not starting debugger since process cannot load the jdwp agent.
2022-08-11 11:35:27.631 9288-9288/? V/GraphicsEnvironment: ANGLE Developer option for 'ch.deletescape.lawnchair.plah' set to: 'default'
2022-08-11 11:35:27.632 9288-9288/? V/GraphicsEnvironment: ANGLE GameManagerService for ch.deletescape.lawnchair.plah: false
2022-08-11 11:35:27.637 9288-9288/? W/.lawnchair.pla: Accessing hidden method Landroid/graphics/HardwareRenderer;->setContextPriority(I)V (blocked, reflection, denied)
2022-08-11 11:35:27.637 9288-9288/? D/LawnchairApp: Hidden APIs allowed: true
2022-08-11 11:35:27.651 9288-9288/? D/LawnchairPreferences: Initializing
    java.lang.Throwable
        at ch.deletescape.lawnchair.LawnchairPreferences.<init>(LawnchairPreferences.kt:243)
        at ch.deletescape.lawnchair.LawnchairPreferences$Companion.getInstance(LawnchairPreferences.kt:3)
        at com.android.launcher3.Utilities.getLawnchairPrefs(Utilities.java:1)
        at ch.deletescape.lawnchair.LawnchairUtilsKt.getLawnchairPrefs(LawnchairUtils.kt:1)
        at ch.deletescape.lawnchair.adaptive.IconShapeManager.<init>(IconShapeManager.kt:7)
        at ch.deletescape.lawnchair.adaptive.IconShapeManager$Companion$1.invoke(IconShapeManager.kt:3)
        at ch.deletescape.lawnchair.LawnchairUtilsKt$useApplicationContext$1.invoke(LawnchairUtils.kt:1)
        at ch.deletescape.lawnchair.LawnchairUtilsKt$ensureOnMainThread$1.invoke(LawnchairUtils.kt:2)
        at ch.deletescape.lawnchair.util.SingletonHolder.getInstance(SingletonHolder.kt:4)
        at com.android.launcher3.MainProcessInitializer.init(MainProcessInitializer.java:2)
        at com.android.quickstep.QuickstepProcessInitializer.init(QuickstepProcessInitializer.java:1)
        at com.android.launcher3.MainProcessInitializer.initialize(MainProcessInitializer.java:2)
        at com.android.launcher3.LauncherProvider.onCreate(LauncherProvider.java:2)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7422)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6933)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
        at android.app.ActivityThread.access$1500(ActivityThread.java:257)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7833)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-11 11:35:27.756 1297-1297/? V/NotificationListeners: 0 notification listener service connected: ComponentInfo{ch.deletescape.lawnchair.plah/com.android.launcher3.notification.NotificationListener}
2022-08-11 11:35:27.842 9288-9288/? D/LawnchairApp: config_recentsComponentName (ComponentInfo{com.android.launcher3/com.android.quickstep.RecentsActivity}) is not Lawnchair, disabling recents
2022-08-11 11:35:27.977 9288-9288/? I/ActivityThread: Schedule relaunch activity: ch.deletescape.lawnchair.LawnchairLauncher
2022-08-11 11:35:28.297 9288-9288/? D/LSC: couldn't create provider
    java.lang.NoSuchMethodException: ch.deletescape.lawnchair.smartspace.OnboardingProvider.<init> [class ch.deletescape.lawnchair.smartspace.LawnchairSmartspaceController]
        at java.lang.Class.getConstructor0(Class.java:2363)
        at java.lang.Class.getConstructor(Class.java:1759)
        at ch.deletescape.lawnchair.smartspace.LawnchairSmartspaceController.createDataProvider(LawnchairSmartspaceController.kt:1)
        at ch.deletescape.lawnchair.smartspace.LawnchairSmartspaceController.<init>(LawnchairSmartspaceController.kt:19)
        at ch.deletescape.lawnchair.LawnchairApp$smartspace$2.invoke(LawnchairApp.kt:1)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
        at ch.deletescape.lawnchair.LawnchairApp.getSmartspace(Unknown Source:9)
        at com.google.android.apps.nexuslauncher.smartspace.SmartspaceView.<init>(SmartspaceView.java:5)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:863)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
        at ch.deletescape.lawnchair.LawnchairLayoutInflater.inflate(LawnchairLayoutInflater.kt:1)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at ch.deletescape.lawnchair.views.HomeWidgetSwitchLayout.setCurrentLayout(HomeWidgetSwitchLayout.kt:4)
        at ch.deletescape.lawnchair.views.HomeWidgetSwitchLayout.onValueChanged(HomeWidgetSwitchLayout.kt:1)
        at ch.deletescape.lawnchair.LawnchairPreferences.addOnPreferenceChangeListener(LawnchairPreferences.kt:4)
        at ch.deletescape.lawnchair.LawnchairPreferences.addOnPreferenceChangeListener(LawnchairPreferences.kt:7)
        at ch.deletescape.lawnchair.views.HomeWidgetSwitchLayout.onAttachedToWindow(HomeWidgetSwitchLayout.kt:2)
        at android.view.View.dispatchAttachedToWindow(View.java:20812)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5289)
        at android.view.ViewGroup.addView(ViewGroup.java:5076)
        at com.android.launcher3.CellLayout.addViewToCellLayout(CellLayout.java:17)
        at com.android.launcher3.Workspace.addInScreen(Workspace.java:23)
        at com.android.launcher3.Workspace.addInScreenFromBind(Workspace.java:7)
        at com.android.launcher3.Launcher.bindItems(Launcher.java:23)
        at com.android.launcher3.model.LoaderResults$9.run(LoaderResults.java:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7833)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-11 11:35:30.785 9288-9301/? I/.lawnchair.pla: Background concurrent copying GC freed 744788(36MB) AllocSpace objects, 279(17MB) LOS objects, 77% free, 11MB/54MB, paused 99us,28us total 137.209ms
```
Also @FlyGuy240, Could you add a more descriptive title instead of "[BUG]"? Maybe something along the lines of "[BUG] fullscreen video exits to homescreen (and opens pip video window).
It's quite difficult to find through search engines when the issue has no title.

**Comment by yasanglass** [comment]
Please create an issue with an appropriate title (and fill out the issue form)
