### ISSUE TITLE
[BUG] Disallowed call from unknown notification listener

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Deletescape-Media/Lawnchair#2825]
### Describe the bug

```
Lawnchair bug report 10.08.2022
Lawnchair version: 9.1 Alpha 3 (9012942)
version.release: 11
version.sdk_int: 30

error: Uncaught exception

--------- beginning of stacktrace
java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@8629470 class android.service.notification.INotificationListener$Stub$Proxy
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:4806)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:937)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:914)
	at com.android.launcher3.notification.NotificationListener.onNotificationRankingUpdate(NotificationListener.java:298)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2150)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:904)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4240)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2182)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)


```

### Steps to reproduce

1. Go to '...' lawnvhair

### Expected behavior

Don't throw exceptions 

### Device information

- Device: Android Smartphone
- OS:  Android version 11
- App version  9.1 Alpha 3 (9012942)

**Comment by Goooler** [comment]
Link #2374, #2370, #227, #156

**Comment by Goooler** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software Could you have a try with [apk here](https://github.com/LawnchairLauncher/lawnchair/suites/8487543055/artifacts/377488178)?

**Comment by Goooler** [comment]
I've observed similar crashes on the Lawnchair 12.1

```
Fatal Exception: java.lang.SecurityException: Disallowed call from unknown notification listener:
android.service.notification.INotificationListener$Stub$Proxy@16852a1 class android.service.notification.INotificationListener$Stub$Proxy
    at android.os.Parcel.readException(Parcel.java:2021)
    at android.os.Parcel.readException(Parcel.java:1967)
    at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:2242)
    at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:886)
    at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:814)
    at app.lawnchair.d$p02z.invokeSuspend(NotificationManager.kt:5)
    at wk.p01z.resumeWith(ContinuationImpl.kt:4)
    at pl.r0.run(DispatchedTask.kt:18)
    at ul.b.run(LimitedDispatcher.kt:2)
    at wl.a.run(Tasks.kt:1)
    at wl.p01z.d(CoroutineScheduler.kt:1)
    at wl.p01z$p03x.x044(CoroutineScheduler.kt:4)
    at wl.p01z$p03x.d(CoroutineScheduler.kt:4)
    at wl.p01z$p03x.run()
```
```

**Comment by William150722** [comment]
@Goooler anyone able to figure this out? Thanks.

**Comment by Goooler** [comment]
> @4-FLOSS-Free-Libre-Open-Source-Software Could you have a try with [apk here](https://github.com/LawnchairLauncher/lawnchair/suites/8487543055/artifacts/377488178)?

@William150722 Try out this.

**Comment by Goooler** [comment]
Now I capture the deobfuscated stacktrack:

```
Fatal Exception: java.lang.SecurityException
Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@47a3ede 
class android.service.notification.INotificationListener$Stub$Proxy
android.os.Parcel.createException(Parcel.java: 1950)
  android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java: 810)
  app.lawnchair.NotificationManager$onNotificationFullRefresh$1.invokeSuspend(NotificationManager.kt: 36)
  kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt: 33)
  kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt: 106)
  kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt: 42)
  kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt: 95)
  kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt: 570)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt: 749)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt: 677)
  kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt: 664)
```
