### ISSUE TITLE
Split screen bug

### ISSUE THREAD

**Issue by Golde2341** [Deletescape-Media/Lawnchair#2836]
### Describe the bug

When I have two split apps then I close them and in recent apps I swipe down to open the split apps, lawnchair crashes. It doesn't happens when you tap on it to open. Another bug is that swipe down split apps is slower than single apps

### Steps to reproduce

1. Split two apps
2. Close them
3. Open recents
3. Scroll down to open split apps
4. Crash

### Expected behavior

.

### Screenshots

.

### Device information

- Device: Redmi 9t
- OS: Aosp 12.1
- App version 12.1.0 alpha 4

### Additional context

Lawnchair bug report Aug 13, 2022 4:53:27 PM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: Xiaomi
build.device: juice
build.display: aosp_juice-userdebug 12 SQ3A.220605.009.B1 1655265009 release-keys
build.fingerprint: google/raven/raven:12/SQ3A.220605.009.B1/8650216:user/release-keys
build.hardware: qcom
build.id: SQ3A.220605.009.B1
build.manufacturer: Xiaomi
build.model: Juice
build.product: aosp_juice
build.type: user
version.codename: REL
version.incremental: 1655265009
version.release: 12
version.sdk_int: 32
display.density_dpi: 417
isRecentsEnabled: true

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'com.android.systemui.shared.system.RemoteAnimationTargetCompat[] com.android.quickstep.RemoteAnimationTargets.nonApps' on a null object reference
	at com.android.quickstep.views.RecentsView.lambda$createTaskLaunchAnimation$29(RecentsView.java:4)
	at com.android.quickstep.views.RecentsView.A(Unknown Source:0)
	at com.android.quickstep.views.l0.accept(Unknown Source:6)
	at com.android.launcher3.anim.AnimatorListeners$EndStateCallbackWrapper.onAnimationEnd(AnimatorListeners.java:5)
	at com.android.launcher3.anim.d.accept(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.lambda$callListenerCommandRecursively$2(AnimatorPlaybackController.java:2)
	at com.android.launcher3.anim.AnimatorPlaybackController.a(Unknown Source:0)
	at com.android.launcher3.anim.g.accept(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(AnimatorPlaybackController.java:1)
	at com.android.launcher3.anim.AnimatorPlaybackController.callAnimatorCommandRecursively(AnimatorPlaybackController.java:4)
	at com.android.launcher3.anim.AnimatorPlaybackController.callListenerCommandRecursively(Unknown Source:5)
	at com.android.launcher3.anim.AnimatorPlaybackController.dispatchOnEnd(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController$OnAnimationEndDispatcher.onAnimationSuccess(AnimatorPlaybackController.java:2)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(AnimationSuccessListener.java:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by kahanzammi** [comment]
I tested this with both Lawnchair and Pixel launcher. First with Pixel launcher, then with Lawnchair. Pixel launcher crashed twice and then started to work. Then I switched to Lawnchair that didn't crash. 
I'm on Pixel Experience ROM and Lawnchair latest dev.

**Comment by kahanzammi** [comment]
Restarted the phone to Lawnchair and tested again. Unable to reproduce the issue. I believe it might be related certain phone or ROM.
