### ISSUE TITLE
[BUG] Can't modify home screen grid size

### ISSUE THREAD

**Issue by joelschmol** [Deletescape-Media/Lawnchair#2859]
### Describe the bug

Can't modify home screen grid

### Steps to reproduce

1. Go to 'Home Settings'
2. Click on 'Home Screen'
3. Scroll down to 'Layout'
4. Click on 'Home Screen Grid'
5. See error 

### Expected behavior

I wanted to change my grid size to 5x5 from the default (which is 4x5)

### Screenshots

https://user-images.githubusercontent.com/88237375/186117093-c0dc14cc-05c6-4796-8313-760acb6a2695.mp4

https://user-images.githubusercontent.com/88237375/186117145-08ae6e5a-cefd-4d63-8b2d-faecb1241a83.mp4

### Device information

- Device: [Huawei Y7 Prime 2018 (LDN-L21)]
- OS: [Stock ROM Android version 8.0]
- App version [12.1.0 Alpha 4]

### Crash Log
Lawnchair bug report Aug 23, 2022 14:44:13
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: HUAWEI
build.device: HWLDN-Q
build.display: LDN-L21 8.0.0.166(C185)
build.fingerprint: HUAWEI/LDN-L21B/HWLDN-Q:8.0.0/HUAWEILDN-L21/166(C185):user/release-keys
build.hardware: qcom
build.id: HUAWEILDN-L21
build.manufacturer: HUAWEI
build.model: LDN-L21
build.product: LDN-L21B
build.type: user
version.codename: REL
version.incremental: 166(C185)
version.release: 8.0.0
version.sdk_int: 26
display.density_dpi: 320
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to stop service com.android.launcher3.notification.NotificationListener@a7e77f6: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.util.SettingsCache.unregister(android.net.Uri, com.android.launcher3.util.SettingsCache$OnChangeListener)' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4223)
	at android.app.ActivityThread.-wrap27(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2128)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.util.SettingsCache.unregister(android.net.Uri, com.android.launcher3.util.SettingsCache$OnChangeListener)' on a null object reference
	at com.android.launcher3.notification.NotificationListener.onListenerDisconnected(NotificationListener.java:3)
	at android.service.notification.NotificationListenerService.onDestroy(NotificationListenerService.java:1038)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4199)
	... 8 more

### Crash Log Link 
content://app.lawnchair.fileprovider/log_files/496a7286/Lawnchair%20bug%20report%20Aug%2023%2C%202022%2014%3A44%3A13.txt

### Additional Context
I also use fluid navigation gestures (FNG) which is an app that can hide the device's navigation bar and set custom navigation options on swipes. I don't think that has anything to do with the issue since i tried it after turning FNG off and the issue still persisted but i thought maybe knowing it could be useful for context.

**Comment by SuperDragonXD** [comment]
Looks like the MP4 file didn't get properly uploaded. Could you upload it again?

Also please provide a proper title to your issue

**Comment by joelschmol** [comment]
> Looks like the MP4 file didn't get properly uploaded. Could you upload it again?
> 
> Also please provide a proper title to your issue

Done
Sorry for the inconvenience. I didn't pay attention to it when i uploaded last time

**Comment by SuperDragonXD** [comment]
Could you also link to/paste the crash log? It's kinda hard to debug without crash logs.

**Comment by joelschmol** [comment]
> Could you also link to/paste the crash log? It's kinda hard to debug without crash logs.

I did it. Sorry about that too. I'm kinda new to GitHub

**Comment by Goooler** [comment]
Same issue:

```
Fatal Exception: java.lang.RuntimeException
Unable to stop service com.android.launcher3.notification.NotificationListener@abf7d16: java.lang.NullPointerException:
Attempt to invoke virtual method 'void com.android.launcher3.util.SettingsCache.unregister(android.net.Uri, com.android.launcher3.util.SettingsCache$OnChangeListener)' on a null object reference
android.app.ActivityThread.handleStopService (ActivityThread.java:4353)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)
```

**Comment by asandikci** [comment]
I have the same issue. Here is my error log
```
Lawnchair bug report 25 Mar 2023 4:15:37 am
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: HUAWEI
build.device: HWATU-QG
build.display: ATU-L21 8.0.0.162(C432)
build.fingerprint: HUAWEI/ATU-L21/HWATU-QG:8.0.0/HUAWEIATU-L21/162(C432):user/release-keys
build.hardware: qcom
build.id: HUAWEIATU-L21
build.manufacturer: HUAWEI
build.model: ATU-L21
build.product: ATU-L21
build.type: user
version.codename: REL
version.incremental: 162(C432)
version.release: 8.0.0
version.sdk_int: 26
display.density_dpi: 320
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to stop service com.android.launcher3.notification.NotificationListener@fda1ca7: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.util.SettingsCache.unregister(android.net.Uri, com.android.launcher3.util.SettingsCache$OnChangeListener)' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4223)
	at android.app.ActivityThread.-wrap27(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2128)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.util.SettingsCache.unregister(android.net.Uri, com.android.launcher3.util.SettingsCache$OnChangeListener)' on a null object reference
	at com.android.launcher3.notification.NotificationListener.onListenerDisconnected(NotificationListener.java:3)
	at android.service.notification.NotificationListenerService.onDestroy(NotificationListenerService.java:1038)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4199)
	... 8 more


```

Problem is about notification permisson i guess. When i turn off notification permission in device settings, error don't occurs.
