### ISSUE TITLE
[BUG] App Crashes when trying to change icons.

### ISSUE THREAD

**Issue by Metr0pl3x** [Deletescape-Media/Lawnchair#2914]
### Describe the bug

Lawnchair crashes when trying to use custom icons.

### Steps to reproduce

Long Press Icon, tap the pencil, tap the icon to change to a custom icon and Lawnchair crashes.

### Expected behavior

I expected a pop up to appear to select a downloaded icon pack and to be able to select a custom icon.

### Device information

- Device: Google Pixel 4a
- OS: Graphene OS Android 13 TP1A.220624.014.2022090400
- App version: e.g. 12.1.0 Alpha 4
- Secondary User Profile

### Additional context

Lawnchair bug report 7 Sept 2022 10:05:15
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: sunfish
build.display: TP1A.220624.014.2022090400
build.fingerprint: google/sunfish/sunfish:13/TP1A.220624.014/2022090400:user/release-keys
build.hardware: sunfish
build.id: TP1A.220624.014
build.manufacturer: Google
build.model: Pixel 4a
build.product: sunfish
build.type: user
version.codename: REL
version.incremental: 2022090400
version.release: 13
version.sdk_int: 33
display.density_dpi: 440
isRecentsEnabled: false

error: Uncaught exception

java.lang.SecurityException: Cannot resolve activity for unrelated profile 0
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3012)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.content.pm.ILauncherApps$Stub$Proxy.resolveLauncherActivityInternal(ILauncherApps.java:852)
	at android.content.pm.LauncherApps.resolveActivity(LauncherApps.java:791)
	at p6.l0.a(SelectIconPreference.kt:12)
	at p6.k$a.a(SelectIconPreference.kt:5)
	at p6.k$a.c0(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.c0(Unknown Source:8)
	at w8.b$i$a.a(AnimatedNavHost.kt:4)
	at w8.b$i$a.invoke(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.invoke(ComposableLambda.jvm.kt:1)
	at n0.r.a(CompositionLocal.kt:3)
	at w0.d.b(SaveableStateHolder.kt:16)
	at o4.h.b(NavBackStackEntryProvider.kt:10)
	at o4.h.c(Unknown Source:0)
	at o4.h$a.a(Unknown Source:28)
	at o4.h$a.invoke(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.invoke(ComposableLambda.jvm.kt:1)
	at n0.r.a(CompositionLocal.kt:3)
	at o4.h.a(NavBackStackEntryProvider.kt:6)
	at w8.b$i.a(AnimatedNavHost.kt:7)
	at w8.b$i.c0(Unknown Source:12)
	at u0.b.c(ComposableLambda.jvm.kt:6)
	at u0.b.c0(Unknown Source:8)
	at t.b$c$c.a(AnimatedContent.kt:6)
	at t.b$c$c.P(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b.P(Unknown Source:8)
	at t.f.a(AnimatedVisibility.kt:78)
	at t.f.b(AnimatedVisibility.kt:5)
	at t.b$c.a(AnimatedContent.kt:30)
	at t.b$c.invoke(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.invoke(ComposableLambda.jvm.kt:1)
	at t.b.a(AnimatedContent.kt:98)
	at w8.b.b(AnimatedNavHost.kt:60)
	at w8.b$a.a(Unknown Source:23)
	at w8.b$a.invoke(Unknown Source:8)
	at n0.f1.h(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.D(Composer.kt:5)
	at x6.i$c.a(ProvideBottomSheetHandler.kt:2)
	at x6.i$c.invoke(Unknown Source:8)
	at u0.b.e(ComposableLambda.jvm.kt:4)
	at u0.b.invoke(ComposableLambda.jvm.kt:1)
	at h0.d1$a.a(ModalBottomSheet.kt:42)
	at h0.d1$a.P(Unknown Source:10)
	at u0.b.d(ComposableLambda.jvm.kt:6)
	at u0.b$a.a(Unknown Source:13)
	at u0.b$a.invoke(Unknown Source:8)
	at n0.f1.h(Unknown Source:14)
	at n0.j.a1(Composer.kt:19)
	at n0.j.x1(Composer.kt:9)
	at n0.j$i.invoke(Composer.kt:12)
	at n0.j$i.invoke(Composer.kt:1)
	at n0.v1.d(DerivedState.kt:6)
	at n0.u1.j(Unknown Source:0)
	at n0.j.s0(Composer.kt:19)
	at n0.j.X0(Composer.kt:5)
	at n0.o.y(Composition.kt:4)
	at n0.g1.f0(Recomposer.kt:8)
	at n0.g1.K(Unknown Source:0)
	at n0.g1$j$a.a(Recomposer.kt:50)
	at n0.g1$j$a.invoke(Unknown Source:6)
	at androidx.compose.ui.platform.e0$c.doFrame(Unknown Source:10)
	at androidx.compose.ui.platform.c0.b1(AndroidUiDispatcher.android.kt:10)
	at androidx.compose.ui.platform.c0.V0(Unknown Source:0)
	at androidx.compose.ui.platform.c0$d.doFrame(AndroidUiDispatcher.android.kt:3)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: bc.z0: [n0.x0@49b3cd7, androidx.compose.ui.platform.h1@7ec99c4, w2{Cancelling}@82f60ad, c0@e6f0fe2]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService$LocalService.isProfileAccessible(UserManagerService.java:6169)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:408)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:384)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.resolveLauncherActivityInternal(LauncherAppsService.java:598)
	at android.content.pm.ILauncherApps$Stub.onTransact(ILauncherApps.java:355)

**Comment by SuperDragonXD** [comment]
Did you try to change the icon for a work app? Also is the work profile disabled, if you've done what I said before?

**Comment by Metr0pl3x** [comment]
I don't use any device management apps so no work profile is active. This is a full user profile. (SETTINGS>SYSTEM>MULTIPLE USERS)
The issue can be replicated for ALL apps, system and user.
This was discovered as I was about to recommend Lawnchair and another launcher I use on my device.
https://discuss.grapheneos.org/d/782-custom-icons-with-grapheneos-launcher/2

**Comment by SuperDragonXD** [comment]
Not really sure then.

**Comment by Metr0pl3x** [comment]
I'll take a broader bug report and grep it to see if I can find anything else.

**Comment by ghost** [comment]
> Did you try to change the icon for a work app? Also is the work profile disabled, if you've done what I said before?

I have the bug in the situation you're discribing, i.e. i try to change the icon of an app in work profile (wich is activated)

**Comment by RWCoding58** [comment]
Hi, we're centralising discussion of this issue at https://github.com/LawnchairLauncher/lawnchair/issues/4988
