### ISSUE TITLE
Lawnchair crashes when clicking "+" button in TickTick Widget

### ISSUE THREAD

**Issue by vbatecan** [Deletescape-Media/Lawnchair#2983]
### Describe the bug

By clicking the "+" button of TickTick widget and it will crash.

Lawnchair also crashes in Youtube Music widget whether clicking next/previous/play button itself as well as clicking the widget itself (the expected behavior is that it will open YouTube Music)

Pardon my English

### Steps to reproduce

1. Go to the page where to specified widget. In this case, TickTick Widget
2. Click on '+' button
3. See error

### Expected behavior

I expect it to open the TickTick app for creating a new task since I clicked the "+" button in the TickTick Widget

### Screenshots

![Screenshot_20220926-194143_Lawnchair~2](https://user-images.githubusercontent.com/50913405/192268147-a8f5f99b-8ad7-4aa6-8f5c-19117566bbaf.png)

### Device information

- Device: Redmi Note 8 Pro
- OS: CrDroid 8.9 Android 12 Bootloader Unlocked with root
- App version: 12.1.0 Alpha 4

### Additional context

Lawnchair bug report Sep 26, 2022 7:38:50 PM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: Redmi
build.device: begonia
build.display: SQ3A.220705.004
build.fingerprint: Redmi/begonia/begonia:11/RP1A.200720.011/V12.5.5.0.RGGMIXM:user/release-keys
build.hardware: mt6785
build.id: SQ3A.220705.004
build.manufacturer: Xiaomi
build.model: Redmi Note 8 Pro
build.product: lineage_begonia
build.type: user
version.codename: REL
version.incremental: 1663596103
version.release: 12
version.sdk_int: 32
display.density_dpi: 396
isRecentsEnabled: true

```
error: Uncaught exception

java.lang.SecurityException: Permission Denial: registerRemoteAnimationForNextActivityStart from pid=31971, uid=10265 requires android.permission.CONTROL_REMOTE_APP_TRANSITION_ANIMATIONS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IActivityTaskManager$Stub$Proxy.registerRemoteAnimationForNextActivityStart(IActivityTaskManager.java:4406)
	at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(QuickstepInteractionHandler.java:16)
	at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:882)
	at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
	at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6555)
	at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6403)
	at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1199)
	at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceCallingPermission(ActivityManagerService.java:5497)
	at com.android.server.am.ActivityManagerService$LocalService.enforceCallingPermission(ActivityManagerService.java:15691)
	at com.android.server.wm.ActivityTaskManagerService.registerRemoteAnimationForNextActivityStart(ActivityTaskManagerService.java:3631)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2078)
	at com.android.server.wm.ActivityTaskManagerService.onTransact(ActivityTaskManagerService.java:5128)
```

**Comment by vbatecan** [comment]
Now it works, I don't know why.
