### ISSUE TITLE
[BUG] "Search for more apps" crashes lawnchair

### ISSUE THREAD

**Issue by Donkey-Doug** [Deletescape-Media/Lawnchair#2988]
### Describe the bug

Clicking on search for more apps crashes the launcher.

### Steps to reproduce

1. Go to drawer
2. Click in search field
3. Type text that is not the name of an app (or make a typo)
4. Click on Search for more apps
5. See error

### Expected behavior

Don't know, open store or something?

### Screenshots

-

### Device information

- Device: Xiaomi Mi 9T Pro
- OS: Lineageos Android version 12.0
- App version: 12.1.0 Alpha 4

### Additional context

Lawnchair bug report Sep 30, 2022 16:38:38
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: Xiaomi
build.device: raphael
build.display: lineage_raphael-userdebug 12 SQ3A.220605.009.A1 eng.seba.20220707.103313 test-keys
build.fingerprint: Xiaomi/raphael/raphael:11/RKQ1.200826.002/V12.5.2.0.RFKMIXM:user/release-keys
build.hardware: qcom
build.id: SQ3A.220605.009.A1
build.manufacturer: Xiaomi
build.model: Mi 9T Pro
build.product: lineage_raphael
build.type: userdebug
version.codename: REL
version.incremental: eng.seba.20220707.103313
version.release: 12
version.sdk_int: 32
display.density_dpi: 396
isRecentsEnabled: false

error: Uncaught exception

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://search?c=apps&q=sv }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
	at android.app.Activity.startActivityForResult(Activity.java:5410)
	at com.android.launcher3.Launcher.startActivityForResult(Launcher.java:2)
	at com.android.launcher3.BaseQuickstepLauncher.startActivityForResult(BaseQuickstepLauncher.java:6)
	at android.app.Activity.startActivityForResult(Activity.java:5368)
	at android.app.Activity.startActivity(Activity.java:5754)
	at android.app.Activity.startActivity(Activity.java:5707)
	at com.android.launcher3.touch.ItemClickHandler.onClickSearchAction(ItemClickHandler.java:4)
	at com.android.launcher3.touch.ItemClickHandler.onClick(ItemClickHandler.java:16)
	at com.android.launcher3.touch.ItemClickHandler.b(Unknown Source:0)
	at com.android.launcher3.touch.f.onClick(Unknown Source:0)
	at app.lawnchair.allapps.SearchResultIcon.onClick(Unknown Source:7)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by SuperDragonXD** [comment]
Do you have Play Store installed? Or a suitable app able to handle the `market://` intent?

**Comment by Donkey-Doug** [comment]
> Do you have Play Store installed? Or a suitable app able to handle the `market://` intent?

I do not have the play store, but I do have aurora store and fdroid.

**Comment by luximus-hunter** [comment]
> > Do you have Play Store installed? Or a suitable app able to handle the `market://` intent?
> 
> I do not have the play store, but I do have aurora store and fdroid.

Have you set those apps to open links of types that they support? I run CalyxOS, and I needed to allow Aurora and F-Droid to open links directly

**Comment by Donkey-Doug** [comment]
All checkmarks are selected in the android "open links" settings.
