### ISSUE TITLE
[BUG] Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3030]
### Describe the bug

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1487474984, result=0, data=null} to activity 
{app.lawnchair/com.android.launcher3.proxy.ProxyActivityStarter}: java.lang.NullPointerException: 
Attempt to invoke virtual method 'boolean java.util.HashSet.remove(java.lang.Object)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4544)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4586)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:205)
    at android.app.ActivityThread.main(ActivityThread.java:6991)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashSet.remove(java.lang.Object)' on a null object reference
    at android.os.Parcel.createException(Parcel.java:1956)
    at android.os.Parcel.readException(Parcel.java:1918)
    at android.os.Parcel.readException(Parcel.java:1868)
    at android.app.IActivityManager$Stub$Proxy.sendIntentSender(IActivityManager.java:9657)
    at android.app.PendingIntent.sendAndReturnResult(PendingIntent.java:892)
    at android.app.PendingIntent.send(PendingIntent.java:874)
    at android.app.PendingIntent.send(PendingIntent.java:723)
    at com.android.launcher3.proxy.StartActivityParams.deliverResult(StartActivityParams.java:92)
    at com.android.launcher3.proxy.ProxyActivityStarter.onActivityResult(ProxyActivityStarter.java:73)
    at android.app.Activity.dispatchActivityResult(Activity.java:7477)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4537)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4586)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:205)
    at android.app.ActivityThread.main(ActivityThread.java:6991)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

### Steps to reproduce

Unkown

### Expected behavior

No crash

### Device information

- Device: LG Stylo 5
- OS: Android 9
- App version: latest

**Comment by Goooler** [comment]
This error might be related to `launcher.recreate`, I'm still seeking the repro procedure.

**Comment by William150722** [comment]
@Goooler is it similar with this issues?

java.lang.IllegalArgumentException: View=DecorView@14a2889[] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:648)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:533)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:140)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5441)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Goooler** [comment]
Not sure, need more detailed stacktraces.

**Comment by William150722** [comment]
@Goooler thanks for the update. I see this issues is occur quite frequent.. is it any issues with decorview? Can I know what the decor view meaning? Thanks in advance

**Comment by Goooler** [comment]
If you can find the repro procedure, we'll easily fix it.

**Comment by William150722** [comment]
@Goooler then what kind of stacktraces or info you needed?

**Comment by Goooler** [comment]
I can't find any words containing the `lawnchair`, can't locate which line code cause your issue.

**Comment by William150722** [comment]
@Goooler i see... I checked the log crash all happen only in Samsung device. 
<img width="1385" alt="Screenshot 2022-11-03 at 11 50 15 AM" src="https://user-images.githubusercontent.com/111726325/199645563-c21b862c-8927-4b8f-8ba9-5bf909e16c17.png">

i research the code i suspect is this area causing the issues.

**Comment by Goooler** [comment]
Alright, I'll take a look later, very busy recently.

**Comment by William150722** [comment]
@Goooler okay, noted on this and Thanks for your time. I will look around also try to resolve it

FYI
https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash
