### ISSUE TITLE
[BUG] OutofMemoryError when going to 'home screen' 

### ISSUE THREAD

**Issue by augtheo** [Deletescape-Media/Lawnchair#3040]
### Describe the bug

Encountered this error when going to the home screen after using an app.

error: Uncaught exception

java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 580568 free bytes and 566KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.Object.internalClone(Native Method)
	at java.lang.Object.clone(Object.java:259)
	at android.animation.StateListAnimator.clone(StateListAnimator.java:138)
	at android.animation.StateListAnimator$StateListAnimatorConstantState.newInstance(StateListAnimator.java:328)
	at android.animation.StateListAnimator$StateListAnimatorConstantState.newInstance(StateListAnimator.java:308)
	at android.content.res.ConstantState.newInstance(ConstantState.java:53)
	at android.content.res.ConstantState.newInstance(ConstantState.java:61)
	at android.content.res.ConfigurationBoundResourceCache.getInstance(ConfigurationBoundResourceCache.java:46)
	at android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:163)
	at android.view.View.<init>(View.java:5902)
	at android.widget.TextView.<init>(TextView.java:1072)
	at android.widget.TextView.<init>(TextView.java:1066)
	at com.android.launcher3.BubbleTextView.<init>(BubbleTextView.java:3)
	at com.android.launcher3.BubbleTextView.<init>(BubbleTextView.java:2)
	at app.lawnchair.v$c.e(Unknown Source:2)
	at app.lawnchair.v$c.invoke(Unknown Source:4)
	at app.lawnchair.v.onCreateView(LawnchairLayoutFactory.kt:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.launcher3.allapps.AllAppsGridAdapter.onCreateViewHolder(AllAppsGridAdapter.java:13)
	at com.android.launcher3.allapps.AllAppsGridAdapter.onCreateViewHolder(AllAppsGridAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView$h.createViewHolder(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$w.N(RecyclerView.java:26)
	at androidx.recyclerview.widget.RecyclerView$w.p(Unknown Source:5)
	at androidx.recyclerview.widget.RecyclerView$w.o(Unknown Source:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.launcher3.views.BaseDragLayer.onLayout(BaseDragLayer.java:1)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.launcher3.LauncherRootView.onLayout(LauncherRootView.java:1)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3911)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3298)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Steps to reproduce

1. Go to 'home screen'

### Expected behavior

Go to 'home screen'

### Device information

- Device: Google Pixel 6a
- OS: Android version 13.0
- App version: 12.1.0 Alpha 4

**Comment by William150722** [comment]
<img width="1273" alt="Screenshot 2022-11-03 at 11 18 08 AM" src="https://user-images.githubusercontent.com/111726325/199641539-0076ef1e-3f1b-410a-a481-42f5976393eb.png">

I think you need to set largeHeap to TRUE flag so allow to allocate more memory for the app. I used to get many memoryOutOfBound in app.

**Comment by Goooler** [comment]
Duplicate of #3238
