### ISSUE TITLE
[BUG] java.lang.RuntimeException: android.os.DeadSystemException

### ISSUE THREAD

**Issue by William150722** [Deletescape-Media/Lawnchair#3082]
### Describe the bug

java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.pm.LauncherApps.getActivityList(LauncherApps.java:728)
	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:6)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:28)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.DeadSystemException

### Steps to reproduce

1. Suspect the user shut down the devices.

### Expected behavior

Is it possible to try catch these android.os.DeadSystemException

### Device information

- Device: moto g pure
- OS: SDK 30, Android 11
- App version: 12.1.0 Alpha 4

**Comment by Goooler** [comment]
I guess this issue was caused by shutting down devices, no need to catch `DeadSystemException`.
