### ISSUE TITLE
Can't create Android widget[BUG] 

### ISSUE THREAD

**Issue by vrushank29** [Deletescape-Media/Lawnchair#3086]
### Describe the bug

When I try to create any widget it fails.

### Steps to reproduce

Just a try to create  widget.

### Expected behavior

Should be able to create widget

### Device information

- Device: Samsung Galaxy S22+
- OS: One UI 5.0 Android version 13
- App version: [e.g. 12.1.0 Alpha 4]

### Additional context

Lawnchair bug report 2 Nov 2022 16:24:09
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: g0s
build.display: TP1A.220624.014.S906BXXU2BVJA
build.fingerprint: samsung/g0sxeea/g0s:13/TP1A.220624.014/S906BXXU2BVJA:user/release-keys
build.hardware: s5e9925
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-S906B
build.product: g0sxeea
build.type: user
version.codename: REL
version.incremental: S906BXXU2BVJA
version.release: 13
version.sdk_int: 33
display.density_dpi: 450
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.CellLayout.cellToRect(int, int, int, int, android.graphics.Rect)' on a null object reference
	at com.android.launcher3.Workspace.estimateItemPosition(Workspace.java:2)
	at com.android.launcher3.Workspace.getFinalPositionForDropAnimation(Workspace.java:3)
	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:2)
	at com.android.launcher3.Launcher.completeTwoStageWidgetDrop(Launcher.java:10)
	at com.android.launcher3.Launcher$3.run(Launcher.java:1)
	at com.android.launcher3.Workspace.removeExtraEmptyScreenDelayed(Workspace.java:9)
	at com.android.launcher3.Workspace.lambda$removeExtraEmptyScreenDelayed$2(Unknown Source:1)
	at com.android.launcher3.Workspace.o(Unknown Source:0)
	at com.android.launcher3.l3.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by vrushank29** [comment]
To be clear, this started happening after I upgraded Android to Android 13(One UI 5); I cannot create any widgets under android. For example, Android Calendar doesn't work, but I downloaded the Google calendar app
, which works.

**Comment by flamendless** [comment]
i also experience this even after restarting the phone. Im using MIUI 13.0.10 Stable and Lawnchair 12.1.0 Alpha 4

**Comment by Goooler** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.CellLayout.cellToRect(int, int, int, int, android.graphics.Rect)' on a null object reference
    at com.android.launcher3.Workspace.estimateItemPosition(Workspace.java:2)
    at com.android.launcher3.Workspace.getFinalPositionForDropAnimation(Workspace.java:3)
    at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:2)
    at com.android.launcher3.Launcher.completeTwoStageWidgetDrop(Launcher.java:10)
    at com.android.launcher3.Launcher$3.run(Launcher.java:1)
    at com.android.launcher3.Workspace.removeExtraEmptyScreenDelayed(Workspace.java:9)
    at com.android.launcher3.Workspace.lambda$removeExtraEmptyScreenDelayed$2(Unknown Source:1)
    at com.android.launcher3.Workspace.o(Unknown Source:0)
    at com.android.launcher3.l3.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8741)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by MuubNito** [comment]
> i also experience this even after restarting the phone. Im using MIUI 13.0.10 Stable and Lawnchair 12.1.0 Alpha 4

Using MIUI 14, still no fix

**Comment by Goooler** [comment]
Can you try with the latest debug builds based on A14?

**Comment by PalmDevs** [comment]
It still doesn't work on the latest builds. The crash logs have a different stack trace though.

I'm:
- On One UI 5.1 (Samsung Galaxy A13)
- Using the A14 debug build `#397`

https://katb.in/ujitujecaju

**Comment by MrSluffy** [comment]
> It still doesn't work on the latest builds. The crash logs have a different stack trace though.
> 
> I'm:
> 
> * On One UI 5.1 (Samsung Galaxy A13)
> * Using the A14 debug build `#397`
> 
> https://katb.in/ujitujecaju

What widget is this? so we can reproduce this issue

**Comment by MrSluffy** [comment]
Try this build with test patch : https://github.com/LawnchairLauncher/lawnchair/actions/runs/7663214207

**Comment by PalmDevs** [comment]
> What widget is this? so we can reproduce this issue

Google (quick search box)'s new Assistant At A Glance widget

**Comment by MrSluffy** [comment]
> > What widget is this? so we can reproduce this issue
> 
> Google (quick search box)'s new Assistant At A Glance widget

Have you tried this build : https://github.com/LawnchairLauncher/lawnchair/actions/runs/7663214207

**Comment by PalmDevs** [comment]
> Try this build with test patch : https://github.com/LawnchairLauncher/lawnchair/actions/runs/7663214207

Instead of crashing, now nothing happens. ~~It seems to be a reoccurring theme for widgets with settings that pop up before you finish adding the widget.~~

Edit: Actually, nevermind. It's only a few apps that are affected. Not sure why. Google app is one of them though.

[!video](https://github.com/LawnchairLauncher/lawnchair/assets/67689562/10ec1e21-4ef6-43ff-884a-cb8c205591b6)

> Have you tried this build

Yes, I'm also on the `#398` build.

**Comment by MrSluffy** [comment]
Yep it's intended. nothing happen, can you send screen record?

**Comment by PalmDevs** [comment]
> Yep it's intended. nothing happen, can you send screen record?

Attached screen recording in the edit.
