### ISSUE TITLE
[BUG] Can't create WhatsApp Widget

### ISSUE THREAD

**Issue by thor9898** [Deletescape-Media/Lawnchair#3092]
### Describe the bug

When I try to add WhatsApp Widget it just crashed

### Steps to reproduce

1. Long click on the launcher
2. Click on 'Widgets'
3. Scroll down to 'Whatsapp'
4. Click on the first one
5. Drag it anywhere(main screen, second screen, create new screen...)
6. It just crashes

### Expected behavior

Create WhatsApp widget

### Device information

- Device: Galaxy S21 5G
- OS: One UI 5.0 Android 13
- App version: 12.1.0 Alpha 4

### Additional context

Lawnchair bug report 7 nov 2022 15:24:21
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: o1s
build.display: TP1A.220624.014.G991BXXU5DVJC
build.fingerprint: samsung/o1sxeea/o1s:13/TP1A.220624.014/G991BXXU5DVJC:user/release-keys
build.hardware: exynos2100
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-G991B
build.product: o1sxeea
build.type: user
version.codename: REL
version.incremental: G991BXXU5DVJC
version.release: 13
version.sdk_int: 33
display.density_dpi: 480
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Goooler** [comment]
Dup with #2820.

**Comment by thor9898** [comment]
But I can create other widgets, it's only whatsapp one that crashed
