### ISSUE TITLE
BUG in Home Screen Grid

### ISSUE THREAD

**Issue by tushar09** [Deletescape-Media/Lawnchair#3109]
### Describe the bug

When I try to change the **Home Screen Grid** it crashes.

### Steps to reproduce

1. Go to **Home Settings**
2. Go to **Home Screen**
3. Scroll down to **Layout** section
4. Tap on **Home Screen Grid**

### Expected behavior

It should allow me to change the grid layout.

### Screenshots

https://user-images.githubusercontent.com/9745378/201538814-0e3e9070-0b14-41f7-bfaa-c5b24e817903.mp4

### Device information

- Device: [Android 12 emulator, Oneplus 6T]
- OS: [Android version 12.0 and 11]
- App version: [12.1.0 Dev (68fe426)]

### Additional context

`Process: app.lawnchair, PID: 22102
                                                                                                    android.view.InflateException: Binary XML file line #29 in app.lawnchair:layout/search_container_workspace: Binary XML file line #29 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #29 in app.lawnchair:layout/search_container_workspace: Error inflating class fragment
                                                                                                    Caused by: java.lang.IllegalStateException: Fragment QsbFragment{c6caba} not attached to Activity
                                                                                                    	at android.app.Fragment.startActivityForResult(Fragment.java:1119)
                                                                                                    	at android.app.Fragment.startActivityForResult(Fragment.java:1110)
                                                                                                    	at com.android.launcher3.qsb.QsbContainerView$QsbFragment.requestQsbCreate(QsbContainerView.java:321)
                                                                                                    	at com.android.launcher3.qsb.QsbContainerView$QsbFragment.getDefaultView(QsbContainerView.java:312)
                                                                                                    	at com.android.launcher3.qsb.QsbContainerView$QsbFragment.createQsb(QsbContainerView.java:253)
                                                                                                    	at com.android.launcher3.qsb.QsbContainerView$QsbFragment.onCreateView(QsbContainerView.java:193)
                                                                                                    	at com.android.launcher3.graphics.LauncherPreviewRenderer.onCreateView(LauncherPreviewRenderer.java:329)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1083)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1019)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1156)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1117)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:704)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:556)
                                                                                                    	at com.android.launcher3.graphics.LauncherPreviewRenderer.populate(LauncherPreviewRenderer.java:517)
                                                                                                    	at com.android.launcher3.graphics.LauncherPreviewRenderer.getRenderedView(LauncherPreviewRenderer.java:304)
                                                                                                    	at app.lawnchair.views.LauncherPreviewView.renderView(LauncherPreviewView.kt:143)
                                                                                                    	at app.lawnchair.views.LauncherPreviewView.loadModelData$lambda$3$lambda$2(LauncherPreviewView.kt:109)
                                                                                                    	at app.lawnchair.views.LauncherPreviewView.$r8$lambda$cYc0chie-2LAfMVJGiDN9mdIeDA(Unknown Source:0)
                                                                                                    	at app.lawnchair.views.LauncherPreviewView$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8068)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

**Comment by naveenccmsd** [comment]
This is know issue , app crashes when selecting icon packs and home grid. Please follow below steps to fix the issue.


Disable At A Glance, go to the preference with the home screen preview (e.g. Icon Style, Home Screen Grid), then it should not crash after that. Re-enable AaG after that

**Comment by yasanglass** [comment]
Closed by 4d6e74742df8ec54cc69f528eb089e88d6f6744a
