### ISSUE TITLE
Crash when dragging Instagram to home screen. 

### ISSUE THREAD

**Issue by kbexit** [Deletescape-Media/Lawnchair#3143]
![Lawnchair bug report Nov 30, 2022 08:05:46.txt](https://github.com/LawnchairLauncher/lawnchair/files/10123449/Lawnchair.bug.report.Nov.30.2022.08.05.46.txt)

**Comment by Goooler** [comment]
```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference
    at com.android.launcher3.Workspace.onDragStart(Workspace.java:4)
    at com.android.launcher3.dragndrop.DragController.callOnDragStart(DragController.java:8)
    at com.android.launcher3.dragndrop.DragController.handleMoveEvent(DragController.java:14)
    at com.android.launcher3.dragndrop.DragController.onDriverDragMove(DragController.java:2)
    at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:6)
    at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(Unknown Source:4)
    at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:6)
    at android.view.View.dispatchTouchEvent(View.java:15004)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
    at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:13)
    at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
    at android.app.Activity.dispatchTouchEvent(Activity.java:4262)
    at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:6)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
    at android.view.View.dispatchPointerEvent(View.java:15263)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6548)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6348)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5804)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5992)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6049)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8857)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8808)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8777)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8980)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8937)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9071)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:824)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
