### ISSUE TITLE
[BUG] Crash while "Turn off work apps"

### ISSUE THREAD

**Issue by yoni13** [Deletescape-Media/Lawnchair#3145]
### Describe the bug

Go app list , click on work apps tab,trunk off work apps

### Steps to reproduce

1. Go to 'App drawer'
2. Click on 'work' tab
3. Click on 'turn off work app'
4. See the error

### Expected behavior

Trun off the work apps

### Device information

- Device: Asus Zenfone 8 
- OS: Stock android 13 beta
- App version: 12.1.0 Alpha 4

### Additional context

https://cdn.discordapp.com/attachments/858972718611562496/1048122897954263073/Lawnchair_bug_report_Dec_2_2022_22511_PM.txt

**Comment by Goooler** [comment]
```
java.lang.IllegalArgumentException: User 2357 is not a profile
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
    at android.os.Parcel.createException(Parcel.java:2995)
    at android.os.Parcel.readException(Parcel.java:2978)
    at android.os.Parcel.readException(Parcel.java:2920)
    at android.os.IUserManager$Stub$Proxy.requestQuietModeEnabled(IUserManager.java:3210)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:4565)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:4550)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:4517)
    at com.android.launcher3.allapps.WorkProfileManager.lambda$setWorkProfileEnabled$0(WorkProfileManager.java:3)
    at com.android.launcher3.allapps.WorkProfileManager.a(Unknown Source:0)
    at com.android.launcher3.allapps.o.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:241)
    at android.os.Looper.loop(Looper.java:358)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.pm.UserManagerService.setQuietModeEnabled(UserManagerService.java:1235)
    at com.android.server.pm.UserManagerService.requestQuietModeEnabled(UserManagerService.java:1143)
    at android.os.IUserManager$Stub.onTransact(IUserManager.java:1662)
    at android.os.Binder.execTransactInternal(Binder.java:1280)
    at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by Goooler** [comment]
On Pixel Android 12:

```
java.lang.SecurityException: Can't modify quiet mode, caller is neither foreground default launcher nor has MANAGE_USERS/MODIFY_QUIET_MODE permission
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
    at android.os.Parcel.createException(Parcel.java:2409)
    at android.os.Parcel.readException(Parcel.java:2392)
    at android.os.Parcel.readException(Parcel.java:2334)
    at android.os.IUserManager$Stub$Proxy.requestQuietModeEnabled(IUserManager.java:3583)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3967)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3952)
    at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3919)
    at com.android.launcher3.allapps.WorkProfileManager.lambda$setWorkProfileEnabled$0$com-android-launcher3-allapps-WorkProfileManager(WorkProfileManager.java:97)
    at com.android.launcher3.allapps.WorkProfileManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.pm.UserManagerService.ensureCanModifyQuietMode(UserManagerService.java:1168)
    at com.android.server.pm.UserManagerService.requestQuietModeEnabled(UserManagerService.java:1075)
    at android.os.IUserManager$Stub.onTransact(IUserManager.java:1648)
    at android.os.Binder.execTransactInternal(Binder.java:1179)
    at android.os.Binder.execTransact(Binder.java:1143)
```

**Comment by Goooler** [comment]
If you set Lawnchair as the default launcher, it would not happen.

**Comment by yoni13** [comment]
[Still happen,maybe problem with asus twin apps?](https://scontent.ftpe8-3.fna.fbcdn.net/v/t42.3356-2/325667035_6644562552226149_2869338302794358997_n.mp4?_nc_cat=106&ccb=1-7&_nc_sid=060d78&_nc_ohc=_gB4R3goGtEAX9i3r1M&tn=xkIlug__9Ahk-EIn&_nc_ht=scontent.ftpe8-3.fna&oh=03_AdQ19SezdfOA2kS9vC3_Ux38R4mnEEAA_xnBF1w0vqAivg&oe=63CACABB&dl=1)

**Comment by Goooler** [comment]
Show me your log.

**Comment by yoni13** [comment]
[Here is the log,I will try debug build later](https://drive.google.com/file/d/1QX9pXdnDY1ZWoowyi4ShWIKI-uLdZnp7/view?usp=drivesdk)

**Comment by Goooler** [comment]
Weird on your phone, but this should be fixed in #3270, no crashes now, you can have a try with the build artifact from https://github.com/LawnchairLauncher/lawnchair/actions/runs/3968842662.

**Comment by Goooler** [comment]
One more thing, I'm wondering what will happen if you tap "Turn off work apps" on your stock phone launcher.

**Comment by yoni13** [comment]
> One more thing, I'm wondering what will happen if you tap "Turn off work apps" on your stock phone launcher.

Rrr,not even a option
But a button to close is more convenience.

**Comment by yoni13** [comment]
So looks like an asus issue

**Comment by Goooler** [comment]
> But a button to close is more convenience.

Yeah, it will be shown in some cases.

The crash had been caught, just use logging instead.
