### ISSUE TITLE
[BUG] Disallowed call from unknown notification listener

### ISSUE THREAD

**Issue by reyarthurr** [Deletescape-Media/Lawnchair#3151]
### Describe the bug

Hi guys, it turns out that the error occurred in a situation where it did not occur before. While I was turning on the phone, some notifications fell on me and at the same time I pressed the "recent" button to go from one app to another and at that moment the error occurred and the screen of which launcher I wanted to use was displayed.

### Steps to reproduce

¿?

### Expected behavior

Don't throw exceptions

### Device information

- Device: [Nokia 5.4]
- OS: [stock ROM Android 12]
- App version: [12.1.0 Alpha 4]

### Additional context

Lawnchair bug report 5 dic. 2022 7:09:47 a. m.
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c

version.release: 12
version.sdk_int: 31
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@5366de5 class android.service.notification.INotificationListener$Stub$Proxy
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:5171)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:1029)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:953)
	at app.lawnchair.y$b.invokeSuspend(NotificationManager.kt:5)
	at ib.a.resumeWith(ContinuationImpl.kt:4)
	at bc.b1.run(DispatchedTask.kt:18)
	at gc.m.run(LimitedDispatcher.kt:2)
	at ic.k.run(Tasks.kt:1)
	at ic.a.K(CoroutineScheduler.kt:1)
	at ic.a$c.d(CoroutineScheduler.kt:4)
	at ic.a$c.n(CoroutineScheduler.kt:4)
	at ic.a$c.run(Unknown Source:0)
	Suppressed: bc.z0: [w2{Cancelling}@8b5e197, Dispatchers.IO]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:993)
	at com.android.server.notification.NotificationManagerService$11.getActiveNotificationsFromListener(NotificationManagerService.java:4713)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2253)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)

**Comment by Goooler** [comment]
Dup with #2825, you can try out apk from https://github.com/LawnchairLauncher/lawnchair/actions/runs/3740845843
