### ISSUE TITLE
When putting widgets on home it crashes  

### ISSUE THREAD

**Issue by arsh225** [Deletescape-Media/Lawnchair#3171]
### Describe the bug

When you put widgets on home screen it crashes and restarts itself without the widget 

### Steps to reproduce

1. Go to 'widgets'
2. Click on ' any widgets that you like from stock aps.'
5. Put it on home screen after doing it multiple times 
6. See error

### Expected behavior

It crashes and restarts itself 

### Screenshots

![Screenshot_20221213_192503_HTML Viewer](https://user-images.githubusercontent.com/68815953/207527721-6d02e538-e867-42a5-a38e-1db6b8f7fed1.jpg)

### Device information

- Device: [Samsung Galaxy S22+ - SM-S906E]
- OS: [One Ui 5.00]
- App version: [ 12.1.0 Alpha 4]

### Additional context

Lawnchair bug report 14-Dec-2022 12:37:55 pm
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: g0q
build.display: TP1A.220624.014.S906EXXU2BVKB
build.fingerprint: samsung/g0qxxx/g0q:13/TP1A.220624.014/S906EXXU2BVKB:user/release-keys
build.hardware: qcom
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-S906E
build.product: g0qxxx
build.type: user
version.codename: REL
version.incremental: S906EXXU2BVKB
version.release: 13
version.sdk_int: 33
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Goooler** [comment]
Dup with #2820.
