### ISSUE TITLE
[BUG] DecorView not attached to window manager

### ISSUE THREAD

**Issue by minguibernardo** [Deletescape-Media/Lawnchair#3200]
### Describe the bug

```

error: Uncaught exception

java.lang.IllegalArgumentException: View=DecorView@7137a97[] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:707)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:593)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6151)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6444)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6342)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6427)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2581)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
(https://github.com/LawnchairLauncher/lawnchair/files/10266513/Lawnchair.bug.report.Dec.20.2022.07_41_53.1.txt)

### Expected behavior

Application had to open normally after restarting the phone but this did not happen it had an unexpected stop so I had to start again, I had it set as default launcher

### Device information

- Device: [Samsung, m52xq]
- OS: [e.g. stock ROM Android version 13.0, One UI 5.0 ]
- [App version: [ 12.1.0 Alpha 4 (12010005)]]
-build.brand: samsung
-build.device: m52xq
-build.display: TP1A.220624.014.M526BXXU1CVJ7
-build.fingerprint: samsung/m52xqins/m52xq:13/TP1A.220624.014/M526BXXU1CVJ7:user/release-keys
-build.hardware: qcom
-build.id: TP1A.220624.014
-build.manufacturer: samsung
-build.model: SM-M526B
-build.product: m52xqins
-build.type: user
-version.codename: REL
-version.incremental: M526BXXU1CVJ7
-version.release: 13
-version.sdk_int: 33
-display.density_dpi: 420
-isRecentsEnabled: false

**Comment by Goooler** [comment]
May only happen on Samsung Android 13, I can't repro this on my Moto X40 (Android 13).
