### ISSUE TITLE
[BUG] OutOfMemory error

### ISSUE THREAD

**Issue by TheGamer1002** [Deletescape-Media/Lawnchair#3238]
### Describe the bug

I was switching to the home screen and lawnchair crashed. That's it. That's the bug.

### Steps to reproduce

I mean like. Go to the home screen? I don't know.

### Expected behavior

...to see the home screen.

### Device information

Lawnchair bug report Jan 9, 2023 9:05:15 PM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: raven
build.display: T2B1.221118.006
build.fingerprint: google/raven/raven:13/T2B1.221118.006/9375477:user/release-keys
build.hardware: raven
build.id: T2B1.221118.006
build.manufacturer: Google
build.model: Pixel 6 Pro
build.product: raven
build.type: user
version.codename: REL
version.incremental: 9375477
version.release: 13
version.sdk_int: 33
display.density_dpi: 476
isRecentsEnabled: false

error: Uncaught exception

java.lang.OutOfMemoryError: Failed to allocate a 200 byte allocation with 1403352 free bytes and 1370KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
	at com.android.internal.util.ArrayUtils.newUnpaddedIntArray(ArrayUtils.java:63)
	at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:160)
	at android.util.SparseArray.put(SparseArray.java:280)
	at android.util.SparseArray.append(SparseArray.java:466)
	at android.view.View.saveAttributeDataForStyleable(View.java:6443)
	at android.widget.TextView.<init>(TextView.java:1159)
	at android.widget.TextView.<init>(TextView.java:1066)
	at com.android.launcher3.BubbleTextView.<init>(BubbleTextView.java:3)
	at com.android.launcher3.views.DoubleShadowBubbleTextView.<init>(DoubleShadowBubbleTextView.java:3)
	at com.android.launcher3.views.DoubleShadowBubbleTextView.<init>(DoubleShadowBubbleTextView.java:2)
	at app.lawnchair.v$d.e(Unknown Source:2)
	at app.lawnchair.v$d.invoke(Unknown Source:4)
	at app.lawnchair.v.onCreateView(LawnchairLayoutFactory.kt:1)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:3)
	at com.android.launcher3.Launcher.createShortcut(Launcher.java:1)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:14)
	at com.android.launcher3.Launcher.bindItems(Launcher.java:1)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$bindWorkspaceItems$7(Unknown Source:6)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.b(Unknown Source:0)
	at com.android.launcher3.model.n.execute(Unknown Source:6)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.lambda$executeCallbacksTask$9(BaseLoaderResults.java:3)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.c(Unknown Source:0)
	at com.android.launcher3.model.q.run(Unknown Source:4)
	at com.android.launcher3.util.LooperExecutor.execute(LooperExecutor.java:2)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.executeCallbacksTask(Unknown Source:5)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.bindWorkspaceItems(BaseLoaderResults.java:2)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.bind(BaseLoaderResults.java:19)
	at com.android.launcher3.model.BaseLoaderResults$WorkspaceBinder.access$000(Unknown Source:0)
	at com.android.launcher3.model.BaseLoaderResults.bindWorkspace(BaseLoaderResults.java:15)
	at com.android.launcher3.LauncherModel.startLoader(LauncherModel.java:13)
	at com.android.launcher3.LauncherModel.addCallbacksAndLoad(LauncherModel.java:3)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:38)
	at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:1)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:3)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Additional context

I have a crash report and the team seems to know their way around, so I'm just gonna put this here. @ me if there's any more questions.

**Comment by Goooler** [comment]
Can you repro this?

**Comment by TheGamer1002** [comment]
Yeah, just did 2 days ago. Same error. I don’t think I was doing anything too memory intensive. It hasn’t crashed when I’ve been playing demanding games.

**Comment by TheGamer1002** [comment]
no way it happened again! 
```Lawnchair bug report Jan 22, 2023 9:56:50 AM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: raven
build.display: T2B2.221216.006
build.fingerprint: google/raven/raven:13/T2B2.221216.006/9443277:user/release-keys
build.hardware: raven
build.id: T2B2.221216.006
build.manufacturer: Google
build.model: Pixel 6 Pro
build.product: raven
build.type: user
version.codename: REL
version.incremental: 9443277
version.release: 13
version.sdk_int: 33
display.density_dpi: 476
isRecentsEnabled: false

error: Uncaught exception

java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 1648968 free bytes and 1610KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3645)
	at java.util.Arrays.copyOf(Arrays.java:3614)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at android.graphics.drawable.VectorDrawable$VGroup.addChild(VectorDrawable.java:1370)
	at android.graphics.drawable.VectorDrawable$VGroup.<init>(VectorDrawable.java:1343)
	at android.graphics.drawable.VectorDrawable$VectorDrawableState.<init>(VectorDrawable.java:994)
	at android.graphics.drawable.VectorDrawable.mutate(VectorDrawable.java:389)
	at com.android.launcher3.icons.ThemedIconDrawable$ThemeData.loadMonochromeDrawable(ThemedIconDrawable.java:1)
	at com.android.launcher3.icons.ThemedIconDrawable.<init>(ThemedIconDrawable.java:5)
	at com.android.launcher3.icons.ThemedIconDrawable$ThemedConstantState.newDrawable(ThemedIconDrawable.java:2)
	at com.android.launcher3.icons.ThemedIconDrawable$ThemedBitmapInfo.newThemedIcon(ThemedIconDrawable.java:3)
	at com.android.launcher3.model.data.ItemInfoWithIcon.newIcon(ItemInfoWithIcon.java:2)
	at com.android.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:2)
	at com.android.launcher3.BubbleTextView.applyFromApplicationInfo(BubbleTextView.java:1)
	at com.android.launcher3.allapps.AllAppsGridAdapter.onBindViewHolder(AllAppsGridAdapter.java:16)
	at com.android.launcher3.allapps.AllAppsGridAdapter.onBindViewHolder(AllAppsGridAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView$h.onBindViewHolder(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$h.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$w.M(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$w.N(RecyclerView.java:47)
	at androidx.recyclerview.widget.RecyclerView$w.p(Unknown Source:5)
	at androidx.recyclerview.widget.RecyclerView$w.o(Unknown Source:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at com.android.launcher3.touch.PortraitPagedViewHandler.getChildBounds(PortraitPagedViewHandler.java:4)
	at com.android.launcher3.PagedView.getPageScrolls(PagedView.java:9)
	at com.android.launcher3.PagedView.onLayout(PagedView.java:5)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.launcher3.views.BaseDragLayer.onLayout(BaseDragLayer.java:1)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.launcher3.LauncherRootView.onLayout(LauncherRootView.java:1)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
	at android.view.View.layout(View.java:23700)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4069)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3437)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2349)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9166)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by TheGamer1002** [comment]
This happened when I was trying to literally just unlock my phone
