### ISSUE TITLE
[BUG] `No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions`

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3247]
### Describe the bug

```
java.lang.NoSuchFieldError: No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions; or its superclasses (declaration of 'androidx.compose.foundation.text.KeyboardActions' appears in /data/app/~~wl3MahlqkGj6CMjGufG2aA==/app.lawnchair-8thOE8dzJFJKokN06p4H7Q==/base.apk)
    at androidx.compose.material.OutlinedTextFieldKt.OutlinedTextField(OutlinedTextField.kt:188)
    at app.lawnchair.override.CustomizeDialogKt.CustomizeDialog(CustomizeDialog.kt:69)
    at app.lawnchair.override.CustomizeDialogKt.CustomizeAppDialog(CustomizeDialog.kt:133)
    at app.lawnchair.ui.popup.LawnchairShortcut$Customize$onClick$1.invoke(LawnchairShortcut.kt:59)
    at app.lawnchair.ui.popup.LawnchairShortcut$Customize$onClick$1.invoke(LawnchairShortcut.kt:58)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1$1$1.invoke(ComposeBottomSheet.kt:75)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1$1$1.invoke(ComposeBottomSheet.kt:74)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at app.lawnchair.views.ComposeBottomSheet$ContentWrapper$2.invoke(ComposeBottomSheet.kt:216)
    at app.lawnchair.views.ComposeBottomSheet$ContentWrapper$2.invoke(ComposeBottomSheet.kt:207)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
    at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)
    at app.lawnchair.views.ComposeBottomSheet.ContentWrapper(ComposeBottomSheet.kt:202)
    at app.lawnchair.views.ComposeBottomSheet.access$ContentWrapper(ComposeBottomSheet.kt:39)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1$1.invoke(ComposeBottomSheet.kt:74)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1$1.invoke(ComposeBottomSheet.kt:73)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1$1$1.invoke(ComposeBottomSheet.kt:183)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1$1$1.invoke(ComposeBottomSheet.kt:182)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1$1.invoke(ComposeBottomSheet.kt:179)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1$1.invoke(ComposeBottomSheet.kt:178)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at app.lawnchair.util.LifecycleKt$ProvideLifecycleState$1.invoke(lifecycle.kt:21)
    at app.lawnchair.util.LifecycleKt$ProvideLifecycleState$1.invoke(lifecycle.kt:20)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at app.lawnchair.util.LifecycleKt.ProvideLifecycleState(lifecycle.kt:20)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1.invoke(ComposeBottomSheet.kt:178)
    at app.lawnchair.views.ComposeBottomSheet$Providers$1.invoke(ComposeBottomSheet.kt:177)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:359)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
    at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
    at app.lawnchair.ui.theme.ThemeKt$LawnchairTheme$1.invoke(Theme.kt:47)
    at app.lawnchair.ui.theme.ThemeKt$LawnchairTheme$1.invoke(Theme.kt:46)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
    at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
    at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:265)
    at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
    at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
    at app.lawnchair.ui.theme.ThemeKt.LawnchairTheme(Theme.kt:42)
    at app.lawnchair.views.ComposeBottomSheet.Providers(ComposeBottomSheet.kt:177)
    at app.lawnchair.views.ComposeBottomSheet.access$Providers(ComposeBottomSheet.kt:39)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1.invoke(ComposeBottomSheet.kt:73)
    at app.lawnchair.views.ComposeBottomSheet$setContent$1.invoke(ComposeBottomSheet.kt:72)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
    at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
    at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3314)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3304)
    at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
    at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3304)
    at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3239)
    at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:967)
    at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1089)
    at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1176)
    at android.view.View.dispatchAttachedToWindow(View.java:21297)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5291)
    at android.view.ViewGroup.addView(ViewGroup.java:5077)
    at android.view.ViewGroup.addView(ViewGroup.java:5017)
    at android.view.ViewGroup.addView(ViewGroup.java:4989)
    at com.android.launcher3.views.AbstractSlideInView.attachToContainer(AbstractSlideInView.java:106)
    at app.lawnchair.views.ComposeBottomSheet.show(ComposeBottomSheet.kt:64)
    at app.lawnchair.views.ComposeBottomSheet$Companion.show(ComposeBottomSheet.kt:241)
    at app.lawnchair.ui.popup.LawnchairShortcut$Customize.onClick(LawnchairShortcut.kt:55)
    at android.view.View.performClick(View.java:7506)
    at android.view.View.performClickInternal(View.java:7483)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29341)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7868)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

### Steps to reproduce

Long press app icon and click on Customize.

### Expected behavior

No crash.

### Device information

All

### Additional context

Seem it comes from #3240.

**Comment by AR-Home** [comment]
While trying to edit in drop down box of the app itself, the launcher
crashes. 👍
