### ISSUE TITLE
crashes on every boot and restart

### ISSUE THREAD

**Issue by idontveapc** [Deletescape-Media/Lawnchair#3397]
### Describe the bug

on every restart and power off-on launcher crashes, but loads after it **but also sometimes system launcher loads not lawnchair!** I'd then have to choose it by pressing home button, each and everytime like permanent.

> the bug log might can't be saved, so there was a log, as notification shows everytime. sorry i’ll add it if i can get it saved or ill copy whole texts if i could.

### Steps to reproduce

**restarting** the device or **powering on**/_**booting Android**_.

### Expected behavior

on restart, launcher should load up showing apps and not crash.

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]
- ***sorry***
- Android 11 GO edition (is it cause 32bit os?)
- 12.1.0 alpha 4

### Additional context

> *I'd edit this*

**edit>>**
error: Uncaught exception

java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@90d7b77 class android.service.notification.INotificationListener$Stub$Proxy
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:4838)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:937)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:861)
	at app.lawnchair.y$b.invokeSuspend(NotificationManager.kt:5)
	at ib.a.resumeWith(ContinuationImpl.kt:4)
	at bc.b1.run(DispatchedTask.kt:18)
	at gc.m.run(LimitedDispatcher.kt:2)
	at ic.k.run(Tasks.kt:1)
	at ic.a.K(CoroutineScheduler.kt:1)
	at ic.a$c.d(CoroutineScheduler.kt:4)
	at ic.a$c.n(CoroutineScheduler.kt:4)
	at ic.a$c.run(Unknown Source:0)
	Suppressed: bc.z0: [w2{Cancelling}@fd0509, Dispatchers.IO]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:876)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4323)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2188)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by Goooler** [comment]
Can you try the apk from https://github.com/LawnchairLauncher/lawnchair/actions/runs/5440062157 ?

**Comment by idontveapc** [comment]
it needs fixes.

- recent items settings doesn’t work(if it worked for dev im on a11(armv8l)[go edition]).
- notification dot option is also not working, it takes you to system notification settings where it’s not an option.
- in drawer popup is plain b&w.

also data leak/heap dump is a lot frequent, it freezes the launcher.

**Comment by Goooler** [comment]
Can you try with the latest build on A14? Closing this for now, fell free to open a new one if issues still exist.
