### ISSUE TITLE
[BUG] AAG Data source error on Battery Status

### ISSUE THREAD

**Issue by validcube** [Deletescape-Media/Lawnchair#3473]
### Describe the bug

Unable to enable **Battery Status** on AAG when the device is charging due to data source error (see logcat)

> **Note** <br>
> * When the device is not connected to any charging source, **Battery Status** will work as intended (show when device's battery is low)

### Steps to reproduce

> **Note** <br>
> * The device must be charging to reproduce this behavior!
> * The app language must be Thai (TH)
1. Go to **At a glance** settings (Settings -> At a glance)
2. Enable show **Battery Status** option
3. Observe the issue

### Expected behavior

Battery Status should working as expected like Lawnchair 12.1.0 Dev 4.

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/93124920/29f69f0a-8295-4f06-a221-48738d5d6288

### Device information

- Device: Samsung M23 5G
- OS: Android 13 (One UI 5.1) - February 2023 Security Patch
- App version: Lawnchair 12.1 Debug ([#1910](https://github.com/LawnchairLauncher/lawnchair/actions/runs/4932524262))

### Additional context

Captured from logcat, the timing might not be the same as the one shown in the video

```log
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource: data source errored
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource: java.util.UnknownFormatConversionException: Conversion = '—'
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2787)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2817)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2630)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter.parse(Formatter.java:2563)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter.format(Formatter.java:2510)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.util.Formatter.format(Formatter.java:2464)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.lang.String.format(String.java:3644)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.content.res.Resources.getString(Resources.java:630)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.content.Context.getString(Context.java:782)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at app.lawnchair.smartspace.provider.BatteryStatusProvider.getSmartspaceTarget(BatteryStatusProvider.kt:44)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at app.lawnchair.smartspace.provider.BatteryStatusProvider.access$getSmartspaceTarget(BatteryStatusProvider.kt:18)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at app.lawnchair.smartspace.provider.BatteryStatusProvider$special$$inlined$map$1$2.emit(Emitters.kt:230)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.os.Handler.handleCallback(Handler.java:942)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.os.Looper.loopOnce(Looper.java:226)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.os.Looper.loop(Looper.java:313)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at android.app.ActivityThread.main(ActivityThread.java:8757)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at java.lang.reflect.Method.invoke(Native Method)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
05-20 11:54:09.755  6449  6449 D SmartspaceDataSource:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)05-20 11:54:09.805 18734 18744 I m.spotify.music: Background young concurrent copying GC
freed 844441(22MB) AllocSpace objects, 12(576KB) LOS objects, 34% free, 44MB/67MB, paused 879us,207us total 273.914ms
```

**Comment by validcube** [comment]
🎉 Update: I've managed to fix the issue, I'll do a PR in about 10 minutes!

This seems to be an issue for only Thai language
