### ISSUE TITLE
[BUG] Lawnchair randomly crashed in the background

### ISSUE THREAD

**Issue by 2br-2b** [Deletescape-Media/Lawnchair#3628]
### Describe the bug

As I was exiting an app, I got the message that Lawnchair wasn't responding.

### Steps to reproduce

Unsure - it happened randomly for a bit, then stopped working

### Expected behavior

The app doesn't crash

### Device information

Grapheneos - not sure what version this happened on, but I think that's in the error message

### Additional context
```
Lawnchair bug report Sep 15, 2023 10:46:07 AM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: lynx
build.display: TQ3A.230705.001.2023070500
build.fingerprint: google/lynx/lynx:13/TQ3A.230705.001/2023070500:user/release-keys
build.hardware: lynx
build.id: TQ3A.230705.001
build.manufacturer: Google
build.model: Pixel 7a
build.product: lynx
build.type: user
version.codename: REL
version.incremental: 2023070500
version.release: 13
version.sdk_int: 33
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2048)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1863)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1696)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1643)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1369)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1359)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1410)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:2)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:4)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:1)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:7)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by rajshekhar99** [comment]
did you try setting it first as default launcher other than quicksetup?

**Comment by 2br-2b** [comment]
Lawnchair has been my default launcher since July, when I did the quick setup. It seems like there's some issue with the icons. I'm not sure what caused this, but it hasn't crashed again since I reported this. It happened a few times within a short timespan, then stopped.
