### ISSUE TITLE
Lawnchair crashed

### ISSUE THREAD

**Issue by judemont** [Deletescape-Media/Lawnchair#3683]
### Describe the bug

Lawnchair crashed

### Steps to reproduce

1. Open the view of currently open applications
2. Click on the button to delete all applications activity
![signal-2023-10-24-15-53-43-621](https://github.com/LawnchairLauncher/lawnchair/assets/96385330/22a1ea8b-ffa4-4c33-afb0-a55f76bebc2c)

4. See lawnchair crash report notification

### Expected behavior

Not lawnchair crash.

### Device information

- Device: Xiaomi Redmi Note 10
- OS: Miui 14 (Based on Android 13)
- App version: 12.1.0 Alpha 4

### Additional context

```crashReport
Lawnchair bug report Oct 24, 2023 15:44:10
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: Redmi
build.device: eos
build.display: TP1A.220624.014
build.fingerprint: Redmi/eos_eea/eos:13/TP1A.220624.014/V14.0.4.0.TKUEUXM:user/release-keys
build.hardware: mt6768
build.id: TP1A.220624.014
build.manufacturer: Xiaomi
build.model: 21061119DG
build.product: eos_eea
build.type: user
version.codename: REL
version.incremental: V14.0.4.0.TKUEUXM
version.release: 13
version.sdk_int: 33
display.density_dpi: 440
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke interface method 'org.thoughtcrime.securesms.recipients.LiveRecipientCache org.thoughtcrime.securesms.dependencies.ApplicationDependencies$Provider.provideRecipientCache()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2027)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1842)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1369)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1359)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1410)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:2)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:4)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:1)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:7)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:5)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by fmikker** [comment]
Same problem experienced on a different phone with the same error message. The crash seems to happen at random, but very frequently and takes other apps with it when crashing which is quite disturbing.

Device information
 - Device: Samsung S9 (starlte)
 - OS: e// OS 1.15-r, based on LineageOS 17.1 (Android 11) and the latest Android security patches available per August 2023
 - App version: 12.1.0 Alpha 4

```Lawnchair bug report Nov 3, 2023 13:15:14
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: starlte
build.display: e_starlte-user 11 RQ3A.211001.001 eng.root.20230915.084000 dev-keys
build.fingerprint: samsung/starltexx/starlte:10/QP1A.190711.020/G960FXXUHFVG4:user/release-keys
build.hardware: samsungexynos9810
build.id: RQ3A.211001.001
build.manufacturer: samsung
build.model: SM-G960F
build.product: starltexx
build.type: user
version.codename: REL
version.incremental: eng.root.20230915.084000
version.release: 11
version.sdk_int: 30
display.density_dpi: 560
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke interface method 'org.thoughtcrime.securesms.recipients.LiveRecipientCache org.thoughtcrime.securesms.dependencies.ApplicationDependencies$Provider.provideRecipientCache()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2380)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1983)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1251)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1241)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1292)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:2)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:4)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:1)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:7)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:13)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```
