### ISSUE TITLE
[BUG] Lawnchair 13 debug crashing when opening

### ISSUE THREAD

**Issue by SeanDylan** [Deletescape-Media/Lawnchair#3744]
### Describe the bug

My tablet running android 12 immediately crash the newest debug version. I tried other versions but they keep crashing in the last one (12.1) 

### Steps to reproduce

1. Go to 'Lawnchiar.'
2. See error

### Expected behavior

Supposed to open the launcher without any problems

### Device information

- Device: [Teclast t40 pro]
- OS: [Android version 12.0]
- App version: [Lawnchair 13 debug]

### Additional context

Lawnchair (Debug) bug report 18 Nov 2023 10:37:21 pm
version: 13 Dev (#2325) (13)
commit: bd0da95
build.brand: Teclast
build.device: T40Pro_2022_EEA
build.display: V1.02_20230826
build.fingerprint: Teclast/T40Pro_2022_EEA/T40Pro_2022_EEA:12/SP1A.210812.016/221010:user/release-keys
build.hardware: ums9230_1h10
build.id: SP1A.210812.016
build.manufacturer: Teclast
build.model: T40 Pro_EEA
build.product: T40Pro_2022_EEA
build.type: user
version.codename: REL
version.incremental: 221010
version.release: 12
version.sdk_int: 31
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No virtual method getOnBackInvokedDispatcher()Landroid/window/OnBackInvokedDispatcher; in class Lcom/android/launcher3/uioverrides/QuickstepLauncher; or its super classes (declaration of 'com.android.launcher3.uioverrides.QuickstepLauncher' appears in /data/app/~~R92ZHVsk9Gx91rH7jt5vPg==/app.lawnchair.debug-K_iM-TH0Qkb4LXd-NOEaoQ==/base.apk!classes11.dex)
	at com.android.launcher3.uioverrides.QuickstepLauncher.registerBackDispatcher(QuickstepLauncher.java:666)
	at com.android.launcher3.BaseActivity.onCreate(BaseActivity.java:200)
	at com.android.launcher3.BaseDraggingActivity.onCreate(BaseDraggingActivity.java:73)
	at com.android.launcher3.statemanager.StatefulActivity.onCreate(StatefulActivity.java:61)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:490)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:526)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:203)
	at android.app.Activity.performCreate(Activity.java:8060)
	at android.app.Activity.performCreate(Activity.java:8040)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3653)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3840)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:105)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:136)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by MrSluffy** [comment]
Fixed #3728

**Comment by SeanDylan** [comment]
Another crash report in the latest debug (patch for crashes in q r and s)

Lawnchair (Debug) bug report 19 Nov 2023 12:06:33 pm
version: 13 Dev (#2327) (13)
commit: 9683178
build.brand: Teclast
build.device: T40Pro_2022_EEA
build.display: V1.02_20230826
build.fingerprint: Teclast/T40Pro_2022_EEA/T40Pro_2022_EEA:12/SP1A.210812.016/221010:user/release-keys
build.hardware: ums9230_1h10
build.id: SP1A.210812.016
build.manufacturer: Teclast
build.model: T40 Pro_EEA
build.product: T40Pro_2022_EEA
build.type: user
version.codename: REL
version.incremental: 221010
version.release: 12
version.sdk_int: 31
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0700b8 type #0x5 is not valid
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3683)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3840)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:105)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:136)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0700b8 type #0x5 is not valid
	at android.content.res.Resources.getFloat(Resources.java:1224)
	at com.android.launcher3.DeviceProfile.<init>(DeviceProfile.java:397)
	at com.android.launcher3.DeviceProfile$Builder.build(DeviceProfile.java:1938)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:441)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:339)
	at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:353)
	at com.android.launcher3.InvariantDeviceProfile.<init>(InvariantDeviceProfile.java:213)
	at com.android.launcher3.InvariantDeviceProfile.$r8$lambda$DNcXzmawjoq65q3wgQi9M48DryY(Unknown Source:2)
	at com.android.launcher3.InvariantDeviceProfile$$ExternalSyntheticLambda4.get(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$xtvr3aByNYHC2nsBQ97HC1SKg4A(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda0.get(Unknown Source:4)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
	at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:166)
	at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:109)
	at com.android.launcher3.LauncherAppState$$ExternalSyntheticLambda12.get(Unknown Source:2)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$xtvr3aByNYHC2nsBQ97HC1SKg4A(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda0.get(Unknown Source:4)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
	at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:97)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:492)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:205)
	at android.app.Activity.performCreate(Activity.java:8060)
	at android.app.Activity.performCreate(Activity.java:8040)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3653)
	... 12 more

**Comment by MrSluffy** [comment]
Hi Thanks for reporting kindly test the latest patch and let me know if it works if not send the new logs Thanks

**Comment by SeanDylan** [comment]
> Hi Thanks for reporting kindly test the latest patch and let me know if it works if not send the new logs Thanks

It works now now i can try out 13 debug but there is some lag in settings
