### ISSUE TITLE
[BUG] Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' when adding some widgets

### ISSUE THREAD

**Issue by WallyCZ** [Deletescape-Media/Lawnchair#3774]
### Describe the bug

Widget is not added and Lawnchair restarts. Occurs only when adding some widgets like from Google, Outlook calendar, while others (f.e. Google Fit) working fine.

### Steps to reproduce

1. Try to add Outlook Calendar widget
2. Lawnchair will restart instead of adding widget

### Expected behavior

Widget is added and no exception occurs

### Device information

- Device: Xiaomi 12
- OS: Xiaomi.EU V14.0.8.0.TLCCNXM
- App version: 3 Dev (#2388) (13)

### Additional context

`Lawnchair (Debug) bug report 26. 11. 2023 13:42:45
version: 13 Dev (BUILD 2388) (13)
commit: 5df1114
build.brand: Xiaomi
build.device: cupid
build.display: TKQ1.220807.001 release-keys
build.fingerprint: Xiaomi/cupid/cupid:13/SKQ1.220303.001/V14.0.8.0.TLCCNXM:user/release-keys
build.hardware: qcom
build.id: TKQ1.220807.001
build.manufacturer: Xiaomi
build.model: 2201123G
build.security.level: 2023-10-01
build.product: cupid
build.type: user
version.codename: REL
version.incremental: V14.0.8.0.TLCCNXM
version.release: 13
version.sdk_int: 33
display.density_dpi: 440
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:1540)
	at com.android.launcher3.Launcher$5.run(Launcher.java:1064)
	at com.android.launcher3.Workspace$5.run(Workspace.java:3148)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(AnimatorListeners.java:54)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Unknown Source:0)
	at android.animation.AnimatorSet.endAnimation(Unknown Source:56)
	at android.animation.AnimatorSet.doAnimationFrame(Unknown Source:269)
	at android.animation.AnimationHandler.doAnimationFrame(Unknown Source:30)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(Unknown Source:10)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:12)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:111)
	at android.view.Choreographer.doFrame(Unknown Source:511)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:108)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

`

**Comment by WallyCZ** [comment]
Maybe same as https://github.com/LawnchairLauncher/lawnchair/issues/2820, but it's closed as fixed.

**Comment by MrSluffy** [comment]
> Maybe same as #2820, but it's closed as fixed.

It fixed in AOSP/Custom roms, Samsung, VIVO etc,

But forgot to test this in miui roms

**Comment by WallyCZ** [comment]
Ok. If you want some tests from me feel free to ping me.
