### ISSUE TITLE
[BUG] Lawchair 13 doesn't work on Android 9

### ISSUE THREAD

**Issue by Rafael2616** [Deletescape-Media/Lawnchair#3778]
### Describe the bug

The app simply doesn't work in these versions.
I don't use Quickstep and I don't even have Root

### Steps to reproduce

1. Install Lawnchair 13 on A9
2. Open it
3. Crash

### Expected behavior

Open normally

### Device information

- Device: an Old LG
- OS: [e.g. stock ROM Android version 9]
- App version: [e.g. 13.0.0]

### Additional context

```
Lawnchair (Debug) bug report 26 de nov de 2023 23:04:43
version: 13 Dev (#2388) (13)
commit: 5df1114
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No static method createPredefined(I)Landroid/os/VibrationEffect; in class Landroid/os/VibrationEffect; or its super classes (declaration of 'android.os.VibrationEffect' appears in /system/framework/framework.jar!classes2.dex)
	at com.android.quickstep.util.VibrationConstants.<clinit>(VibrationConstants.java:22)
	at com.android.quickstep.views.RecentsView.<clinit>(RecentsView.java:294)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1353)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:222)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:269)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:518)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:527)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:205)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by MrSluffy** [comment]
Please change the label and title, since It's expected not to work Lawnchair 13 to A9 for your ref #3728

**Comment by Rafael2616** [comment]
> Please change the label and title, since It's expected not to work Lawnchair 13 to A9 for your ref #3728

Sure. What should the title look like?

**Comment by MrSluffy** [comment]
I picked now ur fixed : #3806

**Comment by Rafael2616** [comment]
> I picked now ur fixed : #3806

Of course, I was going to do a pull, but I forgot 😁. 

This fixes this issue, but the app still crashes when opening on the A9 due to other issues elsewhere

**Comment by MrSluffy** [comment]
> > I picked now ur fixed : #3806
> 
> Of course, I was going to do a pull, but I forgot 😁.
> 
> This fixes this issue, but the app still crashes when opening on the A9 due to other issues elsewhere

Great, I'll take a look too, If you have some fixes you can pushed here branch `fix-crash-a9` : #3806 or do separate pr and mentioned #3806 Thanks

**Comment by Rafael2616** [comment]
> > > I picked now ur fixed : #3806
> > 
> > Of course, I was going to do a pull, but I forgot 😁.
> > 
> > This fixes this issue, but the app still crashes when opening on the A9 due to other issues elsewhere
> 
> Great, I'll take a look too, If you have some fixes you can pushed here branch `fix-crash-a9` : #3806 or do separate pr and mentioned #3806 Thanks
> 

Sure. I will post the new issues that also occur. I'm not sure if these are related to this version. Could you confirm?

**Comment by Rafael2616** [comment]
```
Lawnchair (Debug) bug report 30 de nov de 2023 23:00:59
version: 13 Dev (#2456) (13)
commit: 4466b1a
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class com.android.quickstep.views.GroupedTaskView
Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class com.android.quickstep.views.GroupedTaskView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.util.ViewPool.inflateNewView(ViewPool.java:106)
	at com.android.launcher3.util.ViewPool.lambda$initPool$1(ViewPool.java:69)
	at com.android.launcher3.util.ViewPool.$r8$lambda$wSRnQcMZiOmM7xwf4gm88rNehhg(Unknown Source:0)
	at com.android.launcher3.util.ViewPool$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
	at com.android.quickstep.views.GroupedTaskView.<init>(GroupedTaskView.java:74)
	at com.android.quickstep.views.GroupedTaskView.<init>(GroupedTaskView.java:70)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 20 more

```

**Comment by Rafael2616** [comment]
The second issue:

```

Lawnchair (Debug) bug report 30 de nov de 2023 23:00:59
version: 13 Dev (#2456) (13)
commit: 4466b1a
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class com.android.quickstep.views.DesktopTaskView
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.android.quickstep.views.DesktopTaskView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.util.ViewPool.inflateNewView(ViewPool.java:106)
	at com.android.launcher3.util.ViewPool.lambda$initPool$1(ViewPool.java:69)
	at com.android.launcher3.util.ViewPool.$r8$lambda$wSRnQcMZiOmM7xwf4gm88rNehhg(Unknown Source:0)
	at com.android.launcher3.util.ViewPool$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
	at com.android.quickstep.views.DesktopTaskView.<init>(DesktopTaskView.java:105)
	at com.android.quickstep.views.DesktopTaskView.<init>(DesktopTaskView.java:101)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 20 more

```

**Comment by Rafael2616** [comment]
The third and last:

```

Lawnchair (Debug) bug report 30 de nov de 2023 23:00:59
version: 13 Dev (#2456) (13)
commit: 4466b1a
build.brand: lge
build.device: mmh4
build.display: PKQ1.190522.001
build.fingerprint: lge/mmh4_f/mmh4:9/PKQ1.190522.001/2106722188f70:user/release-keys
build.hardware: mmh4
build.id: PKQ1.190522.001
build.manufacturer: LGE
build.model: LM-X420
build.security.level: 2021-03-01
build.product: mmh4_f
build.type: user
version.codename: REL
version.incremental: 2106722188f70
version.release: 9
version.sdk_int: 28
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class com.android.quickstep.views.TaskView
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class com.android.quickstep.views.TaskView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.util.ViewPool.inflateNewView(ViewPool.java:106)
	at com.android.launcher3.util.ViewPool.lambda$initPool$1(ViewPool.java:69)
	at com.android.launcher3.util.ViewPool.$r8$lambda$wSRnQcMZiOmM7xwf4gm88rNehhg(Unknown Source:0)
	at com.android.launcher3.util.ViewPool$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/policy/ScreenDecorationsUtils;
	at com.android.systemui.shared.system.QuickStepContract.supportsRoundedCornersOnWindows(QuickStepContract.java:384)
	at app.lawnchair.util.LawnchairUtilsKt.supportsRoundedCornersOnWindows(LawnchairUtils.kt:127)
	at com.android.quickstep.util.TaskCornerRadius.get(TaskCornerRadius.java:30)
	at com.android.quickstep.views.TaskView$FullscreenDrawParams.<init>(TaskView.java:1773)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:431)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:422)
	at com.android.quickstep.views.TaskView.<init>(TaskView.java:418)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.ScreenDecorationsUtils" on path: DexPathList[[zip file "/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk"],nativeLibraryDirectories=[/data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/lib/arm, /data/app/app.lawnchair.debug-2IYx9NyOOjIFsbEGavGNSw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 19 more

```

**Comment by MrSluffy** [comment]
Yeah lot's of class in latest launcher3 that does not support by A9, I guess you can simply use Older version

**Comment by Rafael2616** [comment]
So far, what I have found is that this property is what causes the crash in the 3 problems I mentioned above in XML files

Fixing this might solve all 3 problems...

```
    launcher:borderColor="?attr/colorAccentPrimary">
```

**Comment by MrSluffy** [comment]
Yeah try fixing it and do a PR so I can test

**Comment by Rafael2616** [comment]
> Yeah try fixing it and do a PR so I can test


Apparently just change the name of this folder to "values-v28" may solve this issues

https://github.com/LawnchairLauncher/lawnchair/tree/13-dev/lawnchair/res/values-v30

I couldn't change it from here, as I don't have the repository locally and I couldn't even change it via GitHub 

This property that is causing the app to crash is not being found in versions prior to v30 - A11

**Comment by MrSluffy** [comment]
No you don't need to change it, it will crash in A11, just copy the values-v30 and create a new one v28

**Comment by MrSluffy** [comment]
Right, clone it and push then do a pr I'll test it

**Comment by Rafael2616** [comment]
Ok

**Comment by Rafael2616** [comment]
Do I need to create a pull?
