### ISSUE TITLE
[BUG] Exiting application with Predictive Back Gesture will cause Lawnchair to crash

### ISSUE THREAD

**Issue by validcube** [Deletescape-Media/Lawnchair#3812]
### Describe the bug

Exiting applications with Predictive Back Gesture will cause Lawnchair to crash

### Steps to reproduce

Requirement
* Android 13
* Predictive Back Gesture enabled in Android's Developer settings

Steps to reproduce the behaviour:
1. Open any application that enables Predictive Back
2. Exit the application using gesture navigation
3. Observe the error

### Expected behaviour

Predictive Back Gesture should work

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/93124920/fb3869d9-26cf-4ed7-88f3-d84104134b27

### Device information

- Device: Samsung M23
- OS: Android 13 Release 1 (One UI 5.1)
- App version: Lawnchair (Debug) 13 Alpha 1 [#2473](https://github.com/LawnchairLauncher/lawnchair/actions/runs/7058603726)

### Additional context

https://katb.in/kerarikafut

```log
Lawnchair (Debug) bug report 2 ธ.ค. 2023 18:14:40
version: 13 Dev (#2473) (13)
commit: 4402ef1
build.brand: samsung
build.device: m23xq
build.display: TP1A.220624.014.M236BXXU4CWH3
build.fingerprint: samsung/m23xqxx/m23xq:13/TP1A.220624.014/M236BXXU4CWH3:user/release-keys
build.hardware: qcom
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-M236B
build.security.level: 2023-08-01
build.product: m23xqxx
build.type: user
version.codename: REL
version.incremental: M236BXXU4CWH3
version.release: 13
version.sdk_int: 33
display.density_dpi: 450
isRecentsEnabled: true

error: Uncaught exception

java.lang.AbstractMethodError: abstract method "void android.window.IOnBackInvokedCallback.onBackStarted()"
	at android.window.IOnBackInvokedCallback$Stub.onTransact(IOnBackInvokedCallback.java:131)
	at android.os.Binder.execTransactInternal(Binder.java:1321)
	at android.os.Binder.execTransact(Binder.java:1280)

```
(`2 ธ.ค. 2023` is December 2nd 2023)

**Comment by validcube** [comment]
Related to #3781
