### ISSUE TITLE
[BUG] Continuously crashing when transparent themed icons is enabled but the selected icon pack doesn't support it

### ISSUE THREAD

**Issue by D3SOX** [Deletescape-Media/Lawnchair#3830]
### Describe the bug

Lawnchair crashes in an infinite loop

### Steps to reproduce

1. Enable themed icons and transparent themed icons
2. Switch homescreen, open app drawer, open recents (Not sure what I did to initially trigger it)
3. See error

### Expected behavior

Don't crash

### Device information

- Device: OnePlus 8T
- OS: Lineage for microG 20
- App version: Debug build from acfe0ba3a6a19588d8b34199121258e6f3520524

### Additional context

Maybe it has something to do with the icon pack I'm using, which is [Pix Material You Light/Dark](https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark)

```
Lawnchair (Debug) bug report Dec 7, 2023 12:32:50 PM
version: 13 Dev (#2492) (13)
commit: acfe0ba
build.brand: OnePlus
build.device: OnePlus8T
build.display: lineage_kebab-userdebug 13 TQ3A.230901.001 eng.root.20231108.065449 dev-keys
build.fingerprint: OnePlus/OnePlus8T_EEA/OnePlus8T:11/RP1A.201005.001/2110091916:user/release-keys
build.hardware: qcom
build.id: TQ3A.230901.001
build.manufacturer: OnePlus
build.model: KB2003
build.security.level: 2023-10-06
build.product: OnePlus8T
build.type: user
version.codename: REL
version.incremental: eng.root.20231108.065449
version.release: 13
version.sdk_int: 33
display.density_dpi: 411
isRecentsEnabled: true

error: Uncaught exception

java.lang.NullPointerException: forMeta(...) must not be null
	at app.lawnchair.icons.IconPackProvider.getDrawable(IconPackProvider.kt:58)
	at app.lawnchair.icons.LawnchairIconProvider.getIconWithOverrides(LawnchairIconProvider.kt:149)
	at com.android.launcher3.icons.IconProvider.getIcon(IconProvider.java:139)
	at app.lawnchair.icons.LawnchairIconProvider.getIcon(LawnchairIconProvider.kt:195)
	at com.android.launcher3.icons.LauncherActivityCachingLogic.loadIcon(LauncherActivityCachingLogic.java:70)
	at com.android.launcher3.icons.LauncherActivityCachingLogic.loadIcon(LauncherActivityCachingLogic.java:36)
	at com.android.launcher3.icons.cache.BaseIconCache.cacheLocked(BaseIconCache.java:396)
	at com.android.launcher3.icons.cache.BaseIconCache.cacheLocked(BaseIconCache.java:362)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:318)
	at com.android.launcher3.icons.IconCache.getTitleAndIcon(IconCache.java:228)
	at com.android.launcher3.model.AllAppsList.add(AllAppsList.java:150)
	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:969)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:246)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Is there any way to edit my config to fix this without deleting the app data?
Edit: I was able to restore my config by uninstalling the icon pack, then opening Lawnchair, revert those settings and finally installing it again

**Comment by MrSluffy** [comment]
Yes it has something to do with the icon pack you using since It doesn't support transparent like lawnicons

**Comment by MrSluffy** [comment]
To avoid this we can add steps to only show transparent theme icon option to supported icon in this case LawnIcons

**Comment by D3SOX** [comment]
Not tested but as far as I can tell this should stay open
