### ISSUE TITLE
[BUG] Strange crashing

### ISSUE THREAD

**Issue by Manasx100** [Deletescape-Media/Lawnchair#3848]
### Describe the bug

When I try to use the home gesture it crashed when I use recents sometimes it works sometimes it doesn't and the apps don't show but that's a different issue .The back gesture sometimes crashes lawnchair

### Steps to reproduce

1. Try using recents ,home or back gestures
2. Get crash or glitchy expected behavior

### Expected behavior

Get working home ,back or recents gestures

### Device information

- Device: [Poco X3 pro]
- OS: [MIUI verse 14 android 13.0]
- App version: [The latest build]

### Additional context

FATAL EXCEPTION: main
Process: app.lawnchair.debug, PID: 10585
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.SurfaceControl android.view.ViewRootImpl.getSurfaceControl()' on a null object reference
	at com.android.quickstep.util.SurfaceTransactionApplier.<init>(SurfaceTransactionApplier.java:53)
	at com.android.launcher3.QuickstepTransitionManager.getOpeningWindowAnimators(QuickstepTransitionManager.java:671)
	at com.android.launcher3.QuickstepTransitionManager.composeIconLaunchAnimator(QuickstepTransitionManager.java:400)
	at com.android.launcher3.QuickstepTransitionManager.-$$Nest$mcomposeIconLaunchAnimator(Unknown Source:0)
	at com.android.launcher3.QuickstepTransitionManager$AppLaunchAnimationRunner.onAnimationStart(QuickstepTransitionManager.java:1779)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$2(LauncherAnimationRunner.java:95)
	at com.android.launcher3.LauncherAnimationRunner.$r8$lambda$1wv0QB4xe8XmIzQ8-HXfT0gdXvs(Unknown Source:0)
	at com.android.launcher3.LauncherAnimationRunner$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

**Comment by Manasx100** [comment]
Nevermind disabled some modules and the crashing is mainly fixed now ,but the back gesture doesn't work (doesn't matter much) ,but recents doesn't show apps
Edit:recents still does crash
