### ISSUE TITLE
[BUG]: Exit the app drawer search screen and go to home screen makes the app crash 

### ISSUE THREAD

**Issue by Rafael2616** [Deletescape-Media/Lawnchair#3873]
### Describe the bug

I tried debugging it myself but it's a very strange bug

```
error: Uncaught exception

android.view.InflateException: Binary XML file line #45: Binary XML file line #45: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #45: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0403ce a=5 r=0x7f060449}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
	at android.widget.TextView.readTextAppearance(TextView.java:3708)
	at android.widget.TextView.<init>(TextView.java:1015)
	at android.widget.TextView.<init>(TextView.java:925)
	at android.widget.TextView.<init>(TextView.java:921)
	at app.lawnchair.LawnchairLayoutFactory$constructorMap$2.invoke(LawnchairLayoutFactory.kt:18)
	at app.lawnchair.LawnchairLayoutFactory$constructorMap$2.invoke(LawnchairLayoutFactory.kt:18)
	at app.lawnchair.LawnchairLayoutFactory.onCreateView(LawnchairLayoutFactory.kt:29)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.allapps.WorkProfileManager.attachWorkModeSwitch(WorkProfileManager.java:174)
	at com.android.launcher3.allapps.WorkProfileManager.updateCurrentState(WorkProfileManager.java:158)
	at com.android.launcher3.allapps.WorkProfileManager.reset(WorkProfileManager.java:141)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.reset(ActivityAllAppsContainerView.java:502)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.reset(ActivityAllAppsContainerView.java:468)
	at com.android.launcher3.Launcher.onStateSetEnd(Launcher.java:1280)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onStateSetEnd(QuickstepLauncher.java:484)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onStateSetEnd(QuickstepLauncher.java:189)
	at com.android.launcher3.statemanager.StateManager.onStateTransitionEnd(StateManager.java:400)
	at com.android.launcher3.statemanager.StateManager.-$$Nest$monStateTransitionEnd(Unknown Source:0)
	at com.android.launcher3.statemanager.StateManager$1.onAnimationSuccess(StateManager.java:377)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(AnimationSuccessListener.java:40)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1032)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:777)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1020)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6993)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)

```

It appears to originate here when trying to inflate one layout

https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src%2Fcom%2Fandroid%2Flauncher3%2Fallapps%2FWorkProfileManager.java#L174-L175

On line 45 of 'work_mode_fab': this
https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/res%2Flayout%2Fwork_mode_fab.xml#L45

 In other words, along the lines that define this style 

https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/res%2Fvalues%2Fstyles.xml#L381

But looking at the documentation, this was supposed to be compatible since API 14

https://developer.android.com/reference/android/R.style#TextAppearance_DeviceDefault_DialogWindowTitle

### Steps to reproduce

1. Go to 'Seach bar in App Drawer'
2. Wait the content to be loaded (apps etc..)
3. Click outside to minimize the keyboard without leaving search screen
4. Click on 'back' button to go to Home Screen
5. See error

### Expected behavior

Not crash

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/93414086/af8c8906-9e33-4cc8-91a4-b6cddb72dee0

This also happens when I close the search by dragging it down

https://github.com/LawnchairLauncher/lawnchair/assets/93414086/5fd6d3ce-61d1-4003-a14b-87c0859ab09d

### Device information

- Device: old LG
- OS: Android 9
- App version: 14-dev latest debug buil

**Comment by MrSluffy** [comment]
can you try to surround `Utilities.AtleastQ ` on this line https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/allapps/WorkModeSwitch.java#L98 and create a PR

**Comment by MrSluffy** [comment]
Also I noticed the icons is crop in your android 9 in search result

**Comment by Rafael2616** [comment]
> can you try to surround `Utilities.AtleastQ ` on this line https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/allapps/WorkModeSwitch.java#L98 and create a PR

Ok

**Comment by Rafael2616** [comment]
> Also I noticed the icons is crop in your android 9 in search result

Yes, I thought this was a general problem (not restricted to this version)

**Comment by MrSluffy** [comment]
> > Also I noticed the icons is crop in your android 9 in search result
> 
> Yes, I thought this was a general problem (not restricted to this version)

No doesn't occur in my end, can you try to check this too https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/lawnchair/src/app/lawnchair/search/LawnchairSearchAdapterProvider.kt#L72 set to 0 if `!Utilities.AtleastQ`

**Comment by Rafael2616** [comment]
Ok, I'll try these solutions

**Comment by Rafael2616** [comment]
> can you try to surround `Utilities.AtleastQ ` on this line https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/allapps/WorkModeSwitch.java#L98 and create a PR

That didn't work

**Comment by MrSluffy** [comment]
> > can you try to surround `Utilities.AtleastQ ` on this line https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/allapps/WorkModeSwitch.java#L98 and create a PR
> 
> That didn't work

is same logs? can you share your repo?

**Comment by Rafael2616** [comment]
> > > can you try to surround `Utilities.AtleastQ ` on this line https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src/com/android/launcher3/allapps/WorkModeSwitch.java#L98 and create a PR
> > 
> > That didn't work
> 
> is same logs? can you share your repo?

Yes, the same logs

Here the repo:
https://github.com/Rafael2616/lawnchair

I recreated it today with the A14 branch, it's "new"

**Comment by MrSluffy** [comment]
Did you install the build with top of old one with crash issue? If so try clean install

**Comment by Rafael2616** [comment]
> Did you install the build with top of old one with crash issue? If so try clean install

Not really, because as the signature of my repository is different from that of the official Lawnchair, I needed to reinstall it before installing the version with the probable correction and it still happens

**Comment by MrSluffy** [comment]
Seems can't reproduce the error in emulator A9
[Screen_recording_20231218_103551 (1).webm](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/74091587-2d04-451b-bfa1-e575371307fa)

**Comment by Rafael2616** [comment]
Wow, this is very strange, in fact the error itself is very strange, from what I could gather from it is that it occurs when trying to inflate that layout which I mentioned above, but even then it also only occurs in this specific circumstance. 
I don't know if it could be a manufacturer-specific problem.

**Comment by Rafael2616** [comment]
I'll try adding the version conditional here and see what happens

https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src%2Fcom%2Fandroid%2Flauncher3%2Fallapps%2FWorkProfileManager.java#L174-L175

**Comment by Rafael2616** [comment]
> I'll try adding the version conditional here and see what happens
> 
> https://github.com/LawnchairLauncher/lawnchair/blob/14-dev/src%2Fcom%2Fandroid%2Flauncher3%2Fallapps%2FWorkProfileManager.java#L174-L175

Yes, the problem is right here, I was able to fix it without any negative side effects. I'll just fix my repository and push it to the vranch you create
