### ISSUE TITLE
[BUG] SQLiteException: near "DROP": syntax error (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#3881]
### Describe the bug

Upgrade from LC 13:

```
android.database.sqlite.SQLiteException: near "DROP": syntax error (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE favorites DROP COLUMN iconPackage;
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
  at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
  at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1919)
  at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1841)
  at com.android.launcher3.provider.LauncherDbUtils.migrateLegacyShortcuts(LauncherDbUtils.java:175)
  at com.android.launcher3.model.DatabaseHelper.onUpgrade(DatabaseHelper.java:280)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
  at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
  at com.android.launcher3.model.ModelDbController.createDatabaseHelper(ModelDbController.java:119)
  at com.android.launcher3.model.ModelDbController.createDbIfNotExists(ModelDbController.java:100)
  at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(ModelDbController.java:284)
  at com.android.launcher3.model.ModelDbController.tryMigrateDB(ModelDbController.java:265)
  at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(LoaderTask.java:375)
  at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:349)
  at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:212)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:223)
  at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Steps to reproduce

1. Install LC 13 and modify homescreen.
2. Upgrade to LC 14.

### Expected behavior

No Crash.

### Device information

- Device: Emulator
- OS: Stock Android 11.
- App version: 14

**Comment by MrSluffy** [comment]
This happen due to new implementation of migration in launcher3 A14, clearing lawnchair data may resolve this.

**Comment by Goooler** [comment]
Shouldn't we compat the old users?

**Comment by MrSluffy** [comment]
I'll check it out, Anyway since we haven't official release of Lawnchair 13 (dev state). I don't think compat matters atm. But will check backup from 12.1 alpha releases to 14

**Comment by MrSluffy** [comment]
Fixed 26e452f87f954fd4c21fbef9501b84dd2a2224e9

**Comment by Goooler** [comment]
Seems not.

**Comment by MrSluffy** [comment]
No need to reopen this since there's no official LC A13 release. It's supported now 12.1 alpha  releases backup
