### ISSUE TITLE
App drawer crashes in battery saver mode

### ISSUE THREAD

**Issue by Eugeny** [Deletescape-Media/Lawnchair#393]
Android O / 8.0.0 / Nexus 5X / in battery saver mode only when pulling up the app drawer

```
08-03 09:03:28.071 26616 26616 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: java.lang.RuntimeException: Not implemented
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.LauncherViewPropertyAnimator.end(Unknown Source:5)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.end(AnimatorSet.java:509)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:436)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.pulseAnimationFrame(AnimatorSet.java:1095)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1143)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.start(AnimatorSet.java:729)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.animation.AnimatorSet.start(AnimatorSet.java:684)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation$5.run(Unknown Source:88)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation.startAnimationToOverlay(Unknown Source:654)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation.startAnimationToAllApps(Unknown Source:24)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.Launcher.showAppsOrWidgets(Unknown Source:62)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.Launcher.showAppsView(Unknown Source:5)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.allapps.AllAppsTransitionController.onDragEnd(Unknown Source:25)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.reportDragEnd(Unknown Source:17)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.setState(Unknown Source:21)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.onTouchEvent(Unknown Source:110)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.allapps.AllAppsTransitionController.onTouchEvent(Unknown Source:2)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at ch.deletescape.lawnchair.dragndrop.DragLayer.onTouchEvent(Unknown Source:58)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:11721)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:11960)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
08-03 09:03:28.076 26616 26616 E MessageQueue-JNI: 	at and
08-03 09:03:28.082 26616 26616 E AndroidRuntime: FATAL EXCEPTION: main
08-03 09:03:28.082 26616 26616 E AndroidRuntime: Process: ch.deletescape.lawnchair, PID: 26616
08-03 09:03:28.082 26616 26616 E AndroidRuntime: java.lang.RuntimeException: Not implemented
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.LauncherViewPropertyAnimator.end(Unknown Source:5)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.end(AnimatorSet.java:509)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:436)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.pulseAnimationFrame(AnimatorSet.java:1095)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1163)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1143)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1227)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:729)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:684)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation$5.run(Unknown Source:88)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation.startAnimationToOverlay(Unknown Source:654)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.LauncherStateTransitionAnimation.startAnimationToAllApps(Unknown Source:24)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.Launcher.showAppsOrWidgets(Unknown Source:62)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.Launcher.showAppsView(Unknown Source:5)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.allapps.AllAppsTransitionController.onDragEnd(Unknown Source:25)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.reportDragEnd(Unknown Source:17)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.setState(Unknown Source:21)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.allapps.VerticalPullDetector.onTouchEvent(Unknown Source:110)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.allapps.AllAppsTransitionController.onTouchEvent(Unknown Source:2)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at ch.deletescape.lawnchair.dragndrop.DragLayer.onTouchEvent(Unknown Source:58)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:11721)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3292)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:407)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:11960)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4776)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4274)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4331)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4181)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4147)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4155)
08-03 09:03:28.082 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4128)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6642)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6616)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6577)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6745)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:325)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:142)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-03 09:03:28.083 26616 26616 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by nyancrimew** [comment]
This is fixed in unreleased builds
