### ISSUE TITLE
[BUG] Lawnchair crashes with quickswitch(KSU) on Android14

### ISSUE THREAD

**Issue by greed-d** [Deletescape-Media/Lawnchair#4005]
### Describe the bug

When I try flashing changing recent provider to lawnchair (Debug #368). Lawnchair suddenly crashes and gestures are rendered unuseable until I change the recent provider to default 

### Steps to reproduce

https://github.com/LawnchairLauncher/lawnchair/assets/58597122/68a70ae5-3c4d-4c7c-8e46-2aeeee07ea59

### Expected behavior

Lawnchair is properly set as default recents provider

### Screenshots

As provided in steps to reproduce

### Device information

- Device: POCO F3
- OS: GhostOS [AOSP ROM (Lineage Base)]
- App version: `Debug(#368)` 

### Additional context

```log
Lawnchair (Debug) bug report Jan 24, 2024 11:10:46 AM
version: 14 Dev (#368) (14)
commit: cde8994
build.brand: POCO
build.device: alioth
build.display: UQ1A.240105.004 release-keys
build.fingerprint: POCO/alioth_global/alioth:13/TKQ1.220829.002/V14.0.4.0.TKHMIXM:user/release-keys
build.hardware: qcom
build.id: UQ1A.240105.004
build.manufacturer: Xiaomi
build.model: M2012K11AG
build.security.level: 2024-01-05
build.product: lineage_alioth
build.type: user
version.codename: REL
version.incremental: 1705128613
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: true

error: Uncaught exception

java.lang.SecurityException: Permission Denial: createSearchSession from pid=7829, uid=10727
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at android.app.search.ISearchUiManager$Stub$Proxy.createSearchSession(ISearchUiManager.java:219)
	at android.app.search.SearchSession.<init>(SearchSession.java:110)
	at android.app.search.SearchUiManager.createSearchSession(SearchUiManager.java:54)
	at app.lawnchair.search.LawnchairDeviceSearchAlgorithm$Companion.checkSearchCompatibility$lambda$2(LawnchairDeviceSearchAlgorithm.kt:128)
	at app.lawnchair.search.LawnchairDeviceSearchAlgorithm$Companion.$r8$lambda$Xo_kUeSrgktAFvrDmVpYiu_nWd4(Unknown Source:0)
	at app.lawnchair.search.LawnchairDeviceSearchAlgorithm$Companion$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.searchui.SearchUiManagerService$SearchUiManagerStub.runForUserLocked(SearchUiManagerService.java:173)
	at com.android.server.searchui.SearchUiManagerService$SearchUiManagerStub.createSearchSession(SearchUiManagerService.java:109)
	at android.app.search.ISearchUiManager$Stub.onTransact(ISearchUiManager.java:126)
	at android.os.Binder.execTransactInternal(Binder.java:1358)
	at android.os.Binder.execTransact(Binder.java:1304)


```

**Comment by MrSluffy** [comment]
I send test for you in the please check

**Comment by MrSluffy** [comment]
Please use latest : https://github.com/LawnchairLauncher/lawnchair/actions/runs/7644689784

**Comment by greed-d** [comment]
I tried the latest `Debug #382` with Quickswitch but it shows opening animations but not the closing animations

As suggested I tried replacing default APK in Quickswitch zip for v3.3.0 APK but still shows same behaviour 

https://github.com/LawnchairLauncher/lawnchair/assets/58597122/5be31cac-3c94-4d5b-a191-77c50fc3df54

**Comment by MrSluffy** [comment]
Please use magisk, and I never suggested to replace apk inside anything

**Comment by greeid** [comment]
I tried the latest `Debug #382` with Quickswitch but it shows opening animations but not the closing animations

As suggested I tried replacing default APK in Quickswitch zip for v3.3.0 APK but still shows same behaviour 

Uploading screen-20240125-083043.mp4…

**Comment by greed-d** [comment]
Flashed Magisk and used Quickswitch v3.3.0 but still same thing


https://github.com/LawnchairLauncher/lawnchair/assets/58597122/0ebb2c91-fcae-4fa6-942e-2678d001e0e6

**Comment by MrSluffy** [comment]
Maybe your rom doesn't support the closing transition. It's working fine in most common rom even in oneui and OnePlus working fine. And also your inquiry is not related to the issue

**Comment by greed-d** [comment]
Thanks for the reply 
I'll ask the dev about this :)
