### ISSUE TITLE
[BUG] No interface method startAnimation on A14

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#4016]
### Describe the bug

```
Lawnchair bug report 2024年1月26日 16:27:24
version: 14.0.0 (02a6635) (14000000)
commit: 02a6635
build.brand: motorola
build.device: rtwo
build.display: U1TR34.8-19-11
build.fingerprint: motorola/rtwo_cn/rtwo:14/U1TR34.8-19-11/a7b98-bf32f9:user/release-keys
build.hardware: qcom
build.id: U1TR34.8-19-11
build.manufacturer: motorola
build.model: XT2301-5
build.security.level: 2024-01-01
build.product: rtwo_cn
build.type: user
version.codename: REL
version.incremental: a7b98-bf32f9
version.release: 14
version.sdk_int: 34
display.density_dpi: 446
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method startAnimation(Landroid/os/IBinder;Landroid/window/TransitionInfo;Landroid/view/SurfaceControl$Transaction;Landroid/window/e;)V in class Landroid/window/IRemoteTransition; or its super classes (declaration of 'android.window.IRemoteTransition' appears in /system/framework/framework.jar!classes4.dex)
	at android.window.b.onTransact(Unknown Source:95)
	at android.os.Binder.execTransactInternal(Binder.java:1359)
	at android.os.Binder.execTransact(Binder.java:1284)
```

### Steps to reproduce

1. From Recents to home screen.

### Expected behavior

No crash.

### Device information

- Device: Moto X40
- OS: A14
- App version: 3a8b541580653f07bb79ec4720077a51f4f4e5b1

**Comment by MrSluffy** [comment]
Please don't cut the error log

**Comment by Goooler** [comment]
It's the original format.

**Comment by MrSluffy** [comment]
Can you fix it? I can't reproduce it

**Comment by Goooler** [comment]
That might be related to proguard, I build a release on my fork.

**Comment by MrSluffy** [comment]
Oh I see, try to exclude the android.window** in proguard
