### ISSUE TITLE
[BUG] Split screen/mode crashes when quiting 

### ISSUE THREAD

**Issue by zdrawko420** [Deletescape-Media/Lawnchair#4047]
### Describe the bug

In split screen, going to home screen using navigation bar, lawnchair crashes

### Expected behavior

Normal exiting from split screen to home screen using gesture navigation bar

### Device information

- Device: [Samsung A52s]
- OS: [One UI 6.0]
- App version: [debug 14 dev #447 ]

### Additional context

Lawnchair (Debug) bug report 3 Feb 2024 19:49:00
version: 14 Dev (#447) (14)
commit: 84e0a51
build.brand: samsung
build.device: dm1q
build.display: UP1A.231005.007.S911BXXS3BWL3
build.fingerprint: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXS3BWL3:user/release-keys
build.hardware: qcom
build.id: UP1A.231005.007
build.manufacturer: samsung
build.model: SM-S911B
build.security.level: 2024-01-01
build.product: dm1qxeea
build.type: user
version.codename: REL
version.incremental: S911BXXS3BWL3
version.release: 14
version.sdk_int: 34
display.density_dpi: 354
isRecentsEnabled: true

error: Uncaught exception

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.android.wm.shell.util.GroupedRecentTaskInfo.getTaskInfo1(GroupedRecentTaskInfo.java:99)
	at com.android.quickstep.RecentTasksList.loadTasksInBackground(RecentTasksList.java:321)
	at com.android.quickstep.RecentTasksList.lambda$getTasks$4(RecentTasksList.java:200)
	at com.android.quickstep.RecentTasksList.$r8$lambda$A3npYfaMZbFKQjeQ3vtX6rDyaeI(Unknown Source:0)
	at com.android.quickstep.RecentTasksList$$ExternalSyntheticLambda5.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:185)
	at android.os.Looper.loop(Unknown Source:83)
	at android.os.HandlerThread.run(Unknown Source:28)

**Comment by edent** [comment]
Unable to reproduce on 15.Beta 1.

**Recommendation:** Suggest closing unless it can be reproduced on nightly.
