### ISSUE TITLE
[BUG] Crash when force-stopping APPs

### ISSUE THREAD

**Issue by Goooler** [Deletescape-Media/Lawnchair#4070]
### Describe the bug

```
Lawnchair bug report 2024年2月11日 10:30:52
version: 14.0.0 (15e19dd) (14000000)
commit: 15e19dd
build.brand: motorola
build.device: rtwo
build.display: U1TR34.8-19-11
build.fingerprint: motorola/rtwo_cn/rtwo:14/U1TR34.8-19-11/a7b98-bf32f9:user/release-keys
build.hardware: qcom
build.id: U1TR34.8-19-11
build.manufacturer: motorola
build.model: XT2301-5
build.security.level: 2024-01-01
build.product: rtwo_cn
build.type: user
version.codename: REL
version.incremental: a7b98-bf32f9
version.release: 14
version.sdk_int: 34
display.density_dpi: 446
isRecentsEnabled: true

error: Uncaught exception

java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=17298, uid=10338 requires android.permission.FORCE_STOP_PACKAGES
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
 at android.os.Parcel.createException(Parcel.java:3041)
 at android.os.Parcel.readException(Parcel.java:3024)
 at android.os.Parcel.readException(Parcel.java:2966)
 at android.app.IActivityManager$Stub$Proxy.forceStopPackage(IActivityManager.java:7306)
 at a6.h.onClick(Unknown Source:26)
 at com.android.quickstep.views.c0.onClick(Unknown Source:11)
 at android.view.View.performClick(View.java:7684)
 at android.view.View.performClickInternal(View.java:7661)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:30344)
 at android.os.Handler.handleCallback(Handler.java:1000)
 at android.os.Handler.dispatchMessage(Handler.java:104)
 at android.os.Looper.loopOnce(Looper.java:242)
 at android.os.Looper.loop(Looper.java:362)
 at android.app.ActivityThread.main(ActivityThread.java:8393)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:3963)
 at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:3947)
 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3617)
 at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2824)
 at android.os.Binder.execTransactInternal(Binder.java:1354)
```

### Steps to reproduce

1. Force stop fro Recents.

### Expected behavior

No crashing.

### Device information

- Device: Moto X40
- OS: A14
- App version: 861f4439e4d0f8d15c459b4191b2aedf297cad93

**Comment by MrSluffy** [comment]
You need to reapply lawnchair in quickswitch to generate/grant lawnchair permission. you just updated the app not the module
