### ISSUE TITLE
[BUG] Lawnchair bug report 24.02.2024 15:32:04

### ISSUE THREAD

**Issue by Novus4K** [Deletescape-Media/Lawnchair#4093]
### Describe the bug

After a reboot of the phone the app crash. After that you can restart the app and it works.

### Steps to reproduce

1. Reboot device

### Expected behavior

Dont crash after reboot.

### Device information

- Device: Google Pixel 7
- OS: Calyx OS 5.4.0
- App version: 12.1.0 Alpha 4

### Additional context

Lawnchair bug report 24.02.2024 15:32:04
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: panther
build.display: UQ1A.240205.004.24504000
build.fingerprint: google/panther/panther:14/UQ1A.240205.002/11224170:user/release-keys
build.hardware: pantherbuild.id: UQ1A.240205.004
build.manufacturer: Google
build.model: Pixel 7
build.product: panther
build.type: user
version.codename: REL
version.incremental: 24504000
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke interface method 'org.thoughtcrime.securesms.recipients.LiveRecipientCache org.thoughtcrime.securesms.dependencies.ApplicationDependencies$Provider.provideRecipientCache()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2043)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1689)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1635)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1426)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1416)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1467)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:2)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:4)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:1)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:7)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:5)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by TheRedCyclops** [comment]
I'm getting the same problem on the latest version

**Comment by MrSluffy** [comment]
use latest lawnchair 14
