### ISSUE TITLE
[BUG] Crash when changing the name of an app in the drawer 

### ISSUE THREAD

**Issue by fin-w** [Deletescape-Media/Lawnchair#4100]
### Describe the bug

I use AnySoftKeyboard to enter text. This crash https://katb.in/etuqibexuso happened when I deleted all text from the name of an app in the app drawer, when renaming the app. This is likely caused by a bad interaction between ASK trying to delete all the text, and Lawnchair not being able to handle how ASK deletes text.

ASK can delete all the text in a textbox when a gesture is entered. I think behind the scenes it does something like delete from cursor to beginning of text, then move to the end of the text, and delete text from there to beginning of text. Typically the end result is an empty text box.

Here though, when I enter the gesture to delete the text, Lawnchair crashes entirely and then reopens, and I'm prompted to upload the crash log (above). This is reproducible.

### Steps to reproduce

 Use AnySoftKeyboard as keyboard, set e.g. "swipe left on keyboard" to delete all text.

Open Lawnchair app drawer.

Edit a name of an app: put the cursor in the name textbox, then enter the ASK gesture to delete text

### Expected behavior

Text is deleted.

### Device information

See crash log

**Comment by fin-w** [comment]
Crash log added here in case it gets deleted from the url:
```
Lawnchair bug report 28 Feb 2024 03:52:09
version: 12.1.0 Dev (#1491) (12010005)
commit: ccdb590
build.brand: motorola
build.device: ocean
build.display: lineage_ocean-userdebug 14 UQ1A.240205.004 057ef44b7d
build.fingerprint: motorola/ocean/ocean:10/QPOS30.52-29-12/401fd:user/release-keys
build.hardware: qcom
build.id: UQ1A.240205.004
build.manufacturer: motorola
build.model: moto g(7) power
build.product: lineage_ocean
build.type: userdebug
version.codename: REL
version.incremental: 057ef44b7d
version.release: 14
version.sdk_int: 34
display.density_dpi: 315
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Error while applying EditCommand batch to buffer (length=14, composition=null, selection=TextRange(14, 14)):
   FinishComposingTextCommand()
 > DeleteSurroundingTextCommand(lengthBeforeCursor=2147483647, lengthAfterCursor=2147483647)
	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:117)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand(TextFieldDelegate.kt:143)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.access$onEditCommand(TextFieldDelegate.kt:83)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:203)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:200)
	at androidx.compose.ui.text.input.TextInputServiceAndroid$createInputConnection$1.onEditCommands(TextInputServiceAndroid.android.kt:121)
	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEditInternal(RecordingInputConnection.android.kt:157)
	at androidx.compose.ui.text.input.RecordingInputConnection.endBatchEdit(RecordingInputConnection.android.kt:151)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$endBatchEdit$35(RemoteInputConnectionImpl.java:987)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$geU56Yp8mT2x_QTsHEXbMyQfTHo(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda13.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalArgumentException: end cannot be negative. [start: 14, end: -2147483635]
	at androidx.compose.ui.text.TextRangeKt.packWithCheck(TextRange.kt:124)
	at androidx.compose.ui.text.TextRangeKt.TextRange(TextRange.kt:37)
	at androidx.compose.ui.text.input.EditingBuffer.delete$ui_text_release(EditingBuffer.kt:211)
	at androidx.compose.ui.text.input.DeleteSurroundingTextCommand.applyTo(EditCommand.kt:266)
	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:114)
	... 18 more
```

**Comment by daniel4911** [comment]
Hey, I also noticed that bug

**Comment by Goooler** [comment]
This is outdated, can you try with the build from https://github.com/LawnchairLauncher/lawnchair/actions/runs/8076825758?

**Comment by fin-w** [comment]
In the "market" debug build you linked, the problem doesn't occur, so looks like it's been fixed :+1: Thanks!
