### ISSUE TITLE
[BUG] Crashes after Android 14 March 2024 Update

### ISSUE THREAD

**Issue by Bennett-69** [Deletescape-Media/Lawnchair#4114]
### Describe the bug

Lawnchair (Debug) 14 Dev (#558) crashes repeatedly after updating to Android 14 build AP1A.240305.019.A1 (March 2024). Removing Quickswitch seems to mitigate this.

### Steps to reproduce

1. Install Android 14 March 2024 update
2. Watch Lawnchair start throwing `java.lang.NoSuchMethodError` over and over, even before/without user interaction

### Expected behavior

Lawnchair not crashing

### Device information

- Device: Google Pixel 8 Pro
- OS: stock Android 14 (AP1A.240305.019.A1)
- App version: (Debug) 14 Dev (#558)

### Additional context

Lawnchair (Debug) bug report Mar 7, 2024 10:34:59 PM
version: 14 Dev (#558) (14)
commit: d08b6fb
build.brand: google
build.device: husky
build.display: AP1A.240305.019.A1
build.fingerprint: google/husky/husky:14/AP1A.240305.019.A1/11445699:user/release-keys
build.hardware: husky
build.id: AP1A.240305.019.A1
build.manufacturer: Google
build.model: Pixel 8 Pro
build.security.level: 2024-03-05
build.product: husky
build.type: user
version.codename: REL
version.incremental: 11445699
version.release: 14
version.sdk_int: 34
display.density_dpi: 480
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method destroyInputConsumer(Ljava/lang/String;I)Z in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.systemui.shared.system.InputConsumerController.registerInputConsumer(InputConsumerController.java:142)
	at com.android.quickstep.TouchInteractionService.onUserUnlocked(TouchInteractionService.java:567)
	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda6.run(Unknown Source:2)
	at com.android.launcher3.util.RunnableList.add(RunnableList.java:36)
	at com.android.launcher3.util.LockedUserState.runOnUserUnlocked(LockedUserState.kt:72)
	at com.android.quickstep.TouchInteractionService.onCreate(TouchInteractionService.java:504)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4865)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2365)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by LiventNick** [comment]
I believe its a quickswitch problem.
I had to reset it so I can't use quickswitch anymore. When I try to configure it for Lawnchair afterwards, it says incompatible rom.

**Comment by LiventNick** [comment]
There seems to be a new update to QuickSwitch, check it out
https://github.com/skittles9823/QuickSwitch/releases/tag/4.0.0

**Comment by Bennett-69** [comment]
Yeah, I had tried a 3.3.1 test build (posted in QuickSwitch Support on Telegram) which resolved the overlay creation ("incompatible ROM") issue earlier. But it looks like the new 4.0.0 release has broken things even worse, at least for now. Lots of active chatter on the TG group regarding this new issue in particular:

https://github.com/skittles9823/QuickSwitch/issues/49

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue
