### ISSUE TITLE
[BUG] Adding widgets to homescreen crashes the app

### ISSUE THREAD

**Issue by benjaluth09** [Deletescape-Media/Lawnchair#4131]
### Describe the bug

When placing widgets, Lawnchair crashes.

### Steps to reproduce

1. Go to 'Popup menu'
2. Click on 'Widgets'
3. Add a widget

### Expected behavior

Lawnchair not crashing when adding widgets.

### Device information

- OS: [Android 9]
- App version: [Lawnchair 14-dev #600]

### Additional context

version.release: 9
version.sdk_int: 28
display.density_dpi: 130
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.AppWidgetResizeFrame.showForWidget(Unknown Source:22)
	at com.android.launcher3.Workspace.lambda$getWidgetResizeFrameRunnable$8(Unknown Source:6)
	at com.android.launcher3.Workspace.n(Unknown Source:0)
	at androidx.fragment.app.d.run(Unknown Source:187)
	at com.android.launcher3.anim.AnimatorListeners$RunnableSuccessListener.onAnimationSuccess(Unknown Source:2)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(Unknown Source:4)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
	at android.view.Choreographer.doCallbacks(Choreographer.java:772)
	at android.view.Choreographer.doFrame(Choreographer.java:703)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:947)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.content.res.Resources$NotFoundException: Drawable app.lawnchair:drawable/widget_resize_frame with resource ID #0x7f0803af
Caused by: android.content.res.Resources$NotFoundException: File res/Us.xml from drawable resource ID #0x7f0803af
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
	at android.content.res.Resources.loadDrawable(Resources.java:897)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.widget.ImageView.<init>(ImageView.java:189)
	at android.widget.ImageView.<init>(ImageView.java:172)
	at android.widget.ImageView.<init>(ImageView.java:168)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.android.launcher3.AppWidgetResizeFrame.showForWidget(Unknown Source:22)
	at com.android.launcher3.Workspace.lambda$getWidgetResizeFrameRunnable$8(Unknown Source:6)
	at com.android.launcher3.Workspace.n(Unknown Source:0)
	at androidx.fragment.app.d.run(Unknown Source:187)
	at com.android.launcher3.anim.AnimatorListeners$RunnableSuccessListener.onAnimationSuccess(Unknown Source:2)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(Unknown Source:4)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1294)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
	at android.view.Choreographer.doCallbacks(Choreographer.java:772)
	at android.view.Choreographer.doFrame(Choreographer.java:703)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:947)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 0 to dimension: type=0x3
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:736)
	at android.graphics.drawable.GradientDrawable.updateDrawableCorners(GradientDrawable.java:1477)
	at android.graphics.drawable.GradientDrawable.inflateChildElements(GradientDrawable.java:1435)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:1244)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
	... 43 more

**Comment by benjaluth09** [comment]
When trying to resize the widget, Lawnchair crashes again; making it impossible to resize widgets.

**Comment by MrSluffy** [comment]
Send full logs as file

**Comment by MrSluffy** [comment]
this should be fixed in latest nightly if still persists please reopen this issue

**Comment by skdza** [comment]
> this should be fixed in latest nightly if still persists please reopen this issue

It still persists on Android 16. I'm on a Fairphone 6


Logs:
https://katb.in/desasosalum

**Comment by MrSluffy** [comment]
Please use 16 now
