### ISSUE TITLE
Crash upon opening (SDK 28 , A9)

### ISSUE THREAD

**Issue by matsoki** [Deletescape-Media/Lawnchair#4151]
### Describe the bug

crash on opening the app

### Steps to reproduce

1. install.
2. open
3. crash

### Expected behavior

Launch normally 

### Device information

- OS: [Android 9]
- App version: [14-dev # 630]

### Additional context

Lawnchair (Debug) bug report Mar 24, 2024 16:56:51
version: 14 Dev (#630) (14)
commit: 5677ec6
build.brand: HONOR
build.device: HWCOR
build.display: COR-L29 9.1.0.398(C185E1R1P9)
build.fingerprint: HONOR/COR-L29/HWCOR:9/HUAWEICOR-L29/9.1.0.398C185:user/release-keys
build.hardware: kirin970
build.id: HUAWEICOR-L29
build.manufacturer: HUAWEI
build.model: COR-L29
build.security.level: 2020-07-01
build.product: COR-L29
build.type: user
version.codename: REL
version.incremental: 9.1.0.398C185
version.release: 9
version.sdk_int: 28
display.density_dpi: 272
isRecentsEnabled: false

error: Uncaught exception

java.lang.ExceptionInInitializerError
	at com.android.launcher3.QuickstepTransitionManager.registerRemoteTransitions(QuickstepTransitionManager.java:1159)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:242)
	at app.lawnchair.LawnchairLauncher.setupViews(LawnchairLauncher.kt:301)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:541)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:582)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:223)
	at android.app.Activity.performCreate(Activity.java:7458)
	at android.app.Activity.performCreate(Activity.java:7448)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.IllegalStateException: Unsupported SDK version
	at app.lawnchair.compat.LawnchairQuickstepCompat.<clinit>(LawnchairQuickstepCompat.kt:44)
	... 21 more

**Comment by PianCat** [comment]
Use Old Version pls

**Comment by matsoki** [comment]
> Use Old Version pls

okay

**Comment by matsoki** [comment]
> > Use Old Version pls
> 
> okay

version 593  currently last working version since quickstep changed
