### ISSUE TITLE
[BUG] NullPointerException: Attempt to invoke virtual method 'int android.view.View.getScrollX()' on a null object reference

### ISSUE THREAD

**Issue by jaharkema** [Deletescape-Media/Lawnchair#4154]
### Describe the bug

The app crashed...

Stack trace:
```
Lawnchair bug report Mar 27, 2024 17:27:18
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: Fairphone
build.device: FP5
build.display: FP5.TT46.A.144.20240205
build.fingerprint: Fairphone/FP5/FP5:13/TKQ1.230127.002/TT46:user/release-keys
build.hardware: qcom
[build.id](http://build.id/): TKQ1.230127.002
build.manufacturer: Fairphone
build.model: FP5
build.product: FP5
build.type: user
version.codename: REL
version.incremental: TT46
version.release: 13
version.sdk_int: 33
display.density_dpi: 480
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getScrollX()' on a null object reference
	at com.android.launcher3.Utilities.mapCoordInSelfToDescendant(Utilities.java:2)
	at com.android.launcher3.Workspace.updateIsBeingDraggedOnTouchDown(Workspace.java:7)
	at com.android.launcher3.PagedView.onInterceptTouchEvent(PagedView.java:19)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:13)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:6)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15270)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6657)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5913)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5936)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6101)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5944)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6158)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5917)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5970)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5936)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5944)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5917)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8999)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8950)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8918)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9122)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:268)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

### Steps to reproduce

I only started using the launcher recently. I was playing around with widgets. Not sure what caused the crash.

### Expected behavior

No crashes :sweat_smile: 

### Device information

Included in the stack trace.

**Comment by MrSluffy** [comment]
use latest lawnchair 14
