### ISSUE TITLE
[BUG] Lawnchair crashes while adding widget that supports editing

### ISSUE THREAD

**Issue by abdullateefsherani07** [Deletescape-Media/Lawnchair#4294]
### Describe the bug

When we add a widget that supports editing like Google At a glance it opens the widget type like transparent, semi transparent, solid. When we select any it doesn't add widget and app crashes

### Steps to reproduce

1. Long press home screen
2. Click Widgets
3. Select widget that supports editing like Google At a glance 
4. Select widget type like transparent, semi transparent, solid
5. App crashes and notifies bug

### Expected behavior

I expected it to add widget like Google At a glance which supports editing like transparent, semi transparent and solid. But app crashes while selecting

### Device information

- Device: OnePlus Nord N20 SE
- OS: OxygenOS 14
- App version: 14 beta 1

### Additional context

Lawnchair bug report 16 Apr 2024 12:22:53
version: 14 Beta 2 (15)
commit: ff7f459
build.brand: OnePlus
build.device: OP595BL1
build.display: CPH246922875_14.0.0.310(EX01)
build.fingerprint: OnePlus/CPH2469/OP595BL1:14/TP1A.220905.001/S.162035c_1:user/release-keys
build.hardware: mt6765
build.id: TP1A.220905.001
build.manufacturer: OnePlus
build.model: CPH2469
build.security.level: 2024-02-05
build.product: CPH2469
build.type: user
version.codename: REL
version.incremental: S.162035c_1
version.release: 14
version.sdk_int: 34
display.density_dpi: 360
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.launcher3.CellLayout.getUnusedHorizontalSpace()' on a null object reference
	at com.android.launcher3.Workspace.getFinalPositionForDropAnimation(Unknown Source:165)
	at com.android.launcher3.Workspace.animateWidgetDrop(Unknown Source:32)
	at com.android.launcher3.Launcher.completeTwoStageWidgetDrop(Unknown Source:79)
	at com.android.launcher3.Launcher$3.run(Unknown Source:8)
	at com.android.launcher3.Workspace.removeExtraEmptyScreenDelayed(Unknown Source:55)
	at com.android.launcher3.Workspace.lambda$removeExtraEmptyScreenDelayed$3(Unknown Source:1)
	at com.android.launcher3.Workspace.q(Unknown Source:0)
	at com.android.launcher3.c5.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by dunxd** [comment]
Workaround is to set a different launcher as your default. After doing this, open Lawnchair and you can add the widget succesfully. Then set Lawnchair back as the default Launcher.
