### ISSUE TITLE
[BUG] Crashed on adding Yandex.Weather widget

### ISSUE THREAD

**Issue by vityaman** [Deletescape-Media/Lawnchair#4329]
### Describe the bug

Launcher crashes on attempt to add `Yandex.Weather` widget from widgets menu. Widgets from other providers (for example `Google`) work as expected.

### Steps to reproduce

1. Download [Yandex.Weather](https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin) Android app, version `24.4.3`
2. Go to home screen of `Lawnchair` (where at glance, icons and search bar are located)
3. Long press, then click on `Widgets` button
4. Search for an `Y.Weather` widgets
5. Choice `Y.Weather 2x1` (it crashes on others as well) widget by touching and moving on it
6. On opened Y.Weather screen click on `Create widget` button

### Expected behavior

Expected an `Y.Weather` widget added to `Lawnchair` home screen successfully.

### Device information

- OS: Android 11
- App version: 12.1.0 Alpha 4 from F-Droid

### Additional context

```kotlin
...
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
...
build.hardware: qcom
...
build.type: user
version.codename: REL
...
version.release: 11
version.sdk_int: 30
display.density_dpi: 408
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
 at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
 at com.android.launcher3.Launcher$4.run(Launcher.java:1)
 at com.android.launcher3.Workspace$6.run(Workspace.java:4)
 at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
 at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:562)
 at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
 at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
 at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
 at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
 at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1468)
 at android.view.Choreographer.doCallbacks(Choreographer.java:1267)
 at android.view.Choreographer.doFrame(Choreographer.java:974)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1455)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:254)
 at android.app.ActivityThread.main(ActivityThread.java:8243)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by MrSluffy** [comment]
Please use latest nightly build Thanks close this, fixed : dec3850d2bfb4a2513c22b85ef196755af8414c6
