### ISSUE TITLE
[BUG] Launcher crashes when attempting to change icon style

### ISSUE THREAD

**Issue by NormanOsborn** [Deletescape-Media/Lawnchair#4473]
### Describe the bug

Any time I go tap on 'Icon Style' the launcher crashes. This happens after I've already set an icon pack. 

### Steps to reproduce

1. Go to 'Home Settings'
2. Click on 'General'
3. Scroll down to 'Icon Style'
4. Click on 'Icon Style'
5. Set an icon pack
6. Go back to 'General'
7. Click on 'Icon Style'
8. See error

### Expected behavior

I expect it to take me to the 'Icon Style' section of the launcher settings where I can change app icons. 

### Device information

- Device: Google Pixel 7 Pro
- OS: Android 15 - VanillaIceCream
- App version: version 14 Beta 2

### Additional context

error: Uncaught exception

java.lang.SecurityException: Op READ_MEDIA_IMAGES ignore for package app.lawnchair
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
	at android.os.Parcel.createException(Parcel.java:3226)
	at android.os.Parcel.readException(Parcel.java:3209)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:1043)
	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:829)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:723)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:686)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1046)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1008)
	at p7.x$c$a.invokeSuspend(Unknown Source:12)
	at zb.a.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.e.run(Unknown Source:128)
	at dd.m$a.run(Unknown Source:3)
	at fd.k.run(Unknown Source:2)
	at fd.a.M(Unknown Source:0)
	at fd.a$c.d(Unknown Source:14)
	at fd.a$c.p(Unknown Source:28)
	at fd.a$c.run(Unknown Source:0)
	Suppressed: dd.i: [j2.u1@877dfd9, x0.h@c149d9e, h2{Cancelling}@301707f, m0@91dc84c]
Caused by: android.os.RemoteException: Remote stack trace:
	at android.os.storage.StorageManager.noteAppOpAllowingLegacy(StorageManager.java:1882)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1911)
	at com.android.server.wallpaper.WallpaperManagerService.getWallpaperWithFeature(WallpaperManagerService.java:2207)
	at android.app.IWallpaperManager$Stub.onTransact(IWallpaperManager.java:541)
	at android.os.Binder.execTransactInternal(Binder.java:1500)

**Comment by Digitalbullits** [comment]
I had this issue as well and posted the fix in the bug report at the top. Are you on telegram?

**Comment by MrSluffy** [comment]
done : d20ef2a164f40ab756372ecdc93cfa5583625b93
