### ISSUE TITLE
Extremely high RAM usage (over 1GB)

### ISSUE THREAD

**Issue by MrBurgerCZ** [Deletescape-Media/Lawnchair#4488]
### Describe the bug

My RAM usage by Lawnchair is really high, over 1 GB, the phone can't really multitask much

### Steps to reproduce

Install Lawnchair 14 Beta 2 on LineageOS 20 on Redmi Note 10 Pro (sweet) with QuickSwitch

### Expected behavior

RAM usage is like 100MB max

### Screenshots

![Screenshot_20240617-163038_Settings](https://github.com/LawnchairLauncher/lawnchair/assets/111179823/9f9d0d93-062f-4bea-b89e-7cd57373132a)

### Device information

- Device: [Redmi Note 10 Pro (sweet)]
- OS: [LineageOS Android version 13.0]
- App version: [14 Beta 2]

### Additional context

Root, QuickSwitch

**Comment by pacjo** [comment]
Try nightly. On mine sweet with crDroid 10.4 it uses under 300 mb.

![Screenshot_20240622-114150_Settings](https://github.com/LawnchairLauncher/lawnchair/assets/56438628/6e75eb52-0043-4135-88da-6b345c93a063)

**Comment by MrBurgerCZ** [comment]
It is using 500MB right now, so I guess it's ok

**Comment by Zahrun** [comment]
Mine is using 546 MB right now. I consider this too high. I can see the device slow down compared to other lighter launchers. Can memory optimizations be made?

**Comment by thedayofcondor** [comment]
I just had an out of memory:
```
Lawnchair bug report 29 Nov 2025 14:02:28
version: 15.Dev.(4fd5960) (15000203)
commit: 4fd5960
build.brand: google
build.device: husky
build.display: BP41.250916.015.A1
build.fingerprint: google/husky_beta/husky:16/BP41.250916.015.A1/14394230:user/release-keys
build.hardware: husky
build.id: BP41.250916.015.A1
build.manufacturer: Google
build.model: Pixel 8 Pro
build.security.level: 2025-10-05
build.product: husky_beta
build.type: user
version.codename: REL
version.incremental: 14394230
version.release: 16
version.sdk_int: 36
display.density_dpi: 360
isRecentsEnabled: false

error: Uncaught exception

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2466976 free bytes and 2409KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.graphics.Insets.of(Insets.java:65)
	at android.graphics.Insets.max(Insets.java:118)
	at android.view.WindowInsets.getInsets(WindowInsets.java:259)
	at android.view.WindowInsets.getInsetsIgnoringVisibility(WindowInsets.java:411)
	at android.view.WindowInsets.getSystemWindowInsets(WindowInsets.java:365)
	at android.view.WindowInsets.getSystemWindowInsetsAsRect(WindowInsets.java:346)
	at android.view.View.onApplyWindowInsets(View.java:12876)
	at android.view.View.dispatchApplyWindowInsets(View.java:12937)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.dispatchApplyWindowInsets(Unknown Source:17)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at com.android.launcher3.views.BaseDragLayer.dispatchApplyWindowInsets(Unknown Source:79)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7539)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7521)
	at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:3531)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3127)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10807)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1630)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1639)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1235)
	at android.view.Choreographer.doFrame(Choreographer.java:1164)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1613)
	at android.os.Handler.handleCallback(Handler.java:1070)
	at android.os.Handler.dispatchMessage(Handler.java:125)
	at android.os.Looper.dispatchMessage(Looper.java:333)
	at android.os.Looper.loopOnce(Looper.java:263)
	at android.os.Looper.loop(Looper.java:367)
	at android.app.ActivityThread.main(ActivityThread.java:9287)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
```

**Comment by quantavirile** [comment]
I had a similar issue using the beta version. But installing the nightly version, the ram usage averaged around 300mb. I switched off the accessibility feature which enables the double tap gesture and the app immediately went from being active to cache. It seems the accessibility feature is the cause according to my testing.
