### ISSUE TITLE
Uncought exception deadsystemexception

### ISSUE THREAD

**Issue by c00ldude1oo** [Deletescape-Media/Lawnchair#4552]
Been crashing a few times today.

```
Lawnchair bug report Jul 7, 2024 10:34:54 PM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: google
build.device: oriole
build.display: 2024070201
build.fingerprint: google/oriole/oriole:14/AP2A.240705.004/2024070201:user/release-keys
build.hardware: oriole
build.id: AP2A.240705.004
build.manufacturer: Google
build.model: Pixel 6
build.product: oriole
build.type: user
version.codename: REL
version.incremental: 2024070201
version.release: 14
version.sdk_int: 34
display.density_dpi: 460
isRecentsEnabled: false

error: Uncaught exception

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.content.pm.PackageManager.getApplicationInfoAsUserUncached(PackageManager.java:11407)
	at android.content.pm.PackageManager.-$$Nest$smgetApplicationInfoAsUserUncached(Unknown Source:0)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:11418)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:11415)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.content.pm.PackageManager.getApplicationInfoAsUserCached(PackageManager.java:11432)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:517)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:505)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:499)
	at app.lawnchair.z.a(NotificationManager.kt:2)
	at app.lawnchair.z.b(NotificationManager.kt:3)
	at j6.f.s(NowPlayingProvider.kt:7)
	at j6.f.r(Unknown Source:0)
	at j6.f$b.i(Unknown Source:5)
	at j6.f$b.a(Unknown Source:0)
	at j6.g.accept(Unknown Source:6)
	at j6.d.e(Unknown Source:0)
	at j6.d.a(Unknown Source:0)
	at j6.b.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.DeadSystemException
	... 29 more
```

**Comment by iamtheabdi** [comment]
Try upgrading maybe? Checkout the beta build or one of Gooler's.

**Comment by MrSluffy** [comment]
Please use latest nightly build thanks!
