### ISSUE TITLE
Opening settings crashes the app

### ISSUE THREAD

**Issue by 0xAbdiiii** [Deletescape-Media/Lawnchair#4600]
![Lawnchair bug report Jul 27, 2024 1:33:58 PM.txt](https://github.com/user-attachments/files/16398758/Lawnchair.bug.report.Jul.27.2024.1.33.58.PM.txt)

**Comment by 0xAbdiiii** [comment]
Sorry for not using the bug report template, i used the share option from Lawnchair notification and clicked on create an issue so i didn't get the option to. I can't create a bug report from Android app somehow, it takes me to my browser where I'm not logged in.

**Comment by HarriBuh** [comment]
Same here. Downgrading to the previous nightly solved the issue, so it's definitely a fresh bug.

```

[Device Brand]: Google
[Device Model]: Pixel 7
[Android Version]: 14
[Android API Level]: 34
[Process ID]: 25034
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: app.lawnchair
[Version Name]: 14.0.0 (208cba1)
[Version Code]: 14000000
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-07-27T09:09:26.586
[Stack Trace]:
rd.b: Field 'version' is required for type with serial name 'app.lawnchair.ui.preferences.data.liveinfo.model.LiveInformation', but it was missing at path: $
	at xd.u.H(Unknown Source:342)
	at wd.c.a(Unknown Source:29)
	at com.android.launcher3.responsive.a.invoke(Unknown Source:474)
	at c7.h.emit(Unknown Source:585)
	at ld.x0.m(Unknown Source:133)
	at ld.l.invokeSuspend(Unknown Source:11)
	at mc.a.resumeWith(Unknown Source:8)
	at id.k0.run(Unknown Source:112)
	at id.u0.q0(Unknown Source:144)
	at id.c0.I(Unknown Source:75)
	at ja.i.s(Unknown Source:13)
	at ne.l.v(Unknown Source:20)
	at ja.d.c(Unknown Source:39)
	at f8.k5.invoke(Unknown Source:37)
	at g1.b.d(Unknown Source:45)
	at g1.b.invoke(SourceFile:10)
	at b8.x.invoke(Unknown Source:345)
	at g1.b.invoke(SourceFile:7)
	at ne.d.d(Unknown Source:282)
	at ne.d.f(Unknown Source:196)
	at c8.n0.invoke(Unknown Source:607)
	at g1.b.d(Unknown Source:45)
	at g1.b.invoke(SourceFile:10)
	at c8.q0.invoke(Unknown Source:159)
	at g1.b.d(Unknown Source:45)
	at g1.b.invoke(SourceFile:10)
	at u0.u0.invoke(Unknown Source:1213)
	at g1.b.invoke(SourceFile:7)
	at b0.l0.invoke(Unknown Source:866)
	at g1.b.invoke(SourceFile:7)
	at y0.d.Q(Unknown Source:14)
	at y0.q.p(Unknown Source:202)
	at y0.u.m(Unknown Source:31)
	at y0.c2.a(Unknown Source:34)
	at y0.p.a(Unknown Source:4)
	at y0.u.a(Unknown Source:10)
	at i2.j0.i(Unknown Source:133)
	at i2.e0.o0(Unknown Source:165)
	at u0.u0.invoke(Unknown Source:1001)
	at i2.g0.a(Unknown Source:89)
	at k2.t.L(Unknown Source:38)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:55)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.l0.L(Unknown Source:100)
	at e0.s.a(Unknown Source:69)
	at k2.t.L(Unknown Source:38)
	at s1.t0.c(Unknown Source:0)
	at k2.y.L(Unknown Source:14)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:55)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.l0.L(Unknown Source:100)
	at x.m.a(Unknown Source:23)
	at k2.t.L(Unknown Source:38)
	at x.f0.c(Unknown Source:102)
	at k2.y.L(Unknown Source:14)
	at s1.n.c(Unknown Source:0)
	at k2.y.L(Unknown Source:14)
	at e0.p1.invoke(Unknown Source:44)
	at i2.a0.c(Unknown Source:7)
	at k2.y.L(Unknown Source:14)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:55)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.l0.L(Unknown Source:100)
	at x.e.a(Unknown Source:43)
	at k2.t.L(Unknown Source:38)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:55)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.l0.L(Unknown Source:100)
	at e0.s.a(Unknown Source:69)
	at k2.t.L(Unknown Source:38)
	at s1.t0.c(Unknown Source:0)
	at k2.y.L(Unknown Source:14)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:55)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.l0.L(Unknown Source:100)
	at i2.g1.a(Unknown Source:38)
	at k2.t.L(Unknown Source:38)
	at a3.r.invoke(Unknown Source:143)
	at j1.r.f(Unknown Source:113)
	at j1.t.a(Unknown Source:51)
	at j1.u.d(Unknown Source:139)
	at k2.v0.j(Unknown Source:4)
	at k2.l0.G0(Unknown Source:112)
	at k2.f0.U(Unknown Source:17)
	at k2.r0.g(Unknown Source:2)
	at k2.r0.v(Unknown Source:26)
	at k2.r0.r(Unknown Source:71)
	at l2.v.onMeasure(Unknown Source:80)
	at android.view.View.measure(View.java:27866)
	at l2.a.h(Unknown Source:63)
	at l2.a.onMeasure(Unknown Source:3)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7028)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7028)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7028)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7028)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7028)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:768)
	at android.view.View.measure(View.java:27866)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3012)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3333)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: rd.b: Field 'version' is required for type with serial name 'app.lawnchair.ui.preferences.data.liveinfo.model.LiveInformation', but it was missing
	at vd.u0.h(Unknown Source:112)
	at e8.f.<init>(SourceFile:3)
	at e8.d.a(Unknown Source:63)
	at xd.u.H(Unknown Source:284)
	... 150 more
```

**Comment by SuperDragonXD** [comment]
What build are you using? It doesn't seem to be a github actions/nightly build, but rather a custom one.

Can you reproduce this in the latest nightly build (in 14-dev)?

**Comment by HarriBuh** [comment]
Ah right, it's Goooler's own fork. It's very much the same as the official nightly, but with a test signature.

**Comment by HarriBuh** [comment]
@iamtheabdi is using the official nightly, I guess. His description of his bug is identical to mine anyway.

**Comment by 0xAbdiiii** [comment]
> What build are you using? It doesn't seem to be a github actions/nightly build, but rather a custom one.

Yeah I'm using Gooler's build. I'll try the official nightly to see if the crash still occurs.

**Comment by 0xAbdiiii** [comment]
> Can you reproduce this in the latest nightly build (in 14-dev)?

Okay so the crash doesn't happen in Lawnchair.Debug.14-dev.Nightly-CI_1118-291f716.

Should i make a bug report in @Goooler's repo?

**Comment by HarriBuh** [comment]
@iamtheabdi He doesn't allow bug reports in his repo 🤷🏼‍♂️

**Comment by 0xAbdiiii** [comment]
> @iamtheabdi He doesn't allow bug reports in his repo 🤷🏼‍♂️

Yeah i just saw a while ago lol

**Comment by HarriBuh** [comment]
@Goooler 📌

**Comment by HarriBuh** [comment]
https://github.com/Goooler/LawnchairRelease/releases/tag/14.0.0-20240727

**Comment by 0xAbdiiii** [comment]
The new build fixed it!
