### ISSUE TITLE
[BUG] crash on Lenovo tablet when opening settings 

### ISSUE THREAD

**Issue by Plazzmex** [Deletescape-Media/Lawnchair#4602]
### Describe the bug

The launcher crashes with an error when trying to open the launcher home settings. Logs attached.

### Steps to reproduce

1. 'long press homescreen'
2. Click on 'home settings'
3. Crash

### Expected behavior

Open launcher settings 

### Device information

- Device: Lenovo tab P11 pro (Lenovo tb-j706f)
- OS: android 11 
- App version: both 14 beta 2 and the latest nightly Lawnchair.Debug.14-dev.Nightly-CI_1125-90ecc23

### Additional context

Lawnchair bug report 28 jul. 2024 y. 19:20:22
version: 14 Beta 2 (15)
commit: ff7f459
build.brand: Lenovo
build.device: J706F
build.display: TB-J706F_S630601_230828_ROW
build.fingerprint: Lenovo/LenovoTB-J706F/J706F:11/RKQ1.210518.002/S630601_230828_ROW:user/release-keys
build.hardware: qcom
build.id: RKQ1.210518.002
build.manufacturer: LENOVO
build.model: Lenovo TB-J706F
build.security.level: 2023-08-05
build.product: LenovoTB-J706F
build.type: user
version.codename: REL
version.incremental: TB-J706F_USR_S630601_2308281216_Q00067_ROW
version.release: 11
version.sdk_int: 30
display.density_dpi: 320
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to stop activity {app.lawnchair/app.lawnchair.LawnchairLauncher}: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4907)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4878)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4952)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2380)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:789)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:257)
	at com.android.launcher3.widget.LauncherWidgetHolder.stopListening(Unknown Source:59)
	at com.android.launcher3.widget.LauncherWidgetHolder.setShouldListenFlag(Unknown Source:40)
	at com.android.launcher3.widget.LauncherWidgetHolder.setActivityStarted(Unknown Source:1)
	at com.android.launcher3.Launcher.onStop(Unknown Source:25)
	at app.lawnchair.LawnchairLauncher.onStop(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1477)
	at android.app.Activity.performStop(Activity.java:8331)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4899)
	... 12 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids(AppWidgetServiceImpl.java:4172)
	at com.android.server.appwidget.AppWidgetServiceImpl.stopListening(AppWidgetServiceImpl.java:910)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:311)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by MrSluffy** [comment]
This is fixed in nightly build, can you try and check latest [nightly](https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.14-dev.Nightly-CI_1134-d12e46e.apk) build

**Comment by Plazzmex** [comment]
> This is fixed in nightly build, can you try and check latest [nightly](https://github.com/LawnchairLauncher/lawnchair/releases/download/nightly/Lawnchair.Debug.14-dev.Nightly-CI_1134-d12e46e.apk) build

Latest nightly it's even worse. Now it crashes instantly when switching to the launcher.
[Lawnchair (Debug) bug report 31 jul. 2024 y. 172830.txt](https://github.com/user-attachments/files/16444902/Lawnchair.Debug.bug.report.31.jul.2024.y.172830.txt)

**Comment by MrSluffy** [comment]
this should be fixed in latest 15-dev nightly if still persists reopen this issue
