### ISSUE TITLE
[BUG] Crashes on tablet modes (240-280 DPI)

### ISSUE THREAD

**Issue by unihorn78** [Deletescape-Media/Lawnchair#4640]
### Describe the bug

Subj. Crashes on tablet modes (240-280 DPI).

It works on smartphone modes (350 DPI and above).

### Steps to reproduce

Crashes on tablet modes (240-280 DPI).

### Expected behavior

The original Lawnchair (not a fork) is working fine.

### Device information

Ugoos UT8

### Additional context

Lawnchair bug report 9 авг. 2024 г. 03:35:08
version: 14.0.0 (3092a3d) (14000000)
commit: 3092a3d
build.brand: UGOOS
build.device: UT8
build.display: UT8-userdebug 11 RQ3A.210705.001 eng.ugoos.20240508.164859 release-keys
build.fingerprint: Droidlogic/franklin/franklin:11/RQ3A.210705.001/eng.ugoos.20240508.164859:userdebug/release-keys
build.hardware: rk30board
build.id: RQ3A.210705.001
build.manufacturer: UGOOS
build.model: UT8
build.security.level: 2021-07-05
build.product: UT8
build.type: userdebug
version.codename: REL
version.incremental: eng.ugoos.20240508.164859
version.release: 11
version.sdk_int: 30
display.density_dpi: 240
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair/app.lawnchair.LawnchairLauncher}: android.view.InflateException: Binary XML file line #79 in app.lawnchair:layout/launcher: Binary XML file line #25 in app.lawnchair:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #79 in app.lawnchair:layout/launcher: Binary XML file line #25 in app.lawnchair:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
Caused by: android.view.InflateException: Binary XML file line #25 in app.lawnchair:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(Unknown Source:5)
	at com.android.launcher3.Launcher.setupViews(Unknown Source:9)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(Unknown Source:0)
	at com.android.launcher3.Launcher.onCreate(Unknown Source:205)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(Unknown Source:0)
	at app.lawnchair.LawnchairLauncher.onCreate(Unknown Source:14)
	at android.app.Activity.performCreate(Activity.java:8008)
	at android.app.Activity.performCreate(Activity.java:7992)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f060413
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getColor(Resources.java:1059)
	at android.content.Context.getColor(Context.java:677)
	at com.android.launcher3.util.Themes.getNavBarScrimColor(Unknown Source:13)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.<init>(SourceFile:25)
	at com.android.launcher3.allapps.LauncherAllAppsContainerView.<init>(SourceFile:3)
	at com.android.launcher3.allapps.LauncherAllAppsContainerView.<init>(SourceFile:2)
	at app.lawnchair.allapps.views.SearchContainerView.<init>(Unknown Source:0)
	... 33 more

**Comment by unihorn78** [comment]
I apologize. I was inattentive and posted it the wrong way. This is for a fork. Everything is fine with you and it works fine.
