### ISSUE TITLE
[BUG] Crash when trying to move item using TalkBack action

### ISSUE THREAD

**Issue by clay-rip** [Deletescape-Media/Lawnchair#4786]
### Describe the bug

If you try to move a widget using TalkBack actions, Lawnchair crashes.

### Steps to reproduce

1. Hover over a widget
2. With TalkBack enabled, press with 3 fingers to open the actions menu
3. Double-tap the first item in the list, "Actions"
4. Double-tap on "Move item"
5. Move your finger to the widget, which is in the incorrect position
6. Tap with 3 fingers at once
7. Double-tap "Actions"
8. Move your finger to "Move item" and double-tap, and Lawnchair will crash

### Expected behavior

Lawnchair should give an option to move the widget instead of crashing.

### Screenshots

https://github.com/user-attachments/assets/f76a5486-ebd2-475a-ba1f-6b6aa6757e0a

### Device information

- Device: Samsung Galaxy A15 (6GB memory, 128gb storage)
- OS: stock ROM Android 14.0
- App version: 14 Beta 3

**Comment by clay-rip** [comment]
```
Lawnchair bug report Sep 9, 2024 10:16:11 p.m.
version: 14.Beta 3 (14000203)
commit: 6f4a812
build.brand: samsung
build.device: a15
build.display: UP1A.231005.007.A155MUBS3BXF1
build.fingerprint: samsung/a15ub/a15:14/UP1A.231005.007/A155MUBS3BXF1:user/release-keys
build.hardware: mt6789
build.id: UP1A.231005.007
build.manufacturer: samsung
build.model: SM-A155M
build.security.level: 2024-07-01
build.product: a15ub
build.type: user
version.codename: REL
version.incremental: A155MUBS3BXF1
version.release: 14
version.sdk_int: 34
display.density_dpi: 450
isRecentsEnabled: false

error: Uncaught exception

java.lang.ClassCastException: com.android.launcher3.dragndrop.DragLayer cannot be cast to com.android.launcher3.CellLayout
	at com.android.launcher3.Workspace.onDragStart(Unknown Source:43)
	at com.android.launcher3.dragndrop.DragController.callOnDragStart(Unknown Source:97)
	at com.android.launcher3.dragndrop.LauncherDragController.startDrag(Unknown Source:333)
	at com.android.launcher3.dragndrop.DragController.startDrag(SourceFile:2)
	at com.android.launcher3.Workspace.beginDragShared(SourceFile:44)
	at com.android.launcher3.Workspace.beginDragShared(SourceFile:3)
	at com.android.launcher3.Workspace.startDrag(Unknown Source:27)
	at com.android.launcher3.touch.ItemLongClickListener.beginDrag(Unknown Source:46)
	at com.android.launcher3.accessibility.LauncherAccessibilityDelegate.beginAccessibleDrag(Unknown Source:126)
	at com.android.launcher3.accessibility.LauncherAccessibilityDelegate.performAction(Unknown Source:47)
	at com.android.launcher3.QuickstepAccessibilityDelegate.performAction(Unknown Source:25)
	at com.android.launcher3.accessibility.BaseAccessibilityDelegate.performAccessibilityAction(Unknown Source:15)
	at android.view.View.performAccessibilityAction(View.java:15620)
	at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:902)
	at android.view.AccessibilityInteractionController.-$$Nest$mperformAccessibilityActionUiThread(Unknown Source:0)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

**Comment by ROBlNET13** [comment]
does this happen on mobile devices
