### ISSUE TITLE
Changing Number of Dock Icons Clears Homescreen

### ISSUE THREAD

**Issue by Hamster45105** [Deletescape-Media/Lawnchair#4809]
### Describe the bug

When adjusting the number of icons in the dock, Lawnchair crashes and removes all apps from the home screen.

### Steps to reproduce

1. Go to the dock settings
2. Increase/decrease the number of dock icons
3. Go back to homescreen

### Expected behavior

Changing the number of dock icons should just change the number of dock icons, instead of clearing the whole home screen.

### Device information

- Device: Samsung Galaxy A54
- OS: One UI 6.1
- App version: 14 Beta 3

### Additional context

```
error: Uncaught exception

android.database.sqlite.SQLiteException: table favorites_tmp has 19 columns but 21 values were supplied (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO favorites_tmp SELECT * FROM from_db.favorites
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1540)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:975)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2652)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2574)
	at com.android.launcher3.provider.LauncherDbUtils.copyTable(Unknown Source:79)
	at com.android.launcher3.model.GridSizeMigrationUtil.migrateGridIfNeeded(Unknown Source:36)
	at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(Unknown Source:109)
	at com.android.launcher3.model.ModelDbController.tryMigrateDB(Unknown Source:0)
	at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(Unknown Source:36)
	at com.android.launcher3.model.LoaderTask.loadWorkspace(Unknown Source:5)
	at com.android.launcher3.model.LoaderTask.run(Unknown Source:40)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by bbeus88** [comment]
This exact same thing happened to me. With the exact error message. 

Once it happens there's no easy way to get your home screen back. I had to fully uninstall and reinstall.

Device information

    Device: Pixel 7 Pro
    OS: Android 14 Stock
    App version: 14 Beta 3

**Comment by Noxis73** [comment]
Same happend to me right now. Re-arrange the icons is annoying but not the point. Losing all my website shortcuts is really bad, because i can't recall all the urls i've had. 😭
