### ISSUE TITLE
[BUG] Random SQL exceptions

### ISSUE THREAD

**Issue by codenyte** [Deletescape-Media/Lawnchair#4860]
### Describe the bug

Lawnchair crashes and I get a notification with the crash log

### Steps to reproduce

I don't really know what this is related to, it just appears to happen randomly

### Expected behavior

No Lawnchair crash and SQL exceptions I guess

### Screenshots

Not screenshots, but crash logs:

This occurred twice in the last 10 minutes

<details><summary>Log</summary>
<p>

```
Lawnchair bug report Sep 27, 2024 11:18:04 PM
version: 14.Beta 3 (14000203)
commit: 6f4a812
build.brand: google
build.device: bluejay
build.display: 2024091900
build.fingerprint: google/bluejay/bluejay:14/AP2A.240905.003.F1/2024091900:user/release-keys
build.hardware: bluejay
build.id: AP2A.240905.003.F1
build.manufacturer: Google
build.model: Pixel 6a
build.security.level: 2024-09-05
build.product: bluejay
build.type: user
version.codename: REL
version.incremental: 2024091900
version.release: 14
version.sdk_int: 34
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

android.database.sqlite.SQLiteException: table favorites has 19 columns but 21 values were supplied (code 1 SQLITE_ERROR): , while compiling: INSERT INTO favorites SELECT * FROM from_db.favorites
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1562)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1098)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1126)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:686)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:614)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2201)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2121)
	at com.android.launcher3.provider.LauncherDbUtils.copyTable(Unknown Source:79)
	at com.android.launcher3.graphics.PreviewSurfaceRenderer.loadModelData(Unknown Source:60)
	at com.android.launcher3.graphics.PreviewSurfaceRenderer.c(Unknown Source:0)
	at com.android.launcher3.graphics.w.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

</p>
</details> 

### Device information

- Device: Pixel 6a
- OS: Android 14 ([GrapheneOS 2024091900](https://grapheneos.org/releases#2024091900))
- App version: 14.Beta 3

### Additional context
My app-specific hardening settings for Lawnchair in GrapheneOS are as follows:
I have [hardened_malloc](https://github.com/grapheneos/hardened_malloc) enabled, ptrace disabled, WebView JIT enabled, DCL via memory disabled and DCL via storage enabled. The issue doesn't appear to be DCL-related though, as GrapheneOS would notify me in that case.

**Comment by MrSluffy** [comment]
please reopen if still persists in latest nightly
