### ISSUE TITLE
Enable wallpaper blur immediately crashes lawnchair on S24U

### ISSUE THREAD

**Issue by RicketyPumpkin** [Deletescape-Media/Lawnchair#4885]
### Describe the bug

**error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Error inflating class <unknown>

Lawnchair (Debug) bug report Oct 11, 2024 3:36:37 AM
version: 14.Dev.(#1492) (14000203)
commit: 524824e
build.brand: samsung
build.device: e3q
build.display: UP1A.231005.007.S928USQS3AXHG
build.fingerprint: samsung/e3qsqw/e3q:14/UP1A.231005.007/S928USQS3AXHG:user/release-keys
build.hardware: qcom
build.id: UP1A.231005.007
build.manufacturer: samsung
build.model: SM-S928U
build.security.level: 2024-09-01
build.product: e3qsqw
build.type: user
version.codename: REL
version.incremental: S928USQS3AXHG
version.release: 14
version.sdk_int: 34
display.density_dpi: 450
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4172)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4330)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6614)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6463)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:68)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6546)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2703)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #45 in app.lawnchair.debug:layout/launcher: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:882)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1154)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1366)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:227)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:541)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:582)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:113)
	at android.app.Activity.performCreate(Activity.java:9001)
	at android.app.Activity.performCreate(Activity.java:8970)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4154)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4330)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6614)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6463)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:68)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6546)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2703)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.SecurityException: Permission android.permission.READ_EXTERNAL_STORAGE denied for package app.lawnchair.debug
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:2344)
	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:1195)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:1058)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:996)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:979)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1651)
	at android.app.WallpaperManager.getDrawable(WallpaperManager.java:1610)
	at com.android.launcher3.Workspace.<init>(Workspace.java:352)
	at com.android.launcher3.Workspace.<init>(Workspace.java:321)
	... 39 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1889)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1866)
	at android.os.storage.StorageManager.checkPermissionAndAppOp(StorageManager.java:1933)
	at android.os.storage.StorageManager.checkExternalStoragePermissionAndAppOp(StorageManager.java:2001)
	at android.os.storage.StorageManager.checkPermissionReadImages(StorageManager.java:1978)

### Steps to reproduce

1. Go to lawnchair settings 
2. Click on "experimental settings" 
3. Scroll down to 'enable wallpaper blur'
4. Immediate crash of Lawnchair 

### Expected behavior

For the wallpaper to blur

### Device information

Lawnchair (Debug) bug report Oct 11, 2024 3:36:37 AM
version: 14.Dev.(#1492) (14000203)
commit: 524824e
build.brand: samsung
build.device: e3q
build.display: UP1A.231005.007.S928USQS3AXHG
build.fingerprint: samsung/e3qsqw/e3q:14/UP1A.231005.007/S928USQS3AXHG:user/release-keys
build.hardware: qcom
build.id: UP1A.231005.007
build.manufacturer: samsung
build.model: SM-S928U
build.security.level: 2024-09-01
build.product: e3qsqw
build.type: user
version.codename: REL
version.incremental: S928USQS3AXHG
version.release: 14
version.sdk_int: 34
display.density_dpi: 450
isRecentsEnabled: false

### Additional context

Sorry this is my first bug report, I apologize if I put the crash log in the wrong spot.

**Comment by hope0016** [comment]
Happens to Pixel 4 too, I made the phone unusable, I had to clear Lawnchair storage and open it afresh (and never touched the option again). Also they can make it not blurry all the time but only on background of recent apps switch interface

**Comment by RicketyPumpkin** [comment]
@hope0016 That is rough. My phone at least will switch my default home back to OneUI home after the crash so It doesn't really impact me, I just switch back to lawnchair from there and the option is off again. It crashes before the option can even turn on which is why I don't have to clear any app data.
Can I ask where you found the option to blur your recent apps panel? I can't seem to find it. Thanks

**Comment by hope0016** [comment]
I was just thinking they should make it that way, not blurring the entire wallpaper all the time, just behind recent apps section
