### ISSUE TITLE
[BUG] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by mengxiabing** [Deletescape-Media/Lawnchair#4914]
### Describe the bug

FATAL EXCEPTION: launcher-loader (Ask Gemini)
                                                                                                    Process: app.lawnchair.play.debug, PID: 24653
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1396)
                                                                                                    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
                                                                                                    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
                                                                                                    	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
                                                                                                    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
                                                                                                    	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
                                                                                                    	at com.android.launcher3.folder.FolderNameProvider.getSuggestedFolderName(FolderNameProvider.java:127)
                                                                                                    	at com.android.launcher3.folder.Folder.lambda$updateItemLocationsInDatabaseBatch$6(Folder.java:1145)
                                                                                                    	at com.android.launcher3.folder.Folder.$r8$lambda$XIoliuD9dg0oLELAfjVFFkCuQoo(Unknown Source:0)
                                                                                                    	at com.android.launcher3.folder.Folder$$ExternalSyntheticLambda10.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:259)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

### Expected behavior

FATAL EXCEPTION: launcher-loader (Ask Gemini)
                                                                                                    Process: app.lawnchair.play.debug, PID: 24653
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1396)
                                                                                                    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
                                                                                                    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
                                                                                                    	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
                                                                                                    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
                                                                                                    	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
                                                                                                    	at com.android.launcher3.folder.FolderNameProvider.getSuggestedFolderName(FolderNameProvider.java:127)
                                                                                                    	at com.android.launcher3.folder.Folder.lambda$updateItemLocationsInDatabaseBatch$6(Folder.java:1145)
                                                                                                    	at com.android.launcher3.folder.Folder.$r8$lambda$XIoliuD9dg0oLELAfjVFFkCuQoo(Unknown Source:0)
                                                                                                    	at com.android.launcher3.folder.Folder$$ExternalSyntheticLambda10.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:259)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

### Screenshots

![879df2b24ba0ff6b7b4cc09a171290dc](https://github.com/user-attachments/assets/836683ee-bd78-4b6b-a330-c3160fe6d918)

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by MrSluffy** [comment]
closes due to `15-dev` is active
