### ISSUE TITLE
[BUG] Lawnchair crashes as soon as opened on Lenovo K11 Enhanced tablet running android 14

### ISSUE THREAD

**Issue by Supernoww** [Deletescape-Media/Lawnchair#4915]
### Describe the bug

When I launch the current latest version 14 beta 3, the app sometimes shows me my apps for a few seconds then immediately crashes.

### Steps to reproduce

1. Open Lawnchair
2. Watch it crash

### Expected behavior

I expected the launcher to work as normal, and not to crash.

### Device information

- Device: Lenovo Tab K11 Enhanced
- OS: Android 14 with Lenovo ZUI home
- App version: 14.0.0-beta3

### Additional context

Lawnchair bug report Oct 18, 2024 19:37:03
version: 14.Beta 3 (14000203)
commit: 6f4a812
build.brand: Lenovo
build.device: TB330FUP
build.display: TB330FUP_ROW_OPEN_USER_V15.155_U_ZUI_16.0.033_ST_240731
build.fingerprint: Lenovo/TB330FUP_EEA/TB330FUP:14/UP1A.231005.007/S2001068_240731_ROW:user/release-keys
build.hardware: mt8786
build.id: UP1A.231005.007
build.manufacturer: LENOVO
build.model: TB330FUP
build.security.level: 2024-07-05
build.product: TB330FUP_EEA
build.type: user
version.codename: REL
version.incremental: TB330FUP_ROW_OPEN_USER_V15.155_U_ZUI_16.0.033_ST_240731
version.release: 14
version.sdk_int: 34
display.density_dpi: 240
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.mediahome.launcheroverlay.client.PeekyTab com.zui.launcher.Launcher.getPeekyTab()' on a null object reference
	at com.android.systemui.plugins.OHaNaCallbacks.initClient(Unknown Source:32)
	at com.android.systemui.plugins.LauncherCallbacksCompat.onActivityCreated(Unknown Source:28)
	at com.android.systemui.plugins.LauncherOverlayPluginImpl.createOverlayManager(Unknown Source:69)
	at com.android.launcher3.Launcher.lambda$onPluginConnected$1(Unknown Source:0)
	at com.android.launcher3.Launcher.v(Unknown Source:0)
	at com.android.launcher3.e1.get(Unknown Source:4)
	at com.android.launcher3.Launcher.switchOverlay(Unknown Source:7)
	at com.android.launcher3.Launcher.onPluginConnected(SourceFile:2)
	at com.android.launcher3.Launcher.onPluginConnected(SourceFile:1)
	at com.android.systemui.plugins.PluginListener.onPluginLoaded(Unknown Source:0)
	at com.android.systemui.shared.plugins.PluginInstance.loadPlugin(Unknown Source:64)
	at com.android.systemui.shared.plugins.PluginInstance.onCreate(Unknown Source:30)
	at com.android.systemui.shared.plugins.PluginActionManager.onPluginConnected(Unknown Source:5)
	at com.android.systemui.shared.plugins.PluginActionManager.lambda$handleQueryPlugins$6(Unknown Source:0)
	at com.android.systemui.shared.plugins.PluginActionManager.a(Unknown Source:0)
	at com.android.systemui.shared.plugins.e.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:295)
	at android.app.ActivityThread.main(ActivityThread.java:8733)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)

**Comment by Supernoww** [comment]
I've also tried with the nightly release by the way, and it also just crashes.

**Comment by MrSluffy** [comment]
closes due to `15-dev` is active

**Comment by Supernoww** [comment]
Excuse me, where can I get this dev build?

**Comment by 0xAbdiiii** [comment]
> Excuse me, where can I get this dev build?



[releases page](https://github.com/lawnchairlauncher/lawnchair/releases)

download the latest nightly build.
