### ISSUE TITLE
Lawnchair crashes on opening recents from app

### ISSUE THREAD

**Issue by MixSens** [Deletescape-Media/Lawnchair#4925]
### Describe the bug

When i'm in an app and press the recents button, lawnchair crashes and returns back to home screen

### Steps to reproduce

1. Open any app
2. Click recents button
3. Lawnchair crashes and shows logs

### Expected behavior

Recents menu opens

### Device information

- Device: Nothing phone (1) 
- OS: NothingOS 2.6
- App version:  Nightly
btw, I'm using quickswitch for recents provider

### Additional context

error: Uncaught exception

java.lang.AbstractMethodError: abstract method "void android.view.IRecentsAnimationRunner.onAnimationStartWithSurfaceTransaction(android.view.IRecentsAnimationController, android.window.TransitionInfo, android.view.SurfaceControl$Transaction, android.view.RemoteAnimationTarget[], android.view.RemoteAnimationTarget[], android.graphics.Rect, android.graphics.Rect)"
	at android.view.IRecentsAnimationRunner$Stub.onTransact(IRecentsAnimationRunner.java:205)
	at android.os.Binder.execTransactInternal(Binder.java:1347)
	at android.os.Binder.execTransact(Binder.java:1283)

**Comment by MixSens** [comment]
ps: the app info page is showing quickswitch overlay app size as 0B

**Comment by MixSens** [comment]
quick update: it seems to somehow be related to the calling of `irecentsanimationrunner` interface
