### ISSUE TITLE
[BUG] Crashing lastest build

### ISSUE THREAD

**Issue by matthew777777** [Deletescape-Media/Lawnchair#4950]
### Describe the bug

Crashing

### Expected behavior

Working

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

### Additional context

https://katb.in/unoriyuzifo

**Comment by matthew777777** [comment]
Lawnchair (Debug) bug report Oct 30, 2024 10:41:06 AM
version: 14.Dev.(#1551) (14000203)
commit: f07c2b2
build.brand: HUAWEI
build.device: HWBAH3-H
build.display: BAH3-W59 2.0.0.272(C432E1R1P1)
build.fingerprint: HUAWEI/BAH3-W59NM/HWBAH3-H:10/HUAWEIBAH3-W59/102.0.0.272C432:user/release-keys
build.hardware: kirin820
build.id: HUAWEIBAH3-W59
build.manufacturer: HUAWEI
build.model: BAH3-W59
build.security.level: 2020-11-01
build.product: BAH3-W59NM
build.type: user
version.codename: REL
version.incremental: 102.0.0.272C432
version.release: 10
version.sdk_int: 29
display.density_dpi: 272
isRecentsEnabled: false

error: Uncaught exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: android.view.InflateException: Binary XML file line #79 in app.lawnchair.debug:layout/launcher: Binary XML file line #25 in app.lawnchair.debug:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: android.view.InflateException: Binary XML file line #79 in app.lawnchair.debug:layout/launcher: Binary XML file line #25 in app.lawnchair.debug:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
Caused by: android.view.InflateException: Binary XML file line #25 in app.lawnchair.debug:layout/all_apps: Error inflating class app.lawnchair.allapps.views.SearchContainerView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:864)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1243)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at com.android.internal.policy.HwPhoneLayoutInflater.inflate(HwPhoneLayoutInflater.java:138)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1366)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:227)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:541)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:582)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:124)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f060413
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:416)
	at android.content.res.Resources.getColor(Resources.java:1070)
	at android.content.Context.getColor(Context.java:671)
	at com.android.launcher3.util.Themes.getNavBarScrimColor(Themes.java:241)
	at com.android.launcher3.allapps.ActivityAllAppsContainerView.<init>(ActivityAllAppsContainerView.java:224)
	at com.android.launcher3.allapps.LauncherAllAppsContainerView.<init>(LauncherAllAppsContainerView.java:41)
	at com.android.launcher3.allapps.LauncherAllAppsContainerView.<init>(LauncherAllAppsContainerView.java:37)
	at app.lawnchair.allapps.views.SearchContainerView.<init>(SearchContainerView.kt:9)
	... 34 more

**Comment by MrSluffy** [comment]
please try using latest `15-dev` closes this since `15-dev` is active
