### ISSUE TITLE
[BUG] Lawnchair crashes in `15-dev` branch

### ISSUE THREAD

**Issue by CoelacanthusHex** [Deletescape-Media/Lawnchair#4965]
### Describe the bug

backtrace
```
java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setResumed(QuickstepLauncher.java:993)
	at com.android.launcher3.BaseActivity.onResume(BaseActivity.java:226)
	at com.android.launcher3.statemanager.StatefulActivity.onResume(StatefulActivity.java:163)
	at com.android.launcher3.Launcher.onResume(Launcher.java:1323)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onResume(QuickstepLauncher.java:783)
	at app.lawnchair.LawnchairLauncher.onResume(LawnchairLauncher.kt:327)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
	at android.app.Activity.performResume(Activity.java:9118)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:331)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

Downgrade to version before https://github.com/LawnchairLauncher/lawnchair/commit/54fe46d75d94c05b819f5fc0276d805985659a20, the issue disappeared.

### Steps to reproduce

1. Install new lawnchair.
2. Lawnchair crashed.

### Expected behavior

Works normally.

### Device information

- Device: Redmi K40
- OS: Lineage OS 21 (Android 14)
- App version: 15.Dev.(#1575)

**Comment by iamtheabdi** [comment]
crashes instantly on Android 12

**Comment by rabywastaken** [comment]
Crashes on Paranoid Android 14 on POCO X3 NFC as well:

FATAL EXCEPTION: launcher-loader
Process: app.lawnchair.debug, PID: 15135
java.lang.SecurityException: app.lawnchair.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5748)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.android.launcher3.util.SimpleBroadcastReceiver.register(SimpleBroadcastReceiver.java:46)
	at com.android.launcher3.pm.UserCache.initAsync(UserCache.java:103)
	at com.android.launcher3.pm.UserCache.$r8$lambda$h1vhpjwUmiqKWj2nlsBvGYoKghE(Unknown Source:0)
	at com.android.launcher3.pm.UserCache$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14125)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2603)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2792)
	at android.os.Binder.execTransactInternal(Binder.java:1358)
	at android.os.Binder.execTransact(Binder.java:1304)

**Comment by XeonDead** [comment]
15-dev has some issues here too:
`11-06 08:20:50.042   393   446 E AndroidRuntime: FATAL EXCEPTION: launcher-loader
11-06 08:20:50.042   393   446 E AndroidRuntime: Process: app.lawnchair.debug, PID: 393
11-06 08:20:50.042   393   446 E AndroidRuntime: java.lang.SecurityException: app.lawnchair.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:3041)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:3024)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2966)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6085)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.launcher3.util.SimpleBroadcastReceiver.register(SimpleBroadcastReceiver.java:46)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.launcher3.pm.UserCache.initAsync(UserCache.java:103)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.launcher3.pm.UserCache.$r8$lambda$h1vhpjwUmiqKWj2nlsBvGYoKghE(Unknown Source:0)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.launcher3.pm.UserCache$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:1000)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:242)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:362)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:85)
11-06 08:20:50.042   393   446 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14350)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2829)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2824)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1354)
11-06 08:20:50.042   393   446 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:1284)`

**Comment by CoelacanthusHex** [comment]
The issue still exists at the latest commit (https://github.com/LawnchairLauncher/lawnchair/commit/a195be84e360c44306588f4eb45dc82e99b9204f).

**Comment by iamtheabdi** [comment]
> The issue still exists at the latest commit (https://github.com/LawnchairLauncher/lawnchair/commit/a195be84e360c44306588f4eb45dc82e99b9204f).

because it wasn't a fix.

**Comment by pr0927** [comment]
Anyone have a link for the prior nightly? Can't launch without crashing, don't have an .apk for previous nightly. 🙃

**Comment by 0xAbdiiii** [comment]
@pr0927 you can download it from Github actions. this was the last working nightly.


https://github.com/LawnchairLauncher/lawnchair/actions/runs/11646926034

**Comment by nowster** [comment]
> Anyone have a link for the prior nightly? Can't launch without crashing, don't have an .apk for previous nightly. 🙃

It didn't help me. I couldn't install the older .apk without a complete uninstall and reinstall (with loss of configuration). Restoring backups didn't restore widgets.

**Comment by CoelacanthusHex** [comment]
`enableDesktopWindowingWallpaperActivity()` [seems to be there](https://github.com/search?q=repo%3ALawnchairLauncher%2Flawnchair%20enableDesktopWindowingWallpaperActivity&type=code). Will it be some kind of misoptimization?

**Comment by DoYouKnowMyNamePlz** [comment]
Is nobody testing these updates before adding?

**Comment by CoelacanthusHex** [comment]
> Is nobody testing these updates before adding?

They may only test it on Android 15.

**Comment by SuperDragonXD** [comment]
> Is nobody testing these updates before adding?

All nightly builds have an inherent risk of crashing, since these builds are published in the `15-dev` development branch.

Also, we are working on a fix to some of the major crashes. I'd recommend using Lawnchair 14 Beta 3 for a more stable experience, or older nightly builds if you wish to use newer features.

**Comment by HarriBuh** [comment]
Same Here.

Pixel 7
Android 15

**Comment by juman-y** [comment]
I got this on GrapheneOS.
<details>

```
type: crash
osVersion: google/caiman/caiman:15/AP3A.241105.008/2024110700:user/release-keys
flags: dev options enabled
package: app.lawnchair:15000000, targetSdk 35
process: app.lawnchair
processUptime: 134 + 211 ms
installer: dev.imranr.obtainium.fdroid

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair/app.lawnchair.LawnchairLauncher}: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4061)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4248)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3255)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7038)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:586)
	at android.app.PendingIntent.getActivity(PendingIntent.java:567)
	at com.android.quickstep.SystemUiProxy.<init>(Unknown Source:82)
	at com.android.quickstep.SystemUiProxy.i(Unknown Source:2)
	at com.android.launcher3.touch.g.get(Unknown Source:26)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(Unknown Source:2)
	at com.android.launcher3.util.MainThreadInitializedObject.c(Unknown Source:0)
	at a8.p0.get(Unknown Source:26)
	at com.android.launcher3.util.TraceHelper.allowIpcs(SourceFile:7)
	at com.android.launcher3.util.MainThreadInitializedObject.get(Unknown Source:37)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onDeviceProfileInitiated(Unknown Source:5)
	at com.android.launcher3.Launcher.initDeviceProfile(Unknown Source:30)
	at com.android.launcher3.uioverrides.QuickstepLauncher.initDeviceProfile(Unknown Source:0)
	at com.android.launcher3.Launcher.onCreate(Unknown Source:176)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(Unknown Source:18)
	at app.lawnchair.LawnchairLauncher.onCreate(Unknown Source:33)
	at android.app.Activity.performCreate(Activity.java:9055)
	at android.app.Activity.performCreate(Activity.java:9033)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4043)
	... 15 more
```

</details>

**Comment by ToughDBlue** [comment]
> > Also, we are working on a fix to some of the major crashes. I'd recommend using Lawnchair 14 Beta 3 for a more stable experience, or older nightly builds if you wish to use newer features.

Where can I find apks for older nightly builds?

**Comment by 0xAbdiiii** [comment]
> > > Also, we are working on a fix to some of the major crashes. I'd recommend using Lawnchair 14 Beta 3 for a more stable experience, or older nightly builds if you wish to use newer features.
> 
> Where can I find apks for older nightly builds?
> 
> 

Github actions.

**Comment by pr0927** [comment]
Maybe a stupid question, but is there any chance a new nightly is going to be released soon that fixes the crashing? I ask because I had a lot of shortcuts and widgets painstakingly placed, and I'm currently just temporarily using Neo Launcher (what I had been using before Lawnchair) in the hopes a nightly would be released and patch things up.

If not, I'll set it all up again on a previous build, just don't want to cross that bridge if I can wait it out a bit (it's a bit silly how many apps I have in folders and whatnot....).

**Comment by nowster** [comment]
> > Is nobody testing these updates before adding?
> 
> They may only test it on Android 15.

It's broken on Android 15 too, so that's not a factor. (Pixel 7a here.)

**Comment by SuperDragonXD** [comment]
> Maybe a stupid question, but is there any chance a new nightly is going to be released soon that fixes the crashing?

There will be one soon, but [we can't really give an ETA regarding new fixes or launcher builds](https://lawnchair.app/faq/#when-is-the-next-eta).

I would also *not* recommend using Nightly builds as your main launcher [due to the inherent risks development builds have](https://lawnchair.app/faq/#what-are-these-debug-or-development-versions) (also stated in the warning of Lawnchair Settings). If you do plan on using them, make backups before upgrading to newer Nightly builds.

**Comment by ToughDBlue** [comment]
> > Where can I find apks for older nightly builds?
> 
> Github actions.

Github actions?? Is that somewhere on the Lawnchair Github page?

**Comment by atuy1219** [comment]
I've downloaded the latest debug build from GitHubAction, but it still crashes.
Android 15 Pixel 6a
<details>

```
FATAL EXCEPTION: main
Process: app.lawnchair.debug, PID: 25991
java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4161)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4348)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:222)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2739)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
Caused by: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3235)
	at android.os.Parcel.createException(Parcel.java:3215)
	at android.os.Parcel.readException(Parcel.java:3198)
	at android.os.Parcel.readException(Parcel.java:3140)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7004)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:579)
	at android.app.PendingIntent.getActivity(PendingIntent.java:560)
	at com.android.quickstep.SystemUiProxy.<init>(SystemUiProxy.java:197)
	at com.android.quickstep.SystemUiProxy.$r8$lambda$1jbizU9-15TXKEVnBlsEVuW8Kkk(Unknown Source:2)
	at com.android.quickstep.SystemUiProxy$$ExternalSyntheticLambda0.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$icoSB2GSttV1yd5beTvcp2Ed9FU(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda1.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:97)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:60)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onDeviceProfileInitiated(QuickstepLauncher.java:1360)
	at com.android.launcher3.Launcher.initDeviceProfile(Launcher.java:819)
	at com.android.launcher3.uioverrides.QuickstepLauncher.initDeviceProfile(QuickstepLauncher.java:696)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:527)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:678)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:125)
	at android.app.Activity.performCreate(Activity.java:9019)
	at android.app.Activity.performCreate(Activity.java:8997)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4143)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.PendingIntentController.getIntentSender(PendingIntentController.java:145)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5542)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5435)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3464)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2696)
```

</details>

**Comment by CoelacanthusHex** [comment]
The issue still exists on https://github.com/LawnchairLauncher/lawnchair/commit/630d885fcaf5ad1b0e02a438ffb34a5d323cc3e3
The backtrace is same as https://github.com/LawnchairLauncher/lawnchair/issues/4965#issue-2635922977

**Comment by HarriBuh** [comment]
![Screenshot_20241123-074856.png](https://github.com/user-attachments/assets/13230f6b-fe4f-4eb8-b1ed-3d45c6ac08ef)

Sounds to good and easy to be true. Any volunteers? 😅

**Comment by richiesamlie** [comment]
> ![Screenshot_20241123-074856.png](https://private-user-images.githubusercontent.com/123186113/389179115-13230f6b-fe4f-4eb8-b1ed-3d45c6ac08ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNDY3MDcsIm5iZiI6MTczMjM0NjQwNywicGF0aCI6Ii8xMjMxODYxMTMvMzg5MTc5MTE1LTEzMjMwZjZiLWZlNGYtNGViOC1iMWVkLTNkNDVjNmFjMDhlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QwNzIwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjcwYjlkM2VkMTc3MjFiZDU5ZWU0NDMzOTJjNDQxMmZmY2Q1NGZkNTQxMjVjZTIyOGY0MTM2ZjhlNzg5YTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.N5ZLjxPsP2BkeUOA2_fVKQqJzf2wqu4Q0HTWhg-xJ9g)
> 
> Sounds to good and easy to be true. Any volunteers? 😅

Its fixed up. Tried on a15. No more crash

**Comment by atuy1219** [comment]
In my environment (Android 15), it's fixed! Thank you very much

**Comment by mario-g98** [comment]
**Still crashing on Android 14** with latest [dbf2b9a](https://github.com/LawnchairLauncher/lawnchair/commit/dbf2b9a26595fbd00f2d6057593e8a46616ca228).

```
java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
    at com.android.launcher3.uioverrides.QuickstepLauncher.setResumed(QuickstepLauncher.java:1002)
    at com.android.launcher3.BaseActivity.onResume(BaseActivity.java:226)
    at com.android.launcher3.statemanager.StatefulActivity.onResume(StatefulActivity.java:163)
    at com.android.launcher3.Launcher.onResume(Launcher.java:1327)
    at com.android.launcher3.uioverrides.QuickstepLauncher.onResume(QuickstepLauncher.java:790)
    at app.lawnchair.LawnchairLauncher.onResume(LawnchairLauncher.kt:327)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
    at android.app.Activity.performResume(Activity.java:9118)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
    at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8592)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by MrSluffy** [comment]
> **Still crashing on Android 14** with latest [dbf2b9a](https://github.com/LawnchairLauncher/lawnchair/commit/dbf2b9a26595fbd00f2d6057593e8a46616ca228).
> 
> ```
> java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
>     at com.android.launcher3.uioverrides.QuickstepLauncher.setResumed(QuickstepLauncher.java:1002)
>     at com.android.launcher3.BaseActivity.onResume(BaseActivity.java:226)
>     at com.android.launcher3.statemanager.StatefulActivity.onResume(StatefulActivity.java:163)
>     at com.android.launcher3.Launcher.onResume(Launcher.java:1327)
>     at com.android.launcher3.uioverrides.QuickstepLauncher.onResume(QuickstepLauncher.java:790)
>     at app.lawnchair.LawnchairLauncher.onResume(LawnchairLauncher.kt:327)
>     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
>     at android.app.Activity.performResume(Activity.java:9118)
>     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
>     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
>     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
>     at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
>     at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
>     at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
>     at android.os.Handler.dispatchMessage(Handler.java:107)
>     at android.os.Looper.loopOnce(Looper.java:232)
>     at android.os.Looper.loop(Looper.java:317)
>     at android.app.ActivityThread.main(ActivityThread.java:8592)
>     at java.lang.reflect.Method.invoke(Native Method)
>     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
> ```

Please create new issue for this crashes

**Comment by CoelacanthusHex** [comment]
> > **Still crashing on Android 14** with latest [dbf2b9a](https://github.com/LawnchairLauncher/lawnchair/commit/dbf2b9a26595fbd00f2d6057593e8a46616ca228).
> > ```
> > java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
> >     at com.android.launcher3.uioverrides.QuickstepLauncher.setResumed(QuickstepLauncher.java:1002)
> >     at com.android.launcher3.BaseActivity.onResume(BaseActivity.java:226)
> >     at com.android.launcher3.statemanager.StatefulActivity.onResume(StatefulActivity.java:163)
> >     at com.android.launcher3.Launcher.onResume(Launcher.java:1327)
> >     at com.android.launcher3.uioverrides.QuickstepLauncher.onResume(QuickstepLauncher.java:790)
> >     at app.lawnchair.LawnchairLauncher.onResume(LawnchairLauncher.kt:327)
> >     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
> >     at android.app.Activity.performResume(Activity.java:9118)
> >     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5234)
> >     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5277)
> >     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
> >     at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
> >     at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
> >     at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
> >     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
> >     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
> >     at android.os.Handler.dispatchMessage(Handler.java:107)
> >     at android.os.Looper.loopOnce(Looper.java:232)
> >     at android.os.Looper.loop(Looper.java:317)
> >     at android.app.ActivityThread.main(ActivityThread.java:8592)
> >     at java.lang.reflect.Method.invoke(Native Method)
> >     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> >     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
> > ```
> 
> Please create new issue for this crashes

No. This issue is about this crash. I opened this issue for the same backtrace, but it was closed wrong with https://github.com/LawnchairLauncher/lawnchair/pull/4978

**Comment by CoelacanthusHex** [comment]
This crash was fixed by https://github.com/LawnchairLauncher/lawnchair/commit/2b6e0defc076cd5c2d458df7c2d12275e6295cb9, but I meet a new issue, see https://github.com/LawnchairLauncher/lawnchair/issues/5018

**Comment by HarriBuh** [comment]
Can more ppl using Android 15 confirm it's running flawlessly now?

**Comment by AndrewDallas** [comment]
> Can more ppl use Android 15 confirm it's running flawlessly now?

Its not at all. It opens now but a lot of things are not working properly.

**Comment by colemickens** [comment]
> @pr0927 you can download it from Github actions. this was the last working nightly.
> 
> [LawnchairLauncher/lawnchair/actions/runs/11646926034](https://github.com/LawnchairLauncher/lawnchair/actions/runs/11646926034)

So, after logging in, downloading the zip, there are two different apks inside. Which would would correspond with what gets published as the nightly releases?

EDIT:
looking at the success job:

```
Run mv "./Debug APK/lawnWithQuickstepGithub/debug/"*.apk "./$APK_NAME"
```
so, I guess that's my answer.

EDIT2: or maybe it's not, it refuses to install on the device where I already had it installed.

**Comment by colemickens** [comment]
cool, there's downgrade protection, so now I can't downgrade to backup my settings.

**Comment by mario-g98** [comment]
Latest debug version ([#1714](https://github.com/LawnchairLauncher/lawnchair/actions/runs/12191411096)) works fine on Android 14.

**Comment by HyperKiko** [comment]
i think i'm also getting this issue on lineageos 22 fajita. works fine without quickswitch, but when i set it as recents provider it crashes
