### ISSUE TITLE
[BUG] crash on latest dev-15

### ISSUE THREAD

**Issue by M4TH1EU** [Deletescape-Media/Lawnchair#4984]
### Describe the bug

after installing the app, it doesn't open an crashes immediately

### Steps to reproduce

1. Download and install[ latest 15-dev workflow build ](https://github.com/LawnchairLauncher/lawnchair/actions/runs/11734267106)
2. Try to start the app

### Expected behavior

start successfully

### Device information

- Device: Xiaomi 13 Pro
- OS: android 15 - crDroid BETA 11 
- App version: 80f5d7e (15-dev)

### Additional context

```java
4598 characters, 58 lines
12345678910111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758
time: 1731140125324
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.am.PendingIntentController.getIntentSender(PendingIntentController.java:145)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5647)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5540)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3485)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2820)

stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.lawnchair.debug/app.lawnchair.LawnchairLauncher}: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.IllegalArgumentException: pendingIntentBackgroundActivityStartMode must not be set when creating a PendingIntent
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
	at android.os.Parcel.createException(Parcel.java:3226)
	at android.os.Parcel.readException(Parcel.java:3209)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7051)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:579)
	at android.app.PendingIntent.getActivity(PendingIntent.java:560)
	at com.android.quickstep.SystemUiProxy.<init>(SystemUiProxy.java:197)
	at com.android.quickstep.SystemUiProxy.$r8$lambda$1jbizU9-15TXKEVnBlsEVuW8Kkk(Unknown Source:2)
	at com.android.quickstep.SystemUiProxy$$ExternalSyntheticLambda0.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$icoSB2GSttV1yd5beTvcp2Ed9FU(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda1.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:92)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:60)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onDeviceProfileInitiated(QuickstepLauncher.java:1356)
	at com.android.launcher3.Launcher.initDeviceProfile(Launcher.java:819)
	at com.android.launcher3.uioverrides.QuickstepLauncher.initDeviceProfile(QuickstepLauncher.java:694)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:527)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:676)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:125)
	at android.app.Activity.performCreate(Activity.java:9002)
	at android.app.Activity.performCreate(Activity.java:8980)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1530)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.PendingIntentController.getIntentSender(PendingIntentController.java:145)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5647)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5540)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3485)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2820)
``

**Comment by SuperDragonXD** [comment]
Closing this issue to centralize discussion on #4965. You may re-post the crash log as a comment in there.
