### ISSUE TITLE
[BUG] cant customize icons in work profile 

### ISSUE THREAD

**Issue by sid314** [Deletescape-Media/Lawnchair#4989]
### Describe the bug

Customizing icons in work profile does nothing 

### Steps to reproduce

1. Go to work apps drawer
2. Change icon of some app
3. It doesn't do anything 

### Expected behavior

Icon should change

### Device information

- Device: [oneplus 7t]
- OS: [lineageos]
- App version: [every version of lawnchair 14]

**Comment by sid314** [comment]
There is another issue that I saw where  someone had crash trying to customize icons in work profile. For me I have experienced no crashes but it simply does nothing

**Comment by Alonely0** [comment]
I can reproduce consistent crashes with the following log on 14 beta 3:
<details>
```txt

Lawnchair bug report 10 Nov 2024 20:21:24
version: 14.Beta 3 (14000203)
commit: 6f4a812
build.brand: google
build.device: bluejay
build.display: 2024110700
build.fingerprint: google/bluejay/bluejay:15/AP3A.241105.007/2024110700:user/release-keys
build.hardware: bluejay
build.id: AP3A.241105.007
build.manufacturer: Google
build.model: Pixel 6a
build.security.level: 2024-11-05
build.product: bluejay
build.type: user
version.codename: REL
version.incremental: 2024110700
version.release: 15
version.sdk_int: 35
display.density_dpi: 397
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.pm.LauncherActivityInfo.getLabel()' on a null object reference
	at m8.h6.d(Unknown Source:78)
	at n8.a$p.a(Unknown Source:58)
	at n8.a$p.c(Unknown Source:12)
	at j1.b.d(Unknown Source:44)
	at j1.b.c(Unknown Source:8)
	at p5.m$k$a.a(Unknown Source:57)
	at p5.m$k$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.a(Unknown Source:30)
	at l1.e.d(Unknown Source:174)
	at p5.j.b(Unknown Source:139)
	at p5.j.c(Unknown Source:0)
	at p5.j$a.a(Unknown Source:36)
	at p5.j$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at p5.j.a(Unknown Source:129)
	at p5.m$k.a(Unknown Source:84)
	at p5.m$k.c(Unknown Source:12)
	at j1.b.d(Unknown Source:44)
	at j1.b.c(Unknown Source:8)
	at androidx.compose.animation.a$c$d.a(Unknown Source:165)
	at androidx.compose.animation.a$c$d.invoke(Unknown Source:10)
	at j1.b.b(Unknown Source:44)
	at j1.b.invoke(SourceFile:2)
	at y.e.a(Unknown Source:876)
	at androidx.compose.animation.a$c.a(Unknown Source:317)
	at androidx.compose.animation.a$c.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at androidx.compose.animation.a.a(Unknown Source:887)
	at p5.m.b(Unknown Source:1211)
	at p5.m.a(Unknown Source:612)
	at n8.n.l(Unknown Source:338)
	at c8.n$d$a$a$a.a(Unknown Source:27)
	at c8.n$d$a$a$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at c8.n.j(Unknown Source:173)
	at c8.n.p(Unknown Source:0)
	at c8.n$d$a$a.a(Unknown Source:46)
	at c8.n$d$a$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at c8.n$d$a.a(Unknown Source:86)
	at c8.n$d$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at x0.f2$b.a(Unknown Source:212)
	at x0.f2$b.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at x0.f2.a(Unknown Source:177)
	at c8.n$d.a(Unknown Source:90)
	at c8.n$d.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at c8.n$e$a.a(Unknown Source:23)
	at c8.n$e$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at q8.w$a.b(Unknown Source:28)
	at q8.w$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.a(Unknown Source:30)
	at q8.w.j(Unknown Source:278)
	at c8.n$e.a(Unknown Source:34)
	at c8.n$e.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at r8.o0$a.a(Unknown Source:23)
	at r8.o0$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.a(Unknown Source:30)
	at r8.o0.f(Unknown Source:74)
	at c8.n.n(Unknown Source:55)
	at c8.n.l(Unknown Source:395)
	at app.lawnchair.ui.preferences.PreferenceActivity$b$a.a(Unknown Source:29)
	at app.lawnchair.ui.preferences.PreferenceActivity$b$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.a(Unknown Source:30)
	at x0.q2.a(Unknown Source:89)
	at x0.p0$b.a(Unknown Source:40)
	at x0.p0$b.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at x0.p0.a(Unknown Source:289)
	at p8.g.f(Unknown Source:132)
	at app.lawnchair.ui.preferences.PreferenceActivity$b.a(Unknown Source:42)
	at app.lawnchair.ui.preferences.PreferenceActivity$b.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at o2.q0.a(Unknown Source:82)
	at o2.a$a.a(Unknown Source:34)
	at o2.a$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at o2.r0.a(Unknown Source:310)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$i.a(Unknown Source:38)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$i.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.b(Unknown Source:30)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.a(Unknown Source:356)
	at androidx.compose.ui.platform.k$a$a$c.a(Unknown Source:40)
	at androidx.compose.ui.platform.k$a$a$c.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.x.a(Unknown Source:30)
	at androidx.compose.ui.platform.k$a$a.a(Unknown Source:221)
	at androidx.compose.ui.platform.k$a$a.invoke(Unknown Source:8)
	at j1.b.a(Unknown Source:44)
	at j1.b.invoke(SourceFile:1)
	at b1.c.d(Unknown Source:17)
	at b1.n.r0(Unknown Source:236)
	at b1.n.k0(Unknown Source:13)
	at b1.t.v(Unknown Source:15)
	at b1.n2.a(Unknown Source:24)
	at b1.t.B(Unknown Source:15)
	at b1.t.z(Unknown Source:0)
	at androidx.compose.ui.platform.k$a.a(Unknown Source:77)
	at androidx.compose.ui.platform.k$a.invoke(Unknown Source:2)
	at androidx.compose.ui.platform.g.J1(Unknown Source:6)
	at androidx.compose.ui.platform.k.z(Unknown Source:7)
	at androidx.compose.ui.platform.k.s(Unknown Source:18)
	at androidx.lifecycle.l$b.a(Unknown Source:24)
	at androidx.lifecycle.l.c(Unknown Source:105)
	at androidx.compose.ui.platform.k$a.a(Unknown Source:38)
	at androidx.compose.ui.platform.k$a.invoke(Unknown Source:2)
	at androidx.compose.ui.platform.g.onAttachedToWindow(Unknown Source:119)
	at android.view.View.dispatchAttachedToWindow(View.java:22868)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3443)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
</details>

**Comment by TheRedCyclops** [comment]
On the latest nightly it seems like it does nothing but lawnchair is actually crashing (if you do it enough times the message actually appears) it seems like this is the same issue as the one you mentioned just that the crashing previously may have been more visible

**Comment by SuperDragonXD** [comment]
Closing this issue to centralize discussion in #4988.
