### ISSUE TITLE
[BUG] nightly crash on android 15

### ISSUE THREAD

**Issue by mmarca-tech** [Deletescape-Media/Lawnchair#4990]
### Describe the bug

When opening lawnchair it does not open nor react

### Steps to reproduce

1. Install Lawnchair
2. Click on lawnchair icon

### Expected behavior

Lawnchair should start

### Screenshots

https://github.com/user-attachments/assets/61931ec6-b149-4eff-937c-08c6c89a2dd0

### Device information

- Device: Google Pixel 6 pro
- OS: graphene os
- App version: nightly

### Additional context

Crash logs 

```
type: crash
osVersion: google/raven/raven:15/AP3A.241105.007/2024110700:user/release-keys
package: app.lawnchair.debug:15000000, targetSdk 35
process: app.lawnchair.debug
processUptime: 635 + 87 ms
installer: com.android.packageinstaller

java.lang.NoSuchMethodError: No virtual method setEnableOnBackInvokedCallback(Z)V in class Landroid/content/pm/ApplicationInfo; or its super classes (declaration of 'android.content.pm.ApplicationInfo' appears in /system/framework/framework.jar)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:669)
	at app.lawnchair.LawnchairLauncher.onCreate(LawnchairLauncher.kt:125)
	at android.app.Activity.performCreate(Activity.java:9055)
	at android.app.Activity.performCreate(Activity.java:9033)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4043)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4248)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:902)
```

**Comment by mirsella** [comment]
Same crash log with latest nightly tag, but on android 14 with a custom rom too (evolution x)

edit: tried with the latest commit CI action debug apk and i get another crash. should i open another issue ?
```
msg: java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
stacktrace: java.lang.NoSuchMethodError: No static method enableDesktopWindowingWallpaperActivity()Z in class Lcom/android/window/flags/Flags; or its super classes (declaration of 'com.android.window.flags.Flags' appears in /system/framework/framework.jar!classes5.dex)
```

**Comment by DoYouKnowMyNamePlz** [comment]
Seems to be crashing no matter the os version.

**Comment by SuperDragonXD** [comment]
We will centralize `15-dev` crashes on #4965 for now, so closing this issue.
