### ISSUE TITLE
[BUG] Lawnchair 14.Dev.(d7e3f32) crashes with Uncaught exception

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#5007]
### Describe the bug

The app crashes from time to time with a NullPointerException when I return to Lawnchair from the recents screen.
Crash Report - https://katb.in/vibibevugid

### Steps to reproduce

1. Go to another app.
2. Click on 'recents' nav button
3. Exit 'home'
4. Lawnchair crashes with java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.launcher3.ShortcutAndWidgetContainer com.android.launcher3.CellLayout.getShortcutsAndWidgets()' on a null object reference
5. The Default Launcher is reset and "Select a Default Home App" appears

### Expected behavior

It shouldn't crash.

### Screenshots

Not Applicable

### Device information

- Device: **Xiaomi Redmi 5 (rosy)**
- OS: **Stock ROM** **Android version 8.1** (*MIUI 11*)
- App version: **14.Dev.(d7e3f32) -> (Google Play)**

### Additional context

https://katb.in/vibibevugid
[Lawnchair bug report Nov 18, 2024 2:04:29 AM](https://katb.in/)
version: 14.Dev.(d7e3f32) (14000205)
commit: d7e3f32
build.brand: Xiaomi
build.device: rosy
build.display: CUSTOMER_VERSION_rosy
build.fingerprint: Xiaomi/rosy/rosy:8.1.0/OPM1.171019.026/V11.0.2.0.ODAMIXM:user/release-keys
build.hardware: qcom
build.id: OPM1.171019.026
build.manufacturer: Xiaomi
build.model: Redmi 5
build.security.level: 2019-12-01
build.product: rosy
build.type: user
version.codename: REL
version.incremental: V11.0.2.0.ODAMIXM
version.release: 8.1.0
version.sdk_int: 27
display.density_dpi: 320
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.launcher3.ShortcutAndWidgetContainer com.android.launcher3.CellLayout.getShortcutsAndWidgets()' on a null object reference
	at com.android.launcher3.Workspace.isEventOverQsb(Unknown Source:8)
	at com.android.launcher3.Workspace.updateIsBeingDraggedOnTouchDown(Unknown Source:100)
	at com.android.launcher3.PagedView.onInterceptTouchEvent(Unknown Source:93)
	at com.android.launcher3.Workspace.onInterceptTouchEvent(Unknown Source:8)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(Unknown Source:64)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(Unknown Source:8)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:451)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3375)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Unknown Source:32)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:413)
	at android.view.View.dispatchPointerEvent(View.java:12030)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4695)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4377)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4434)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6793)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6765)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6726)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6901)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:254)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:331)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by MrSluffy** [comment]
closes due to `15-dev` is active
