### ISSUE TITLE
[CRASH] Lawnchair crashs when i open 

### ISSUE THREAD

**Issue by omerracetr** [Deletescape-Media/Lawnchair#5030]
### Describe the bug

Lawnchair bug report
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: HUAWEI
build.device: HWDUB-Q
build.display: DUB-LX1 8.2.0.170(C185)
build.fingerprint: HUAWEI/DUB-L41/HWDUB-Q:8.1.0/HUAWEIDUB-LX1/170(C185):user/release-keys
build.hardware: qcom
build.id: HUAWEIDUB-LX1
build.manufacturer: HUAWEI
build.model: DUB-LX1
build.product: DUB-L41
build.type: user
version.codename: REL
version.incremental: 170(C185)
version.release: 8.1.0
version.sdk_int: 27
display.density_dpi: 320
isRecentsEnabled: false

error: Uncaught exception

java.lang.SecurityException: read wallpaper: Neither user 10801 nor current process has android.permission.READ_EXTERNAL_STORAGE.
	at android.os.Parcel.readException(Parcel.java:2016)
	at android.os.Parcel.readException(Parcel.java:1962)
	at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:552)
	at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:498)
	at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:435)
	at android.app.WallpaperManager.getBitmapAsUser(WallpaperManager.java:1103)
	at android.app.WallpaperManager.getBitmap(WallpaperManager.java:1092)
	at huawei.android.app.HwWallpaperManager.getBitmap(HwWallpaperManager.java:119)
	at android.app.WallpaperManager.setWallpaperOffsets(WallpaperManager.java:1975)
	at com.android.launcher3.util.WallpaperOffsetInterpolator$OffsetHandler.setOffsetSafely(WallpaperOffsetInterpolator.java:1)
	at com.android.launcher3.util.WallpaperOffsetInterpolator$OffsetHandler.handleMessage(WallpaperOffsetInterpolator.java:21)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:166)
	at android.os.HandlerThread.run(HandlerThread.java:65)

### Steps to reproduce

1. Open lawnchair
2. get crash

### Expected behavior

İ want to open it

### Device information

- Device: [Huawei y7 2019 prime]
- OS: [Emui 8.2.0 Android 8.1.0]
- App version: [12.1.0 Alpha 4]

**Comment by omerracetr** [comment]
I found the solution.Only tick the storage permission
