### ISSUE TITLE
[BUG] Seemingly random crash in nightly

### ISSUE THREAD

**Issue by 88572** [Deletescape-Media/Lawnchair#5055]
### Describe the bug

Last night while I was sleeping, LogFox picked up a crash in Lawnchair. At the time the crash happened, I hadn't unlocked the phone for ~5 hours.

### Steps to reproduce

1. Wait 

### Expected behavior

Shouldn't be crashing in the background 

### Device information

- Device: Google Pixel 8a
- OS: Pixel OS 15
- App version: 15.Dev.(#1708)

### Additional context

```
FATAL EXCEPTION: main

Process: app.lawnchair.debug, PID: 21860
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.launcher3.model.data.ItemInfo.getViewId()' on a null object reference
	at com.android.launcher3.WorkspaceLayoutManager.addInScreen(WorkspaceLayoutManager.java:140)
	at com.android.launcher3.WorkspaceLayoutManager.addInScreenFromBind(WorkspaceLayoutManager.java:65)
	at com.android.launcher3.Launcher.bindInflatedItems(Launcher.java:2375)
	at com.android.launcher3.Launcher.bindInflatedItems(Launcher.java:2333)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$inflateAsyncAndBind$11(BaseLauncherBinder.java:429)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda4.execute(D8$$SyntheticClass:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$13(BaseLauncherBinder.java:451)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$t7RE6I8t79xuZlzs9WoQFPVK6Y4(Unknown Source:0)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
	at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:68)
	at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:56)
	at com.android.launcher3.util.ViewOnDrawExecutor.markCompleted(ViewOnDrawExecutor.java:92)
	at com.android.launcher3.ModelCallbacks$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:68)
	at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:56)
	at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by CoelacanthusHex** [comment]
I meet the same crash backtrace, but I can reproduce it stably by swiping up to call the recents out. See https://github.com/LawnchairLauncher/lawnchair/issues/5047#issuecomment-2551349844

**Comment by guniens** [comment]
Continues to happen in latest nightly

**Comment by 0xAbdiiii** [comment]
hadn't unlocked phone in half an hour.

![Lawnchair bug report Dec 18, 2024 8_16_32 PM.txt](https://github.com/user-attachments/files/18225256/Lawnchair.bug.report.Dec.18.2024.8_16_32.PM.txt)
