### ISSUE TITLE
[A10] Lawnchair crashes when started

### ISSUE THREAD

**Issue by NekoMimiOfficial** [Deletescape-Media/Lawnchair#5063]
### Describe the bug

Fresh install of lawnchair 15, does not launch

### Steps to reproduce

1. Install latest version on A10
2. Start it
3. Notice crash

### Expected behavior

Starts and works as intended

### Device information

- Device: Samsung j6 (j6lte)
- OS: android 10 oneui 2.0
- App version: gooler fork 20241207 (and all version since LC15)

### Additional context

Lawnchair bug report Dec 7, 2024 8:21:01 PM
version: 15.0.0 (f337f0b) (15000000)
commit: f337f0b
build.brand: samsung
build.device: j6lte
build.display: QP1A.190711.020.J600FXXUACVK3
build.fingerprint: samsung/j6ltecis/j6lte:10/QP1A.190711.020/J600FXXUACVK3:user/release-keys
build.hardware: samsungexynos7870
build.id: QP1A.190711.020
build.manufacturer: samsung
build.model: SM-J600F
build.security.level: 2022-02-01
build.product: j6ltecis
build.type: user
version.codename: REL
version.incremental: J600FXXUACVK3
version.release: 10
version.sdk_int: 29
display.density_dpi: 280
isRecentsEnabled: false

error: Uncaught exception

java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at com.android.app.viewcapture.g.a(Unknown Source:0)
	at com.android.launcher3.provider.RestoreDbTask.existingDbs(Unknown Source:17)
	at com.android.launcher3.provider.RestoreDbTask.restoreIfNeeded(Unknown Source:54)
	at com.android.launcher3.model.ModelDbController.createDbIfNotExists(Unknown Source:14)
	at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(Unknown Source:0)
	at com.android.launcher3.model.ModelDbController.tryMigrateDB(Unknown Source:0)
	at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(Unknown Source:31)
	at com.android.launcher3.model.LoaderTask.loadWorkspace(Unknown Source:5)
	at com.android.launcher3.model.LoaderTask.run(Unknown Source:85)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by MrSluffy** [comment]
this is not lawnchair debug and it fixed in latest `15-dev` 1b59c20031dca6d57dd2e3aaa1c172e6314187de
