### ISSUE TITLE
[BUG] App not start on Api 28

### ISSUE THREAD

**Issue by Rafael2616** [Deletescape-Media/Lawnchair#5076]
### Describe the bug

after the commit https://github.com/LawnchairLauncher/lawnchair/commit/1a9982ad653d50407d82a840390b775ec7820567, the app do not starts anymore, and i was unable to fix :(

### Expected behavior

laucnh app normally

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

### Additional context

```
java.lang.ExceptionInInitializerError
                                                                                                    	at com.android.quickstep.SystemUiProxy.<init>(SystemUiProxy.java:203)
                                                                                                    	at com.android.quickstep.SystemUiProxy.$r8$lambda$1jbizU9-15TXKEVnBlsEVuW8Kkk(Unknown Source:2)
                                                                                                    	at com.android.quickstep.SystemUiProxy$$ExternalSyntheticLambda0.get(D8$$SyntheticClass:0)
                                                                                                    	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
                                                                                                    	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$icoSB2GSttV1yd5beTvcp2Ed9FU(Unknown Source:0)
                                                                                                    	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda1.get(D8$$SyntheticClass:0)
                                                                                                    	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:97)
                                                                                                    	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:60)
                                                                                                    	at com.android.launcher3.uioverrides.QuickstepLauncher.onDeviceProfileInitiated(QuickstepLauncher.java:1358)
                                                                                                    	at com.android.launcher3.Launcher.initDeviceProfile(Launcher.java:813)
                                                                                                    	at com.android.launcher3.uioverrides.QuickstepLauncher.initDeviceProfile(QuickstepLauncher.java:693)
                                                                                                    	at com.android.launcher3.Launcher.onCreate(Launcher.java:521)
                                                                                                    	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:675)
```

**Comment by validcube** [comment]
The code seems fine and check if the Android version is 15 or higher, not sure why it fail but I think it might be related to how the code is compiled, can you try this build? https://github.com/BoringExperiments/lawnchair/actions/runs/12296888833
