### ISSUE TITLE
[BUG] crash after enabling recents

### ISSUE THREAD

**Issue by imyxh** [Deletescape-Media/Lawnchair#5116]
### Describe the bug

See steps to reproduce section. Then, I get two crash notifications:

```
Lawnchair bug report Dec 23, 2024 11:17:11 PM
version: 15.Dev.(#1838) (15000201)
commit: d682681
build.brand: lge
build.device: alphalm
build.display: SKQ1.211103.001
build.fingerprint: lge/alphalm_lao_com/alphalm:12/SKQ1.211103.001/222102013847d:user/release-keys
build.hardware: alphalm
build.id: SKQ1.211103.001
build.manufacturer: LGE
build.model: LM-G820
build.security.level: 2022-07-01
build.product: alphalm_lao_com
build.type: user
version.codename: REL
version.incremental: 222102013847d
version.release: 12
version.sdk_int: 31
display.density_dpi: 420
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No static method createId(Ljava/lang/Object;II)I in class Landroid/view/InsetsSource; or its super classes (declaration of 'android.view.InsetsSource' appears in /system/framework/framework.jar!classes3.dex)
	at android.view.InsetsFrameProvider.<init>(SourceFile:7)
	at com.android.launcher3.taskbar.TaskbarSharedState.<init>(Unknown Source:31)
	at com.android.launcher3.taskbar.TaskbarManager.<init>(Unknown Source:24)
	at com.android.quickstep.TouchInteractionService.onCreate(Unknown Source:98)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4550)
	at android.app.ActivityThread.access$1700(ActivityThread.java:255)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8005)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
```

```
Lawnchair bug report Dec 23, 2024 11:16:36 PM
version: 15.Dev.(#1838) (15000201)
commit: d682681
build.brand: lge
build.device: alphalm
build.display: SKQ1.211103.001
build.fingerprint: lge/alphalm_lao_com/alphalm:12/SKQ1.211103.001/222102013847d:user/release-keys
build.hardware: alphalm
build.id: SKQ1.211103.001
build.manufacturer: LGE
build.model: LM-G820
build.security.level: 2022-07-01
build.product: alphalm_lao_com
build.type: user
version.codename: REL
version.incremental: 222102013847d
version.release: 12
version.sdk_int: 31
display.density_dpi: 420
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchFieldError: No field mNotFlags of type I in class Landroid/window/TransitionFilter; or its superclasses (declaration of 'android.window.TransitionFilter' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.launcher3.QuickstepTransitionManager.registerRemoteTransitions(Unknown Source:71)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(Unknown Source:184)
	at com.android.launcher3.Launcher.onCreate(Unknown Source:219)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(Unknown Source:18)
	at app.lawnchair.LawnchairLauncher.onCreate(Unknown Source:32)
	at android.app.Activity.performCreate(Activity.java:8071)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3820)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2218)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8005)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
```

### Steps to reproduce

My recents (handled by LG Home 12) started crashing on my degoogled and rooted device, but Lawnchair home was working. I installed quickswitch and set Lawnchair as the recents provider, and now Lawnchair crashes when being opened either as the recents provider or as the home app.

### Expected behavior

Lawnchair home and recents do not crash.

### Device information

- Device: alphalm
- OS: stock + magisk + debloating of: {HotwordEnrollmentXGoogle, GoogleFeedback, GoogleServicesFramework, SetupWizard, GooglePartnerSetup, GmsCore, Velvet, GoogleRestore, Turbo, Phonesky, Wellbeing, GoogleOneTimeInitializer} + microG installed with signature spoofing
- App version: nightly d682681

### Additional context

love y'all + this project <3

**Comment by imyxh** [comment]
Duplicate of #5047 :woman_facepalming:
