### ISSUE TITLE
[BUG] Gesture crash on One UI 5.1

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#5121]
### Describe the bug

Gesture animations are not working on lawnchair 15.
Gestures were working smoothly on lawnchair 14.

Latest LC15 build 
Samsung F22
One UI 5.1 core Android 13

### Steps to reproduce

Set lawnchair 15 as default launcher on One UI 5.1 device > access gestures and see crash

### Expected behavior

Should work smooth.

### Screenshots

https://github.com/user-attachments/assets/09bc0988-9fc1-4e70-8802-f3ae6fd1a6d6

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

### Additional context

Lawnchair bug report 29 Dec 2024 1:45:09 am
version: 15.Dev.(#1857) (15000201)
commit: 4ad2e73
build.brand: samsung
build.device: qssi
build.display: TQ1A.230105.002
build.fingerprint: samsung/r9qxxx/qssi:13/TQ1A.230105.002/9325679:user/release-keys
build.hardware: mt6769t
build.id: TQ1A.230105.002
build.manufacturer: samsung
build.model: SM-G990B
build.security.level: 2023-01-05
build.product: r9qxxx
build.type: user
version.codename: REL
version.incremental: 9325679
version.release: 13
version.sdk_int: 33
display.density_dpi: 260
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchFieldError: No field rotationChange of type I in class Landroid/view/RemoteAnimationTarget; or its superclasses (declaration of 'android.view.RemoteAnimationTarget' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.launcher3.QuickstepTransitionManager.getRotationChange(Unknown Source:7)
	at com.android.launcher3.QuickstepTransitionManager.x(Unknown Source:0)
	at com.android.launcher3.QuickstepTransitionManager$WallpaperOpenLauncherAnimationRunner.onAnimationStart(SourceFile:10)
	at com.android.launcher3.LauncherAnimationRunner.lambda$onAnimationStart$2(Unknown Source:26)
	at com.android.launcher3.LauncherAnimationRunner.f(Unknown Source:0)
	at com.android.launcher3.f4.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by ujwal246** [comment]
Still App opening animations and recents are not fixed.

Somehow App closing animation is fixed.


New Bug report : https://katb.in/itofohulovi


https://github.com/user-attachments/assets/cf58cb9a-ec0c-4855-8028-1ad446612d5b
