### ISSUE TITLE
[BUG] Gesture crash on One UI 5.1

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#5127]
### Describe the bug

Tried #5126 

But still app opening animation and gestures are not fixed.

Somehow it fixed app closing animation.

Latest LC15 build 
One UI 5.1 Android 13

### Steps to reproduce

Set lawnchair 15 as recents provider in One UI 5.1 > Access gesture

### Expected behavior

Should work smooth.

### Screenshots

https://github.com/user-attachments/assets/8142cb95-c806-46d1-bc15-85e2f4d21a0b

### Device information

.

### Additional context

Lawnchair bug report 30 Dec 2024 3:23:23 am
version: 15.Dev.(#1861) (15000201)
commit: 45c8552
build.brand: samsung
build.device: qssi
build.display: TQ1A.230105.002
build.fingerprint: samsung/r9qxxx/qssi:13/TQ1A.230105.002/9325679:user/release-keys
build.hardware: mt6769t
build.id: TQ1A.230105.002
build.manufacturer: samsung
build.model: SM-G990B
build.security.level: 2023-01-05
build.product: r9qxxx
build.type: user
version.codename: REL
version.incremental: 9325679
version.release: 13
version.sdk_int: 33
display.density_dpi: 260
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No static method createId(Ljava/lang/Object;II)I in class Landroid/view/InsetsSource; or its super classes (declaration of 'android.view.InsetsSource' appears in /system/framework/framework.jar!classes4.dex)
	at android.view.InsetsFrameProvider.<init>(SourceFile:7)
	at com.android.launcher3.taskbar.TaskbarSharedState.<init>(Unknown Source:31)
	at com.android.launcher3.taskbar.TaskbarManager.<init>(Unknown Source:24)
	at com.android.quickstep.TouchInteractionService.onCreate(Unknown Source:98)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by validcube** [comment]
Note: This is different than #5121 as this is an exception for NSME in Taskbar or TIS
