### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'float com.google.android.gms.a.c.b.a(int)' on a null object reference

### ISSUE THREAD

**Issue by npike** [Deletescape-Media/Lawnchair#585]
Not sure if Google Play Services updated on my device or not, but within the last hour Lawnchair force closes as soon as you try to launch it / go home.  See stacktrace below.

`08-23 11:18:04.813 10573-10573/ch.deletescape.lawnchair E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: ch.deletescape.lawnchair, PID: 10573
                                                                          java.lang.NullPointerException: Attempt to invoke interface method 'float com.google.android.gms.a.c.b.a(int)' on a null object reference
                                                                              at ch.deletescape.lawnchair.weather.AwarenessWeatherAPI.onResult(Unknown Source)
                                                                              at ch.deletescape.lawnchair.weather.AwarenessWeatherAPI.onResult(Unknown Source)
                                                                              at com.google.android.gms.c.gy.onResult(Unknown Source)
                                                                              at com.google.android.gms.c.bm.handleMessage(Unknown Source)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`

**Comment by nyancrimew** [comment]
Have you granted location permission to lawnchair?
