### ISSUE TITLE
Failed to query for shortcuts java.lang.SecurityException: Caller can't access shortcut information

### ISSUE THREAD

**Issue by feresr** [Deletescape-Media/Lawnchair#887]
I just discovered lawnchair and it's already the default launcher on my phone. I've been looking for an open source project to contribute to for a while and this seems like the perfect one. I forked the repository and tried to build the project and the first thing that shows up is the following stack trace:

> java.lang.SecurityException: Caller can't access shortcut information

## Steps to Reproduce

1. Fork the repo
2. Build the project in Android studio (3.1 canary)

* Device: tried Several 

## Logcat

```
ch.deletescape.lawnchair E/DeepShortcutManager: Failed to query for shortcuts
                                                                             java.lang.SecurityException: Caller can't access shortcut information
                                                                                 at android.os.Parcel.readException(Parcel.java:1942)
                                                                                 at android.os.Parcel.readException(Parcel.java:1888)
                                                                                 at android.content.pm.ILauncherApps$Stub$Proxy.getShortcuts(ILauncherApps.java:779)
                                                                                 at android.content.pm.LauncherApps.getShortcuts(LauncherApps.java:701)
                                                                                 at ch.deletescape.lawnchair.shortcuts.DeepShortcutManagerNative.query(DeepShortcutManagerNative.java:180)
                                                                                 at ch.deletescape.lawnchair.shortcuts.DeepShortcutManager.queryForPinnedShortcuts(DeepShortcutManager.java:70)
                                                                                 at ch.deletescape.lawnchair.LauncherModel$LoaderTask.loadWorkspace(LauncherModel.java:1840)
                                                                                 at ch.deletescape.lawnchair.LauncherModel$LoaderTask.loadAndBindWorkspace(LauncherModel.java:1493)
                                                                                 at ch.deletescape.lawnchair.LauncherModel$LoaderTask.run(LauncherModel.java:1585)
                                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by NickAcPT** [comment]
This happens due to a missing permission (?). We can see that by looking at the android's source code.
In the class com,android.server.pm.LauncherAppsService, there is a method called ensureShortcutPermission.
But, if we look at the class com.android.server.pm.ShortcutService we get to this code:
```java
boolean hasShortcutHostPermissionInner(@NonNull String packageName, int userId) {
        synchronized (mLock) {
            throwIfUserLockedL(userId);
            final ShortcutUser user = getUserShortcutsLocked(userId);
            // Always trust the cached component.
            final ComponentName cached = user.getCachedLauncher();
            if (cached != null) {
                if (cached.getPackageName().equals(packageName)) {
                    return true;
                }
            }
            // If the cached one doesn't match, then go ahead
            final ComponentName detected = getDefaultLauncher(userId);
            // Update the cache.
            user.setLauncher(detected);
            if (detected != null) {
                if (DEBUG) {
                    Slog.v(TAG, "Detected launcher: " + detected);
                }
                return detected.getPackageName().equals(packageName);
            } else {
                // Default launcher not found.
                return false;
            }
        }
    }
```
###### Sorry if this didn't help.

**Comment by divadsn** [comment]
That's only happening when Lawnchair **isn't** the default launcher ¯\_(ツ)_/¯
